approx_ge – FIDASIM
approx_ge Function
7 statements
Source File
public function approx_ge(x, y, tol) result(a)
Inexact greater than or equal to comparison: x >~= y
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: x
First value in comparison
real(kind=Float64), intent(in) :: y
Second value in comparison
real(kind=Float64), intent(in) :: tol
Equality tolerance
Return Value logical
Calls
Called by
Contents
Source Code
approx_ge
Source Code
function approx_ge(x,y,tol) result(a)
    !+ Inexact greater than or equal to comparison: `x >~= y`
    real(Float64), intent(in) :: x
        !+First value in comparison
    real(Float64), intent(in) :: y
        !+Second value in comparison
    real(Float64), intent(in) :: tol
        !+Equality tolerance
    logical :: a
    a = (x.gt.y).or.(approx_eq(x,y,tol))
end function approx_ge
Call graph
approx_ge calls approx_eq
in_grid calls approx_ge
in_passive_grid calls approx_ge
grid_intersect calls in_passive_grid
read_mc calls in_grid, circle_grid_intersect
circle_grid_intersect calls in_grid, grid_intersect
mc_nbi calls grid_intersect
fida_weights_los calls grid_intersect
read_distribution calls read_mc
make_diagnostic_grids calls grid_intersect
ndmc calls mc_nbi
fidasim calls fida_weights_los, read_distribution, make_diagnostic_grids, ndmc