Aq_ioniz – FIDASIM
Aq_ioniz Function
10 statements
Source File
public function Aq_ioniz(eb, q, n_max) result(sigma)
Calculates an array of total ionization cross sections for a Neutral Hydrogen atom in the n=1...n_max states colliding with a ion with charge q at energy eb
Note
Uses specialized cross sections if available else uses generic cross sections
Equation
References
Page 152 in Ref. 5 atomic_tables
Page 154 in Ref. 5 atomic_tables
Page 160 in Ref. 5 atomic_tables
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: eb
Relative collision energy [keV/amu]
integer, intent(in) :: q
Ion charge
integer, intent(in) :: n_max
Number of initial states n to calculate
Return Value real(kind=Float64), dimension(n_max)
Array of cross sections where the n'th index refers to a ionization from the n'th state []
Calls
Called by
Contents
Source Code
Aq_ioniz
Source Code
function Aq_ioniz(eb, q, n_max) result(sigma)
    !+ Calculates an array of total ionization cross sections for a Neutral Hydrogen atom
    !+in the n=1...n_max states colliding with a ion with charge `q` at energy `eb`
    !+
    !+@note Uses specialized cross sections if available else uses generic cross sections
    !+
    !+###Equation
    !+$$ A^{q+} + H(n=1..n_{max}) \rightarrow A^{(q-1)+} + H^+, q \gt 3 $$
    !+
    !+###References
    !+* Page 152 in Ref. 5 [[atomic_tables(module)]]
    !+* Page 154 in Ref. 5 [[atomic_tables(module)]]
    !+* Page 160 in Ref. 5 [[atomic_tables(module)]]
    real(Float64), intent(in)       :: eb
        !+ Relative collision energy [keV/amu]
    integer, intent(in)             :: q
        !+ Ion charge
    integer, intent(in)             :: n_max
        !+ Number of initial states n to calculate
    real(Float64), dimension(n_max) :: sigma
        !+ Array of cross sections where the n'th index refers to a ionization from the n'th state [\(cm^2\)]
    integer :: n
    do n=1,n_max
        sigma(n) = Aq_ioniz_n(eb, q, n)
    enddo
end function Aq_ioniz
Call graph
aq_ioniz calls aq_ioniz_n
aq_ioniz_n calls c6_ioniz_1_janev, aq_ioniz_n_janev, b5_ioniz_1_janev
write_bb_h_aq calls aq_ioniz
generate_tables calls write_bb_h_aq