Aq_ioniz_n – FIDASIM
Aq_ioniz_n Function
15 statements
Source File
public function Aq_ioniz_n(eb, q, n) result(sigma)
Calculates the total ionization cross section for a Neutral Hydrogen atom in the n state colliding with a ion with charge q at energy eb
Note
Uses specialized cross sections if available else uses generic cross sections
Equation
References
Page 152 in Ref. 5 atomic_tables
Page 154 in Ref. 5 atomic_tables
Page 160 in Ref. 5 atomic_tables
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: eb
Relative collision energy [keV/amu]
integer, intent(in) :: q
Ion charge
integer, intent(in) :: n
Initial atomic energy level/state
Return Value real(kind=Float64)
Cross Section []
Calls
Called by
Contents
Source Code
Aq_ioniz_n
Source Code
function Aq_ioniz_n(eb, q, n) result(sigma)
    !+ Calculates the total ionization cross section for a Neutral Hydrogen atom
    !+in the `n` state colliding with a ion with charge `q` at energy `eb`
    !+
    !+@note Uses specialized cross sections if available else uses generic cross sections
    !+
    !+###Equation
    !+$$ A^{q+} + H(n) \rightarrow A^{(q-1)+} + H^+, q \gt 3 $$
    !+
    !+###References
    !+* Page 152 in Ref. 5 [[atomic_tables(module)]]
    !+* Page 154 in Ref. 5 [[atomic_tables(module)]]
    !+* Page 160 in Ref. 5 [[atomic_tables(module)]]
    real(Float64), intent(in) :: eb
        !+ Relative collision energy [keV/amu]
    integer, intent(in)       :: q
        !+ Ion charge
    integer, intent(in)       :: n
        !+ Initial atomic energy level/state
    real(Float64)             :: sigma
        !+ Cross Section [\(cm^2\)]
    if((q.eq.5).and.(n.eq.1)) then
        sigma = B5_ioniz_1_janev(eb)
        return
    endif
    if((q.eq.6).and.(n.eq.1)) then
        sigma = C6_ioniz_1_janev(eb)
        return
    endif
    sigma = Aq_ioniz_n_janev(eb, q, n)
end function Aq_ioniz_n
Call graph
aq_ioniz_n calls b5_ioniz_1_janev, aq_ioniz_n_janev, c6_ioniz_1_janev
aq_ioniz calls aq_ioniz_n
write_bb_h_aq calls aq_ioniz
generate_tables calls write_bb_h_aq