chunk_size – FIDASIM
chunk_size Subroutine
16 statements
Source File
public subroutine chunk_size(elsize, dims, cdims)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: elsize
Size of elements in bytes
integer(kind=HSIZE_T), intent(in), dimension(*) :: dims
Dimensions of dataset
integer(kind=HSIZE_T), intent(out), dimension(:) :: cdims
Maximum allowed chunk size/dims
Called by
Contents
Source Code
chunk_size
Source Code
subroutine chunk_size(elsize, dims, cdims)
    integer, intent(in)                          :: elsize
        !+ Size of elements in bytes
    integer(HSIZE_T), dimension(*), intent(in)   :: dims
        !+ Dimensions of dataset
    integer(HSIZE_T), dimension(:), intent(out)  :: cdims
        !+ Maximum allowed chunk size/dims
    real, parameter :: max_bytes = 4*1e9 !GigaBytes
    integer :: d
    real(Float64) :: nbytes
    d = size(cdims)
    cdims(1:d) = dims(1:d)
    nbytes = elsize*product(1.d0*cdims)
    do while ((nbytes.gt.max_bytes).and.(d.gt.0))
        cdims(d) = max(floor(cdims(d)*max_bytes/nbytes,Int32),1)
        nbytes = elsize*product(1.d0*cdims)
        d = d - 1
    enddo
end subroutine chunk_size
Call graph
h5ltmake_compressed_dataset_double_f_4 calls chunk_size
h5ltmake_compressed_dataset_int_f_1 calls chunk_size
h5ltmake_compressed_dataset_int_f_2 calls chunk_size
h5ltmake_compressed_dataset_int_f_3 calls chunk_size
h5ltmake_compressed_dataset_double_f_2 calls chunk_size
h5ltmake_compressed_dataset_double_f_1 calls chunk_size
h5ltmake_compressed_dataset_double_f_5 calls chunk_size
h5ltmake_compressed_dataset_double_f_3 calls chunk_size
h5ltmake_compressed_dataset_int_f_4 calls chunk_size
h5ltmake_compressed_dataset_int_f_5 calls chunk_size
h5ltmake_compressed_dataset_int_f_6 calls chunk_size
h5ltmake_compressed_dataset_int_f_7 calls chunk_size
h5ltmake_compressed_dataset_double_f_6 calls chunk_size
h5ltmake_compressed_dataset_double_f_7 calls chunk_size
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_4, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_6, h5ltmake_compressed_dataset_double_f_7
h5ltmake_compressed_dataset_int_f calls h5ltmake_compressed_dataset_int_f_1, h5ltmake_compressed_dataset_int_f_2, h5ltmake_compressed_dataset_int_f_3, h5ltmake_compressed_dataset_int_f_4, h5ltmake_compressed_dataset_int_f_5, h5ltmake_compressed_dataset_int_f_6, h5ltmake_compressed_dataset_int_f_7
write_einstein calls h5ltmake_compressed_dataset_double_f
write_bt_d_he3 calls h5ltmake_compressed_dataset_double_f
write_bt_d_d calls h5ltmake_compressed_dataset_double_f
write_fida_weights calls h5ltmake_compressed_dataset_double_f
write_bt_d_t calls h5ltmake_compressed_dataset_double_f
write_bb_h_h calls h5ltmake_compressed_dataset_double_f
write_bt_h_e calls h5ltmake_compressed_dataset_double_f
write_bb_h_e calls h5ltmake_compressed_dataset_double_f
write_bt_h_h calls h5ltmake_compressed_dataset_double_f
write_bb_h_aq calls h5ltmake_compressed_dataset_double_f
write_spectra calls h5ltmake_compressed_dataset_double_f
write_npa calls h5ltmake_compressed_dataset_double_f, h5ltmake_compressed_dataset_int_f
write_cfpd_weights calls h5ltmake_compressed_dataset_double_f
write_bb_d_t calls h5ltmake_compressed_dataset_double_f
write_bb_d_he3 calls h5ltmake_compressed_dataset_double_f
write_bt_h_aq calls h5ltmake_compressed_dataset_double_f
write_npa_weights calls h5ltmake_compressed_dataset_double_f, write_beam_grid
write_beam_grid calls h5ltmake_compressed_dataset_double_f
write_neutral_population calls h5ltmake_compressed_dataset_double_f, h5ltmake_compressed_dataset_int_f
write_birth_profile calls h5ltmake_compressed_dataset_double_f, h5ltmake_compressed_dataset_int_f, write_beam_grid
write_bb_d_d calls h5ltmake_compressed_dataset_double_f
write_neutrons calls h5ltmake_compressed_dataset_double_f
fidasim calls write_spectra, write_npa, write_birth_profile, neutron_f, fida_weights_los, write_neutrals, neutron_mc, cfpd_f, fida_weights_mc, npa_weights
neutron_f calls write_neutrons
fida_weights_los calls write_fida_weights
write_neutrals calls write_beam_grid, write_neutral_population
neutron_mc calls write_neutrons
cfpd_f calls write_cfpd_weights
fida_weights_mc calls write_fida_weights
npa_weights calls write_npa_weights
generate_tables calls write_einstein, write_bt_d_he3, write_bt_d_d, write_bb_h_h, write_bt_h_e, write_bb_h_e, write_bt_h_h, write_bb_h_aq, write_bb_d_he3, write_bt_h_aq, write_bb_d_d