colrad – FIDASIM
colrad Subroutine
48 statements
Source File
public subroutine colrad(plasma, i_type, vn, dt, states, dens, photons)
Evolve density of states in time dt via collisional radiative model
Arguments
Type Intent Optional Attributes Name
type(LocalProfiles), intent(in) :: plasma
Plasma parameters
integer, intent(in) :: i_type
Ion/Neutral type (beam,thermal)
real(kind=Float64), intent(in), dimension(:) :: vn
Neutral velocitiy [cm/s]
real(kind=Float64), intent(in) :: dt
Time interval [s]
real(kind=Float64), intent(inout), dimension(:) :: states
Density of states
real(kind=Float64), intent(out), dimension(nlevs) :: dens
Density of neutrals
real(kind=Float64), intent(out) :: photons
Emitted photons(3->2)
Calls
Called By
Source Code
colrad
Source Code
subroutine colrad(plasma,i_type,vn,dt,states,dens,photons)
    !+ Evolve density of states in time `dt` via collisional radiative model
    type(LocalProfiles), intent(in)              :: plasma
        !+ Plasma parameters
    integer, intent(in)                          :: i_type
        !+ Ion/Neutral type (beam,thermal)
    real(Float64), dimension(:), intent(in)      :: vn
        !+ Neutral velocitiy [cm/s]
    real(Float64), intent(in)                    :: dt
        !+ Time interval [s]
    real(Float64), dimension(:), intent(inout)   :: states
        !+ Density of states
    real(Float64), dimension(nlevs), intent(out) :: dens
        !+ Density of neutrals
    real(Float64), intent(out)                   :: photons
        !+ Emitted photons(3->2)
    real(Float64), dimension(nlevs,nlevs) :: matrix  !! Matrix
    real(Float64) :: b_amu
    real(Float64) :: vnet_square    !! net velocity of neutrals squared
    real(Float64) :: eb             !! Energy of the fast neutral
    real(Float64), dimension(nlevs,nlevs) :: eigvec
    real(Float64), dimension(nlevs) :: eigval, coef
    real(Float64), dimension(nlevs) :: exp_eigval_dt
    real(Float64) :: iflux !!Initial total flux
    integer :: n
    photons=0.d0
    dens=0.d0
    iflux=sum(states)
    if(.not.plasma%in_plasma) then
        dens = states*dt
        return
    endif
    if(i_type.eq.beam_ion) then
        b_amu = inputs%ab
    else
        b_amu = inputs%ai
    endif
    vnet_square=dot_product(vn-plasma%vrot,vn-plasma%vrot)  ![cm/s]
    eb = v2_to_E_per_amu*b_amu*vnet_square ![kev]
    call get_rate_matrix(plasma, i_type, eb, matrix)
    call eigen(nlevs,matrix, eigvec, eigval)
    call linsolve(eigvec,states,coef) !coeffs determined from states at t=0
    exp_eigval_dt = exp(eigval*dt)   ! to improve speed (used twice)
    do n=1,nlevs
        if(eigval(n).eq.0.0) eigval(n)=eigval(n)+1 !protect against dividing by zero
    enddo
    states = matmul(eigvec, coef * exp_eigval_dt)  ![neutrals/cm^3/s]!
    dens   = matmul(eigvec,coef*(exp_eigval_dt-1.d0)/eigval)
    if ((minval(states).lt.0).or.(minval(dens).lt.0)) then
        do n=1,nlevs
            if(states(n).lt.0) states(n)=0.d0
            if(dens(n).lt.0) dens(n)=0.d0
        enddo
    endif
    photons=dens(3)*tables%einstein(2,3) !! - [Ph/(s*cm^3)] - !!
end subroutine colrad
All Procedures
approx_eq approx_ge approx_le Aq_cx Aq_cx_n Aq_cx_n_adas Aq_cx_n_janev Aq_excit Aq_excit_1_2_janev Aq_excit_1_3_janev Aq_excit_1_4_janev Aq_excit_1_5_janev Aq_excit_1_janev Aq_excit_2_10_janev Aq_excit_2_3_janev Aq_excit_2_4_janev Aq_excit_2_5_janev Aq_excit_2_6_janev Aq_excit_2_7_janev Aq_excit_2_8_janev Aq_excit_2_9_janev Aq_excit_2_janev Aq_excit_3_10_janev Aq_excit_3_4_janev Aq_excit_3_5_janev Aq_excit_3_6_janev Aq_excit_3_7_janev Aq_excit_3_8_janev Aq_excit_3_9_janev Aq_excit_3_janev Aq_excit_n Aq_excit_n_janev Aq_excit_n_m Aq_ioniz Aq_ioniz_n Aq_ioniz_n_janev assignment(=) attenuate B5_cx_1_adas B5_cx_1_janev B5_cx_2_adas B5_ioniz_1_janev balance balback bb_cx_rates boundary_edge bremsstrahlung bt_cx_rates bt_maxwellian bt_maxwellian_eb bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m C6_cx_1_adas C6_cx_1_janev C6_cx_2_adas C6_cx_3_adas C6_ioniz_1_janev calc_perp_vectors check_compression_availability circle_grid_intersect cold_spec colrad comabs Comdiv cross_product cumsum d_d_fusion_he d_d_fusion_t d_t_fusion dcx dcx_spec deriv e_excit e_excit_1_2_janev e_excit_1_3_janev e_excit_1_4_janev e_excit_1_5_janev e_excit_1_janev e_excit_2_3_janev e_excit_f e_excit_n e_excit_n_m e_ioniz e_ioniz_1_janev e_ioniz_2_janev e_ioniz_3_janev e_ioniz_n eigen elmhes elmtrans fast_ion_assign ff_add ff_assign ff_subtract fida_f fida_mc fida_weights_los fida_weights_mc fidampi_clenup fidampi_init fidampi_my_rank fidampi_num_ranks fidampi_sum fidampi_sum_d0 fidampi_sum_d1 fidampi_sum_d2 fidampi_sum_d3 fidampi_sum_d4 fidampi_sum_d5 fidampi_sum_i0 fidampi_sum_i1 fidampi_sum_i2 flf_assign fs_divide fs_multiply get_beam_cx_rate get_distribution get_ep_denf get_fields get_indices get_neutron_rate get_nlaunch get_plasma get_position get_rate_matrix get_rng get_value grid_intersect gyro_correction gyro_radius gyro_range gyro_step gyro_surface gyro_surface_coordinates gyro_trajectory h5ltmake_compressed_dataset_double_f h5ltmake_compressed_dataset_double_f_1 h5ltmake_compressed_dataset_double_f_2 h5ltmake_compressed_dataset_double_f_3 h5ltmake_compressed_dataset_double_f_4 h5ltmake_compressed_dataset_double_f_5 h5ltmake_compressed_dataset_double_f_6 h5ltmake_compressed_dataset_double_f_7 h5ltmake_compressed_dataset_int_f h5ltmake_compressed_dataset_int_f_1 h5ltmake_compressed_dataset_int_f_2 h5ltmake_compressed_dataset_int_f_3 h5ltmake_compressed_dataset_int_f_4 h5ltmake_compressed_dataset_int_f_5 h5ltmake_compressed_dataset_int_f_6 h5ltmake_compressed_dataset_int_f_7 h5ltread_dataset_double_scalar_f h5ltread_dataset_int_scalar_f halo halo_spec hit_npa_detector hqr2 hqrvec in_boundary in_grid in_gyro_surface in_plasma ind2sub interpol interpol1D_arr interpol1D_coeff interpol1D_coeff_arr interpol2D_2D_arr interpol2D_arr interpol2D_coeff interpol2D_coeff_arr interpol_coeff lff_assign lflf_add lflf_assign lflf_subtract lfs_divide lfs_multiply line_basis line_gyro_surface_intersect line_plane_intersect linsolve lplp_add lplp_assign lplp_subtract lpp_assign lps_divide lps_multiply lubksb ludcmp m_spread make_beam_grid matinv mc_fastion mc_halo mc_nbi mc_nbi_cell nbi_spec ndmc neutron_f neutron_mc norm2 npa_f npa_gyro_range npa_mc npa_part_assign npa_weights operator(*) operator(+) operator(-) operator(/) outerprod p_cx p_cx_1 p_cx_1_1_adas p_cx_1_2_adas p_cx_1_3_adas p_cx_1_4_adas p_cx_1_janev p_cx_2 p_cx_2_2_adas p_cx_2_3_adas p_cx_2_janev p_cx_3 p_cx_3_2_adas p_cx_3_3_adas p_cx_3_4_adas p_cx_3_5_adas p_cx_3_6inf_adas p_cx_3_janev p_cx_janev p_cx_n p_cx_n_janev p_cx_n_m p_excit p_excit_1_2_janev p_excit_1_3_janev p_excit_1_4_janev p_excit_1_5_janev p_excit_1_6_janev p_excit_1_janev p_excit_2_10_janev p_excit_2_3_janev p_excit_2_4_janev p_excit_2_5_janev p_excit_2_6_janev p_excit_2_7_janev p_excit_2_8_janev p_excit_2_9_janev p_excit_2_janev p_excit_3_10_janev p_excit_3_4_janev p_excit_3_5_janev p_excit_3_6_janev p_excit_3_7_janev p_excit_3_8_janev p_excit_3_9_janev p_excit_3_janev p_excit_n p_excit_n_m p_ioniz p_ioniz_1_janev p_ioniz_2_omullane p_ioniz_3_omullane p_ioniz_4_omullane p_ioniz_5_omullane p_ioniz_n pfida_f pfida_mc pitch_to_vec plane_basis plp_assign pnpa_f pnpa_mc pp_add pp_assign pp_subtract print_banner print_default_namelist ps_divide ps_multiply randind randind_cdf randn randu read_atomic_cross read_atomic_rate read_atomic_transitions read_beam read_chords read_distribution read_equilibrium read_f read_inputs read_mc read_neutrals read_npa read_nuclear_rates read_tables rng_init rng_normal rng_seed rng_uniform RSWAP sf_multiply simpsons_rule slf_multiply slp_multiply sp_multiply sparse spectrum store_bes_photons store_births store_fida_photons store_fw_photons store_fw_photons_at_chan store_neutrals store_neutrons store_npa store_photons sub2ind swap tb_zyx time track uvw_to_xyz write_bb_D_D write_bb_D_T write_bb_H_Aq write_bb_H_e write_bb_H_H write_beam_grid write_birth_profile write_bt_D_D write_bt_D_T write_bt_H_Aq write_bt_H_e write_bt_H_H write_einstein write_fida_weights write_neutrals write_neutrons write_npa write_npa_weights write_spectra xyz_to_uvw
Call graph
colrad calls get_rate_matrix, linsolve, eigen
get_rate_matrix calls interpol_coeff
linsolve calls dgetrs, dgetrf, matinv
eigen calls balance, hqr2, balback, elmhes, elmtrans
interpol_coeff calls interpol2d_coeff_arr, interpol2d_coeff, interpol1d_coeff, interpol1d_coeff_arr
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
matinv calls ludcmp, lubksb
ludcmp calls swap, outerprod
balance calls rswap
hqr2 calls hqrvec
balback calls rswap
elmhes calls rswap
hqrvec calls comdiv
read_equilibrium calls colrad
ndmc calls colrad
pfida_f calls colrad
fida_f calls colrad
fida_mc calls colrad
attenuate calls colrad
fida_weights_mc calls colrad
pfida_mc calls colrad
fida_weights_los calls colrad
dcx calls colrad
halo calls colrad
fidasim calls read_equilibrium, ndmc, pfida_f, fida_f, fida_mc, fida_weights_mc, pfida_mc, fida_weights_los, dcx, halo, npa_weights, npa_mc, pnpa_mc, npa_f, pnpa_f
npa_weights calls attenuate
npa_mc calls attenuate
pnpa_mc calls attenuate
npa_f calls attenuate
pnpa_f calls attenuate