cumsum – FIDASIM
cumsum Subroutine
12 statements
Source File
public subroutine cumsum(x, cs)
Calculate cumulative sum
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in), dimension(:) :: x
Array to sum
real(kind=Float64), intent(out), dimension(:) :: cs
Cumulative sum of x
Called by
Contents
Source Code
cumsum
Source Code
subroutine cumsum(x, cs)
    !+ Calculate cumulative sum
    real(Float64), dimension(:), intent(in)  :: x
        !+ Array to sum
    real(Float64), dimension(:), intent(out) :: cs
        !+ Cumulative sum of `x`
    integer :: i, n
    real(Float64) :: cdf_val, t
    n = size(x)
    t = 0.d0
    do i=1, n
        cs(i) = t + x(i)
        t = cs(i)
    enddo
end subroutine cumsum
Call graph
get_nlaunch calls cumsum
get_nlaunch_pass_grid calls cumsum
npa_f calls get_nlaunch
fida_weights_mc calls get_nlaunch
halo calls get_nlaunch
pnpa_f calls get_nlaunch_pass_grid
fida_f calls get_nlaunch
dcx calls get_nlaunch
pfida_f calls get_nlaunch_pass_grid
fidasim calls npa_f, fida_weights_mc, halo, pnpa_f, fida_f, dcx, pfida_f