cyl_to_uvw – FIDASIM
cyl_to_uvw Subroutine
7 statements
Source File
public subroutine cyl_to_uvw(cyl, uvw)
Convert cylindrical coordinate cyl to machine coordinate uvw
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in), dimension(3) :: cyl
real(kind=Float64), intent(out), dimension(3) :: uvw
Called by
Contents
Source Code
cyl_to_uvw
Source Code
subroutine cyl_to_uvw(cyl, uvw)
    !+ Convert cylindrical coordinate `cyl` to machine coordinate `uvw`
    real(Float64), dimension(3), intent(in)  :: cyl
    real(Float64), dimension(3), intent(out) :: uvw
    uvw(1) = cyl(1) * cos(cyl(3))
    uvw(2) = cyl(1) * sin(cyl(3))
    uvw(3) = cyl(2)
end subroutine cyl_to_uvw
Call graph
track_cylindrical calls cyl_to_uvw, in_plasma, get_fields, get_plasma
in_plasma calls cyl_to_uvw
cyl_to_xyz calls cyl_to_uvw
cold_spec calls cyl_to_uvw, get_plasma, store_photons
mc_passive_grid calls cyl_to_uvw
read_mc calls in_plasma
pfida_mc calls track_cylindrical, get_fields, get_plasma, store_fida_photons
make_beam_grid calls in_plasma
mc_fastion_pass_grid calls mc_passive_grid, get_fields, get_distribution
get_fields calls in_plasma, get_position
dcx_spec calls in_plasma, get_plasma, store_photons
mc_nbi calls in_plasma
halo_spec calls in_plasma, get_plasma, store_photons
fidasim calls cold_spec, pfida_mc, make_beam_grid, dcx_spec, halo_spec, nbi_spec, make_diagnostic_grids, pfida_f, fida_weights_los, npa_mc, npa_weights, pnpa_f, read_distribution, fida_mc, halo, bremsstrahlung, fida_weights_mc, dcx, neutron_f, neutron_mc, pnpa_mc, fida_f, npa_f, cfpd_f, ndmc
get_plasma_extrema calls in_plasma
track calls in_plasma, get_fields, get_plasma
get_plasma calls in_plasma, get_position
nbi_spec calls in_plasma, store_photons
make_diagnostic_grids calls track_cylindrical, get_fields, track, make_passive_grid
get_position calls cyl_to_xyz
pfida_f calls track_cylindrical, mc_fastion_pass_grid, get_plasma, store_fida_photons
fida_weights_los calls in_plasma, get_fields, track, get_plasma, get_ep_denf
npa_mc calls get_fields, attenuate, store_npa
npa_weights calls get_fields, attenuate, get_ep_denf
pnpa_f calls mc_fastion_pass_grid, get_plasma, attenuate, store_npa
read_distribution calls read_mc
fida_mc calls get_fields, track, get_plasma, store_fida_photons
halo calls track, get_plasma, store_photons
bremsstrahlung calls get_plasma
make_passive_grid calls get_plasma_extrema
fida_weights_mc calls get_fields, track, get_plasma, store_fw_photons, get_ep_denf
mc_fastion calls get_fields, get_distribution
dcx calls track, get_plasma, store_photons
attenuate calls get_plasma
neutron_f calls get_fields, get_plasma
neutron_mc calls get_fields, get_plasma
store_fw_photons calls get_fields
store_npa calls get_fields
pnpa_mc calls get_fields, get_plasma, attenuate, store_npa
fida_f calls track, get_plasma, mc_fastion, store_fida_photons
npa_f calls get_plasma, mc_fastion, attenuate, store_npa
cfpd_f calls get_fields, get_plasma, get_ep_denf
store_photons calls get_fields
get_ep_denf calls get_position
ndmc calls get_fields, mc_nbi, track, get_plasma, store_nbi_photons
get_distribution calls get_position
store_nbi_photons calls store_photons
store_fida_photons calls store_photons