cyl_to_xyz – FIDASIM
cyl_to_xyz Subroutine
7 statements
Source File
public subroutine cyl_to_xyz(cyl, xyz)
Convert cylindrical coordinate cyl to beam coordinate xyz
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in), dimension(3) :: cyl
real(kind=Float64), intent(out), dimension(3) :: xyz
Calls
Called by
Contents
Source Code
cyl_to_xyz
Source Code
subroutine cyl_to_xyz(cyl, xyz)
    !+ Convert cylindrical coordinate `cyl` to beam coordinate `xyz`
    real(Float64), dimension(3), intent(in)  :: cyl
    real(Float64), dimension(3), intent(out) :: xyz
    real(Float64), dimension(3) :: uvw
    call cyl_to_uvw(cyl, uvw)
    call uvw_to_xyz(uvw, xyz)
end subroutine cyl_to_xyz
Call graph
cyl_to_xyz calls cyl_to_uvw, uvw_to_xyz
get_position calls cyl_to_xyz
get_fields calls get_position
get_distribution calls get_position
get_plasma calls get_position
get_ep_denf calls get_position
mc_fastion_pass_grid calls get_fields, get_distribution
pnpa_mc calls get_fields, get_plasma, attenuate, store_npa
dcx_spec calls get_plasma, store_photons
dcx calls get_plasma, track, store_photons
pnpa_f calls get_plasma, mc_fastion_pass_grid, attenuate, store_npa
track calls get_fields, get_plasma
pfida_mc calls get_fields, get_plasma, track_cylindrical, store_fida_photons
npa_weights calls get_fields, get_ep_denf, attenuate
attenuate calls get_plasma
halo_spec calls get_plasma, store_photons
store_fw_photons calls get_fields
neutron_f calls get_fields, get_plasma
make_diagnostic_grids calls get_fields, track, track_cylindrical
fida_f calls get_plasma, track, mc_fastion, store_fida_photons
cfpd_f calls get_fields, get_plasma, get_ep_denf
track_cylindrical calls get_fields, get_plasma
neutron_mc calls get_fields, get_plasma
cold_spec calls get_plasma, store_photons
npa_f calls get_plasma, attenuate, mc_fastion, store_npa
mc_fastion calls get_fields, get_distribution
fida_mc calls get_fields, get_plasma, track, store_fida_photons
pfida_f calls get_plasma, mc_fastion_pass_grid, track_cylindrical, store_fida_photons
store_npa calls get_fields
ndmc calls get_fields, get_plasma, track, store_nbi_photons
bremsstrahlung calls get_plasma
store_photons calls get_fields
npa_mc calls get_fields, attenuate, store_npa
fida_weights_mc calls get_fields, get_plasma, get_ep_denf, track, store_fw_photons
halo calls get_plasma, track, store_photons
fida_weights_los calls get_fields, get_plasma, get_ep_denf, track
fidasim calls pnpa_mc, dcx_spec, dcx, pnpa_f, pfida_mc, npa_weights, halo_spec, neutron_f, make_diagnostic_grids, fida_f, cfpd_f, neutron_mc, cold_spec, npa_f, fida_mc, pfida_f, ndmc, bremsstrahlung, npa_mc, fida_weights_mc, halo, fida_weights_los, nbi_spec
store_nbi_photons calls store_photons
store_fida_photons calls store_photons
nbi_spec calls store_photons