cyl_interpol3D_coeff_arr – FIDASIM
cyl_interpol3D_coeff_arr Subroutine
40 statements
Source File
public subroutine cyl_interpol3D_coeff_arr(r, z, phi, rout, zout, phiout, c, err)
Cylindrical interpolation coefficients and indicies for a 3D grid
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in), dimension(:) :: r
R values
real(kind=Float64), intent(in), dimension(:) :: z
Z values
real(kind=Float64), intent(in), dimension(:) :: phi
Phi values
real(kind=Float64), intent(in) :: rout
R value to interpolate
real(kind=Float64), intent(in) :: zout
Z value to interpolate
real(kind=Float64), intent(in) :: phiout
Phi value to interpolate
type(InterpolCoeffs3D), intent(out) :: c
Cylindrical Interpolation Coefficients
integer, intent(out), optional :: err
Error code
Calls
Called by
Contents
Source Code
cyl_interpol3D_coeff_arr
Source Code
subroutine cyl_interpol3D_coeff_arr(r,z,phi,rout,zout,phiout,c,err)
    !+ Cylindrical interpolation coefficients and indicies for a 3D grid
    real(Float64), dimension(:), intent(in) :: r
        !+ R values
    real(Float64), dimension(:), intent(in) :: z
        !+ Z values
    real(Float64), dimension(:), intent(in) :: phi
        !+ Phi values
    real(Float64), intent(in)               :: rout
        !+ R value to interpolate
    real(Float64), intent(in)               :: zout
        !+ Z value to interpolate
    real(Float64), intent(in)               :: phiout
        !+ Phi value to interpolate
    type(InterpolCoeffs3D), intent(out)     :: c
        !+ Cylindrical Interpolation Coefficients
    integer, intent(out), optional          :: err
        !+ Error code
    type(InterpolCoeffs2D) :: b
    real(Float64) :: rmin, phimin, zmin, dr, dphi, dz
    integer :: sr, sphi, sz, err_status
    err_status = 1
    sr = size(r)
    sphi = size(phi)
    sz = size(z)
    rmin = r(1)
    zmin = z(1)
    dr = abs(r(2)-r(1))
    dz = abs(z(2)-z(1))
    if (sphi .eq. 1) then
        call interpol2D_coeff(rmin, dr, sr, zmin, dz, sz, rout, zout, b, err_status)
        c%b111 = b%b11
        c%b121 = b%b12
        c%b221 = b%b22
        c%b211 = b%b21
        c%b212 = 0
        c%b222 = 0
        c%b122 = 0
        c%b112 = 0
        c%i = b%i
        c%j = b%j
        c%k = 1
    else
        phimin = phi(1)
        dphi = abs(phi(2)-phi(1))
        call cyl_interpol3D_coeff(rmin, dr, sr, zmin, dz, sz, phimin, dphi, sphi, rout, zout, phiout, c, err_status)
    endif
    if(present(err)) err = err_status
end subroutine cyl_interpol3D_coeff_arr
Call graph
cyl_interpol3d_coeff_arr calls interpol2d_coeff, cyl_interpol3d_coeff
cyl_interpol3d_coeff calls interpol2d_coeff
interpol_coeff calls cyl_interpol3d_coeff_arr
in_plasma calls interpol_coeff
get_rate_matrix calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol3d_arr calls interpol_coeff
interpol2d_2d_arr calls interpol_coeff
get_neutron_rate calls interpol_coeff
bt_cx_rates calls interpol_coeff
bb_cx_rates calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol3d_2d_arr calls interpol_coeff
get_fields calls in_plasma
make_beam_grid calls in_plasma
pnpa_mc calls bt_cx_rates, get_fields, get_plasma, store_npa, attenuate
mc_nbi calls in_plasma
fida_weights_los calls in_plasma, bt_cx_rates, bb_cx_rates, get_fields, get_plasma, track, colrad
read_mc calls in_plasma
pfida_mc calls bt_cx_rates, get_fields, get_plasma, track
get_plasma calls in_plasma
dcx_spec calls in_plasma, get_plasma, store_photons
neutron_mc calls get_neutron_rate, get_fields, get_plasma
track calls in_plasma
halo_spec calls in_plasma, get_plasma, store_photons
nbi_spec calls in_plasma, store_photons
interpol calls interpol2d_arr, interpol3d_arr, interpol2d_2d_arr, interpol1d_arr, interpol3d_2d_arr
neutron_f calls get_neutron_rate, get_fields, get_plasma
pfida_f calls bt_cx_rates, get_plasma, track, mc_fastion
get_beam_cx_rate calls bt_cx_rates, bb_cx_rates, get_plasma
colrad calls get_rate_matrix
pnpa_f calls bt_cx_rates, get_plasma, store_npa, attenuate, mc_fastion
bremsstrahlung calls get_plasma
read_distribution calls read_mc
get_distribution calls interpol
npa_mc calls get_fields, get_beam_cx_rate, store_npa, attenuate
ndmc calls get_fields, mc_nbi, track
read_npa calls get_fields
fidasim calls make_beam_grid, pnpa_mc, fida_weights_los, pfida_mc, dcx_spec, neutron_mc, halo_spec, nbi_spec, neutron_f, pfida_f, pnpa_f, bremsstrahlung, read_distribution, npa_mc, ndmc, read_npa, read_equilibrium, npa_weights, fida_mc, halo, dcx, fida_f, read_chords, fida_weights_mc, cold_spec, npa_f
read_equilibrium calls colrad
npa_weights calls get_fields, get_beam_cx_rate, attenuate
fida_mc calls get_fields, track
mc_halo calls get_plasma
halo calls get_plasma, track, mc_halo
dcx calls get_plasma, track, mc_halo
store_npa calls get_fields
fida_f calls get_plasma, track, mc_fastion
store_photons calls get_fields
read_chords calls track
attenuate calls get_plasma, colrad
store_fw_photons calls get_fields
fida_weights_mc calls get_fields, get_plasma, track, get_ep_denf
cold_spec calls get_plasma, store_photons
get_ep_denf calls interpol
npa_f calls get_plasma, get_beam_cx_rate, store_npa, attenuate, mc_fastion
mc_fastion calls get_fields, get_distribution
store_bes_photons calls store_photons
store_fida_photons calls store_photons