doppler_stark – FIDASIM
doppler_stark Subroutine
20 statements
Source File
public subroutine doppler_stark(vecp, vi, fields, lambda0, lambda)
Calculates doppler shift and stark split wavelengths
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in), dimension(3) :: vecp
Vector directing towards optical head
real(kind=Float64), intent(in), dimension(3) :: vi
Particle velocity
type(LocalEMFields), intent(in) :: fields
Electro-magnetic fields
real(kind=Float64), intent(in) :: lambda0
Reference wavelength [nm]
real(kind=Float64), intent(out), dimension(n_stark) :: lambda
Wavelengths [nm]
Called by
Contents
None
Call graph
track calls doppler_stark
track_cylindrical calls doppler_stark
pfida_mc calls track_cylindrical
halo calls track
dcx calls track
make_diagnostic_grids calls track, track_cylindrical
fida_weights_mc calls track
pfida_f calls track_cylindrical
fida_mc calls track
ndmc calls track
fida_f calls track
fida_weights_los calls track
fidasim calls pfida_mc, halo, dcx, make_diagnostic_grids, fida_weights_mc, pfida_f, fida_mc, ndmc, fida_f, fida_weights_los