e_ioniz – FIDASIM
e_ioniz Function
9 statements
Source File
public function e_ioniz(eb, n_max) result(sigma)
Calculates an array of cross sections for a electron-Hydrogen impact ionization from the states at energy eb
Equation
References
Eq. 14 and Table 3 in Ref. 2 atomic_tables
Eq. 15-16 in Ref. 2 atomic_tables
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: eb
Collision energy [keV]
integer, intent(in) :: n_max
Number of initial atomic energy levels/states to calculate
Return Value real(kind=Float64), dimension(n_max)
Array of cross sections where the n'th index refers to a ionization from the n'th state []
Calls
Called by
Contents
Source Code
e_ioniz
Source Code
function e_ioniz(eb, n_max) result(sigma)
    !+Calculates an array of cross sections for a electron-Hydrogen impact ionization from
    !+the \(n=1..n_{max}\) states at energy `eb`
    !+
    !+###Equation
    !+$$ e + H(n=1..n_{max}) \rightarrow e + H^+ + e$$
    !+
    !+###References
    !+* Eq. 14 and Table 3 in Ref. 2 [[atomic_tables(module)]]
    !+* Eq. 15-16 in Ref. 2 [[atomic_tables(module)]]
    !+
    real(Float64), intent(in)       :: eb
        !+ Collision energy [keV]
    integer, intent(in)             :: n_max
        !+ Number of initial atomic energy levels/states to calculate
    real(Float64), dimension(n_max) :: sigma
        !+ Array of cross sections where the n'th index refers to a ionization from the n'th state [\(cm^2\)]
    integer :: i
    do i=1,n_max
        sigma(i) = e_ioniz_n(eb,i)
    enddo
end function e_ioniz
Call graph
e_ioniz calls e_ioniz_n
e_ioniz_n calls e_ioniz_3_janev, e_ioniz_1_janev, e_ioniz_2_janev
write_bb_h_e calls e_ioniz
generate_tables calls write_bb_h_e