fida_weights_mc – FIDASIM
fida_weights_mc Subroutine
125 statements
Source File
public subroutine fida_weights_mc()
Calculates FIDA weights
Arguments
None
Calls
Called By
Source Code
fida_weights_mc
Source Code
subroutine fida_weights_mc
    !+ Calculates FIDA weights
    integer :: i,j,k,ic,ncell
    integer(Int64) :: iion,ip
    real(Float64), dimension(3) :: ri,rg      !! start position
    real(Float64), dimension(3) :: vi     !! velocity of fast ions
    integer, dimension(3) :: ind      !! new actual cell
    integer,dimension(5) :: neut_types=[1,2,3,4,5]
    logical :: los_intersect
    !! Determination of the CX rates
    type(LocalProfiles) :: plasma
    type(LocalEMFields) :: fields
    real(Float64), dimension(nlevs) :: rates !! CX rates
    !! Collisiional radiative model along track
    integer :: ntrack
    integer :: jj      !! counter along track
    type(ParticleTrack),dimension(beam_grid%ntrack) :: tracks
    real(Float64) :: photons !! photon flux
    real(Float64), dimension(nlevs) :: states  !! Density of n-states
    real(Float64), dimension(nlevs) :: denn
    integer :: nwav
    real(Float64) :: etov2, energy, pitch
    real(Float64) :: dE, dP, dEdP
    real(Float64), dimension(:), allocatable :: ebarr, ptcharr
    integer, dimension(1) :: ienergy, ipitch
    real(Float64), dimension(3) :: randomu3
    !! Number of particles to launch
    real(Float64) :: fbm_denf,phase_area, max_papprox
    integer, dimension(beam_grid%ngrid) :: cell_ind
    real(Float64), dimension(beam_grid%nx,beam_grid%ny,beam_grid%nz) :: papprox
    integer(Int32), dimension(beam_grid%nx,beam_grid%ny,beam_grid%nz) :: nlaunch
    nwav = inputs%nlambda_wght
    !! define arrays
    !! define energy - array
    allocate(ebarr(inputs%ne_wght))
    do i=1,inputs%ne_wght
        ebarr(i)=real(i-0.5)*inputs%emax_wght/real(inputs%ne_wght)
    enddo
    dE = abs(ebarr(2)-ebarr(1))
    !! define pitch - array
    allocate(ptcharr(inputs%np_wght))
    do i=1,inputs%np_wght
        ptcharr(i)=real(i-0.5)*2./real(inputs%np_wght)-1.
    enddo
    dP = abs(ptcharr(2)-ptcharr(1))
    dEdP = dE*dP
    phase_area = dEdP*real(inputs%np_wght)*real(inputs%ne_wght)
    !! allocate storage arrays
    allocate(fweight%weight(nwav,inputs%ne_wght,inputs%np_wght,spec_chords%nchan))
    allocate(fweight%mean_f(inputs%ne_wght,inputs%np_wght,spec_chords%nchan))
    if(inputs%verbose.ge.1) then
        write(*,'(T3,"Number of Channels: ",i5)') spec_chords%nchan
        write(*,'(T3,"Nlambda: ",i4)') nwav
        write(*,'(T3,"Nenergy: ",i3)') inputs%ne_wght
        write(*,'(T3,"Maximum Energy: ",f7.2)') inputs%emax_wght
        write(*,'(T3,"LOS averaged: ",a)') "False"
    endif
    !! zero out arrays
    fweight%weight = 0.d0
    fweight%mean_f = 0.d0
    etov2 = 1.d0/(v2_to_E_per_amu*inputs%ab)
    !! Estimate how many particles to launch in each cell
    papprox=0.d0
    do ic=1,beam_grid%ngrid
        call ind2sub(beam_grid%dims,ic,ind)
        i = ind(1) ; j = ind(2) ; k = ind(3)
        call get_plasma(plasma,ind=ind)
        if(.not.plasma%in_plasma) cycle
        papprox(i,j,k)=(sum(neut%full(:,i,j,k)) + &
                        sum(neut%half(:,i,j,k)) + &
                        sum(neut%third(:,i,j,k)) + &
                        sum(neut%dcx(:,i,j,k)) + &
                        sum(neut%halo(:,i,j,k)))
    enddo
    !! TODO: Remove this once we have a 3D interpolation grid
    max_papprox = maxval(papprox)
    where (papprox.lt.(max_papprox*1.d-3))
        papprox = 0.0
    endwhere
    ncell = 0
    do ic=1,beam_grid%ngrid
        call ind2sub(beam_grid%dims,ic,ind)
        i = ind(1) ; j = ind(2) ; k = ind(3)
        if(papprox(i,j,k).gt.0.0) then
            ncell = ncell + 1
            cell_ind(ncell) = ic
        endif
    enddo
    call get_nlaunch(10*inputs%n_fida,papprox, nlaunch)
    if(inputs%verbose.ge.1) then
        write(*,'(T6,"# of markers: ",i9)') sum(nlaunch)
    endif
    !! Loop over all cells that have neutrals
    !$OMP PARALLEL DO schedule(guided) private(ic,i,j,k,ind,iion,vi,ri,rg,ienergy,ipitch, &
    !$OMP tracks,ntrack,jj,plasma,fields,rates,denn,states,photons,energy,pitch, &
    !$OMP los_intersect,randomu3,fbm_denf)
    loop_over_cells: do ic = istart, ncell, istep
        call ind2sub(beam_grid%dims,cell_ind(ic),ind)
        i = ind(1) ; j = ind(2) ; k = ind(3)
        loop_over_fast_ions: do iion=1, nlaunch(i, j, k)
            !! Sample fast ion distribution uniformally
            call randind(inputs%ne_wght, ienergy)
            call randind(inputs%np_wght, ipitch)
            call randu(randomu3)
            energy = ebarr(ienergy(1)) + dE*(randomu3(1)-0.5)
            pitch = ptcharr(ipitch(1)) + dP*(randomu3(2)-0.5)
            if(energy.le.0) cycle loop_over_fast_ions
            call randu(randomu3)
            rg = [beam_grid%xc(i),beam_grid%yc(j),beam_grid%zc(k)] + beam_grid%dr*(randomu3-0.5)
            !! Get velocity
            call get_fields(fields,pos=rg)
            if(.not.fields%in_plasma) cycle loop_over_fast_ions
            call gyro_correction(fields,energy,pitch,ri,vi)
            fbm_denf = 0.0
            if (inputs%dist_type.eq.1) then
                call get_ep_denf(energy,pitch,fbm_denf,coeffs=fields%c)
            endif
            !! Find the particles path through the beam grid
            call track(ri, vi, tracks, ntrack, los_intersect)
            if(.not.los_intersect) cycle loop_over_fast_ions
            if(ntrack.eq.0) cycle loop_over_fast_ions
            !! Calculate CX probability with beam and halo neutrals
            call get_beam_cx_rate(tracks(1)%ind, ri, vi, beam_ion, neut_types, rates)
            if(sum(rates).le.0.) cycle loop_over_fast_ions
            states=rates*1.d20
            !! Calculate the spectra produced in each cell along the path
            loop_along_track: do jj=1,ntrack
                call get_plasma(plasma,pos=tracks(jj)%pos)
                call colrad(plasma,beam_ion, vi, tracks(jj)%time, states, denn, photons)
                call store_fw_photons(ienergy(1), ipitch(1), &
                     tracks(jj)%pos, vi, fbm_denf, photons/nlaunch(i,j,k))
            enddo loop_along_track
        enddo loop_over_fast_ions
    enddo loop_over_cells
    !$OMP END PARALLEL DO
    fweight%weight = ((1.d-20)*phase_area/dEdP)*fweight%weight
    fweight%mean_f = ((1.d-20)*phase_area/dEdP)*fweight%mean_f
    if(inputs%verbose.ge.1) then
        write(*,*) 'write fida weights:    ' , time(time_start)
    endif
#ifdef _MPI
    call fidampi_sum(fweight%weight)
    call fidampi_sum(fweight%mean_f)
    if(fidampi_my_rank().eq.0) call write_fida_weights()
#else
    call write_fida_weights()
#endif
end subroutine fida_weights_mc
All Procedures
approx_eq approx_ge approx_le Aq_cx Aq_cx_n Aq_cx_n_adas Aq_cx_n_janev Aq_excit Aq_excit_1_2_janev Aq_excit_1_3_janev Aq_excit_1_4_janev Aq_excit_1_5_janev Aq_excit_1_janev Aq_excit_2_10_janev Aq_excit_2_3_janev Aq_excit_2_4_janev Aq_excit_2_5_janev Aq_excit_2_6_janev Aq_excit_2_7_janev Aq_excit_2_8_janev Aq_excit_2_9_janev Aq_excit_2_janev Aq_excit_3_10_janev Aq_excit_3_4_janev Aq_excit_3_5_janev Aq_excit_3_6_janev Aq_excit_3_7_janev Aq_excit_3_8_janev Aq_excit_3_9_janev Aq_excit_3_janev Aq_excit_n Aq_excit_n_janev Aq_excit_n_m Aq_ioniz Aq_ioniz_n Aq_ioniz_n_janev assignment(=) attenuate B5_cx_1_adas B5_cx_1_janev B5_cx_2_adas B5_ioniz_1_janev balance balback bb_cx_rates boundary_edge bremsstrahlung bt_cx_rates bt_maxwellian bt_maxwellian_eb bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m C6_cx_1_adas C6_cx_1_janev C6_cx_2_adas C6_cx_3_adas C6_ioniz_1_janev calc_perp_vectors check_compression_availability circle_grid_intersect cold_spec colrad comabs Comdiv cross_product cumsum d_d_fusion_he d_d_fusion_t d_t_fusion dcx dcx_spec deriv e_excit e_excit_1_2_janev e_excit_1_3_janev e_excit_1_4_janev e_excit_1_5_janev e_excit_1_janev e_excit_2_3_janev e_excit_f e_excit_n e_excit_n_m e_ioniz e_ioniz_1_janev e_ioniz_2_janev e_ioniz_3_janev e_ioniz_n eigen elmhes elmtrans fast_ion_assign ff_add ff_assign ff_subtract fida_f fida_mc fida_weights_los fida_weights_mc fidampi_clenup fidampi_init fidampi_my_rank fidampi_num_ranks fidampi_sum fidampi_sum_d0 fidampi_sum_d1 fidampi_sum_d2 fidampi_sum_d3 fidampi_sum_d4 fidampi_sum_d5 fidampi_sum_i0 fidampi_sum_i1 fidampi_sum_i2 flf_assign fs_divide fs_multiply get_beam_cx_rate get_distribution get_ep_denf get_fields get_indices get_neutron_rate get_nlaunch get_plasma get_position get_rate_matrix get_rng get_value grid_intersect gyro_correction gyro_radius gyro_range gyro_step gyro_surface gyro_surface_coordinates gyro_trajectory h5ltmake_compressed_dataset_double_f h5ltmake_compressed_dataset_double_f_1 h5ltmake_compressed_dataset_double_f_2 h5ltmake_compressed_dataset_double_f_3 h5ltmake_compressed_dataset_double_f_4 h5ltmake_compressed_dataset_double_f_5 h5ltmake_compressed_dataset_double_f_6 h5ltmake_compressed_dataset_double_f_7 h5ltmake_compressed_dataset_int_f h5ltmake_compressed_dataset_int_f_1 h5ltmake_compressed_dataset_int_f_2 h5ltmake_compressed_dataset_int_f_3 h5ltmake_compressed_dataset_int_f_4 h5ltmake_compressed_dataset_int_f_5 h5ltmake_compressed_dataset_int_f_6 h5ltmake_compressed_dataset_int_f_7 h5ltread_dataset_double_scalar_f h5ltread_dataset_int_scalar_f halo halo_spec hit_npa_detector hqr2 hqrvec in_boundary in_grid in_gyro_surface in_plasma ind2sub interpol interpol1D_arr interpol1D_coeff interpol1D_coeff_arr interpol2D_2D_arr interpol2D_arr interpol2D_coeff interpol2D_coeff_arr interpol_coeff lff_assign lflf_add lflf_assign lflf_subtract lfs_divide lfs_multiply line_basis line_gyro_surface_intersect line_plane_intersect linsolve lplp_add lplp_assign lplp_subtract lpp_assign lps_divide lps_multiply lubksb ludcmp m_spread make_beam_grid matinv mc_fastion mc_halo mc_nbi mc_nbi_cell nbi_spec ndmc neutron_f neutron_mc norm2 npa_f npa_gyro_range npa_mc npa_part_assign npa_weights operator(*) operator(+) operator(-) operator(/) outerprod p_cx p_cx_1 p_cx_1_1_adas p_cx_1_2_adas p_cx_1_3_adas p_cx_1_4_adas p_cx_1_janev p_cx_2 p_cx_2_2_adas p_cx_2_3_adas p_cx_2_janev p_cx_3 p_cx_3_2_adas p_cx_3_3_adas p_cx_3_4_adas p_cx_3_5_adas p_cx_3_6inf_adas p_cx_3_janev p_cx_janev p_cx_n p_cx_n_janev p_cx_n_m p_excit p_excit_1_2_janev p_excit_1_3_janev p_excit_1_4_janev p_excit_1_5_janev p_excit_1_6_janev p_excit_1_janev p_excit_2_10_janev p_excit_2_3_janev p_excit_2_4_janev p_excit_2_5_janev p_excit_2_6_janev p_excit_2_7_janev p_excit_2_8_janev p_excit_2_9_janev p_excit_2_janev p_excit_3_10_janev p_excit_3_4_janev p_excit_3_5_janev p_excit_3_6_janev p_excit_3_7_janev p_excit_3_8_janev p_excit_3_9_janev p_excit_3_janev p_excit_n p_excit_n_m p_ioniz p_ioniz_1_janev p_ioniz_2_omullane p_ioniz_3_omullane p_ioniz_4_omullane p_ioniz_5_omullane p_ioniz_n pfida_f pfida_mc pitch_to_vec plane_basis plp_assign pnpa_f pnpa_mc pp_add pp_assign pp_subtract print_banner print_default_namelist ps_divide ps_multiply randind randind_cdf randn randu read_atomic_cross read_atomic_rate read_atomic_transitions read_beam read_chords read_distribution read_equilibrium read_f read_inputs read_mc read_neutrals read_npa read_nuclear_rates read_tables rng_init rng_normal rng_seed rng_uniform RSWAP sf_multiply simpsons_rule slf_multiply slp_multiply sp_multiply sparse spectrum store_bes_photons store_births store_fida_photons store_fw_photons store_fw_photons_at_chan store_neutrals store_neutrons store_npa store_photons sub2ind swap tb_zyx time track uvw_to_xyz write_bb_D_D write_bb_D_T write_bb_H_Aq write_bb_H_e write_bb_H_H write_beam_grid write_birth_profile write_bt_D_D write_bt_D_T write_bt_H_Aq write_bt_H_e write_bt_H_H write_einstein write_fida_weights write_neutrals write_neutrons write_npa write_npa_weights write_spectra xyz_to_uvw
Call graph
fida_weights_mc calls store_fw_photons, ind2sub, randind, randu, get_fields, track, fidampi_my_rank, get_plasma, write_fida_weights, get_beam_cx_rate, fidampi_sum, colrad, gyro_correction, get_ep_denf, get_nlaunch
store_fw_photons calls get_fields, get_indices, store_fw_photons_at_chan
get_fields calls get_position, calc_perp_vectors, in_plasma
track calls get_indices, in_plasma
get_plasma calls get_position, in_plasma
write_fida_weights calls h5close_f, h5ltmake_compressed_dataset_double_f, h5open_f, h5ltset_attribute_string_f, h5ltmake_dataset_int_f, h5fclose_f, h5fcreate_f
get_beam_cx_rate calls get_plasma, bb_cx_rates, bt_cx_rates
fidampi_sum calls fidampi_sum_d4, fidampi_sum_i2, fidampi_sum_d5, fidampi_sum_i0, fidampi_sum_d2, fidampi_sum_i1, fidampi_sum_d3, fidampi_sum_d0, fidampi_sum_d1
colrad calls get_rate_matrix, linsolve, eigen
gyro_correction calls randu, pitch_to_vec, gyro_step
get_ep_denf calls get_position, xyz_to_uvw, interpol
get_nlaunch calls ind2sub, randind_cdf, cumsum, rng_init
store_fw_photons_at_chan calls spectrum
in_plasma calls xyz_to_uvw, interpol_coeff
interpol_coeff calls interpol2d_coeff_arr, interpol2d_coeff, interpol1d_coeff, interpol1d_coeff_arr
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_6, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_4
h5ltmake_compressed_dataset_double_f_6 calls h5pset_shuffle_f, h5pcreate_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5pclose_f, h5dclose_f, h5dcreate_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f_2 calls h5pset_shuffle_f, h5pcreate_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5pclose_f, h5dclose_f, h5dcreate_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f_5 calls h5pset_shuffle_f, h5pcreate_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5pclose_f, h5dclose_f, h5dcreate_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f_3 calls h5pset_shuffle_f, h5pcreate_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5pclose_f, h5dclose_f, h5dcreate_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f_1 calls h5pset_shuffle_f, h5pcreate_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5pclose_f, h5dclose_f, h5dcreate_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f_7 calls h5pset_shuffle_f, h5pcreate_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5pclose_f, h5dclose_f, h5dcreate_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f_4 calls h5pset_shuffle_f, h5pcreate_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5pclose_f, h5dclose_f, h5dcreate_f, h5ltmake_dataset_double_f
bb_cx_rates calls interpol_coeff
bt_cx_rates calls interpol_coeff
fidampi_sum_d4 calls mpi_allreduce
fidampi_sum_i2 calls mpi_allreduce
fidampi_sum_d5 calls mpi_allreduce
fidampi_sum_i0 calls mpi_allreduce
fidampi_sum_d2 calls mpi_allreduce
fidampi_sum_i1 calls mpi_allreduce
fidampi_sum_d3 calls mpi_allreduce
fidampi_sum_d0 calls mpi_allreduce
fidampi_sum_d1 calls mpi_allreduce
get_rate_matrix calls interpol_coeff
linsolve calls dgetrs, dgetrf, matinv
eigen calls balance, hqr2, balback, elmhes, elmtrans
matinv calls ludcmp, lubksb
ludcmp calls swap, outerprod
balance calls rswap
hqr2 calls hqrvec
balback calls rswap
elmhes calls rswap
hqrvec calls comdiv
gyro_step calls cross_product
interpol calls interpol1d_arr, interpol2d_2d_arr, interpol2d_arr
interpol1d_arr calls interpol_coeff
interpol2d_2d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
rng_init calls fidampi_my_rank, rng_seed
fidasim calls fida_weights_mc