fida_weights_los – FIDASIM
fida_weights_los Subroutine
186 statements
Source File
public subroutine fida_weights_los()
Calculates LOS averaged FIDA weights
Arguments
None
Calls
Called By
Source Code
fida_weights_los
Source Code
subroutine fida_weights_los
    !+ Calculates LOS averaged FIDA weights
    type(LocalProfiles) :: plasma, plasma_cell
    type(LocalEMFields) :: fields, fields_cell
    real(Float64) :: denf
    real(Float64) :: wght, wght_tot
    real(Float64) :: photons !! photon flux
    real(Float64) :: length
    type(ParticleTrack), dimension(beam_grid%ntrack) :: tracks
    integer :: nwav
    integer(Int32) :: i, j, k, ienergy, cid, cind
    integer(Int32) :: ipitch, igyro, icell, ichan
    real(Float64), dimension(:), allocatable :: ebarr,ptcharr,phiarr
    real(Float64), dimension(:,:), allocatable :: mean_f
    real(Float64), dimension(3) :: vi, vi_norm, vp
    real(Float64), dimension(3) :: vnbi_f, vnbi_h, vnbi_t, vhalo
    real(Float64), dimension(3) :: r_enter, r_exit
    real(Float64) :: vabs, dE, dP
    !! Determination of the CX probability
    real(Float64), dimension(nlevs) :: fdens,hdens,tdens,dcxdens,halodens
    real(Float64), dimension(nlevs) :: rates
    real(Float64), dimension(nlevs) :: states ! Density of n-states
    real(Float64), dimension(nlevs) :: denn  ! Density of n-states
    !! COLRAD
    real(Float64) :: dt, max_dens, dlength, sigma_pi
    type(LOSInters) :: inter
    real(Float64) :: eb, ptch, phi
    !! Solution of differential equation
    integer, dimension(3) :: ind  !!actual cell
    real(Float64), dimension(3) :: ri
    integer(Int32) :: ntrack
    logical :: inp
    real(Float64):: etov2, dEdP
    nwav = inputs%nlambda_wght
    !! Define energy array
    allocate(ebarr(inputs%ne_wght))
    do i=1,inputs%ne_wght
        ebarr(i)=real(i-0.5)*inputs%emax_wght/real(inputs%ne_wght)
    enddo
    dE = abs(ebarr(2)-ebarr(1))
    !! Define pitch array
    allocate(ptcharr(inputs%np_wght))
    do i=1,inputs%np_wght
        ptcharr(i)=real(i-0.5)*2./real(inputs%np_wght)-1.
    enddo
    dP = abs(ptcharr(2)-ptcharr(1))
    dEdP = dE*dP
    !! define gyro - array
    allocate(phiarr(inputs%nphi_wght))
    do i=1,inputs%nphi_wght
        phiarr(i)=real(i-0.5)*2.d0*pi/real(inputs%nphi_wght)
    enddo
    !! allocate storage arrays
    allocate(fweight%mean_f(inputs%ne_wght,inputs%np_wght,spec_chords%nchan))
    allocate(fweight%weight(nwav,inputs%ne_wght,inputs%np_wght,spec_chords%nchan))
    allocate(mean_f(inputs%ne_wght,inputs%np_wght))
    !! zero out arrays
    fweight%weight = 0.d0
    fweight%mean_f = 0.d0
    mean_f = 0.d0
    if(inputs%verbose.ge.1) then
        write(*,'(T3,"Number of Channels: ",i5)') spec_chords%nchan
        write(*,'(T3,"Nlambda: ",i4)') nwav
        write(*,'(T3,"Nenergy: ",i3)') inputs%ne_wght
        write(*,'(T3,"Npitch: ",i3)') inputs%np_wght
        write(*,'(T3,"Ngyro: ", i3)') inputs%nphi_wght
        write(*,'(T3,"Maximum Energy: ",f7.2)') inputs%emax_wght
        write(*,'(T3,"LOS averaged: ",a)') "True"
        write(*,*) ''
    endif
    etov2 = 1.0/(v2_to_E_per_amu*inputs%ab)
    chan_loop: do ichan=1,spec_chords%nchan
        fdens = 0.d0 ; hdens = 0.d0 ; tdens = 0.d0
        halodens = 0.d0 ; dcxdens = 0.d0
        plasma = plasma*0.d0
        fields = fields*0.d0
        wght_tot = 0.d0
        mean_f = 0.d0
        do k=1,beam_grid%nz
            do j=1,beam_grid%ny
                x_loop: do i=1,beam_grid%nx
                    inter = spec_chords%inter(i,j,k)
                    cid = 0
                    cind = 0
                    do while (cid.ne.ichan.and.cind.lt.inter%nchan)
                        cind = cind + 1
                        cid = inter%los_elem(cind)%id
                    enddo
                    if(cid.eq.ichan) then
                        ind = [i,j,k]
                        ri = [beam_grid%xc(i), beam_grid%yc(j), beam_grid%zc(k)]
                        call in_plasma(ri,inp)
                        if(.not.inp) cycle x_loop
                        dlength = inter%los_elem(cind)%length
                        fdens = fdens + neut%full(:,i,j,k)*dlength
                        hdens = hdens + neut%half(:,i,j,k)*dlength
                        tdens = tdens + neut%third(:,i,j,k)*dlength
                        dcxdens = dcxdens + neut%dcx(:,i,j,k)*dlength
                        halodens = halodens + neut%halo(:,i,j,k)*dlength
                        wght = (neut%full(3,i,j,k) + neut%half(3,i,j,k) + &
                                neut%third(3,i,j,k) + neut%dcx(3,i,j,k) + &
                                neut%halo(3,i,j,k))*dlength
                        call get_plasma(plasma_cell,pos=ri)
                        call get_fields(fields_cell,pos=ri)
                        plasma = plasma + wght*plasma_cell
                        fields = fields + wght*fields_cell
                        if (inputs%dist_type.eq.1) then
                            do ipitch=1,inputs%np_wght
                                do ienergy=1,inputs%ne_wght
                                    call get_ep_denf(ebarr(ienergy),ptcharr(ipitch),denf,coeffs=fields_cell%c)
                                    mean_f(ienergy,ipitch) = mean_f(ienergy,ipitch) + wght*denf
                                enddo
                            enddo
                        endif
                        wght_tot = wght_tot + wght
                    endif
                enddo x_loop
            enddo
        enddo
        if(wght_tot.le.0) then
            if(inputs%verbose.ge.1) then
                write(*,'(T4,"Skipping channel ",i5,": Neutral density is zero")') ichan
            endif
            cycle chan_loop
        else
            plasma = plasma/wght_tot
            plasma%in_plasma = .True.
            fields = fields/wght_tot
            fields%in_plasma= .True.
            mean_f = mean_f/wght_tot
            if(inputs%verbose.ge.1) then
                write(*,'(T4,"Channel: ",i5)') ichan
                write(*,'(T4,"Radius: ",f7.2)') spec_chords%radius(ichan)
                write(*,'(T4,"Mean Fast-ion Density: ",ES14.5)') sum(mean_f)*dEdP
                write(*,*)''
            endif
        endif
        ri = plasma%pos
        vp = ri - spec_chords%los(ichan)%lens
        vnbi_f = ri - nbi%src
        vnbi_f = vnbi_f/norm2(vnbi_f)*nbi%vinj
        vnbi_h = vnbi_f/sqrt(2.d0)
        vnbi_t = vnbi_f/sqrt(3.d0)
        sigma_pi = spec_chords%los(ichan)%sigma_pi
        dlength = 1.d0
        !$OMP PARALLEL DO schedule(guided) collapse(3) private(eb,vabs,ptch,phi,vi,vi_norm, &
        !$OMP& r_enter,r_exit,length,max_dens,ind,tracks,ntrack,dt,icell,states,rates, &
        !$OMP& vhalo,denn,denf,photons,ienergy,ipitch,igyro)
        do ienergy=istart,inputs%ne_wght,istep
            do ipitch=1,inputs%np_wght
                do igyro=1,inputs%nphi_wght
                    eb = ebarr(ienergy)
                    vabs = sqrt(eb*etov2)
                    ptch = ptcharr(ipitch)
                    phi = phiarr(igyro)
                    call pitch_to_vec(ptch,phi,fields,vi_norm)
                    vi = vabs*vi_norm
                    call grid_intersect(ri,vi,length,r_enter,r_exit)
                    call track(r_enter, vi, tracks, ntrack)
                    max_dens = 0.d0
                    do icell=1,ntrack
                        ind = tracks(icell)%ind
                        tracks(icell)%flux = neut%full(3,ind(1),ind(2),ind(3))  + &
                                             neut%half(3,ind(1),ind(2),ind(3))  + &
                                             neut%third(3,ind(1),ind(2),ind(3)) + &
                                             neut%dcx(3,ind(1),ind(2),ind(3))   + &
                                             neut%halo(3,ind(1),ind(2),ind(3))
                        if(tracks(icell)%flux.gt.max_dens) max_dens=tracks(icell)%flux
                    enddo
                    dt = 0.d0
                    do icell=1,ntrack
                        if(tracks(icell)%flux.gt.(0.5*max_dens)) then
                            dt = dt + tracks(icell)%time
                        endif
                    enddo
                    states=0.d0
                    call bb_cx_rates(fdens,vi,vnbi_f,rates)
                    states = states + rates
                    call bb_cx_rates(hdens,vi,vnbi_h,rates)
                    states = states + rates
                    call bb_cx_rates(tdens,vi,vnbi_t,rates)
                    states = states + rates
                    call bt_cx_rates(plasma, dcxdens + halodens, vi, beam_ion, rates)
                    states = states + rates
                    call colrad(plasma,beam_ion,vi,dt,states,denn,photons)
                    denf = mean_f(ienergy,ipitch)*dEdP
                    photons = photons/real(inputs%nphi_wght)
                    call store_fw_photons_at_chan(ichan, ienergy, ipitch, &
                         vp, vi, fields, dlength, sigma_pi, denf, photons)
                enddo
            enddo
        enddo
        !$OMP END PARALLEL DO
    enddo chan_loop
    fweight%mean_f = fweight%mean_f/(dEdP)
    if(inputs%verbose.ge.1) then
        write(*,*) 'write fida weights:    ' , time(time_start)
    endif
#ifdef _MPI
    call parallel_sum(fweight%weight)
    call parallel_sum(fweight%mean_f)
    if(my_rank().eq.0) call write_fida_weights()
#else
    call write_fida_weights()
#endif
end subroutine fida_weights_los
All Procedures
approx_eq approx_ge approx_le Aq_cx Aq_cx_n Aq_cx_n_adas Aq_cx_n_janev Aq_excit Aq_excit_1_2_janev Aq_excit_1_3_janev Aq_excit_1_4_janev Aq_excit_1_5_janev Aq_excit_1_janev Aq_excit_2_10_janev Aq_excit_2_3_janev Aq_excit_2_4_janev Aq_excit_2_5_janev Aq_excit_2_6_janev Aq_excit_2_7_janev Aq_excit_2_8_janev Aq_excit_2_9_janev Aq_excit_2_janev Aq_excit_3_10_janev Aq_excit_3_4_janev Aq_excit_3_5_janev Aq_excit_3_6_janev Aq_excit_3_7_janev Aq_excit_3_8_janev Aq_excit_3_9_janev Aq_excit_3_janev Aq_excit_n Aq_excit_n_janev Aq_excit_n_m Aq_ioniz Aq_ioniz_n Aq_ioniz_n_janev assignment(=) attenuate B5_cx_1_adas B5_cx_1_janev B5_cx_2_adas B5_ioniz_1_janev balance balback bb_cx_rates boundary_edge bremsstrahlung bt_cx_rates bt_maxwellian bt_maxwellian_eb bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m C6_cx_1_adas C6_cx_1_janev C6_cx_2_adas C6_cx_3_adas C6_ioniz_1_janev calc_perp_vectors check_compression_availability circle_grid_intersect cleanup_mpi cold_spec colrad comabs Comdiv cross_product cumsum d_d_fusion_he d_d_fusion_t d_t_fusion dcx dcx_spec deriv e_excit e_excit_1_2_janev e_excit_1_3_janev e_excit_1_4_janev e_excit_1_5_janev e_excit_1_janev e_excit_2_3_janev e_excit_f e_excit_n e_excit_n_m e_ioniz e_ioniz_1_janev e_ioniz_2_janev e_ioniz_3_janev e_ioniz_n eigen elmhes elmtrans fast_ion_assign ff_add ff_assign ff_subtract fida_f fida_mc fida_weights_los fida_weights_mc flf_assign fs_divide fs_multiply get_beam_cx_rate get_distribution get_ep_denf get_fields get_indices get_neutron_rate get_nlaunch get_plasma get_position get_rate_matrix get_rng get_value grid_intersect gyro_correction gyro_radius gyro_range gyro_step gyro_surface gyro_surface_coordinates gyro_trajectory h5ltmake_compressed_dataset_double_f h5ltmake_compressed_dataset_double_f_1 h5ltmake_compressed_dataset_double_f_2 h5ltmake_compressed_dataset_double_f_3 h5ltmake_compressed_dataset_double_f_4 h5ltmake_compressed_dataset_double_f_5 h5ltmake_compressed_dataset_double_f_6 h5ltmake_compressed_dataset_double_f_7 h5ltmake_compressed_dataset_int_f h5ltmake_compressed_dataset_int_f_1 h5ltmake_compressed_dataset_int_f_2 h5ltmake_compressed_dataset_int_f_3 h5ltmake_compressed_dataset_int_f_4 h5ltmake_compressed_dataset_int_f_5 h5ltmake_compressed_dataset_int_f_6 h5ltmake_compressed_dataset_int_f_7 h5ltread_dataset_double_scalar_f h5ltread_dataset_int_scalar_f halo halo_spec hit_npa_detector hqr2 hqrvec in_boundary in_grid in_gyro_surface in_plasma ind2sub init_mpi interpol interpol1D_arr interpol1D_coeff interpol1D_coeff_arr interpol2D_2D_arr interpol2D_arr interpol2D_coeff interpol2D_coeff_arr interpol_coeff lff_assign lflf_add lflf_assign lflf_subtract lfs_divide lfs_multiply line_basis line_gyro_surface_intersect line_plane_intersect linsolve lplp_add lplp_assign lplp_subtract lpp_assign lps_divide lps_multiply lubksb ludcmp m_spread make_beam_grid matinv mc_fastion mc_halo mc_nbi mc_nbi_cell my_rank nbi_spec ndmc neutron_f neutron_mc norm2 npa_f npa_gyro_range npa_mc npa_part_assign npa_weights num_ranks operator(*) operator(+) operator(-) operator(/) outerprod p_cx p_cx_1 p_cx_1_1_adas p_cx_1_2_adas p_cx_1_3_adas p_cx_1_4_adas p_cx_1_janev p_cx_2 p_cx_2_2_adas p_cx_2_3_adas p_cx_2_janev p_cx_3 p_cx_3_2_adas p_cx_3_3_adas p_cx_3_4_adas p_cx_3_5_adas p_cx_3_6inf_adas p_cx_3_janev p_cx_janev p_cx_n p_cx_n_janev p_cx_n_m p_excit p_excit_1_2_janev p_excit_1_3_janev p_excit_1_4_janev p_excit_1_5_janev p_excit_1_6_janev p_excit_1_janev p_excit_2_10_janev p_excit_2_3_janev p_excit_2_4_janev p_excit_2_5_janev p_excit_2_6_janev p_excit_2_7_janev p_excit_2_8_janev p_excit_2_9_janev p_excit_2_janev p_excit_3_10_janev p_excit_3_4_janev p_excit_3_5_janev p_excit_3_6_janev p_excit_3_7_janev p_excit_3_8_janev p_excit_3_9_janev p_excit_3_janev p_excit_n p_excit_n_m p_ioniz p_ioniz_1_janev p_ioniz_2_omullane p_ioniz_3_omullane p_ioniz_4_omullane p_ioniz_5_omullane p_ioniz_n parallel_sum parallel_sum_d0 parallel_sum_d1 parallel_sum_d2 parallel_sum_d3 parallel_sum_d4 parallel_sum_d5 parallel_sum_i0 parallel_sum_i1 parallel_sum_i2 pfida_f pfida_mc pitch_to_vec plane_basis plp_assign pnpa_f pnpa_mc pp_add pp_assign pp_subtract print_banner print_default_namelist ps_divide ps_multiply randind randind_cdf randn randu read_atomic_cross read_atomic_rate read_atomic_transitions read_beam read_chords read_distribution read_equilibrium read_f read_inputs read_mc read_neutrals read_npa read_nuclear_rates read_tables rng_init rng_normal rng_seed rng_uniform RSWAP sf_multiply simpsons_rule slf_multiply slp_multiply sp_multiply sparse spectrum store_bes_photons store_births store_fida_photons store_fw_photons store_fw_photons_at_chan store_neutrals store_neutrons store_npa store_photons sub2ind swap tb_zyx time track uvw_to_xyz write_bb_D_D write_bb_D_T write_bb_H_Aq write_bb_H_e write_bb_H_H write_beam_grid write_birth_profile write_bt_D_D write_bt_D_T write_bt_H_Aq write_bt_H_e write_bt_H_H write_einstein write_fida_weights write_neutrals write_neutrons write_npa write_npa_weights write_spectra xyz_to_uvw
Call graph
fida_weights_los calls in_plasma, get_ep_denf, bt_cx_rates, bb_cx_rates, store_fw_photons_at_chan, parallel_sum, get_fields, track, grid_intersect, write_fida_weights, my_rank, pitch_to_vec, get_plasma, colrad
in_plasma calls xyz_to_uvw, interpol_coeff
get_ep_denf calls xyz_to_uvw, interpol, get_position
bt_cx_rates calls interpol_coeff
bb_cx_rates calls interpol_coeff
store_fw_photons_at_chan calls spectrum
parallel_sum calls parallel_sum_i1, parallel_sum_d3, parallel_sum_d2, parallel_sum_i2, parallel_sum_d4, parallel_sum_d0, parallel_sum_d5, parallel_sum_d1, parallel_sum_i0
get_fields calls in_plasma, get_position, calc_perp_vectors
track calls in_plasma, get_indices
write_fida_weights calls h5ltmake_compressed_dataset_double_f, h5ltset_attribute_string_f, h5close_f, h5open_f, h5fcreate_f, h5ltmake_dataset_int_f, h5fclose_f
get_plasma calls in_plasma, get_position
colrad calls eigen, get_rate_matrix, linsolve
interpol_coeff calls interpol2d_coeff_arr, interpol1d_coeff_arr, interpol1d_coeff, interpol2d_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
interpol calls interpol1d_arr, interpol2d_2d_arr, interpol2d_arr
interpol1d_arr calls interpol_coeff
interpol2d_2d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
parallel_sum_i1 calls mpi_allreduce
parallel_sum_d3 calls mpi_allreduce
parallel_sum_d2 calls mpi_allreduce
parallel_sum_i2 calls mpi_allreduce
parallel_sum_d4 calls mpi_allreduce
parallel_sum_d0 calls mpi_allreduce
parallel_sum_d5 calls mpi_allreduce
parallel_sum_d1 calls mpi_allreduce
parallel_sum_i0 calls mpi_allreduce
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_6, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_4, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_1
h5ltmake_compressed_dataset_double_f_7 calls h5ltmake_dataset_double_f, h5pclose_f, h5sclose_f, h5pset_deflate_f, h5dclose_f, h5screate_simple_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f, h5pcreate_f, h5pset_shuffle_f
h5ltmake_compressed_dataset_double_f_2 calls h5ltmake_dataset_double_f, h5pclose_f, h5sclose_f, h5pset_deflate_f, h5dclose_f, h5screate_simple_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f, h5pcreate_f, h5pset_shuffle_f
h5ltmake_compressed_dataset_double_f_6 calls h5ltmake_dataset_double_f, h5pclose_f, h5sclose_f, h5pset_deflate_f, h5dclose_f, h5screate_simple_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f, h5pcreate_f, h5pset_shuffle_f
h5ltmake_compressed_dataset_double_f_3 calls h5ltmake_dataset_double_f, h5pclose_f, h5sclose_f, h5pset_deflate_f, h5dclose_f, h5screate_simple_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f, h5pcreate_f, h5pset_shuffle_f
h5ltmake_compressed_dataset_double_f_4 calls h5ltmake_dataset_double_f, h5pclose_f, h5sclose_f, h5pset_deflate_f, h5dclose_f, h5screate_simple_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f, h5pcreate_f, h5pset_shuffle_f
h5ltmake_compressed_dataset_double_f_5 calls h5ltmake_dataset_double_f, h5pclose_f, h5sclose_f, h5pset_deflate_f, h5dclose_f, h5screate_simple_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f, h5pcreate_f, h5pset_shuffle_f
h5ltmake_compressed_dataset_double_f_1 calls h5ltmake_dataset_double_f, h5pclose_f, h5sclose_f, h5pset_deflate_f, h5dclose_f, h5screate_simple_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f, h5pcreate_f, h5pset_shuffle_f
eigen calls balance, hqr2, balback, elmhes, elmtrans
get_rate_matrix calls interpol_coeff
linsolve calls dgetrf, dgetrs, matinv
balance calls rswap
hqr2 calls hqrvec
balback calls rswap
elmhes calls rswap
hqrvec calls comdiv
matinv calls ludcmp, lubksb
ludcmp calls swap, outerprod
fidasim calls fida_weights_los