get_passive_grid_indices – FIDASIM
get_passive_grid_indices Subroutine
40 statements
Source File
public subroutine get_passive_grid_indices(pos, ind, input_coords)
Find closest pass_grid indices ind to position pos
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in), dimension(3) :: pos
Position [cm]
integer(kind=Int32), intent(out), dimension(3) :: ind
Closest indices to position
integer, intent(in), optional :: input_coords
Indicates coordinate system of pos. Beam grid (0), machine (1) and cylindrical (2)
Calls
Called by
Contents
Source Code
get_passive_grid_indices
Source Code
subroutine get_passive_grid_indices(pos, ind, input_coords)
    !+ Find closest [[libfida:pass_grid]] indices `ind` to position `pos`
    real(Float64),  dimension(3), intent(in)  :: pos
        !+ Position [cm]
    integer(Int32), dimension(3), intent(out) :: ind
        !+ Closest indices to position
    integer, intent(in), optional             :: input_coords
        !+ Indicates coordinate system of `pos`. Beam grid (0), machine (1) and cylindrical (2)
    real(Float64),  dimension(3) :: mini, differentials, loc
    integer(Int32), dimension(3) :: maxind
    integer :: i, ics
    if(present(input_coords)) then
        ics = input_coords
    else
        ics = 2
    endif
    if(ics.eq.0) then
        call xyz_to_cyl(pos, loc)
    endif
    if(ics.eq.1) then
        loc(1) = sqrt(pos(1)*pos(1) + pos(2)*pos(2))
        loc(2) = pos(3)
        loc(3) = atan2(pos(2),pos(1))
    endif
    if(ics.eq.2) then
        loc(1) = pos(1)
        loc(2) = pos(2)
        loc(3) = pos(3)
    endif
    maxind(1) = pass_grid%nr
    maxind(2) = pass_grid%nz
    maxind(3) = pass_grid%nphi
    mini(1) = minval(pass_grid%r)
    mini(2) = minval(pass_grid%z)
    mini(3) = minval(pass_grid%phi)
    differentials(1) = pass_grid%dr
    differentials(2) = pass_grid%dz
    differentials(3) = pass_grid%dphi
    do i=1,3
        ind(i) = floor((loc(i)-mini(i))/differentials(i)) + 1
        if (ind(i).gt.maxind(i)) ind(i)=maxind(i)
        if (ind(i).lt.1) ind(i)=1
    enddo
end subroutine get_passive_grid_indices
Call graph
get_passive_grid_indices calls xyz_to_cyl
xyz_to_cyl calls xyz_to_uvw, uvw_to_cyl
track_cylindrical calls get_passive_grid_indices
store_photon_birth calls get_passive_grid_indices
store_photons calls get_passive_grid_indices
store_fida_photons calls store_photons
halo calls store_photon_birth, store_photons
make_diagnostic_grids calls track_cylindrical
halo_spec calls store_photons
pfida_f calls track_cylindrical, store_photon_birth, store_fida_photons
pfida_mc calls track_cylindrical, store_photon_birth, store_fida_photons
store_nbi_photons calls store_photons
nbi_spec calls store_photons
cold_spec calls store_photons
dcx_spec calls store_photons
fida_f calls store_photon_birth, store_fida_photons
fida_mc calls store_photon_birth, store_fida_photons
dcx calls store_photon_birth, store_photons
fidasim calls halo, make_diagnostic_grids, halo_spec, pfida_f, pfida_mc, nbi_spec, cold_spec, dcx_spec, fida_f, fida_mc, dcx, ndmc
ndmc calls store_nbi_photons