gyro_radius – FIDASIM
gyro_radius Function
19 statements
Source File
public function gyro_radius(fields, energy, pitch, Ai) result(gyro_rad)
Calculates mean gyro-radius
Arguments
Type Intent Optional Attributes Name
type(LocalEMFields), intent(in) :: fields
Electromagnetic fields at guiding center
real(kind=Float64), intent(in) :: energy
Energy of particle
real(kind=Float64), intent(in) :: pitch
Particle pitch w.r.t the magnetic field
real(kind=Float64), intent(in) :: Ai
Atomic Mass of ion
Return Value real(kind=Float64)
Mean gyro-radius
Calls
Contents
Source Code
gyro_radius
Source Code
function gyro_radius(fields, energy, pitch, Ai) result (gyro_rad)
    !+ Calculates mean gyro-radius
    type(LocalEMFields), intent(in)          :: fields
        !+ Electromagnetic fields at guiding center
    real(Float64), intent(in)                :: energy
        !+ Energy of particle
    real(Float64), intent(in)                :: pitch
        !+ Particle pitch w.r.t the magnetic field
    real(Float64), intent(in)                :: Ai
        !+ Atomic Mass of ion
    real(Float64) :: gyro_rad
        !+ Mean gyro-radius
    real(Float64), dimension(3) :: vi_norm, r_step
    real(Float64) :: vabs, phi
    integer :: i,n
    vabs  = sqrt(energy/(v2_to_E_per_amu*Ai))
    gyro_rad = 0.d0
    n = 6
    do i=1,n
        phi = i*2*pi/n
        call pitch_to_vec(pitch, phi, fields, vi_norm)
        call gyro_step(vabs*vi_norm, fields, Ai, r_step)
        gyro_rad = gyro_rad + norm2(r_step)/n
    enddo
end function gyro_radius
Call graph
gyro_radius calls pitch_to_vec, gyro_step
gyro_step calls cross_product