gyro_trajectory – FIDASIM
gyro_trajectory Subroutine
13 statements
Source File
public subroutine gyro_trajectory(gs, theta, ri, vi)
Calculate particle trajectory for a given gyro-angle and gyro-surface
Arguments
Type Intent Optional Attributes Name
type(GyroSurface), intent(in) :: gs
Gyro-Surface
real(kind=Float64), intent(in) :: theta
Gyro-angle
real(kind=Float64), dimension(3) :: ri
Particle position
real(kind=Float64), dimension(3) :: vi
Particle Velocity
Called by
Contents
Source Code
gyro_trajectory
Source Code
subroutine gyro_trajectory(gs, theta, ri, vi)
    !+ Calculate particle trajectory for a given gyro-angle and gyro-surface
    type(GyroSurface), intent(in) :: gs
        !+ Gyro-Surface
    real(Float64), intent(in) :: theta
        !+ Gyro-angle
    real(Float64), dimension(3) :: ri
        !+ Particle position
    real(Float64), dimension(3) :: vi
        !+ Particle Velocity
    real(Float64) :: a,b,c,th
    a = gs%axes(1)
    b = gs%axes(2)
    c = gs%axes(3)
    th = theta + pi/2
    ri = matmul(gs%basis, [a*cos(th), b*sin(th), 0.d0]) + gs%center
    vi = gs%omega*matmul(gs%basis, [-a*sin(th), b*cos(th), c])
end subroutine gyro_trajectory
Call graph
npa_mc calls gyro_trajectory
pnpa_f calls gyro_trajectory
pnpa_mc calls gyro_trajectory
npa_f calls gyro_trajectory
fidasim calls npa_mc, pnpa_f, pnpa_mc, npa_f