gyro_range – FIDASIM
gyro_range Subroutine
63 statements
Source File
public subroutine gyro_range(b, gs, gyrange, nrange)
Calculates the range(s) of gyro-angles that would land within a bounded plane
Arguments
Type Intent Optional Attributes Name
type(BoundedPlane), intent(in) :: b
Bounded Plane
type(GyroSurface), intent(in) :: gs
Gyro-surface
real(kind=Float64), intent(out), dimension(2,4) :: gyrange
(theta, dtheta) values
integer, intent(out) :: nrange
Number of ranges. 1 <= nrange <= 4
Calls
Called By
Source Code
gyro_range
Source Code
subroutine gyro_range(b, gs, gyrange, nrange)
    !+ Calculates the range(s) of gyro-angles that would land within a bounded plane
    type(BoundedPlane), intent(in)             :: b
        !+ Bounded Plane
    type(GyroSurface), intent(in)              :: gs
        !+ Gyro-surface
    real(Float64), dimension(2,4), intent(out) :: gyrange
        !+ (theta, dtheta) values
    integer, intent(out) :: nrange
        !+ Number of ranges. `1 <= nrange <= 4`
    integer :: nb, i, j, ninter
    logical :: in_gs, bin_gs
    logical, dimension(8) :: cross = .False.
    real(Float64) :: t_p, th1, th2, dth
    real(Float64), dimension(2) :: u_cur, t_i
    real(Float64), dimension(3) :: rc, p_pre, p_cur, v0, ri
    real(Float64), dimension(2,8) :: u
    real(Float64), dimension(3,50) :: bedge
    nrange = 0
    call line_plane_intersect(gs%center, gs%basis(:,3), b%origin, b%basis(:,3), rc, t_p)
    if(t_p.eq.0.0) return
    call boundary_edge(b, bedge, nb)
    p_pre = bedge(:,1)
    in_gs = in_gyro_surface(gs, p_pre)
    bin_gs = .False.
    ninter = 0
    u = 0.d0
    boundary_loop: do i=1,nb
        p_cur = bedge(:,modulo(i,nb)+1)
        v0 = p_cur - p_pre
        call line_gyro_surface_intersect(p_pre, v0, gs, t_i)
        do j=1,2
            if((t_i(j).gt.0.0).and.(t_i(j).lt.1.0)) then
                ri = p_pre + t_i(j)*v0
                call gyro_surface_coordinates(gs, ri, u_cur)
                if(u_cur(2).gt.0.0) then
                    in_gs = .not.in_gs
                    ninter = ninter + 1
                    cross(ninter) = in_gs
                    u(:,ninter) = u_cur
                endif
            endif
        enddo
        p_pre = p_cur
    enddo boundary_loop
    gyrange = 0.d0
    if((ninter.eq.0).and.(.not.bin_gs)) then
        if(in_boundary(b, rc)) then
            nrange = 1
            gyrange(:,1) = [0.d0,2*pi]
        endif
        return
    endif
    do i=1, ninter
        if(cross(i)) then
            th1 = u(1,i)
            j = modulo(i,ninter) + 1
            th2 = u(1,j)
            dth = th2-th1
            nrange = nrange + 1
            if(dth.gt.0.0) then
                gyrange(:,nrange) = [th1, dth]
            else
                gyrange(:,nrange) = [th2, -dth]
            endif
        endif
    enddo
end subroutine gyro_range
All Procedures
approx_eq approx_ge approx_le Aq_cx Aq_cx_n Aq_cx_n_adas Aq_cx_n_janev Aq_excit Aq_excit_1_2_janev Aq_excit_1_3_janev Aq_excit_1_4_janev Aq_excit_1_5_janev Aq_excit_1_janev Aq_excit_2_10_janev Aq_excit_2_3_janev Aq_excit_2_4_janev Aq_excit_2_5_janev Aq_excit_2_6_janev Aq_excit_2_7_janev Aq_excit_2_8_janev Aq_excit_2_9_janev Aq_excit_2_janev Aq_excit_3_10_janev Aq_excit_3_4_janev Aq_excit_3_5_janev Aq_excit_3_6_janev Aq_excit_3_7_janev Aq_excit_3_8_janev Aq_excit_3_9_janev Aq_excit_3_janev Aq_excit_n Aq_excit_n_janev Aq_excit_n_m Aq_ioniz Aq_ioniz_n Aq_ioniz_n_janev assignment(=) attenuate B5_cx_1_adas B5_cx_1_janev B5_cx_2_adas B5_ioniz_1_janev balance balback boundary_edge bremsstrahlung bt_maxwellian bt_maxwellian_eb bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m C6_cx_1_adas C6_cx_1_janev C6_cx_2_adas C6_cx_3_adas C6_ioniz_1_janev calc_perp_vectors check_compression_availability circle_grid_intersect colrad comabs Comdiv cross_product d_d_fusion_he d_d_fusion_t d_t_fusion dcx e_excit e_excit_1_2_janev e_excit_1_3_janev e_excit_1_4_janev e_excit_1_5_janev e_excit_1_janev e_excit_2_3_janev e_excit_f e_excit_n e_excit_n_m e_ioniz e_ioniz_1_janev e_ioniz_2_janev e_ioniz_3_janev e_ioniz_n eigen elmhes elmtrans fast_ion_assign ff_add ff_assign ff_subtract fida_f fida_mc fida_weights_los fida_weights_mc flf_assign fs_divide fs_multiply get_beam_cx_prob get_distribution get_ep_denf get_fields get_indices get_neutron_rate get_nlaunch get_plasma get_position get_rate_matrix get_value grid_intersect gyro_correction gyro_radius gyro_range gyro_step gyro_surface gyro_surface_coordinates gyro_trajectory h5ltmake_compressed_dataset_double_f h5ltmake_compressed_dataset_double_f_1 h5ltmake_compressed_dataset_double_f_2 h5ltmake_compressed_dataset_double_f_3 h5ltmake_compressed_dataset_double_f_4 h5ltmake_compressed_dataset_double_f_5 h5ltmake_compressed_dataset_double_f_6 h5ltmake_compressed_dataset_double_f_7 h5ltmake_compressed_dataset_int_f h5ltmake_compressed_dataset_int_f_1 h5ltmake_compressed_dataset_int_f_2 h5ltmake_compressed_dataset_int_f_3 h5ltmake_compressed_dataset_int_f_4 h5ltmake_compressed_dataset_int_f_5 h5ltmake_compressed_dataset_int_f_6 h5ltmake_compressed_dataset_int_f_7 h5ltread_dataset_double_scalar_f h5ltread_dataset_int_scalar_f halo hit_npa_detector hqr2 hqrvec in_boundary in_grid in_gyro_surface in_plasma ind2sub interpol interpol1D_arr interpol1D_coeff interpol1D_coeff_arr interpol2D_2D_arr interpol2D_arr interpol2D_coeff interpol2D_coeff_arr interpol_coeff lff_assign lflf_add lflf_assign lflf_subtract lfs_divide lfs_multiply line_basis line_gyro_surface_intersect line_plane_intersect lplp_add lplp_assign lplp_subtract lpp_assign lps_divide lps_multiply lubksb ludcmp m_spread make_beam_grid matinv mc_fastion mc_halo mc_nbi ndmc neut_rates neutron_f neutron_mc npa_f npa_gyro_range npa_mc npa_part_assign npa_weights operator(*) operator(+) operator(-) operator(/) outerprod p_cx p_cx_1 p_cx_1_1_adas p_cx_1_2_adas p_cx_1_3_adas p_cx_1_4_adas p_cx_1_janev p_cx_2 p_cx_2_2_adas p_cx_2_3_adas p_cx_2_janev p_cx_3 p_cx_3_2_adas p_cx_3_3_adas p_cx_3_4_adas p_cx_3_5_adas p_cx_3_6inf_adas p_cx_3_janev p_cx_janev p_cx_n p_cx_n_janev p_cx_n_m p_excit p_excit_1_2_janev p_excit_1_3_janev p_excit_1_4_janev p_excit_1_5_janev p_excit_1_6_janev p_excit_1_janev p_excit_2_10_janev p_excit_2_3_janev p_excit_2_4_janev p_excit_2_5_janev p_excit_2_6_janev p_excit_2_7_janev p_excit_2_8_janev p_excit_2_9_janev p_excit_2_janev p_excit_3_10_janev p_excit_3_4_janev p_excit_3_5_janev p_excit_3_6_janev p_excit_3_7_janev p_excit_3_8_janev p_excit_3_9_janev p_excit_3_janev p_excit_n p_excit_n_m p_ioniz p_ioniz_1_janev p_ioniz_2_omullane p_ioniz_3_omullane p_ioniz_4_omullane p_ioniz_5_omullane p_ioniz_n pitch_to_vec plane_basis plp_assign pp_add pp_assign pp_subtract print_banner print_default_namelist ps_divide ps_multiply randind randn randu read_atomic_cross read_atomic_rates read_beam read_chords read_distribution read_equilibrium read_f read_inputs read_mc read_neutrals read_npa read_nuclear_rates read_tables rng_init rng_normal rng_uniform RSWAP sf_multiply simpsons_rule slf_multiply slp_multiply sp_multiply sparse spectrum store_bes_photons store_births store_fida_photons store_fw_photons store_fw_photons_at_chan store_neutrals store_neutrons store_npa sub2ind swap tb_zyx track uvw_to_xyz write_bb_D_D write_bb_D_T write_bb_H_Aq write_bb_H_e write_bb_H_H write_beam_grid write_birth_profile write_bt_D_D write_bt_D_T write_bt_H_Aq write_bt_H_e write_bt_H_H write_dcx write_einstein write_fida_weights write_neutrals write_neutrons write_npa write_npa_weights write_spectra xyz_to_uvw
Call graph
gyro_range calls boundary_edge, line_plane_intersect, in_boundary, line_gyro_surface_intersect, in_gyro_surface, gyro_surface_coordinates
npa_gyro_range calls gyro_range
npa_f calls npa_gyro_range
npa_mc calls npa_gyro_range
fidasim calls npa_f, npa_mc