h5ltmake_compressed_dataset_double_f_6 – FIDASIM
h5ltmake_compressed_dataset_double_f_6 Subroutine
24 statements
Source File
public subroutine h5ltmake_compressed_dataset_double_f_6(loc_id, dset_name, rank, dims, buf, error)
Write a compressed 64-bit float dataset of dimension 6
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: loc_id
HDF5 file or group identifier
character(len=*), intent(in) :: dset_name
Name of the dataset to create
integer, intent(in) :: rank
Number of dimensions of dataspace
integer(kind=HSIZE_T), intent(in), dimension(*) :: dims
Array of the size of each dimension
real(kind=double), intent(in), dimension(dims(1),dims(2),dims(3),dims(4),dims(5),dims(6)) :: buf
Buffer with data to be written to the dataset
integer, intent(out) :: error
HDF5 error code
Calls
Called By
Source Code
h5ltmake_compressed_dataset_double_f_6
Source Code
subroutine h5ltmake_compressed_dataset_double_f_6(loc_id,&
           dset_name, rank, dims, buf, error )
    !+ Write a compressed 64-bit float dataset of dimension 6
    IMPLICIT NONE
    integer(hid_t), intent(in)                                   :: loc_id
        !+ HDF5 file or group identifier
    character(len=*), intent(in)                                 :: dset_name
        !+ Name of the dataset to create
    integer, intent(in)                                          :: rank
        !+ Number of dimensions of dataspace
    integer(HSIZE_T), dimension(*), intent(in)                   :: dims
        !+ Array of the size of each dimension
    real(double), intent(in), &
      dimension(dims(1),dims(2),dims(3),dims(4),dims(5),dims(6)) :: buf
        !+ Buffer with data to be written to the dataset
    integer, intent(out)                                         :: error
        !+ HDF5 error code
    integer(HID_T) :: did, sid, plist_id
    if(.not.compress_data) then
        call h5ltmake_dataset_double_f(loc_id, dset_name, rank, dims, buf, error)
    else
        call h5screate_simple_f(rank, dims, sid, error)
        call h5pcreate_f(H5P_DATASET_CREATE_F, plist_id, error)
        call h5pset_shuffle_f(plist_id, error)
        call h5pset_deflate_f(plist_id, 9, error)
        call h5pset_chunk_f(plist_id, rank, dims, error)
        call h5dcreate_f(loc_id, dset_name, H5T_NATIVE_DOUBLE, sid, &
             did, error, dcpl_id=plist_id)
        call h5dwrite_f(did, H5T_NATIVE_DOUBLE, buf, dims, error)
        call h5sclose_f(sid, error)
        call h5pclose_f(plist_id, error)
        call h5dclose_f(did, error)
    endif
end subroutine h5ltmake_compressed_dataset_double_f_6
All Procedures
approx_eq approx_ge approx_le Aq_cx Aq_cx_n Aq_cx_n_adas Aq_cx_n_janev Aq_excit Aq_excit_1_2_janev Aq_excit_1_3_janev Aq_excit_1_4_janev Aq_excit_1_5_janev Aq_excit_1_janev Aq_excit_2_10_janev Aq_excit_2_3_janev Aq_excit_2_4_janev Aq_excit_2_5_janev Aq_excit_2_6_janev Aq_excit_2_7_janev Aq_excit_2_8_janev Aq_excit_2_9_janev Aq_excit_2_janev Aq_excit_3_10_janev Aq_excit_3_4_janev Aq_excit_3_5_janev Aq_excit_3_6_janev Aq_excit_3_7_janev Aq_excit_3_8_janev Aq_excit_3_9_janev Aq_excit_3_janev Aq_excit_n Aq_excit_n_janev Aq_excit_n_m Aq_ioniz Aq_ioniz_n Aq_ioniz_n_janev assignment(=) attenuate B5_cx_1_adas B5_cx_1_janev B5_cx_2_adas B5_ioniz_1_janev balance balback bb_cx_rates boundary_edge bremsstrahlung bt_cx_rates bt_maxwellian bt_maxwellian_eb bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m C6_cx_1_adas C6_cx_1_janev C6_cx_2_adas C6_cx_3_adas C6_ioniz_1_janev calc_perp_vectors check_compression_availability circle_grid_intersect cold_spec colrad comabs Comdiv cross_product cumsum d_d_fusion_he d_d_fusion_t d_t_fusion dcx dcx_spec deriv e_excit e_excit_1_2_janev e_excit_1_3_janev e_excit_1_4_janev e_excit_1_5_janev e_excit_1_janev e_excit_2_3_janev e_excit_f e_excit_n e_excit_n_m e_ioniz e_ioniz_1_janev e_ioniz_2_janev e_ioniz_3_janev e_ioniz_n eigen elmhes elmtrans fast_ion_assign ff_add ff_assign ff_subtract fida_f fida_mc fida_weights_los fida_weights_mc fidampi_clenup fidampi_init fidampi_my_rank fidampi_num_ranks fidampi_sum fidampi_sum_d0 fidampi_sum_d1 fidampi_sum_d2 fidampi_sum_d3 fidampi_sum_d4 fidampi_sum_d5 fidampi_sum_i0 fidampi_sum_i1 fidampi_sum_i2 flf_assign fs_divide fs_multiply get_beam_cx_rate get_distribution get_ep_denf get_fields get_indices get_neutron_rate get_nlaunch get_plasma get_position get_rate_matrix get_rng get_value grid_intersect gyro_correction gyro_radius gyro_range gyro_step gyro_surface gyro_surface_coordinates gyro_trajectory h5ltmake_compressed_dataset_double_f h5ltmake_compressed_dataset_double_f_1 h5ltmake_compressed_dataset_double_f_2 h5ltmake_compressed_dataset_double_f_3 h5ltmake_compressed_dataset_double_f_4 h5ltmake_compressed_dataset_double_f_5 h5ltmake_compressed_dataset_double_f_6 h5ltmake_compressed_dataset_double_f_7 h5ltmake_compressed_dataset_int_f h5ltmake_compressed_dataset_int_f_1 h5ltmake_compressed_dataset_int_f_2 h5ltmake_compressed_dataset_int_f_3 h5ltmake_compressed_dataset_int_f_4 h5ltmake_compressed_dataset_int_f_5 h5ltmake_compressed_dataset_int_f_6 h5ltmake_compressed_dataset_int_f_7 h5ltread_dataset_double_scalar_f h5ltread_dataset_int_scalar_f halo halo_spec hit_npa_detector hqr2 hqrvec in_boundary in_grid in_gyro_surface in_plasma ind2sub interpol interpol1D_arr interpol1D_coeff interpol1D_coeff_arr interpol2D_2D_arr interpol2D_arr interpol2D_coeff interpol2D_coeff_arr interpol_coeff lff_assign lflf_add lflf_assign lflf_subtract lfs_divide lfs_multiply line_basis line_gyro_surface_intersect line_plane_intersect linsolve lplp_add lplp_assign lplp_subtract lpp_assign lps_divide lps_multiply lubksb ludcmp m_spread make_beam_grid matinv mc_fastion mc_halo mc_nbi mc_nbi_cell nbi_spec ndmc neutron_f neutron_mc norm2 npa_f npa_gyro_range npa_mc npa_part_assign npa_weights operator(*) operator(+) operator(-) operator(/) outerprod p_cx p_cx_1 p_cx_1_1_adas p_cx_1_2_adas p_cx_1_3_adas p_cx_1_4_adas p_cx_1_janev p_cx_2 p_cx_2_2_adas p_cx_2_3_adas p_cx_2_janev p_cx_3 p_cx_3_2_adas p_cx_3_3_adas p_cx_3_4_adas p_cx_3_5_adas p_cx_3_6inf_adas p_cx_3_janev p_cx_janev p_cx_n p_cx_n_janev p_cx_n_m p_excit p_excit_1_2_janev p_excit_1_3_janev p_excit_1_4_janev p_excit_1_5_janev p_excit_1_6_janev p_excit_1_janev p_excit_2_10_janev p_excit_2_3_janev p_excit_2_4_janev p_excit_2_5_janev p_excit_2_6_janev p_excit_2_7_janev p_excit_2_8_janev p_excit_2_9_janev p_excit_2_janev p_excit_3_10_janev p_excit_3_4_janev p_excit_3_5_janev p_excit_3_6_janev p_excit_3_7_janev p_excit_3_8_janev p_excit_3_9_janev p_excit_3_janev p_excit_n p_excit_n_m p_ioniz p_ioniz_1_janev p_ioniz_2_omullane p_ioniz_3_omullane p_ioniz_4_omullane p_ioniz_5_omullane p_ioniz_n pfida_f pfida_mc pitch_to_vec plane_basis plp_assign pnpa_f pnpa_mc pp_add pp_assign pp_subtract print_banner print_default_namelist ps_divide ps_multiply randind randind_cdf randn randu read_atomic_cross read_atomic_rate read_atomic_transitions read_beam read_chords read_distribution read_equilibrium read_f read_inputs read_mc read_neutrals read_npa read_nuclear_rates read_tables rng_init rng_normal rng_seed rng_uniform RSWAP sf_multiply simpsons_rule slf_multiply slp_multiply sp_multiply sparse spectrum store_bes_photons store_births store_fida_photons store_fw_photons store_fw_photons_at_chan store_neutrals store_neutrons store_npa store_photons sub2ind swap tb_zyx time track uvw_to_xyz write_bb_D_D write_bb_D_T write_bb_H_Aq write_bb_H_e write_bb_H_H write_beam_grid write_birth_profile write_bt_D_D write_bt_D_T write_bt_H_Aq write_bt_H_e write_bt_H_H write_einstein write_fida_weights write_neutrals write_neutrons write_npa write_npa_weights write_spectra xyz_to_uvw
Call graph
h5ltmake_compressed_dataset_double_f_6 calls h5pset_shuffle_f, h5pcreate_f, h5dwrite_f, h5pset_deflate_f, h5pclose_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5dclose_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_6
write_bt_d_d calls h5ltmake_compressed_dataset_double_f
write_spectra calls h5ltmake_compressed_dataset_double_f
write_bb_h_e calls h5ltmake_compressed_dataset_double_f
write_bt_h_h calls h5ltmake_compressed_dataset_double_f
write_neutrons calls h5ltmake_compressed_dataset_double_f
write_einstein calls h5ltmake_compressed_dataset_double_f
write_npa calls h5ltmake_compressed_dataset_double_f
write_birth_profile calls h5ltmake_compressed_dataset_double_f, write_beam_grid
write_npa_weights calls h5ltmake_compressed_dataset_double_f, write_beam_grid
write_bt_h_aq calls h5ltmake_compressed_dataset_double_f
write_bb_h_h calls h5ltmake_compressed_dataset_double_f
write_bb_d_d calls h5ltmake_compressed_dataset_double_f
write_bt_h_e calls h5ltmake_compressed_dataset_double_f
write_bt_d_t calls h5ltmake_compressed_dataset_double_f
write_fida_weights calls h5ltmake_compressed_dataset_double_f
write_beam_grid calls h5ltmake_compressed_dataset_double_f
write_bb_h_aq calls h5ltmake_compressed_dataset_double_f
write_neutrals calls h5ltmake_compressed_dataset_double_f, write_beam_grid
write_bb_d_t calls h5ltmake_compressed_dataset_double_f
generate_tables calls write_bt_d_d, write_bb_h_e, write_bt_h_h, write_einstein, write_bt_h_aq, write_bb_h_h, write_bb_d_d, write_bt_h_e, write_bb_h_aq
fidasim calls write_spectra, write_npa, write_birth_profile, write_neutrals, neutron_f, neutron_mc, npa_weights, fida_weights_mc, fida_weights_los
neutron_f calls write_neutrons
neutron_mc calls write_neutrons
npa_weights calls write_npa_weights
fida_weights_mc calls write_fida_weights
fida_weights_los calls write_fida_weights