halo – FIDASIM
halo Subroutine
139 statements
Source File
public subroutine halo()
Calculates halo neutral density and spectra
Arguments
None
Calls
Called By
Source Code
halo
Source Code
subroutine halo
    !+ Calculates halo neutral density and spectra
    integer :: ic,i,j,k,ncell
    integer(Int64) :: ihalo !! counter
    real(Float64), dimension(3) :: ri    !! start position
    real(Float64), dimension(3) :: vihalo!! velocity bulk plasma ion
    integer,dimension(3) :: ind,tind    !! actual cell
    !! Determination of the CX probability
    type(LocalProfiles) :: plasma
    real(Float64), dimension(nlevs) :: denn    !!  neutral dens (n=1-4)
    real(Float64), dimension(nlevs) :: rates    !! CX rates
    !! Collisiional radiative model along track
    real(Float64), dimension(nlevs) :: states  ! Density of n-states
    integer :: ntrack
    type(ParticleTrack), dimension(beam_grid%ntrack) :: tracks  !! Particle Tracks
    integer :: jj       !! counter along track
    real(Float64) :: tot_denn, photons  !! photon flux
    integer, dimension(beam_grid%ngrid) :: cell_ind
    real(Float64), dimension(beam_grid%nx,beam_grid%ny,beam_grid%nz) :: papprox
    integer(Int32), dimension(beam_grid%nx,beam_grid%ny,beam_grid%nz) :: nlaunch
    real(Float64), dimension(nlevs,beam_grid%nx,beam_grid%ny,beam_grid%nz) :: dens_prev
    real(Float64), dimension(:,:,:,:,:),allocatable :: dens_cur
    real(Float64) :: local_iter_dens
    integer :: n_slices, cur_slice, is
#ifdef _OMP
    integer, external :: omp_get_max_threads, omp_get_thread_num
#endif
    !! Halo iteration
    integer(Int64) :: hh, n_halo !! counters
    real(Float64) :: max_papprox,dcx_dens, halo_iteration_dens,seed_dcx
    integer :: prev_type  ! previous iteration
    integer :: cur_type  ! current iteration
    prev_type = fida_type
    cur_type = brems_type
    cur_slice = 1
    n_slices = 1
#ifdef _OMP
    n_slices = omp_get_max_threads()
#endif
    allocate(dens_cur(nlevs,beam_grid%nx,beam_grid%ny,beam_grid%nz,n_slices))
    dens_prev = 0.d0
    dens_cur = 0.d0
    dcx_dens = halo_iter_dens(dcx_type)
    halo_iter_dens(prev_type) = dcx_dens
    if(dcx_dens.eq.0) then
        if(inputs%verbose.ge.0) then
            write(*,'(a)') 'HALO: Density of DCX-neutrals is zero'
        endif
        stop
    endif
    dens_prev = neut%dcx
    n_halo = inputs%n_halo
    seed_dcx = 1.0
    iterations: do hh=1,200
        papprox=0.d0
        tot_denn=0.d0
        halo_iter_dens(cur_type) = 0.d0
        do ic=1,beam_grid%ngrid
            call ind2sub(beam_grid%dims,ic,ind)
            i = ind(1) ; j = ind(2) ; k = ind(3)
            call get_plasma(plasma,ind=ind)
            if(.not.plasma%in_plasma) cycle
            tot_denn = sum(dens_prev(:,i,j,k))
            papprox(i,j,k)= tot_denn*(plasma%denp-plasma%denf)
        enddo
        !! TODO: Remove this once we have a 3D interpolation grid
        max_papprox = maxval(papprox)
        where (papprox.lt.(max_papprox*1.d-3))
            papprox = 0.0
        endwhere
        cell_ind = 0
        ncell = 0
        do ic=1,beam_grid%ngrid
            call ind2sub(beam_grid%dims,ic,ind)
            i = ind(1) ; j = ind(2) ; k = ind(3)
            if(papprox(i,j,k).gt.0.0) then
                ncell = ncell + 1
                cell_ind(ncell) = ic
            endif
        enddo
        call get_nlaunch(n_halo, papprox, nlaunch)
        if(inputs%verbose.ge.1) then
            write(*,'(T6,"# of markers: ",i9," --- Seed/DCX: ",f5.3)') sum(nlaunch), seed_dcx
        endif
        local_iter_dens = halo_iter_dens(cur_type)
        !$OMP PARALLEL DO schedule(dynamic,1) private(i,j,k,ic,ihalo,ind,vihalo, &
        !$OMP& ri,tracks,ntrack,rates,denn,states,jj,photons,plasma,tind, cur_slice) &
        !$OMP& reduction(+: local_iter_dens )
        loop_over_cells: do ic=istart,ncell,istep
#ifdef _OMP
            cur_slice = omp_get_thread_num()+1
#endif
            call ind2sub(beam_grid%dims,cell_ind(ic),ind)
            i = ind(1) ; j = ind(2) ; k = ind(3)
            !! Loop over the markers
            loop_over_halos: do ihalo=1, nlaunch(i,j,k)
                !! Calculate ri,vhalo and track
                call mc_halo(ind,vihalo,ri)
                call track(ri,vihalo,tracks,ntrack)
                if(ntrack.eq.0)cycle loop_over_halos
                !! Get plasma parameters at particle location
                call get_plasma(plasma, pos=ri)
                !! Calculate CX probability
                tind = tracks(1)%ind
                call bt_cx_rates(plasma, dens_prev(:,tind(1),tind(2),tind(3)), vihalo, thermal_ion, rates)
                if(sum(rates).le.0.)cycle loop_over_halos
                !! Get plasma parameters at mean point in cell
                call get_plasma(plasma,pos=tracks(1)%pos)
                !! Weight CX rates by ion source density
                states = rates*plasma%denp
                loop_along_track: do jj=1,ntrack
                    call get_plasma(plasma,pos=tracks(jj)%pos)
                    if(.not.plasma%in_plasma) exit loop_along_track
                    call colrad(plasma,thermal_ion,vihalo,tracks(jj)%time,states,denn,photons)
                    !! Store Neutrals
                    tind = tracks(jj)%ind
                    dens_cur(:,tind(1),tind(2),tind(3),cur_slice) = &
                        dens_cur(:,tind(1),tind(2),tind(3),cur_slice) + denn/nlaunch(i,j,k)
                    local_iter_dens = &
                        local_iter_dens + sum(denn)/nlaunch(i,j,k)
                    if((photons.gt.0.d0).and.(inputs%calc_halo.ge.1)) then
                      call store_bes_photons(tracks(jj)%pos,vihalo,photons/nlaunch(i,j,k),halo_type)
                    endif
                enddo loop_along_track
            enddo loop_over_halos
        enddo loop_over_cells
        !$OMP END PARALLEL DO
        halo_iter_dens(cur_type) = local_iter_dens
#ifdef _OMP
        !$OMP PARALLEL DO private(i,j,is)
        do i=1,beam_grid%nz
         do j=1,beam_grid%ny
          do is = 2, n_slices
            dens_cur(:,:,j,i,1) = dens_cur(:,:,j,i,1) + dens_cur(:,:,j,i,is)
          enddo
         enddo
        enddo
#endif
        ! at this point, dens_cur(*,1) contains all the info
#ifdef _MPI
        !! Combine densities
        call parallel_sum(dens_cur(:,:,:,:,1))
        call parallel_sum(halo_iter_dens(cur_type))
#endif
        if(halo_iter_dens(cur_type)/halo_iter_dens(prev_type).gt.1.0) then
            write(*,'(a)') "HALO: Halo generation density exceeded seed density. This shouldn't happen."
            exit iterations
        endif
        halo_iteration_dens = halo_iter_dens(cur_type)
        halo_iter_dens(prev_type) = halo_iter_dens(cur_type)
        !$OMP PARALLEL DO private(i)
        do i=1,beam_grid%nz
          neut%halo(:,:,:,i) = neut%halo(:,:,:,i) + dens_cur(:,:,:,i,1)
          dens_prev(:,:,:,i) = dens_cur(:,:,:,i,1)
          dens_cur(:,:,:,i,:) = 0.d0
        enddo
        seed_dcx = halo_iteration_dens/dcx_dens
        n_halo=int(inputs%n_halo*seed_dcx,Int64)
        if(seed_dcx.lt.0.01) exit iterations
    enddo iterations
#ifdef _MPI
    !! Combine Spectra
    if(inputs%calc_halo.ge.1) then
        call parallel_sum(spec%halo)
    endif
#endif
    deallocate(dens_cur)
end subroutine halo
All Procedures
approx_eq approx_ge approx_le Aq_cx Aq_cx_n Aq_cx_n_adas Aq_cx_n_janev Aq_excit Aq_excit_1_2_janev Aq_excit_1_3_janev Aq_excit_1_4_janev Aq_excit_1_5_janev Aq_excit_1_janev Aq_excit_2_10_janev Aq_excit_2_3_janev Aq_excit_2_4_janev Aq_excit_2_5_janev Aq_excit_2_6_janev Aq_excit_2_7_janev Aq_excit_2_8_janev Aq_excit_2_9_janev Aq_excit_2_janev Aq_excit_3_10_janev Aq_excit_3_4_janev Aq_excit_3_5_janev Aq_excit_3_6_janev Aq_excit_3_7_janev Aq_excit_3_8_janev Aq_excit_3_9_janev Aq_excit_3_janev Aq_excit_n Aq_excit_n_janev Aq_excit_n_m Aq_ioniz Aq_ioniz_n Aq_ioniz_n_janev assignment(=) attenuate B5_cx_1_adas B5_cx_1_janev B5_cx_2_adas B5_ioniz_1_janev balance balback bb_cx_rates boundary_edge bremsstrahlung bt_cx_rates bt_maxwellian bt_maxwellian_eb bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m C6_cx_1_adas C6_cx_1_janev C6_cx_2_adas C6_cx_3_adas C6_ioniz_1_janev calc_perp_vectors check_compression_availability circle_grid_intersect cleanup_mpi cold_spec colrad comabs Comdiv cross_product cumsum d_d_fusion_he d_d_fusion_t d_t_fusion dcx dcx_spec deriv e_excit e_excit_1_2_janev e_excit_1_3_janev e_excit_1_4_janev e_excit_1_5_janev e_excit_1_janev e_excit_2_3_janev e_excit_f e_excit_n e_excit_n_m e_ioniz e_ioniz_1_janev e_ioniz_2_janev e_ioniz_3_janev e_ioniz_n eigen elmhes elmtrans fast_ion_assign ff_add ff_assign ff_subtract fida_f fida_mc fida_weights_los fida_weights_mc flf_assign fs_divide fs_multiply get_beam_cx_rate get_distribution get_ep_denf get_fields get_indices get_neutron_rate get_nlaunch get_plasma get_position get_rate_matrix get_rng get_value grid_intersect gyro_correction gyro_radius gyro_range gyro_step gyro_surface gyro_surface_coordinates gyro_trajectory h5ltmake_compressed_dataset_double_f h5ltmake_compressed_dataset_double_f_1 h5ltmake_compressed_dataset_double_f_2 h5ltmake_compressed_dataset_double_f_3 h5ltmake_compressed_dataset_double_f_4 h5ltmake_compressed_dataset_double_f_5 h5ltmake_compressed_dataset_double_f_6 h5ltmake_compressed_dataset_double_f_7 h5ltmake_compressed_dataset_int_f h5ltmake_compressed_dataset_int_f_1 h5ltmake_compressed_dataset_int_f_2 h5ltmake_compressed_dataset_int_f_3 h5ltmake_compressed_dataset_int_f_4 h5ltmake_compressed_dataset_int_f_5 h5ltmake_compressed_dataset_int_f_6 h5ltmake_compressed_dataset_int_f_7 h5ltread_dataset_double_scalar_f h5ltread_dataset_int_scalar_f halo halo_spec hit_npa_detector hqr2 hqrvec in_boundary in_grid in_gyro_surface in_plasma ind2sub init_mpi interpol interpol1D_arr interpol1D_coeff interpol1D_coeff_arr interpol2D_2D_arr interpol2D_arr interpol2D_coeff interpol2D_coeff_arr interpol_coeff lff_assign lflf_add lflf_assign lflf_subtract lfs_divide lfs_multiply line_basis line_gyro_surface_intersect line_plane_intersect linsolve lplp_add lplp_assign lplp_subtract lpp_assign lps_divide lps_multiply lubksb ludcmp m_spread make_beam_grid matinv mc_fastion mc_halo mc_nbi mc_nbi_cell my_rank nbi_spec ndmc neutron_f neutron_mc norm2 npa_f npa_gyro_range npa_mc npa_part_assign npa_weights num_ranks operator(*) operator(+) operator(-) operator(/) outerprod p_cx p_cx_1 p_cx_1_1_adas p_cx_1_2_adas p_cx_1_3_adas p_cx_1_4_adas p_cx_1_janev p_cx_2 p_cx_2_2_adas p_cx_2_3_adas p_cx_2_janev p_cx_3 p_cx_3_2_adas p_cx_3_3_adas p_cx_3_4_adas p_cx_3_5_adas p_cx_3_6inf_adas p_cx_3_janev p_cx_janev p_cx_n p_cx_n_janev p_cx_n_m p_excit p_excit_1_2_janev p_excit_1_3_janev p_excit_1_4_janev p_excit_1_5_janev p_excit_1_6_janev p_excit_1_janev p_excit_2_10_janev p_excit_2_3_janev p_excit_2_4_janev p_excit_2_5_janev p_excit_2_6_janev p_excit_2_7_janev p_excit_2_8_janev p_excit_2_9_janev p_excit_2_janev p_excit_3_10_janev p_excit_3_4_janev p_excit_3_5_janev p_excit_3_6_janev p_excit_3_7_janev p_excit_3_8_janev p_excit_3_9_janev p_excit_3_janev p_excit_n p_excit_n_m p_ioniz p_ioniz_1_janev p_ioniz_2_omullane p_ioniz_3_omullane p_ioniz_4_omullane p_ioniz_5_omullane p_ioniz_n parallel_sum parallel_sum_d0 parallel_sum_d1 parallel_sum_d2 parallel_sum_d3 parallel_sum_d4 parallel_sum_d5 parallel_sum_i0 parallel_sum_i1 parallel_sum_i2 pfida_f pfida_mc pitch_to_vec plane_basis plp_assign pnpa_f pnpa_mc pp_add pp_assign pp_subtract print_banner print_default_namelist ps_divide ps_multiply randind randind_cdf randn randu read_atomic_cross read_atomic_rate read_atomic_transitions read_beam read_chords read_distribution read_equilibrium read_f read_inputs read_mc read_neutrals read_npa read_nuclear_rates read_tables rng_init rng_normal rng_seed rng_uniform RSWAP sf_multiply simpsons_rule slf_multiply slp_multiply sp_multiply sparse spectrum store_bes_photons store_births store_fida_photons store_fw_photons store_fw_photons_at_chan store_neutrals store_neutrons store_npa store_photons sub2ind swap tb_zyx time track uvw_to_xyz write_bb_D_D write_bb_D_T write_bb_H_Aq write_bb_H_e write_bb_H_H write_beam_grid write_birth_profile write_bt_D_D write_bt_D_T write_bt_H_Aq write_bt_H_e write_bt_H_H write_einstein write_fida_weights write_neutrals write_neutrons write_npa write_npa_weights write_spectra xyz_to_uvw
Call graph
halo calls ind2sub, omp_get_max_threads, track, colrad, store_bes_photons, mc_halo, omp_get_thread_num, parallel_sum, bt_cx_rates, get_plasma, get_nlaunch
track calls get_indices, in_plasma
colrad calls linsolve, get_rate_matrix, eigen
store_bes_photons calls store_photons
mc_halo calls get_plasma, randu, randn
parallel_sum calls parallel_sum_d5, parallel_sum_d0, parallel_sum_i1, parallel_sum_i2, parallel_sum_d3, parallel_sum_d4, parallel_sum_d2, parallel_sum_d1, parallel_sum_i0
bt_cx_rates calls interpol_coeff
get_plasma calls in_plasma, get_position
get_nlaunch calls ind2sub, rng_init, cumsum, randind_cdf
in_plasma calls interpol_coeff, xyz_to_uvw
interpol_coeff calls interpol1d_coeff_arr, interpol2d_coeff_arr, interpol1d_coeff, interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
interpol2d_coeff_arr calls interpol2d_coeff
linsolve calls dgetrf, dgetrs, matinv
get_rate_matrix calls interpol_coeff
eigen calls balback, hqr2, elmtrans, balance, elmhes
matinv calls ludcmp, lubksb
ludcmp calls swap, outerprod
balback calls rswap
hqr2 calls hqrvec
balance calls rswap
elmhes calls rswap
hqrvec calls comdiv
store_photons calls get_indices, spectrum, get_fields
get_fields calls in_plasma, get_position, calc_perp_vectors
parallel_sum_d5 calls mpi_allreduce
parallel_sum_d0 calls mpi_allreduce
parallel_sum_i1 calls mpi_allreduce
parallel_sum_i2 calls mpi_allreduce
parallel_sum_d3 calls mpi_allreduce
parallel_sum_d4 calls mpi_allreduce
parallel_sum_d2 calls mpi_allreduce
parallel_sum_d1 calls mpi_allreduce
parallel_sum_i0 calls mpi_allreduce
rng_init calls rng_seed, my_rank
fidasim calls halo