in_passive_grid – FIDASIM
in_passive_grid Function
15 statements
Source File
public function in_passive_grid(uvw) result(ing)
Determines if a position pos is in the pass_grid
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in), dimension(3) :: uvw
Position in machine coordinates [cm]
Return Value logical
Indicates whether the position is in the passive neutral grid
Calls
Called by
Contents
None
Call graph
in_passive_grid calls approx_ge, uvw_to_cyl, approx_le
approx_ge calls approx_eq
approx_le calls approx_eq
grid_intersect calls in_passive_grid
make_diagnostic_grids calls grid_intersect
circle_grid_intersect calls grid_intersect
fida_weights_los calls grid_intersect
mc_nbi calls grid_intersect
ndmc calls mc_nbi
fidasim calls make_diagnostic_grids, fida_weights_los, ndmc, read_distribution
read_mc calls circle_grid_intersect
read_distribution calls read_mc