init_reservoir – FIDASIM
init_reservoir Subroutine
11 statements
Source File
public subroutine init_reservoir(res)
Initialize reservoir
Arguments
Type Intent Optional Attributes Name
type(NeutralParticleReservoir), intent(inout) :: res
Neutral Particle Reservoir
Size of reservoir
Calls
Called by
Contents
Source Code
init_reservoir
Source Code
subroutine init_reservoir(res)
    !+ Initialize reservoir
    type(NeutralParticleReservoir), intent(inout) :: res
        !+ Neutral Particle Reservoir
    !integer, intent(in) :: k
        !+ Size of reservoir
    real(Float64) :: randomu(2)
    if (res%n.lt.1) then
        res%n = 1
        res%k = reservoir_size
        call randu(randomu)
        res%W = exp(log(randomu(1))/res%k)
        res%i = res%k + floor(log(randomu(2))/log(1.0-res%W)) + 1
    endif
end subroutine init_reservoir
Call graph
init_reservoir calls randu
npr_assign calls init_reservoir
read_neutral_population calls init_reservoir
parallel_merge_reservoirs calls init_reservoir, merge_reservoirs
merge_reservoirs calls init_reservoir, update_reservoir
update_reservoir calls init_reservoir
update_neutrals calls update_reservoir
np_assign calls npr_assign
halo calls parallel_merge_reservoirs, update_neutrals, merge_neutral_populations, store_photon_birth, parallel_merge_populations
assignment(=) calls npr_assign, np_assign
pfida_f calls parallel_merge_reservoirs, store_photon_birth
merge_neutral_populations calls merge_reservoirs
read_neutrals calls read_neutral_population
pfida_mc calls parallel_merge_reservoirs, store_photon_birth
store_photon_birth calls update_reservoir
fida_f calls parallel_merge_reservoirs, store_photon_birth
fida_mc calls parallel_merge_reservoirs, store_photon_birth
parallel_merge_populations calls parallel_merge_reservoirs
dcx calls parallel_merge_reservoirs, store_photon_birth, parallel_merge_populations, store_neutrals
ndmc calls parallel_merge_populations, store_neutrals
fidasim calls halo, pfida_f, read_neutrals, pfida_mc, fida_f, fida_mc, dcx, ndmc
store_neutrals calls update_neutrals