init_mpi – FIDASIM
init_mpi Subroutine
17 statements
Source File
public subroutine init_mpi()
Uses
mpi
Arguments
None
Calls
Called by
Contents
None
Call graph
init_mpi calls mpi_comm_size, mpi_init_thread, mpi_comm_rank, mpi_init
fidasim calls init_mpi