init_neutral_population – FIDASIM
init_neutral_population Subroutine
12 statements
Source File
public subroutine init_neutral_population(pop, amu)
Initialize NeutralPopulation
Arguments
Type Intent Optional Attributes Name
type(NeutralPopulation), intent(inout) :: pop
Neutral Population to initialize
real(kind=Float64), intent(in) :: amu
Neutral Particle Atomic Mass
Called by
Contents
Source Code
init_neutral_population
Source Code
subroutine init_neutral_population(pop, amu)
    !+ Initialize [[NeutralPopulation]]
    type(NeutralPopulation), intent(inout) :: pop
        !+ Neutral Population to initialize
    real(Float64), intent(in) :: amu
        !+ Neutral Particle Atomic Mass
    integer :: i, j, k, ic, ind(3)
    pop%amu = amu
    if(.not.allocated(pop%dens)) then
        allocate(pop%dens(nlevs,beam_grid%nx,beam_grid%ny,beam_grid%nz))
        allocate(pop%res(beam_grid%nx,beam_grid%ny,beam_grid%nz))
    endif
    pop%dens = 0.d0
    pop%res%n = 0
end subroutine init_neutral_population
Call graph
read_neutral_population calls init_neutral_population
ndmc calls init_neutral_population
fidasim calls ndmc, read_neutrals
read_neutrals calls read_neutral_population