line_plane_intersect – FIDASIM
line_plane_intersect Subroutine
16 statements
Source File
public subroutine line_plane_intersect(l0, l, p0, n, p, t)
Calculates the intersection of a line and a plane
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in), dimension(3) :: l0
Point on line
real(kind=Float64), intent(in), dimension(3) :: l
Ray of line
real(kind=Float64), intent(in), dimension(3) :: p0
Point on plane
real(kind=Float64), intent(in), dimension(3) :: n
Normal vector of plane
real(kind=Float64), intent(out), dimension(3) :: p
Line-plane intersect point
real(kind=Float64), intent(out) :: t
"time" to intersect
Called by
Contents
Source Code
line_plane_intersect
Source Code
subroutine line_plane_intersect(l0, l, p0, n, p, t)
    !+ Calculates the intersection of a line and a plane
    real(Float64), dimension(3), intent(in)  :: l0
        !+ Point on line
    real(Float64), dimension(3), intent(in)  :: l
        !+ Ray of line
    real(Float64), dimension(3), intent(in)  :: p0
        !+ Point on plane
    real(Float64), dimension(3), intent(in)  :: n
        !+ Normal vector of plane
    real(Float64), dimension(3), intent(out) :: p
        !+ Line-plane intersect point
    real(Float64), intent(out)               :: t
        !+ "time" to intersect
    real(Float64) :: ldotn
    ldotn = dot_product(l, n)
    if(ldotn.eq.0.0)then
        t = 0.0
    else
        t = dot_product(p0 - l0, n)/ldotn
    endif
    p = l0 + t*l
end subroutine line_plane_intersect
Call graph
track_cylindrical calls line_plane_intersect
gyro_range calls line_plane_intersect
hit_npa_detector calls line_plane_intersect
npa_gyro_range calls gyro_range
make_diagnostic_grids calls track_cylindrical, hit_npa_detector
pnpa_mc calls hit_npa_detector, npa_gyro_range
pfida_f calls track_cylindrical
pnpa_f calls hit_npa_detector, npa_gyro_range
pfida_mc calls track_cylindrical
npa_mc calls hit_npa_detector, npa_gyro_range
npa_weights calls hit_npa_detector
npa_f calls hit_npa_detector, npa_gyro_range
fidasim calls make_diagnostic_grids, pnpa_mc, pfida_f, pnpa_f, pfida_mc, npa_mc, npa_weights, npa_f