lubksb – FIDASIM
lubksb Subroutine
23 statements
Source File
public subroutine lubksb(a, indx, b)
Does LU back substitution
Arguments
Type Intent Optional Attributes Name
real(kind=double), intent(in), dimension(:,:) :: a
integer, intent(in), dimension(:) :: indx
real(kind=double), intent(inout), dimension(:) :: b
Called by
Contents
Source Code
lubksb
Source Code
  subroutine lubksb(a,indx,b)
    !+ Does LU back substitution
    real(double), dimension(:,:),intent(IN)   :: a
    integer,dimension(:),  intent(IN)         :: indx
    real(double), dimension(:),  intent(INOUT):: b
    integer       :: i,n,ii,ll
    real(double)  :: summ
    n=size(indx)
    ii=0
    do i=1,n
       ll=indx(i)
       summ=b(ll)
       b(ll)=b(i)
       if (ii /= 0) then
          summ=summ-dot_product(a(i,ii:i-1),b(ii:i-1))
       else if (summ /= 0.0) then
          ii=i
       endif
       b(i)=summ
    enddo
    do i=n,1,-1
       b(i) = (b(i)-dot_product(a(i,i+1:n),b(i+1:n)))/a(i,i)
    enddo
  end subroutine lubksb
Call graph
matinv calls lubksb
linsolve calls matinv
colrad calls linsolve
attenuate calls colrad
fida_weights_los calls colrad
pfida_mc calls colrad
fida_mc calls colrad
fida_f calls colrad
pfida_f calls colrad
fida_weights_mc calls colrad
read_equilibrium calls colrad
dcx calls colrad
ndmc calls colrad
halo calls colrad
npa_f calls attenuate
pnpa_mc calls attenuate
fidasim calls fida_weights_los, pfida_mc, fida_mc, fida_f, pfida_f, fida_weights_mc, read_equilibrium, dcx, ndmc, halo, npa_f, pnpa_mc, npa_weights, pnpa_f, npa_mc
npa_weights calls attenuate
pnpa_f calls attenuate
npa_mc calls attenuate