make_passive_grid – FIDASIM
make_passive_grid Subroutine
170 statements
Source File
public subroutine make_passive_grid()
Makes [[libfida:pass_grid] from user defined inputs
Arguments
None
Calls
Called by
Contents
Source Code
make_passive_grid
Source Code
subroutine make_passive_grid
    !+ Makes [[libfida:pass_grid] from user defined inputs
    integer(HID_T) :: fid, gid
    integer(HSIZE_T), dimension(2) :: dims
    logical :: path_valid_spec, path_valid_npa
    real(Float64), dimension(:,:), allocatable :: a_cent, d_cent
    real(Float64), dimension(:,:), allocatable :: lenses, axes, r0_arr, v0_arr
    real(Float64), dimension(3) :: vertex111, vertex111_cyl
    real(Float64), dimension(3) :: vertex221, vertex221_cyl
    real(Float64), dimension(3) :: vertex112, vertex112_cyl
    real(Float64), dimension(3) :: vertex121, vertex121_cyl
    real(Float64), dimension(3) :: vertex211, vertex211_cyl
    real(Float64), dimension(3) :: vertex212, vertex212_cyl
    real(Float64), dimension(3) :: vertex222, vertex222_cyl
    real(Float64), dimension(3) :: vertex122, vertex122_cyl
    real(Float64), dimension(3) :: r0, v0, r0_cyl
    real(Float64), dimension(2) :: phi_dum
    real(Float64) :: xmin, ymin, xmax, ymax, zmin, zmax
    real(Float64) :: rmin, rmax, phimax, phimin
    integer :: spec_nchan, npa_nchan, i, error
    logical :: inp1, inp2
    spec_nchan = 0
    npa_nchan = 0
    !!Initialize HDF5 interface
    call h5open_f(error)
    !!Open HDF5 file
    call h5fopen_f(inputs%geometry_file, H5F_ACC_RDONLY_F, fid, error)
    !!If SPEC group exists, read FIDA LOS info
    call h5ltpath_valid_f(fid, "/spec", .True., path_valid_spec, error)
    if(.not.path_valid_spec) then
        if(inputs%verbose.ge.1) then
            write(*,'(a)') 'FIDA/BES geometry is not in the geometry file'
            write(*,'(a)') 'Passive FIDA calculations will not be performed'
        endif
        inputs%calc_pfida = 0
    endif
    if(inputs%calc_pfida.gt.0) then
        !!Open SPEC group
        call h5gopen_f(fid, "/spec", gid, error)
        call h5ltread_dataset_int_scalar_f(gid, "/spec/nchan", spec_nchan, error)
        allocate(lenses(3, spec_nchan), axes(3, spec_nchan))
        !! Read in lenses and axes info
        dims = [3,spec_nchan]
        call h5ltread_dataset_double_f(gid, "/spec/lens", lenses, dims, error)
        call h5ltread_dataset_double_f(gid, "/spec/axis", axes, dims, error)
        !!Close SPEC group
        call h5gclose_f(gid, error)
    endif
    !!If NPA group exists, read NPA LOS info
    call h5ltpath_valid_f(fid, "/npa", .True., path_valid_npa, error)
    if(.not.path_valid_npa) then
        if(inputs%verbose.ge.0) then
            write(*,'(a)') 'NPA geometry is not in the geometry file'
            write(*,'(a)') 'Passive NPA calculations will not be performed'
        endif
        inputs%calc_pnpa = 0
    endif
    if(inputs%calc_pnpa.gt.0) then
        !!Open NPA group
        call h5gopen_f(fid, "/npa", gid, error)
        call h5ltread_dataset_int_scalar_f(gid, "/npa/nchan", npa_nchan, error)
        allocate(a_cent(3,  npa_nchan), d_cent(3,  npa_nchan))
        !! Read in a_cent and d_cent info
        dims = [3,spec_nchan]
        call h5ltread_dataset_double_f(gid, "/npa/a_cent",  a_cent, dims, error)
        call h5ltread_dataset_double_f(gid, "/npa/d_cent",  d_cent, dims, error)
        !!Close NPA group
        call h5gclose_f(gid, error)
    endif
    !!Close file id
    call h5fclose_f(fid, error)
    !!Close HDF5 interface
    call h5close_f(error)
    !!Collect all LOS info
    allocate(r0_arr(3,  spec_nchan+npa_nchan), v0_arr(3,  spec_nchan+npa_nchan))
    if((inputs%calc_pfida.gt.0).and.(inputs%calc_pnpa.gt.0)) then
        r0_arr(:,1:spec_nchan) = lenses
        v0_arr(:,1:spec_nchan) = axes
        r0_arr(:,(1+spec_nchan):(spec_nchan+npa_nchan)) = d_cent
        v0_arr(:,(1+spec_nchan):(spec_nchan+npa_nchan)) = a_cent - d_cent
    else if(inputs%calc_pfida.gt.0) then
        r0_arr(:,1:spec_nchan) = lenses
        v0_arr(:,1:spec_nchan) = axes
    else !pnpa>=1 case
        r0_arr(:,1:npa_nchan) = d_cent
        v0_arr(:,1:npa_nchan) = a_cent - d_cent
    endif
    !! The remainder of the code will make the passive neutral grid
    pass_grid%dr = inter_grid%dr
    pass_grid%dz = inter_grid%dz
    pass_grid%nr = inter_grid%nr
    pass_grid%nz = inter_grid%nz
    allocate(pass_grid%r(pass_grid%nr), pass_grid%z(pass_grid%nz))
    pass_grid%r = inter_grid%r
    pass_grid%z = inter_grid%z
    pass_grid%da = pass_grid%dr*pass_grid%dz
    !! Start by finding the limits of the beam grid vertices to define the phi information
    xmin = beam_grid%xmin ; xmax = beam_grid%xmax
    ymin = beam_grid%ymin ; ymax = beam_grid%ymax
    zmin = beam_grid%zmin ; zmax = beam_grid%zmax
    vertex111(1) = xmin   ; vertex111(2) = ymin   ; vertex111(3) = zmin
    vertex222(1) = xmax   ; vertex222(2) = ymax   ; vertex222(3) = zmax
    vertex112 = vertex111 ; vertex211 = vertex111 ; vertex121 = vertex111
    vertex112(3) = zmax   ; vertex211(1) = xmax   ; vertex121(2) = ymax
    vertex122 = vertex222 ; vertex221 = vertex222 ; vertex212 = vertex222
    vertex122(1) = xmin   ; vertex221(3) = zmin   ; vertex212(2) = ymin
    call xyz_to_cyl(vertex111,vertex111_cyl)
    call xyz_to_cyl(vertex112,vertex112_cyl)
    call xyz_to_cyl(vertex121,vertex121_cyl)
    call xyz_to_cyl(vertex211,vertex211_cyl)
    call xyz_to_cyl(vertex212,vertex212_cyl)
    call xyz_to_cyl(vertex222,vertex222_cyl)
    call xyz_to_cyl(vertex122,vertex122_cyl)
    call xyz_to_cyl(vertex221,vertex221_cyl)
    phimin = min(vertex111_cyl(3),vertex112_cyl(3),vertex121_cyl(3),vertex211_cyl(3) &
                ,vertex212_cyl(3),vertex222_cyl(3),vertex122_cyl(3),vertex221_cyl(3))
    phimax = max(vertex111_cyl(3),vertex112_cyl(3),vertex121_cyl(3),vertex211_cyl(3) &
                ,vertex212_cyl(3),vertex222_cyl(3),vertex122_cyl(3),vertex221_cyl(3))
    !! Update phi with LOS limits
    track_loop: do i=1,(spec_nchan+npa_nchan)
        r0 = r0_arr(:,i)
        v0 = v0_arr(:,i)
        v0 = 2.d0*v0/norm2(v0)
        phi_dum = -1.d0 !Initialize phi_dum outside of domain
        call in_plasma(r0, inp2)
        if (inp2) cycle track_loop
        inp2 = .True. ; inp1 = .False.
        do while (inp2) !Loop until los 'particle' is outside the plasma
            do while (.not.inp1) !Loop until los 'particle' is inside the plasma
                call uvw_to_cyl(r0, r0_cyl)
                if ((r0_cyl(1).gt.600.d0).or.(abs(r0_cyl(2)).gt.600.d0)) exit !Never intersects
                call in_plasma(r0, inp1)
                if (inp1) phi_dum(1) = r0_cyl(3)
                r0 = r0 + v0  !dt=1
            enddo
            call in_plasma(r0, inp2)
            if (.not.inp2) then
                call uvw_to_cyl(r0, r0_cyl)
                phi_dum(2) = r0_cyl(3)
            endif
            r0 = r0 + v0  !dt=1
        enddo
        if((minval(phi_dum).lt.phimin).and.(minval(phi_dum).ge.0.d0)) phimin = minval(phi_dum)
        if((maxval(phi_dum).gt.phimax).and.(maxval(phi_dum).ge.0.d0)) phimax = maxval(phi_dum)
    enddo track_loop
    pass_grid%dphi = 0.1
    pass_grid%nphi = int(ceiling((phimax-phimin)/pass_grid%dphi))
    if (pass_grid%nphi.gt.20) then !! Avoid large memory allocation
        pass_grid%nphi = 20
        pass_grid%dphi = (phimax-phimin)/pass_grid%nphi
    endif
    allocate(pass_grid%phi(pass_grid%nphi))
    do i=1, pass_grid%nphi
        pass_grid%phi(i) = phimin + (i-1)*pass_grid%dphi
    enddo
    pass_grid%dv = pass_grid%dr*pass_grid%dphi*pass_grid%dz
    pass_grid%dims = [pass_grid%nr, pass_grid%nz, pass_grid%nphi]
    pass_grid%ntrack = pass_grid%nr+pass_grid%nz+pass_grid%nphi
    pass_grid%ngrid  = pass_grid%nr*pass_grid%nz*pass_grid%nphi
    if(inputs%verbose.ge.1) then
        write(*,'(a)') "---- Passive neutral grid settings ----"
        write(*,'(T2,"Nr: ", i3)') pass_grid%nr
        write(*,'(T2,"Nz: ", i3)') pass_grid%nz
        write(*,'(T2,"Nphi: ", i3)') pass_grid%nphi
        write(*,'(T2,"R  range = [",f6.2,",",f6.2,"]")') &
              pass_grid%r(1),pass_grid%r(pass_grid%nr)
        write(*,'(T2,"Z  range = [",f7.2,",",f6.2,"]")') &
              pass_grid%z(1),pass_grid%z(pass_grid%nz)
        write(*,'(T2,"Phi  range = [",f5.2,",",f5.2,"]")') &
              pass_grid%phi(1),pass_grid%phi(pass_grid%nphi)
        write(*,'(T2,"dA: ", f5.2," [cm^3]")') pass_grid%da
        write(*,*) ''
    endif
    if(inputs%calc_pnpa.gt.0) deallocate(a_cent, d_cent)
    if(inputs%calc_pfida.gt.0) deallocate(lenses, axes)
end subroutine make_passive_grid
Call graph
make_passive_grid calls uvw_to_cyl, h5close_f, h5gopen_f, h5ltpath_valid_f, h5gclose_f, in_plasma, xyz_to_cyl, h5ltread_dataset_int_scalar_f, h5open_f, h5ltread_dataset_double_f, h5fclose_f, h5fopen_f
in_plasma calls cyl_to_uvw, interpol_coeff, xyz_to_uvw
xyz_to_cyl calls uvw_to_cyl, xyz_to_uvw
h5ltread_dataset_int_scalar_f calls h5ltread_dataset_int_f
interpol_coeff calls cyl_interpol3d_coeff, interpol1d_coeff, interpol2d_coeff_arr, interpol2d_coeff, cyl_interpol3d_coeff_arr, interpol1d_coeff_arr
cyl_interpol3d_coeff calls interpol2d_coeff
interpol2d_coeff_arr calls interpol2d_coeff
cyl_interpol3d_coeff_arr calls cyl_interpol3d_coeff, interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
fidasim calls make_passive_grid