mc_fastion_pass_grid – FIDASIM
mc_fastion_pass_grid Subroutine
36 statements
Source File
public subroutine mc_fastion_pass_grid(ind, fields, eb, ptch, denf, output_coords)
Samples a Guiding Center Fast-ion distribution function at a given pass_grid index
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(3) :: ind
pass_grid index
type(LocalEMFields), intent(out) :: fields
Electromagnetic fields at the guiding center
real(kind=Float64), intent(out) :: eb
Energy of the fast ion
real(kind=Float64), intent(out) :: ptch
Pitch of the fast ion
real(kind=Float64), intent(out) :: denf
Fast-ion density at guiding center
integer, intent(in), optional :: output_coords
Indicates coordinate system of fields. Beam grid (0), machine (1) and cylindrical (2)
Calls
Called by
Contents
Source Code
mc_fastion_pass_grid
Source Code
subroutine mc_fastion_pass_grid(ind,fields,eb,ptch,denf,output_coords)
    !+ Samples a Guiding Center Fast-ion distribution function at a given [[libfida:pass_grid]] index
    integer, dimension(3), intent(in)      :: ind
        !+ [[libfida:pass_grid]] index
    type(LocalEMFields), intent(out)       :: fields
        !+ Electromagnetic fields at the guiding center
    real(Float64), intent(out)             :: eb
        !+ Energy of the fast ion
    real(Float64), intent(out)             :: ptch
        !+ Pitch of the fast ion
    real(Float64), intent(out)             :: denf
        !+ Fast-ion density at guiding center
    integer, intent(in), optional          :: output_coords
        !+ Indicates coordinate system of `fields`. Beam grid (0), machine (1) and cylindrical (2)
    real(Float64), dimension(fbm%nenergy,fbm%npitch) :: fbeam
    real(Float64), dimension(3) :: rg, rg_cyl
    real(Float64), dimension(3) :: randomu3
    real(Float64) :: rmin, rmax, zmin, phimin
    integer, dimension(2,1) :: ep_ind
    integer :: ocs
    if(present(output_coords)) then
        ocs = output_coords
    else
        ocs = 0
    endif
    denf=0.d0
    call randu(randomu3)
    rmin = pass_grid%r(ind(1))
    rmax = rmin + pass_grid%dr
    zmin = pass_grid%z(ind(2))
    phimin = pass_grid%phi(ind(3))
    ! Sample uniformally in annulus
    rg_cyl(1) = sqrt(randomu3(1)*(rmax**2 - rmin**2) + rmin**2)
    rg_cyl(2) = zmin + randomu3(2)*pass_grid%dz
    rg_cyl(3) = phimin + randomu3(3)*pass_grid%dphi
    call cyl_to_uvw(rg_cyl, rg)
    call get_fields(fields,pos=rg,input_coords=1,output_coords=ocs)
    if(.not.fields%in_plasma) return
    call get_distribution(fbeam,denf,coeffs=fields%b)
    call randind(fbeam,ep_ind)
    call randu(randomu3)
    eb = fbm%energy(ep_ind(1,1)) + fbm%dE*(randomu3(1)-0.5)
    ptch = fbm%pitch(ep_ind(2,1)) + fbm%dp*(randomu3(2)-0.5)
end subroutine mc_fastion_pass_grid
Call graph
mc_fastion_pass_grid calls get_fields, randu, cyl_to_uvw, get_distribution, randind
get_fields calls calc_perp_vectors, uvw_to_xyz, in_plasma, xyz_to_uvw
get_distribution calls interpol, xyz_to_uvw
interpol calls interpol3d_arr, interpol2d_2d_arr, interpol2d_arr, interpol1d_arr, interpol3d_2d_arr
in_plasma calls cyl_to_uvw, xyz_to_uvw, interpol_coeff
interpol_coeff calls cyl_interpol3d_coeff, interpol1d_coeff, interpol2d_coeff_arr, interpol2d_coeff, cyl_interpol3d_coeff_arr, interpol1d_coeff_arr
interpol3d_arr calls interpol_coeff
interpol2d_2d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol1d_arr calls interpol_coeff
interpol3d_2d_arr calls interpol_coeff
cyl_interpol3d_coeff calls interpol2d_coeff
interpol2d_coeff_arr calls interpol2d_coeff
cyl_interpol3d_coeff_arr calls cyl_interpol3d_coeff, interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
pnpa_f calls mc_fastion_pass_grid
pfida_f calls mc_fastion_pass_grid
fidasim calls pnpa_f, pfida_f