ndmc – FIDASIM
ndmc Subroutine
83 statements
Source File
public subroutine ndmc()
Calculates neutral beam deposition and spectra
Arguments
None
Calls
Called By
Source Code
ndmc
Source Code
subroutine ndmc
    !+ Calculates neutral beam deposition and spectra
    integer :: neut_type !! full half third energy
    real(Float64)  :: nlaunch   !! nr. of markers
    real(Float64)  :: nneutrals !! # NBI particles
    real(Float64), dimension(3) :: vnbi !! velocities(full..)
    real(Float64), dimension(3) :: rnbi !! initial position
    integer(Int64) :: jj, ii, kk, cnt
    integer :: ntrack
    type(ParticleTrack), dimension(beam_grid%ntrack) :: tracks
    integer(Int64), dimension(3) :: nl_birth
    type(LocalProfiles) :: plasma
    real(Float64), dimension(nlevs) :: states, dens
    real(Float64) :: photons, iflux
    integer(Int32), dimension(3) :: ind
    real(Float64), dimension(1) :: randomu
    integer, dimension(1) :: randi
    logical :: err
    if(inputs%verbose.ge.1) then
        write(*,'(T6,"# of markers: ",i9)') inputs%n_nbi
    endif
    !! # of injected neutrals = NBI power/energy_per_particle
    nneutrals=1.d6*nbi%pinj/ (1.d3*nbi%einj*e0 &
         *( nbi%current_fractions(1)      &
         +  nbi%current_fractions(2)/2.d0 &
         +  nbi%current_fractions(3)/3.d0 ) )
    nlaunch=real(inputs%n_nbi)
    !$OMP PARALLEL DO schedule(guided) &
    !$OMP& private(vnbi,rnbi,tracks,ntrack,plasma,nl_birth,randi, &
    !$OMP& states,dens,iflux,photons,neut_type,jj,ii,kk,ind,err)
    loop_over_markers: do ii=istart,inputs%n_nbi,istep
        if(inputs%calc_birth.ge.1) then
            !! Determine the type of birth particle (1, 2, or 3)
            nl_birth = 0
            do kk=1,inputs%n_birth
                call randind(nbi%current_fractions,randi)
                nl_birth(randi(1)) = nl_birth(randi(1)) + 1
            enddo
        endif
        energy_fractions: do neut_type=1,3
            !! (type = 1: full energy, =2: half energy, =3: third energy
            call mc_nbi(vnbi,neut_type,rnbi,err)
            if(err) cycle energy_fractions
            call track(rnbi,vnbi,tracks,ntrack)
            if(ntrack.eq.0) cycle energy_fractions
            !! Solve collisional radiative model along track
            states=0.d0
            states(1)=nneutrals*nbi%current_fractions(neut_type)/beam_grid%dv
            loop_along_track: do jj=1,ntrack
                iflux = sum(states)
                ind = tracks(jj)%ind
                call get_plasma(plasma,pos=tracks(jj)%pos)
                call colrad(plasma,beam_ion,vnbi,tracks(jj)%time,states,dens,photons)
                call store_neutrals(ind,neut_type,dens/nlaunch,vnbi)
                tracks(jj)%flux = (iflux - sum(states))*beam_grid%dv/nlaunch
                if(inputs%calc_birth.ge.1) then
                    call store_births(ind,neut_type,tracks(jj)%flux)
                endif
                if((photons.gt.0.d0).and.(inputs%calc_nbi.ge.1)) then
                    call store_bes_photons(tracks(jj)%pos,vnbi,photons/nlaunch,neut_type)
                endif
            enddo loop_along_track
            if(inputs%calc_birth.ge.1) then
                !! Sample according to deposited flux along neutral trajectory
                !$OMP CRITICAL(ndmc_birth)
                do kk=1,nl_birth(neut_type)
                    call randind(tracks(1:ntrack)%flux,randi)
                    call randu(randomu)
                    birth%neut_type(birth%cnt) = neut_type
                    birth%ind(:,birth%cnt) = tracks(randi(1))%ind
                    birth%vi(:,birth%cnt) = vnbi
                    birth%ri(:,birth%cnt) = tracks(randi(1))%pos + &
                                            vnbi*(tracks(randi(1))%time*(randomu(1)-0.5))
                    birth%cnt = birth%cnt+1
                enddo
                !$OMP END CRITICAL(ndmc_birth)
            endif
        enddo energy_fractions
    enddo loop_over_markers
    !$OMP END PARALLEL DO
#ifdef _MPI
    !! Combine beam neutrals
    call parallel_sum(neut%full)
    call parallel_sum(neut%half)
    call parallel_sum(neut%third)
    call parallel_sum(nbi_outside)
    if(inputs%calc_birth.ge.1) then
        call parallel_sum(birth%dens)
    endif
    !! Combine spectra
    if(inputs%calc_nbi.ge.1) then
        call parallel_sum(spec%full)
        call parallel_sum(spec%half)
        call parallel_sum(spec%third)
    endif
#endif
    if(nbi_outside.gt.0)then
        if(inputs%verbose.ge.0) then
            write(*,'(T4,a, f6.2)') 'Percent of markers outside the grid: ', &
                                  100.*nbi_outside/(3.*inputs%n_nbi)
        endif
        if(sum(neut%full).eq.0) stop 'Beam does not intersect the grid!'
    endif
end subroutine ndmc
All Procedures
approx_eq approx_ge approx_le Aq_cx Aq_cx_n Aq_cx_n_adas Aq_cx_n_janev Aq_excit Aq_excit_1_2_janev Aq_excit_1_3_janev Aq_excit_1_4_janev Aq_excit_1_5_janev Aq_excit_1_janev Aq_excit_2_10_janev Aq_excit_2_3_janev Aq_excit_2_4_janev Aq_excit_2_5_janev Aq_excit_2_6_janev Aq_excit_2_7_janev Aq_excit_2_8_janev Aq_excit_2_9_janev Aq_excit_2_janev Aq_excit_3_10_janev Aq_excit_3_4_janev Aq_excit_3_5_janev Aq_excit_3_6_janev Aq_excit_3_7_janev Aq_excit_3_8_janev Aq_excit_3_9_janev Aq_excit_3_janev Aq_excit_n Aq_excit_n_janev Aq_excit_n_m Aq_ioniz Aq_ioniz_n Aq_ioniz_n_janev assignment(=) attenuate B5_cx_1_adas B5_cx_1_janev B5_cx_2_adas B5_ioniz_1_janev balance balback bb_cx_rates boundary_edge bremsstrahlung bt_cx_rates bt_maxwellian bt_maxwellian_eb bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m C6_cx_1_adas C6_cx_1_janev C6_cx_2_adas C6_cx_3_adas C6_ioniz_1_janev calc_perp_vectors check_compression_availability circle_grid_intersect cleanup_mpi cold_spec colrad comabs Comdiv cross_product cumsum d_d_fusion_he d_d_fusion_t d_t_fusion dcx dcx_spec deriv e_excit e_excit_1_2_janev e_excit_1_3_janev e_excit_1_4_janev e_excit_1_5_janev e_excit_1_janev e_excit_2_3_janev e_excit_f e_excit_n e_excit_n_m e_ioniz e_ioniz_1_janev e_ioniz_2_janev e_ioniz_3_janev e_ioniz_n eigen elmhes elmtrans fast_ion_assign ff_add ff_assign ff_subtract fida_f fida_mc fida_weights_los fida_weights_mc flf_assign fs_divide fs_multiply get_beam_cx_rate get_distribution get_ep_denf get_fields get_indices get_neutron_rate get_nlaunch get_plasma get_position get_rate_matrix get_rng get_value grid_intersect gyro_correction gyro_radius gyro_range gyro_step gyro_surface gyro_surface_coordinates gyro_trajectory h5ltmake_compressed_dataset_double_f h5ltmake_compressed_dataset_double_f_1 h5ltmake_compressed_dataset_double_f_2 h5ltmake_compressed_dataset_double_f_3 h5ltmake_compressed_dataset_double_f_4 h5ltmake_compressed_dataset_double_f_5 h5ltmake_compressed_dataset_double_f_6 h5ltmake_compressed_dataset_double_f_7 h5ltmake_compressed_dataset_int_f h5ltmake_compressed_dataset_int_f_1 h5ltmake_compressed_dataset_int_f_2 h5ltmake_compressed_dataset_int_f_3 h5ltmake_compressed_dataset_int_f_4 h5ltmake_compressed_dataset_int_f_5 h5ltmake_compressed_dataset_int_f_6 h5ltmake_compressed_dataset_int_f_7 h5ltread_dataset_double_scalar_f h5ltread_dataset_int_scalar_f halo halo_spec hit_npa_detector hqr2 hqrvec in_boundary in_grid in_gyro_surface in_plasma ind2sub init_mpi interpol interpol1D_arr interpol1D_coeff interpol1D_coeff_arr interpol2D_2D_arr interpol2D_arr interpol2D_coeff interpol2D_coeff_arr interpol_coeff lff_assign lflf_add lflf_assign lflf_subtract lfs_divide lfs_multiply line_basis line_gyro_surface_intersect line_plane_intersect linsolve lplp_add lplp_assign lplp_subtract lpp_assign lps_divide lps_multiply lubksb ludcmp m_spread make_beam_grid matinv mc_fastion mc_halo mc_nbi mc_nbi_cell my_rank nbi_spec ndmc neutron_f neutron_mc norm2 npa_f npa_gyro_range npa_mc npa_part_assign npa_weights num_ranks operator(*) operator(+) operator(-) operator(/) outerprod p_cx p_cx_1 p_cx_1_1_adas p_cx_1_2_adas p_cx_1_3_adas p_cx_1_4_adas p_cx_1_janev p_cx_2 p_cx_2_2_adas p_cx_2_3_adas p_cx_2_janev p_cx_3 p_cx_3_2_adas p_cx_3_3_adas p_cx_3_4_adas p_cx_3_5_adas p_cx_3_6inf_adas p_cx_3_janev p_cx_janev p_cx_n p_cx_n_janev p_cx_n_m p_excit p_excit_1_2_janev p_excit_1_3_janev p_excit_1_4_janev p_excit_1_5_janev p_excit_1_6_janev p_excit_1_janev p_excit_2_10_janev p_excit_2_3_janev p_excit_2_4_janev p_excit_2_5_janev p_excit_2_6_janev p_excit_2_7_janev p_excit_2_8_janev p_excit_2_9_janev p_excit_2_janev p_excit_3_10_janev p_excit_3_4_janev p_excit_3_5_janev p_excit_3_6_janev p_excit_3_7_janev p_excit_3_8_janev p_excit_3_9_janev p_excit_3_janev p_excit_n p_excit_n_m p_ioniz p_ioniz_1_janev p_ioniz_2_omullane p_ioniz_3_omullane p_ioniz_4_omullane p_ioniz_5_omullane p_ioniz_n parallel_sum parallel_sum_d0 parallel_sum_d1 parallel_sum_d2 parallel_sum_d3 parallel_sum_d4 parallel_sum_d5 parallel_sum_i0 parallel_sum_i1 parallel_sum_i2 pfida_f pfida_mc pitch_to_vec plane_basis plp_assign pnpa_f pnpa_mc pp_add pp_assign pp_subtract print_banner print_default_namelist ps_divide ps_multiply randind randind_cdf randn randu read_atomic_cross read_atomic_rate read_atomic_transitions read_beam read_chords read_distribution read_equilibrium read_f read_inputs read_mc read_neutrals read_npa read_nuclear_rates read_tables rng_init rng_normal rng_seed rng_uniform RSWAP sf_multiply simpsons_rule slf_multiply slp_multiply sp_multiply sparse spectrum store_bes_photons store_births store_fida_photons store_fw_photons store_fw_photons_at_chan store_neutrals store_neutrons store_npa store_photons sub2ind swap tb_zyx time track uvw_to_xyz write_bb_D_D write_bb_D_T write_bb_H_Aq write_bb_H_e write_bb_H_H write_beam_grid write_birth_profile write_bt_D_D write_bt_D_T write_bt_H_Aq write_bt_H_e write_bt_H_H write_einstein write_fida_weights write_neutrals write_neutrons write_npa write_npa_weights write_spectra xyz_to_uvw
Call graph
ndmc calls colrad, store_bes_photons, parallel_sum, randind, mc_nbi, track, get_plasma, store_births, store_neutrals, randu
colrad calls get_rate_matrix, eigen, linsolve
store_bes_photons calls store_photons
parallel_sum calls parallel_sum_d5, parallel_sum_i0, parallel_sum_d3, parallel_sum_i1, parallel_sum_d1, parallel_sum_d4, parallel_sum_d0, parallel_sum_i2, parallel_sum_d2
mc_nbi calls randu, in_plasma, grid_intersect, randn
track calls get_indices, in_plasma
get_plasma calls get_position, in_plasma
get_rate_matrix calls interpol_coeff
eigen calls hqr2, balback, balance, elmtrans, elmhes
linsolve calls matinv, dgetrf, dgetrs
interpol_coeff calls interpol2d_coeff_arr, interpol1d_coeff, interpol1d_coeff_arr, interpol2d_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
hqr2 calls hqrvec
balback calls rswap
balance calls rswap
elmhes calls rswap
hqrvec calls comdiv
matinv calls ludcmp, lubksb
ludcmp calls swap, outerprod
store_photons calls get_fields, get_indices, spectrum
get_fields calls get_position, calc_perp_vectors, in_plasma
in_plasma calls interpol_coeff, xyz_to_uvw
parallel_sum_d5 calls mpi_allreduce
parallel_sum_i0 calls mpi_allreduce
parallel_sum_d3 calls mpi_allreduce
parallel_sum_i1 calls mpi_allreduce
parallel_sum_d1 calls mpi_allreduce
parallel_sum_d4 calls mpi_allreduce
parallel_sum_d0 calls mpi_allreduce
parallel_sum_i2 calls mpi_allreduce
parallel_sum_d2 calls mpi_allreduce
fidasim calls ndmc