neutron_mc – FIDASIM
neutron_mc Subroutine
60 statements
Source File
public subroutine neutron_mc()
Calculate neutron flux using a Monte Carlo Fast-ion distribution
Arguments
None
Calls
Called By
Source Code
neutron_mc
Source Code
subroutine neutron_mc
    !+ Calculate neutron flux using a Monte Carlo Fast-ion distribution
    integer :: iion, nphi, iphi
    type(FastIon) :: fast_ion
    type(LocalProfiles) :: plasma
    type(LocalEMFields) :: fields
    real(Float64) :: eb, rate
    real(Float64), dimension(3) :: ri, rg
    real(Float64), dimension(3) :: vi
    real(Float64), dimension(3) :: uvw, uvw_vi
    real(Float64)  :: vnet_square
    if(inputs%verbose.ge.1) then
        write(*,'(T6,"# of markers: ",i9)') particles%nparticle
    endif
    rate=0.0
    nphi = 20
    !$OMP PARALLEL DO schedule(guided) private(iion,fast_ion,vi,ri,rg, &
    !$OMP& plasma,fields,uvw,uvw_vi,vnet_square,rate,eb,iphi)
    loop_over_fast_ions: do iion=istart,particles%nparticle,istep
        fast_ion = particles%fast_ion(iion)
        if(fast_ion%vabs.eq.0.d0) cycle loop_over_fast_ions
        !! Calculate position
        uvw(1) = fast_ion%r
        uvw(2) = 0.0
        uvw(3) = fast_ion%z
        if(inputs%dist_type.eq.2) then
            call uvw_to_xyz(uvw, rg)
            !! Get electomagnetic fields
            call get_fields(fields, pos=rg)
            if(.not.fields%in_plasma) cycle loop_over_fast_ions
            gyro_loop: do iphi=1,nphi
                !! Correct for Gyro-motion
                call gyro_correction(fields, fast_ion%energy, fast_ion%pitch, ri, vi)
                !! Get plasma parameters
                call get_plasma(plasma,pos=ri)
                if(.not.plasma%in_plasma) cycle gyro_loop
                !! Calculate effective beam energy
                vnet_square=dot_product(vi-plasma%vrot,vi-plasma%vrot)  ![cm/s]
                eb = v2_to_E_per_amu*inputs%ab*vnet_square ![kev]
                !! Get neutron production rate
                call get_neutron_rate(plasma, eb, rate)
                rate = rate*fast_ion%weight*(2*pi/fast_ion%delta_phi)*beam_grid%dv/nphi
                !! Store neutrons
                call store_neutrons(rate, fast_ion%class)
            enddo gyro_loop
        else
            call uvw_to_xyz(uvw, ri)
            !! Get plasma parameters
            call get_plasma(plasma,pos=ri)
            if(.not.plasma%in_plasma) cycle loop_over_fast_ions
            !! Calculate effective beam energy
            uvw_vi(1) = fast_ion%vr
            uvw_vi(2) = fast_ion%vt
            uvw_vi(3) = fast_ion%vz
            vi = matmul(beam_grid%inv_basis,uvw_vi)
            vnet_square=dot_product(vi-plasma%vrot,vi-plasma%vrot)  ![cm/s]
            eb = v2_to_E_per_amu*inputs%ab*vnet_square ![kev]
            !! Get neutron production rate
            call get_neutron_rate(plasma, eb, rate)
            rate = rate*fast_ion%weight*(2*pi/fast_ion%delta_phi)*beam_grid%dv
            !! Store neutrons
            call store_neutrons(rate, fast_ion%class)
        endif
    enddo loop_over_fast_ions
    !$OMP END PARALLEL DO
#ifdef _MPI
    call fidampi_sum(neutron%rate)
#endif
    if(inputs%verbose.ge.1) then
        write(*,'(T4,A,ES14.5," [neutrons/s]")') 'Rate:   ',sum(neutron%rate)
        write(*,'(30X,a)') ''
        write(*,*) 'write neutrons:    ' , time(time_start)
        write(*,'(30X,a)') ''
    endif
#ifdef _MPI
    if(fidampi_my_rank().eq.0) call write_neutrons()
#else
    call write_neutrons()
#endif
end subroutine neutron_mc
All Procedures
approx_eq approx_ge approx_le Aq_cx Aq_cx_n Aq_cx_n_adas Aq_cx_n_janev Aq_excit Aq_excit_1_2_janev Aq_excit_1_3_janev Aq_excit_1_4_janev Aq_excit_1_5_janev Aq_excit_1_janev Aq_excit_2_10_janev Aq_excit_2_3_janev Aq_excit_2_4_janev Aq_excit_2_5_janev Aq_excit_2_6_janev Aq_excit_2_7_janev Aq_excit_2_8_janev Aq_excit_2_9_janev Aq_excit_2_janev Aq_excit_3_10_janev Aq_excit_3_4_janev Aq_excit_3_5_janev Aq_excit_3_6_janev Aq_excit_3_7_janev Aq_excit_3_8_janev Aq_excit_3_9_janev Aq_excit_3_janev Aq_excit_n Aq_excit_n_janev Aq_excit_n_m Aq_ioniz Aq_ioniz_n Aq_ioniz_n_janev assignment(=) attenuate B5_cx_1_adas B5_cx_1_janev B5_cx_2_adas B5_ioniz_1_janev balance balback bb_cx_rates boundary_edge bremsstrahlung bt_cx_rates bt_maxwellian bt_maxwellian_eb bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m C6_cx_1_adas C6_cx_1_janev C6_cx_2_adas C6_cx_3_adas C6_ioniz_1_janev calc_perp_vectors check_compression_availability circle_grid_intersect cold_spec colrad comabs Comdiv cross_product cumsum d_d_fusion_he d_d_fusion_t d_t_fusion dcx dcx_spec deriv e_excit e_excit_1_2_janev e_excit_1_3_janev e_excit_1_4_janev e_excit_1_5_janev e_excit_1_janev e_excit_2_3_janev e_excit_f e_excit_n e_excit_n_m e_ioniz e_ioniz_1_janev e_ioniz_2_janev e_ioniz_3_janev e_ioniz_n eigen elmhes elmtrans fast_ion_assign ff_add ff_assign ff_subtract fida_f fida_mc fida_weights_los fida_weights_mc fidampi_clenup fidampi_init fidampi_my_rank fidampi_num_ranks fidampi_sum fidampi_sum_d0 fidampi_sum_d1 fidampi_sum_d2 fidampi_sum_d3 fidampi_sum_d4 fidampi_sum_d5 fidampi_sum_i0 fidampi_sum_i1 fidampi_sum_i2 flf_assign fs_divide fs_multiply get_beam_cx_rate get_distribution get_ep_denf get_fields get_indices get_neutron_rate get_nlaunch get_plasma get_position get_rate_matrix get_rng get_value grid_intersect gyro_correction gyro_radius gyro_range gyro_step gyro_surface gyro_surface_coordinates gyro_trajectory h5ltmake_compressed_dataset_double_f h5ltmake_compressed_dataset_double_f_1 h5ltmake_compressed_dataset_double_f_2 h5ltmake_compressed_dataset_double_f_3 h5ltmake_compressed_dataset_double_f_4 h5ltmake_compressed_dataset_double_f_5 h5ltmake_compressed_dataset_double_f_6 h5ltmake_compressed_dataset_double_f_7 h5ltmake_compressed_dataset_int_f h5ltmake_compressed_dataset_int_f_1 h5ltmake_compressed_dataset_int_f_2 h5ltmake_compressed_dataset_int_f_3 h5ltmake_compressed_dataset_int_f_4 h5ltmake_compressed_dataset_int_f_5 h5ltmake_compressed_dataset_int_f_6 h5ltmake_compressed_dataset_int_f_7 h5ltread_dataset_double_scalar_f h5ltread_dataset_int_scalar_f halo halo_spec hit_npa_detector hqr2 hqrvec in_boundary in_grid in_gyro_surface in_plasma ind2sub interpol interpol1D_arr interpol1D_coeff interpol1D_coeff_arr interpol2D_2D_arr interpol2D_arr interpol2D_coeff interpol2D_coeff_arr interpol_coeff lff_assign lflf_add lflf_assign lflf_subtract lfs_divide lfs_multiply line_basis line_gyro_surface_intersect line_plane_intersect linsolve lplp_add lplp_assign lplp_subtract lpp_assign lps_divide lps_multiply lubksb ludcmp m_spread make_beam_grid matinv mc_fastion mc_halo mc_nbi mc_nbi_cell nbi_spec ndmc neutron_f neutron_mc norm2 npa_f npa_gyro_range npa_mc npa_part_assign npa_weights operator(*) operator(+) operator(-) operator(/) outerprod p_cx p_cx_1 p_cx_1_1_adas p_cx_1_2_adas p_cx_1_3_adas p_cx_1_4_adas p_cx_1_janev p_cx_2 p_cx_2_2_adas p_cx_2_3_adas p_cx_2_janev p_cx_3 p_cx_3_2_adas p_cx_3_3_adas p_cx_3_4_adas p_cx_3_5_adas p_cx_3_6inf_adas p_cx_3_janev p_cx_janev p_cx_n p_cx_n_janev p_cx_n_m p_excit p_excit_1_2_janev p_excit_1_3_janev p_excit_1_4_janev p_excit_1_5_janev p_excit_1_6_janev p_excit_1_janev p_excit_2_10_janev p_excit_2_3_janev p_excit_2_4_janev p_excit_2_5_janev p_excit_2_6_janev p_excit_2_7_janev p_excit_2_8_janev p_excit_2_9_janev p_excit_2_janev p_excit_3_10_janev p_excit_3_4_janev p_excit_3_5_janev p_excit_3_6_janev p_excit_3_7_janev p_excit_3_8_janev p_excit_3_9_janev p_excit_3_janev p_excit_n p_excit_n_m p_ioniz p_ioniz_1_janev p_ioniz_2_omullane p_ioniz_3_omullane p_ioniz_4_omullane p_ioniz_5_omullane p_ioniz_n pfida_f pfida_mc pitch_to_vec plane_basis plp_assign pnpa_f pnpa_mc pp_add pp_assign pp_subtract print_banner print_default_namelist ps_divide ps_multiply randind randind_cdf randn randu read_atomic_cross read_atomic_rate read_atomic_transitions read_beam read_chords read_distribution read_equilibrium read_f read_inputs read_mc read_neutrals read_npa read_nuclear_rates read_tables rng_init rng_normal rng_seed rng_uniform RSWAP sf_multiply simpsons_rule slf_multiply slp_multiply sp_multiply sparse spectrum store_bes_photons store_births store_fida_photons store_fw_photons store_fw_photons_at_chan store_neutrals store_neutrons store_npa store_photons sub2ind swap tb_zyx time track uvw_to_xyz write_bb_D_D write_bb_D_T write_bb_H_Aq write_bb_H_e write_bb_H_H write_beam_grid write_birth_profile write_bt_D_D write_bt_D_T write_bt_H_Aq write_bt_H_e write_bt_H_H write_einstein write_fida_weights write_neutrals write_neutrons write_npa write_npa_weights write_spectra xyz_to_uvw
Call graph
neutron_mc calls uvw_to_xyz, write_neutrons, get_neutron_rate, store_neutrons, get_fields, fidampi_my_rank, get_plasma, fidampi_sum, gyro_correction
write_neutrons calls h5close_f, h5ltmake_compressed_dataset_double_f, h5fclose_f, h5open_f, h5ltset_attribute_string_f, h5ltmake_dataset_int_f, h5ltmake_dataset_double_f, h5fcreate_f
get_neutron_rate calls interpol_coeff
get_fields calls get_position, calc_perp_vectors, in_plasma
get_plasma calls get_position, in_plasma
fidampi_sum calls fidampi_sum_d4, fidampi_sum_i2, fidampi_sum_d5, fidampi_sum_i0, fidampi_sum_d2, fidampi_sum_i1, fidampi_sum_d3, fidampi_sum_d0, fidampi_sum_d1
gyro_correction calls randu, pitch_to_vec, gyro_step
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_6, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_4
h5ltmake_compressed_dataset_double_f_6 calls h5ltmake_dataset_double_f, h5pset_shuffle_f, h5pcreate_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5pclose_f, h5dclose_f
h5ltmake_compressed_dataset_double_f_2 calls h5ltmake_dataset_double_f, h5pset_shuffle_f, h5pcreate_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5pclose_f, h5dclose_f
h5ltmake_compressed_dataset_double_f_5 calls h5ltmake_dataset_double_f, h5pset_shuffle_f, h5pcreate_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5pclose_f, h5dclose_f
h5ltmake_compressed_dataset_double_f_3 calls h5ltmake_dataset_double_f, h5pset_shuffle_f, h5pcreate_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5pclose_f, h5dclose_f
h5ltmake_compressed_dataset_double_f_1 calls h5ltmake_dataset_double_f, h5pset_shuffle_f, h5pcreate_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5pclose_f, h5dclose_f
h5ltmake_compressed_dataset_double_f_7 calls h5ltmake_dataset_double_f, h5pset_shuffle_f, h5pcreate_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5pclose_f, h5dclose_f
h5ltmake_compressed_dataset_double_f_4 calls h5ltmake_dataset_double_f, h5pset_shuffle_f, h5pcreate_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5pclose_f, h5dclose_f
interpol_coeff calls interpol2d_coeff_arr, interpol2d_coeff, interpol1d_coeff, interpol1d_coeff_arr
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
in_plasma calls interpol_coeff, xyz_to_uvw
fidampi_sum_d4 calls mpi_allreduce
fidampi_sum_i2 calls mpi_allreduce
fidampi_sum_d5 calls mpi_allreduce
fidampi_sum_i0 calls mpi_allreduce
fidampi_sum_d2 calls mpi_allreduce
fidampi_sum_i1 calls mpi_allreduce
fidampi_sum_d3 calls mpi_allreduce
fidampi_sum_d0 calls mpi_allreduce
fidampi_sum_d1 calls mpi_allreduce
gyro_step calls cross_product
fidasim calls neutron_mc