npa_weights – FIDASIM
npa_weights Subroutine
109 statements
Source File
public subroutine npa_weights()
Calculates NPA weights
Arguments
None
Calls
Called By
Source Code
npa_weights
Source Code
subroutine npa_weights
    !+ Calculates NPA weights
    type(LocalEMFields) :: fields
    type(NPAProbability) :: phit
    real(Float64) :: pitch
    real(Float64) :: pcxa
    integer(Int32) :: det
    integer(Int32) :: ii, jj, kk, i, ic   !!indices
    integer,dimension(1) :: ipitch
    real(Float64), dimension(3) :: vi,vi_norm
    real(Float64) :: vabs, fbm_denf, dE, dP
    real(Float64), dimension(nlevs) :: pcx   !! Rate coefficiants for CX
    real(Float64), dimension(nlevs) :: states, states_i  ! Density of n-states
    integer, dimension(5) :: neut_types=[1,2,3,4,5]
    real(Float64), dimension(3) :: pos,dpos,r_gyro
    integer(Int32) :: ichan
    real(Float64), dimension(:), allocatable :: ebarr, ptcharr
    !! define energy - array
    allocate(ebarr(inputs%ne_wght))
    do i=1,inputs%ne_wght
        ebarr(i)=real(i-0.5)*inputs%emax_wght/real(inputs%ne_wght)
    enddo
    dE=abs(ebarr(2)-ebarr(1))
    !! define pitch - array
    allocate(ptcharr(inputs%np_wght))
    do i=1,inputs%np_wght
        ptcharr(i)=real(i-0.5)*2./real(inputs%np_wght)-1.
    enddo
    dP=abs(ptcharr(2)-ptcharr(1))
    if(inputs%verbose.ge.1) then
        write(*,'(T3,"Number of Channels: ",i3)') npa_chords%nchan
        write(*,'(T3,"Nenergy: ",i3)') inputs%ne_wght
        write(*,'(T3,"Npitch: ",i3)') inputs%np_wght
        write(*,'(T3,"Maximum energy: ",f7.2)') inputs%emax_wght
        write(*,*) ''
    endif
    !! define storage arrays
    allocate(nweight%emissivity(beam_grid%nx, &
                                beam_grid%ny, &
                                beam_grid%nz, &
                                npa_chords%nchan))
    allocate(nweight%attenuation(inputs%ne_wght, &
                                 beam_grid%nx, &
                                 beam_grid%ny, &
                                 beam_grid%nz, &
                                 npa_chords%nchan))
    allocate(nweight%cx(inputs%ne_wght, &
                        beam_grid%nx, &
                        beam_grid%ny, &
                        beam_grid%nz, &
                        npa_chords%nchan))
    allocate(nweight%weight(inputs%ne_wght, &
                            inputs%np_wght, &
                            npa_chords%nchan))
    allocate(nweight%flux(inputs%ne_wght, npa_chords%nchan))
    nweight%emissivity = 0.d0
    nweight%attenuation = 0.d0
    nweight%cx = 0.d0
    nweight%weight = 0.d0
    nweight%flux = 0.d0
    loop_over_channels: do ichan=1,npa_chords%nchan
        !$OMP PARALLEL DO schedule(guided) collapse(3) private(ii,jj,kk,fields,phit,&
        !$OMP& ic,det,pos,dpos,r_gyro,pitch,ipitch,vabs,vi,pcx,pcxa,states,states_i,vi_norm,fbm_denf)
        loop_along_z: do kk=1,beam_grid%nz
            loop_along_y: do jj=1,beam_grid%ny
                loop_along_x: do ii=1,beam_grid%nx
                    phit = npa_chords%phit(ii,jj,kk,ichan)
                    if(phit%p.gt.0.d0) then
                        pos = [beam_grid%xc(ii), beam_grid%yc(jj), beam_grid%zc(kk)]
                        call get_fields(fields,pos=pos)
                        if(.not.fields%in_plasma) cycle loop_along_x
                        !!Check if it hits a detector just to make sure
                        dpos = phit%eff_rd
                        vi_norm = phit%dir
                        call hit_npa_detector(pos,vi_norm,det)
                        if (det.ne.ichan) then
                            if(inputs%verbose.ge.0) then
                                write(*,'(a)') 'NPA_WEIGHTS: Missed detector'
                            endif
                            cycle loop_along_x
                        endif
                        !! Determine the angle between the B-field and the Line of Sight
                        pitch = phit%pitch
                        ipitch=minloc(abs(ptcharr - pitch))
                        loop_over_energy: do ic = istart, inputs%ne_wght,istep !! energy loop
                            vabs = sqrt(ebarr(ic)/(v2_to_E_per_amu*inputs%ab))
                            vi = vi_norm*vabs
                            !!Correct for gyro orbit
                            call gyro_step(vi,fields,r_gyro)
                            fbm_denf=0
                            if (inputs%dist_type.eq.1) then
                                !get dist at guiding center
                                call get_ep_denf(ebarr(ic),pitch,fbm_denf,pos=(pos+r_gyro))
                            endif
                            if (fbm_denf.ne.fbm_denf) cycle loop_over_energy
                            !! -------------- calculate CX probability -------!!
                            call get_beam_cx_rate([ii,jj,kk],pos,vi,beam_ion,neut_types,pcx)
                            if(sum(pcx).le.0) cycle loop_over_energy
                            !!Calculate attenuation
                            states = pcx*1.0d14 !!needs to be large aribitrary number so colrad works
                            states_i=states
                            call attenuate(pos,dpos,vi,states)
                            pcxa=sum(states)/sum(states_i)
                            !$OMP CRITICAL(npa_wght)
                            nweight%attenuation(ic,ii,jj,kk,ichan) = pcxa
                            nweight%cx(ic,ii,jj,kk,ichan) = sum(pcx)
                            nweight%weight(ic,ipitch(1),ichan) = nweight%weight(ic,ipitch(1),ichan) + &
                                      2*sum(pcx)*pcxa*phit%p*beam_grid%dv/dP
                            nweight%flux(ic,ichan) = nweight%flux(ic,ichan) + &
                                      2*beam_grid%dv*fbm_denf*sum(pcx)*pcxa*phit%p
                                      !Factor of 2 above is to convert fbm to ions/(cm^3 dE (domega/4pi))
                            nweight%emissivity(ii,jj,kk,ichan)=nweight%emissivity(ii,jj,kk,ichan)+ &
                                      2*fbm_denf*sum(pcx)*pcxa*phit%p*dE
                            !$OMP END CRITICAL(npa_wght)
                        enddo loop_over_energy
                    endif
                enddo loop_along_x
            enddo loop_along_y
        enddo loop_along_z
        !$OMP END PARALLEL DO
    enddo loop_over_channels
#ifdef _MPI
    call fidampi_sum(nweight%weight)
    call fidampi_sum(nweight%flux)
    call fidampi_sum(nweight%cx)
    call fidampi_sum(nweight%attenuation)
    call fidampi_sum(nweight%emissivity)
#endif
    do ichan=1,npa_chords%nchan
        if(inputs%verbose.ge.1) then
            write(*,'(T4,"Channel: ",i3)') ichan
            write(*,'(T4,"Radius: ",f10.3)') npa_chords%radius(ichan)
            write(*,'(T4,A,ES14.5)') 'Flux:   ',sum(nweight%flux(:,ichan))*dE
            write(*,'(T4,A,ES14.5)') 'Weight: ',sum(nweight%weight(:,:,ichan))*dE*dP
            write(*,*) ''
        endif
    enddo
    if(inputs%verbose.ge.1) then
        write(*,*) 'write npa weights:    ' , time(time_start)
    endif
#ifdef _MPI
    if(fidampi_my_rank().eq.0) call write_npa_weights()
#else
    call write_npa_weights()
#endif
end subroutine npa_weights
All Procedures
approx_eq approx_ge approx_le Aq_cx Aq_cx_n Aq_cx_n_adas Aq_cx_n_janev Aq_excit Aq_excit_1_2_janev Aq_excit_1_3_janev Aq_excit_1_4_janev Aq_excit_1_5_janev Aq_excit_1_janev Aq_excit_2_10_janev Aq_excit_2_3_janev Aq_excit_2_4_janev Aq_excit_2_5_janev Aq_excit_2_6_janev Aq_excit_2_7_janev Aq_excit_2_8_janev Aq_excit_2_9_janev Aq_excit_2_janev Aq_excit_3_10_janev Aq_excit_3_4_janev Aq_excit_3_5_janev Aq_excit_3_6_janev Aq_excit_3_7_janev Aq_excit_3_8_janev Aq_excit_3_9_janev Aq_excit_3_janev Aq_excit_n Aq_excit_n_janev Aq_excit_n_m Aq_ioniz Aq_ioniz_n Aq_ioniz_n_janev assignment(=) attenuate B5_cx_1_adas B5_cx_1_janev B5_cx_2_adas B5_ioniz_1_janev balance balback bb_cx_rates boundary_edge bremsstrahlung bt_cx_rates bt_maxwellian bt_maxwellian_eb bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m C6_cx_1_adas C6_cx_1_janev C6_cx_2_adas C6_cx_3_adas C6_ioniz_1_janev calc_perp_vectors check_compression_availability circle_grid_intersect cold_spec colrad comabs Comdiv cross_product cumsum d_d_fusion_he d_d_fusion_t d_t_fusion dcx dcx_spec deriv e_excit e_excit_1_2_janev e_excit_1_3_janev e_excit_1_4_janev e_excit_1_5_janev e_excit_1_janev e_excit_2_3_janev e_excit_f e_excit_n e_excit_n_m e_ioniz e_ioniz_1_janev e_ioniz_2_janev e_ioniz_3_janev e_ioniz_n eigen elmhes elmtrans fast_ion_assign ff_add ff_assign ff_subtract fida_f fida_mc fida_weights_los fida_weights_mc fidampi_clenup fidampi_init fidampi_my_rank fidampi_num_ranks fidampi_sum fidampi_sum_d0 fidampi_sum_d1 fidampi_sum_d2 fidampi_sum_d3 fidampi_sum_d4 fidampi_sum_d5 fidampi_sum_i0 fidampi_sum_i1 fidampi_sum_i2 flf_assign fs_divide fs_multiply get_beam_cx_rate get_distribution get_ep_denf get_fields get_indices get_neutron_rate get_nlaunch get_plasma get_position get_rate_matrix get_rng get_value grid_intersect gyro_correction gyro_radius gyro_range gyro_step gyro_surface gyro_surface_coordinates gyro_trajectory h5ltmake_compressed_dataset_double_f h5ltmake_compressed_dataset_double_f_1 h5ltmake_compressed_dataset_double_f_2 h5ltmake_compressed_dataset_double_f_3 h5ltmake_compressed_dataset_double_f_4 h5ltmake_compressed_dataset_double_f_5 h5ltmake_compressed_dataset_double_f_6 h5ltmake_compressed_dataset_double_f_7 h5ltmake_compressed_dataset_int_f h5ltmake_compressed_dataset_int_f_1 h5ltmake_compressed_dataset_int_f_2 h5ltmake_compressed_dataset_int_f_3 h5ltmake_compressed_dataset_int_f_4 h5ltmake_compressed_dataset_int_f_5 h5ltmake_compressed_dataset_int_f_6 h5ltmake_compressed_dataset_int_f_7 h5ltread_dataset_double_scalar_f h5ltread_dataset_int_scalar_f halo halo_spec hit_npa_detector hqr2 hqrvec in_boundary in_grid in_gyro_surface in_plasma ind2sub interpol interpol1D_arr interpol1D_coeff interpol1D_coeff_arr interpol2D_2D_arr interpol2D_arr interpol2D_coeff interpol2D_coeff_arr interpol_coeff lff_assign lflf_add lflf_assign lflf_subtract lfs_divide lfs_multiply line_basis line_gyro_surface_intersect line_plane_intersect linsolve lplp_add lplp_assign lplp_subtract lpp_assign lps_divide lps_multiply lubksb ludcmp m_spread make_beam_grid matinv mc_fastion mc_halo mc_nbi mc_nbi_cell nbi_spec ndmc neutron_f neutron_mc norm2 npa_f npa_gyro_range npa_mc npa_part_assign npa_weights operator(*) operator(+) operator(-) operator(/) outerprod p_cx p_cx_1 p_cx_1_1_adas p_cx_1_2_adas p_cx_1_3_adas p_cx_1_4_adas p_cx_1_janev p_cx_2 p_cx_2_2_adas p_cx_2_3_adas p_cx_2_janev p_cx_3 p_cx_3_2_adas p_cx_3_3_adas p_cx_3_4_adas p_cx_3_5_adas p_cx_3_6inf_adas p_cx_3_janev p_cx_janev p_cx_n p_cx_n_janev p_cx_n_m p_excit p_excit_1_2_janev p_excit_1_3_janev p_excit_1_4_janev p_excit_1_5_janev p_excit_1_6_janev p_excit_1_janev p_excit_2_10_janev p_excit_2_3_janev p_excit_2_4_janev p_excit_2_5_janev p_excit_2_6_janev p_excit_2_7_janev p_excit_2_8_janev p_excit_2_9_janev p_excit_2_janev p_excit_3_10_janev p_excit_3_4_janev p_excit_3_5_janev p_excit_3_6_janev p_excit_3_7_janev p_excit_3_8_janev p_excit_3_9_janev p_excit_3_janev p_excit_n p_excit_n_m p_ioniz p_ioniz_1_janev p_ioniz_2_omullane p_ioniz_3_omullane p_ioniz_4_omullane p_ioniz_5_omullane p_ioniz_n pfida_f pfida_mc pitch_to_vec plane_basis plp_assign pnpa_f pnpa_mc pp_add pp_assign pp_subtract print_banner print_default_namelist ps_divide ps_multiply randind randind_cdf randn randu read_atomic_cross read_atomic_rate read_atomic_transitions read_beam read_chords read_distribution read_equilibrium read_f read_inputs read_mc read_neutrals read_npa read_nuclear_rates read_tables rng_init rng_normal rng_seed rng_uniform RSWAP sf_multiply simpsons_rule slf_multiply slp_multiply sp_multiply sparse spectrum store_bes_photons store_births store_fida_photons store_fw_photons store_fw_photons_at_chan store_neutrals store_neutrons store_npa store_photons sub2ind swap tb_zyx time track uvw_to_xyz write_bb_D_D write_bb_D_T write_bb_H_Aq write_bb_H_e write_bb_H_H write_beam_grid write_birth_profile write_bt_D_D write_bt_D_T write_bt_H_Aq write_bt_H_e write_bt_H_H write_einstein write_fida_weights write_neutrals write_neutrons write_npa write_npa_weights write_spectra xyz_to_uvw
Call graph
npa_weights calls fidampi_my_rank, get_ep_denf, fidampi_sum, write_npa_weights, hit_npa_detector, gyro_step, get_fields, get_beam_cx_rate, attenuate
get_ep_denf calls get_position, interpol, xyz_to_uvw
fidampi_sum calls fidampi_sum_d4, fidampi_sum_i2, fidampi_sum_d5, fidampi_sum_i0, fidampi_sum_d2, fidampi_sum_i1, fidampi_sum_d3, fidampi_sum_d0, fidampi_sum_d1
write_npa_weights calls h5close_f, h5ltset_attribute_string_f, h5open_f, h5ltmake_compressed_dataset_double_f, h5ltmake_dataset_int_f, write_beam_grid, h5fclose_f, h5fcreate_f
hit_npa_detector calls in_boundary, line_plane_intersect
gyro_step calls cross_product
get_fields calls get_position, calc_perp_vectors, in_plasma
get_beam_cx_rate calls get_plasma, bb_cx_rates, bt_cx_rates
attenuate calls get_plasma, colrad
interpol calls interpol1d_arr, interpol2d_2d_arr, interpol2d_arr
interpol1d_arr calls interpol_coeff
interpol2d_2d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol_coeff calls interpol2d_coeff_arr, interpol2d_coeff, interpol1d_coeff, interpol1d_coeff_arr
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
fidampi_sum_d4 calls mpi_allreduce
fidampi_sum_i2 calls mpi_allreduce
fidampi_sum_d5 calls mpi_allreduce
fidampi_sum_i0 calls mpi_allreduce
fidampi_sum_d2 calls mpi_allreduce
fidampi_sum_i1 calls mpi_allreduce
fidampi_sum_d3 calls mpi_allreduce
fidampi_sum_d0 calls mpi_allreduce
fidampi_sum_d1 calls mpi_allreduce
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_6, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_4
write_beam_grid calls xyz_to_uvw, h5ltset_attribute_string_f, h5ltmake_compressed_dataset_double_f, h5ltmake_dataset_int_f, h5gcreate_f, h5gclose_f
h5ltmake_compressed_dataset_double_f_6 calls h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5dclose_f, h5dcreate_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f_2 calls h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5dclose_f, h5dcreate_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f_5 calls h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5dclose_f, h5dcreate_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f_3 calls h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5dclose_f, h5dcreate_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f_1 calls h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5dclose_f, h5dcreate_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f_7 calls h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5dclose_f, h5dcreate_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f_4 calls h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5sclose_f, h5pset_chunk_f, h5screate_simple_f, h5dclose_f, h5dcreate_f, h5ltmake_dataset_double_f
in_plasma calls xyz_to_uvw, interpol_coeff
get_plasma calls get_position, in_plasma
bb_cx_rates calls interpol_coeff
bt_cx_rates calls interpol_coeff
colrad calls get_rate_matrix, linsolve, eigen
get_rate_matrix calls interpol_coeff
linsolve calls dgetrs, dgetrf, matinv
eigen calls balback, balance, hqr2, elmhes, elmtrans
matinv calls ludcmp, lubksb
ludcmp calls swap, outerprod
balback calls rswap
balance calls rswap
hqr2 calls hqrvec
elmhes calls rswap
hqrvec calls comdiv
fidasim calls npa_weights