num_ranks – FIDASIM
num_ranks Function
3 statements
Source File
public recursive function num_ranks() result(n)
Arguments
None
Return Value integer
Called by
Contents
None
Call graph
write_birth_profile calls num_ranks
generate_tables calls num_ranks
parallel_merge_reservoirs calls num_ranks
write_npa calls num_ranks
fidasim calls num_ranks, write_birth_profile, write_npa, fida_mc, fida_f, pfida_mc, pfida_f, dcx, halo, ndmc
parallel_merge_populations calls parallel_merge_reservoirs
fida_mc calls parallel_merge_reservoirs
fida_f calls parallel_merge_reservoirs
pfida_mc calls parallel_merge_reservoirs
pfida_f calls parallel_merge_reservoirs
dcx calls parallel_merge_reservoirs, parallel_merge_populations
halo calls parallel_merge_reservoirs, parallel_merge_populations
ndmc calls parallel_merge_populations