p_cx_2 – FIDASIM
p_cx_2 Function
23 statements
Source File
public function p_cx_2(Erel, m_max) result(sigma)
Calculates an array of cross sections for proton-Hydrogen charge exchange interactions from the state to m = 1..m_max states at energy Erel
Note
Cross sections are normalized to the total cross sections calculated by p_cx_janev.
Note
Cross sections for the states are calculated via equivalence principle using p_cx_1_2_adas.
Note
Cross Sections for are calculated by "spreading" their expected total cross sections among the states.
Equation
References
Ref. 2 atomic_tables
Ref. 4 atomic_tables
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: Erel
Relative collision energy [keV/amu]
integer, intent(in) :: m_max
Number of m states to calculate
Return Value real(kind=Float64), dimension(m_max)
Array of cross sections where the index refers to the m'th state []
Calls
Called by
Contents
Source Code
p_cx_2
Source Code
function p_cx_2(Erel,m_max) result(sigma)
    !+Calculates an array of cross sections for proton-Hydrogen charge exchange interactions
    !+from the \(n=2\) state to m = 1..`m_max` states at energy `Erel`
    !+
    !+@note
    !+Cross sections are normalized to the total cross sections calculated by
    !+[[p_cx_janev(proc)]].
    !+
    !+@note
    !+Cross sections for the \(n=2 \rightarrow m=1\) states are calculated via
    !+equivalence principle using [[p_cx_1_2_adas(proc)]].
    !+
    !+@note
    !+Cross Sections for \(m \geq 4\) are calculated by "spreading" their
    !+expected total cross sections among the \(m \geq 4\) states.
    !+
    !+###Equation
    !+ $$H^+ + H(2) \rightarrow H(m=1..m_{max}) + H^+$$
    !+###References
    !+* Ref. 2 [[atomic_tables(module)]]
    !+* Ref. 4 [[atomic_tables(module)]]
    real(Float64), intent(in)       :: Erel
        !+ Relative collision energy [keV/amu]
    integer, intent(in)             :: m_max
        !+ Number of `m` states to calculate
    real(Float64), dimension(m_max) :: sigma
        !+ Array of cross sections where the index refers to the `m`'th state [\(cm^2\)]
    real(Float64), parameter :: n2 = 4.d0
    integer :: i
    real(Float64) :: En, Em, sigma_n, norm_fac
    sigma = 0.d0
    do i=1,min(m_max,3)
        select case (i)
            case (1)
                sigma(1) = p_cx_1_2_adas(Erel*n2)/n2
            case (2)
                sigma(2) = p_cx_2_2_adas(Erel)
            case (3)
                sigma(3) = p_cx_2_3_adas(Erel)
        end select
    enddo
    sigma_n = max(p_cx_janev(Erel, 2) - sum(sigma), 0.d0)
    call m_spread(2,m_max,sigma_n,sigma)
    norm_fac = p_cx_janev(Erel, 2)/sum(sigma)
    sigma = sigma*norm_fac
end function p_cx_2
Call graph
p_cx_2 calls p_cx_janev, m_spread, p_cx_1_2_adas, p_cx_2_3_adas, p_cx_2_2_adas
p_cx_janev calls p_cx_n_janev, p_cx_1_janev, p_cx_3_janev, p_cx_2_janev
p_cx_n calls p_cx_2
p_cx calls p_cx_n
p_cx_n_m calls p_cx_n
write_bb_h_h calls p_cx
generate_tables calls write_bb_h_h