p_cx_1_2_janev – FIDASIM
p_cx_1_2_janev Function
18 statements
Source File
public function p_cx_1_2_janev(Erel) result(sigma)
Calculates cross section for a proton-Hydrogen charge exchange interaction from the state to the state at energy Erel
Equation
References
Ref. 8 atomic_tables
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: Erel
Relative collision energy [keV/amu]
Return Value real(kind=Float64)
Cross Section []
Calls
Called by
Contents
None
Call graph
p_cx_1_2_janev calls aljan1
p_cx_1 calls p_cx_1_2_janev
p_cx_n calls p_cx_1, p_cx_3
p_cx_3 calls p_cx_1
p_cx calls p_cx_n
p_cx_n_m calls p_cx_n
write_bb_h_h calls p_cx
generate_tables calls write_bb_h_h