p_excit_3_6_janev – FIDASIM
p_excit_3_6_janev Function
6 statements
Source File
public function p_excit_3_6_janev(eb) result(sigma)
Calculates cross section for a proton-Hydrogen impact excitation transition from the state to the state at energy eb
Equation
References
Eq. 35 and Table 7 in Ref. 2 atomic_tables
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: eb
Relative collision energy [keV/amu]
Return Value real(kind=Float64)
Cross Section []
Called by
Contents
Source Code
p_excit_3_6_janev
Source Code
function p_excit_3_6_janev(eb) result(sigma)
    !+Calculates cross section for a proton-Hydrogen impact excitation transition from
    !+the \(n=3\) state to the \(m=6\) state at energy `eb`
    !+
    !+###Equation
    !+$$ H^+ + H(3) \rightarrow H^+ + H(6) $$
    !+
    !+###References
    !+* Eq. 35 and Table 7 in Ref. 2 [[atomic_tables(module)]]
    !+
    real(Float64), intent(in) :: eb
        !+ Relative collision energy [keV/amu]
    real(Float64)             :: sigma
        !+ Cross Section [\(cm^2\)]
    real(Float64), dimension(6), parameter :: c = [63.494d0, 0.077953d0, &
                                                   0.53461d0, -1.2881d0, &
                                                   11.507d0,   4.3417d0  ]
        !+ Fitting parameters from Table 7 in Ref. 2
    sigma = 1.d-16 * c(1)*(c(2)*exp(-c(3)*eb)/(eb**c(4)) + &
                     exp(-c(5)/eb)*log(1.+c(6)*eb)/eb)
end function p_excit_3_6_janev
Call graph
p_excit_3_8_janev calls p_excit_3_6_janev
p_excit_3_9_janev calls p_excit_3_6_janev
p_excit_3_7_janev calls p_excit_3_6_janev
p_excit_3_10_janev calls p_excit_3_6_janev
p_excit_3_janev calls p_excit_3_6_janev, p_excit_3_8_janev, p_excit_3_9_janev, p_excit_3_7_janev, p_excit_3_10_janev
p_excit_n calls p_excit_3_janev
p_excit_n_m calls p_excit_n
p_excit calls p_excit_n
write_bb_h_h calls p_excit
generate_tables calls write_bb_h_h