p_ioniz_n – FIDASIM
p_ioniz_n Function
19 statements
Source File
public function p_ioniz_n(eb, n) result(sigma)
Calculates cross section for a proton-Hydrogen impact ionization interaction from the nth state at energy eb
Equation
References
Eq. 40 and Table 8 in Ref. 2 for atomic_tables
Eq. 5 and Table 1 in Ref. 3 for atomic_tables
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: eb
Relative collision energy [keV/amu]
integer, intent(in) :: n
Initial atomic energy level/state
Return Value real(kind=Float64)
Cross Section []
Calls
Called by
Contents
Source Code
p_ioniz_n
Source Code
function p_ioniz_n(eb,n) result(sigma)
    !+Calculates cross section for a proton-Hydrogen impact ionization interaction
    !+from the `n`th state at energy `eb`
    !+
    !+###Equation
    !+ $$H^+ + H(n) \rightarrow H^+ + H^+ + e$$
    !+###References
    !+* Eq. 40 and Table 8 in Ref. 2 for \(n=1\) [[atomic_tables(module)]]
    !+* Eq. 5 and Table 1 in Ref. 3 for \(n \geq 2\) [[atomic_tables(module)]]
    real(Float64), intent(in) :: eb
        !+ Relative collision energy [keV/amu]
    integer, intent(in)       :: n
        !+ Initial atomic energy level/state
    real(Float64)             :: sigma
        !+ Cross Section [\(cm^2\)]
    select case (n)
        case (0)
            stop
        case (1)
            sigma = p_ioniz_1_janev(eb)
        case (2)
            sigma = p_ioniz_2_omullane(eb)
        case (3)
            sigma = p_ioniz_3_omullane(eb)
        case (4)
            sigma = p_ioniz_4_omullane(eb)
        case DEFAULT
            sigma = p_ioniz_5_omullane(eb)*(n/5.d0)**4
    end select
end function p_ioniz_n
Call graph
p_ioniz_n calls p_ioniz_5_omullane, p_ioniz_4_omullane, p_ioniz_3_omullane, p_ioniz_2_omullane, p_ioniz_1_janev
p_ioniz calls p_ioniz_n
write_bb_h_h calls p_ioniz
generate_tables calls write_bb_h_h