parallel_sum_i3 – FIDASIM
parallel_sum_i3 Subroutine
21 statements
Source File
public recursive subroutine parallel_sum_i3(A)
Uses
iso_c_binding
mpi
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), dimension(:,:,:), target :: A
Calls
Called by
Contents
None
Call graph
parallel_sum_i3 calls parallel_sum_i1, mpi_allreduce
parallel_sum_i1 calls parallel_sum_i1, mpi_allreduce
parallel_sum calls parallel_sum_i3
cfpd_f calls parallel_sum
pnpa_mc calls parallel_sum
pfida_mc calls parallel_sum
write_bt_d_d calls parallel_sum
write_bb_h_e calls parallel_sum
write_bb_d_d calls parallel_sum
write_bt_h_e calls parallel_sum
dcx calls parallel_sum, parallel_merge_populations
halo calls parallel_sum, parallel_merge_populations
write_bb_h_aq calls parallel_sum
neutron_mc calls parallel_sum
cold_spec calls parallel_sum
bremsstrahlung calls parallel_sum
pfida_f calls parallel_sum
fida_weights_mc calls parallel_sum
neutron_f calls parallel_sum
write_npa calls parallel_sum
make_diagnostic_grids calls parallel_sum
npa_f calls parallel_sum
write_bb_d_t calls parallel_sum
fida_f calls parallel_sum
fida_mc calls parallel_sum
halo_spec calls parallel_sum
parallel_merge_populations calls parallel_sum, parallel_merge_reservoirs
parallel_merge_reservoirs calls parallel_sum
pnpa_f calls parallel_sum
ndmc calls parallel_sum, parallel_merge_populations
fida_weights_los calls parallel_sum
npa_weights calls parallel_sum
write_bt_h_h calls parallel_sum
write_birth_profile calls parallel_sum
dcx_spec calls parallel_sum
write_bt_h_aq calls parallel_sum
write_bt_d_he3 calls parallel_sum
write_bb_h_h calls parallel_sum
npa_mc calls parallel_sum
nbi_spec calls parallel_sum
write_bt_d_t calls parallel_sum
write_bb_d_he3 calls parallel_sum
fidasim calls cfpd_f, pnpa_mc, pfida_mc, dcx, halo, neutron_mc, cold_spec, bremsstrahlung, pfida_f, fida_weights_mc, neutron_f, write_npa, make_diagnostic_grids, npa_f, fida_f, fida_mc, halo_spec, pnpa_f, ndmc, fida_weights_los, npa_weights, write_birth_profile, dcx_spec, npa_mc, nbi_spec