parallel_merge_populations – FIDASIM
parallel_merge_populations Subroutine
12 statements
Source File
public subroutine parallel_merge_populations(pop)
Update neutral population
Arguments
Type Intent Optional Attributes Name
type(NeutralPopulation), intent(inout) :: pop
Neutral Population
Calls
Called by
Contents
Source Code
parallel_merge_populations
Source Code
subroutine parallel_merge_populations(pop)
    !+Update neutral population
    type(NeutralPopulation), intent(inout)   :: pop
        !+ Neutral Population
    integer :: i, j, k, ic, ind(3)
    call parallel_sum(pop%dens)
    do ic=1,beam_grid%ngrid
        call ind2sub(beam_grid%dims,ic,ind)
        i = ind(1) ; j = ind(2) ; k = ind(3)
        call parallel_merge_reservoirs(pop%res(i,j,k))
    enddo
end subroutine parallel_merge_populations
Call graph
parallel_merge_populations calls ind2sub, parallel_sum, parallel_merge_reservoirs
parallel_sum calls parallel_sum_d4, parallel_sum_i2, parallel_sum_d3, parallel_sum_i0, parallel_sum_d1, parallel_sum_i1, parallel_sum_d5, parallel_sum_d2, parallel_sum_d0, parallel_sum_i3
parallel_merge_reservoirs calls parallel_sum, merge_reservoirs, num_ranks, init_reservoir, my_rank
parallel_sum_d4 calls parallel_sum_d1, mpi_allreduce
parallel_sum_i2 calls parallel_sum_i1, mpi_allreduce
parallel_sum_d3 calls parallel_sum_d1, mpi_allreduce
parallel_sum_i0 calls mpi_allreduce
parallel_sum_d1 calls parallel_sum_d1, mpi_allreduce
parallel_sum_i1 calls parallel_sum_i1, mpi_allreduce
merge_reservoirs calls init_reservoir, randu, update_reservoir, float
parallel_sum_d5 calls parallel_sum_d1, mpi_allreduce
parallel_sum_d2 calls parallel_sum_d1, mpi_allreduce
init_reservoir calls randu
parallel_sum_d0 calls mpi_allreduce
parallel_sum_i3 calls parallel_sum_i1, mpi_allreduce
update_reservoir calls init_reservoir, randu, randind
dcx calls parallel_merge_populations
halo calls parallel_merge_populations
ndmc calls parallel_merge_populations
fidasim calls dcx, halo, ndmc