parallel_sum_d3 – FIDASIM
parallel_sum_d3 Subroutine
21 statements
Source File
public recursive subroutine parallel_sum_d3(A)
Uses
iso_c_binding
mpi
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(inout), dimension(:,:,:), target :: A
Calls
Called by
Contents
None
Call graph
parallel_sum_d3 calls mpi_allreduce, parallel_sum_d1
parallel_sum_d1 calls mpi_allreduce, parallel_sum_d1
parallel_sum calls parallel_sum_d3
write_bt_h_e calls parallel_sum
fida_weights_los calls parallel_sum
bremsstrahlung calls parallel_sum
write_birth_profile calls parallel_sum
write_bb_d_d calls parallel_sum
halo calls parallel_sum, parallel_merge_populations
pfida_f calls parallel_sum
write_bt_d_t calls parallel_sum
cold_spec calls parallel_sum
fida_weights_mc calls parallel_sum
pfida_mc calls parallel_sum
write_bb_d_t calls parallel_sum
write_bt_d_he3 calls parallel_sum
parallel_merge_populations calls parallel_sum, parallel_merge_reservoirs
halo_spec calls parallel_sum
write_bt_h_h calls parallel_sum
nbi_spec calls parallel_sum
ndmc calls parallel_sum, parallel_merge_populations
pnpa_mc calls parallel_sum
write_bb_h_h calls parallel_sum
write_bt_d_d calls parallel_sum
npa_f calls parallel_sum
dcx_spec calls parallel_sum
neutron_mc calls parallel_sum
npa_weights calls parallel_sum
pnpa_f calls parallel_sum
npa_mc calls parallel_sum
write_bt_h_aq calls parallel_sum
fida_mc calls parallel_sum
write_npa calls parallel_sum
write_bb_h_e calls parallel_sum
parallel_merge_reservoirs calls parallel_sum
dcx calls parallel_sum, parallel_merge_populations
make_diagnostic_grids calls parallel_sum
fida_f calls parallel_sum
cfpd_f calls parallel_sum
neutron_f calls parallel_sum
write_bb_d_he3 calls parallel_sum
write_bb_h_aq calls parallel_sum
fidasim calls fida_weights_los, bremsstrahlung, write_birth_profile, halo, pfida_f, cold_spec, fida_weights_mc, pfida_mc, halo_spec, nbi_spec, ndmc, pnpa_mc, npa_f, dcx_spec, neutron_mc, npa_weights, pnpa_f, npa_mc, fida_mc, write_npa, dcx, make_diagnostic_grids, fida_f, cfpd_f, neutron_f