parallel_sum_d5 – FIDASIM
parallel_sum_d5 Subroutine
21 statements
Source File
public recursive subroutine parallel_sum_d5(A)
Uses
mpi
iso_c_binding
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(inout), dimension(:,:,:,:,:), target :: A
Calls
Called by
Contents
None
Call graph
parallel_sum_d5 calls mpi_allreduce, parallel_sum_d1
parallel_sum_d1 calls mpi_allreduce, parallel_sum_d1
parallel_sum calls parallel_sum_d5
cfpd_f calls parallel_sum
halo_spec calls parallel_sum
write_bb_d_he3 calls parallel_sum
npa_weights calls parallel_sum
parallel_merge_populations calls parallel_sum, parallel_merge_reservoirs
fida_mc calls parallel_sum, parallel_merge_reservoirs
write_bt_h_h calls parallel_sum
pfida_mc calls parallel_sum, parallel_merge_reservoirs
write_npa calls parallel_sum
pfida_f calls parallel_sum, parallel_merge_reservoirs
fida_weights_los calls parallel_sum
write_bt_d_he3 calls parallel_sum
halo calls parallel_sum, parallel_merge_populations, parallel_merge_reservoirs
write_bt_d_d calls parallel_sum
bremsstrahlung calls parallel_sum
npa_mc calls parallel_sum
neutron_f calls parallel_sum
npa_f calls parallel_sum
write_birth_profile calls parallel_sum
write_bt_d_t calls parallel_sum
fida_f calls parallel_sum, parallel_merge_reservoirs
write_bb_d_t calls parallel_sum
write_bt_h_e calls parallel_sum
write_bb_h_e calls parallel_sum
nbi_spec calls parallel_sum
dcx calls parallel_sum, parallel_merge_populations, parallel_merge_reservoirs
dcx_spec calls parallel_sum
write_bb_h_aq calls parallel_sum
pnpa_mc calls parallel_sum
pnpa_f calls parallel_sum
ndmc calls parallel_sum, parallel_merge_populations
write_bb_d_d calls parallel_sum
cold_spec calls parallel_sum
write_bt_h_aq calls parallel_sum
parallel_merge_reservoirs calls parallel_sum
make_diagnostic_grids calls parallel_sum
neutron_mc calls parallel_sum
fida_weights_mc calls parallel_sum
write_bb_h_h calls parallel_sum
fidasim calls cfpd_f, halo_spec, npa_weights, fida_mc, pfida_mc, write_npa, pfida_f, fida_weights_los, halo, bremsstrahlung, npa_mc, neutron_f, npa_f, write_birth_profile, fida_f, nbi_spec, dcx, dcx_spec, pnpa_mc, pnpa_f, ndmc, cold_spec, make_diagnostic_grids, neutron_mc, fida_weights_mc
generate_tables calls write_bb_d_he3, write_bt_h_h, write_bt_d_he3, write_bt_d_d, write_bt_h_e, write_bb_h_e, write_bb_h_aq, write_bb_d_d, write_bt_h_aq, write_bb_h_h