parallel_sum_d0 – FIDASIM
parallel_sum_d0 Subroutine
10 statements
Source File
public recursive subroutine parallel_sum_d0(A)
Uses
mpi
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(inout) :: A
Calls
Called by
Contents
None
Call graph
parallel_sum_d0 calls mpi_allreduce
parallel_sum calls parallel_sum_d0
nbi_spec calls parallel_sum
halo calls parallel_sum, parallel_merge_populations
dcx calls parallel_sum, parallel_merge_populations
write_birth_profile calls parallel_sum
pnpa_f calls parallel_sum
fida_weights_mc calls parallel_sum
fida_weights_los calls parallel_sum
pfida_mc calls parallel_sum
make_diagnostic_grids calls parallel_sum
pfida_f calls parallel_sum
cold_spec calls parallel_sum
halo_spec calls parallel_sum
write_bb_h_h calls parallel_sum
parallel_merge_reservoirs calls parallel_sum
write_bb_h_e calls parallel_sum
neutron_f calls parallel_sum
write_bt_h_e calls parallel_sum
dcx_spec calls parallel_sum
pnpa_mc calls parallel_sum
write_bt_d_t calls parallel_sum
write_bb_h_aq calls parallel_sum
neutron_mc calls parallel_sum
fida_f calls parallel_sum
write_bt_h_h calls parallel_sum
fida_mc calls parallel_sum
write_npa calls parallel_sum
parallel_merge_populations calls parallel_sum, parallel_merge_reservoirs
npa_f calls parallel_sum
bremsstrahlung calls parallel_sum
npa_weights calls parallel_sum
write_bb_d_t calls parallel_sum
ndmc calls parallel_sum, parallel_merge_populations
npa_mc calls parallel_sum
write_bb_d_d calls parallel_sum
write_bt_d_d calls parallel_sum
write_bt_h_aq calls parallel_sum
generate_tables calls write_bb_h_h, write_bb_h_e, write_bt_h_e, write_bb_h_aq, write_bt_h_h, write_bb_d_d, write_bt_d_d, write_bt_h_aq
fidasim calls nbi_spec, halo, dcx, write_birth_profile, pnpa_f, fida_weights_mc, fida_weights_los, pfida_mc, make_diagnostic_grids, pfida_f, cold_spec, halo_spec, neutron_f, dcx_spec, pnpa_mc, neutron_mc, fida_f, fida_mc, write_npa, npa_f, bremsstrahlung, npa_weights, ndmc, npa_mc