read_npa – FIDASIM
read_npa Subroutine
163 statements
Source File
public subroutine read_npa()
Reads the NPA geometry and stores the quantities in npa_chords
Arguments
None
Calls
Called By
Source Code
read_npa
Source Code
subroutine read_npa
    !+ Reads the NPA geometry and stores the quantities in [[libfida:npa_chords]]
    integer(HID_T) :: fid, gid
    integer(HSIZE_T), dimension(2) :: dims
    logical :: path_valid
    real(Float64), dimension(:,:), allocatable :: a_tedge,a_redge,a_cent
    real(Float64), dimension(:,:), allocatable :: d_tedge,d_redge,d_cent
    real(Float64), dimension(beam_grid%ngrid) :: probs
    real(Float64), dimension(3,beam_grid%ngrid) :: eff_rds
    integer, dimension(:), allocatable :: a_shape, d_shape
    character(len=20) :: system = ''
    real(Float64), parameter :: inv_4pi = (4.d0*pi)**(-1)
    real(Float64), dimension(3) :: xyz_a_tedge,xyz_a_redge,xyz_a_cent
    real(Float64), dimension(3) :: xyz_d_tedge,xyz_d_redge,xyz_d_cent
    real(Float64), dimension(3) :: eff_rd, rd, rd_d, r0, r0_d, v0
    real(Float64), dimension(3,3) :: basis, inv_basis
    real(Float64), dimension(50) :: xd, yd
    type(LocalEMFields) :: fields
    real(Float64) :: length,total_prob, hh, hw, dprob, dx, dy, r, pitch
    integer :: ichan,ic,i,j,k,id,ix,iy,d_index,nd,ind_d(2),ind(3)
    integer :: error
    !!Initialize HDF5 interface
    call h5open_f(error)
    !!Open HDF5 file
    call h5fopen_f(inputs%geometry_file, H5F_ACC_RDWR_F, fid, error)
    !!Check if NPA group exists
    call h5ltpath_valid_f(fid, "/npa", .True., path_valid, error)
    if(.not.path_valid) then
        if(inputs%verbose.ge.0) then
            write(*,'(a)') 'NPA geometry is not in the geometry file'
            write(*,'(a)') 'Continuing without NPA diagnostics'
        endif
        inputs%calc_npa = 0
        inputs%calc_npa_wght = 0
        call h5fclose_f(fid, error)
        call h5close_f(error)
        return
    endif
    !!Open NPA group
    call h5gopen_f(fid, "/npa", gid, error)
    call h5ltread_dataset_string_f(gid, "/npa/system", system, error)
    call h5ltread_dataset_int_scalar_f(gid, "/npa/nchan", npa_chords%nchan, error)
    if(inputs%verbose.ge.1) then
        write(*,'(a)') "---- NPA settings ----"
        write(*,'(T2,"NPA System: ", a)') trim(adjustl(system))
        write(*,'(T2,"Number of channels: ",i3)') npa_chords%nchan
    endif
    allocate(a_tedge(3, npa_chords%nchan))
    allocate(a_redge(3, npa_chords%nchan))
    allocate(a_cent(3,  npa_chords%nchan))
    allocate(a_shape(npa_chords%nchan))
    allocate(d_tedge(3, npa_chords%nchan))
    allocate(d_redge(3, npa_chords%nchan))
    allocate(d_cent(3,  npa_chords%nchan))
    allocate(d_shape(npa_chords%nchan))
    allocate(npa_chords%radius(npa_chords%nchan))
    allocate(npa_chords%det(npa_chords%nchan))
    allocate(npa_chords%phit(beam_grid%nx, &
                             beam_grid%ny, &
                             beam_grid%nz, &
                             npa_chords%nchan) )
    allocate(npa_chords%hit(beam_grid%nx, &
                            beam_grid%ny, &
                            beam_grid%nz) )
    npa_chords%hit = .False.
    dims = [3,spec_chords%nchan]
    call h5ltread_dataset_double_f(gid,"/npa/radius", npa_chords%radius, dims(2:2), error)
    call h5ltread_dataset_int_f(gid, "/npa/a_shape", a_shape, dims(2:2), error)
    call h5ltread_dataset_double_f(gid, "/npa/a_tedge", a_tedge, dims, error)
    call h5ltread_dataset_double_f(gid, "/npa/a_redge", a_redge, dims, error)
    call h5ltread_dataset_double_f(gid, "/npa/a_cent",  a_cent, dims, error)
    call h5ltread_dataset_int_f(gid, "/npa/d_shape", d_shape, dims(2:2), error)
    call h5ltread_dataset_double_f(gid, "/npa/d_tedge", d_tedge, dims, error)
    call h5ltread_dataset_double_f(gid, "/npa/d_redge", d_redge, dims, error)
    call h5ltread_dataset_double_f(gid, "/npa/d_cent",  d_cent, dims, error)
    !!Close NPA group
    call h5gclose_f(gid, error)
    !!Close file id
    call h5fclose_f(fid, error)
    !!Close HDF5 interface
    call h5close_f(error)
    ! Define detector/aperture shape
    npa_chords%det%detector%shape = d_shape
    npa_chords%det%aperture%shape = a_shape
    chan_loop: do ichan=1,npa_chords%nchan
        ! Convert to beam grid coordinates
        call uvw_to_xyz(a_cent(:,ichan), xyz_a_cent)
        call uvw_to_xyz(a_redge(:,ichan),xyz_a_redge)
        call uvw_to_xyz(a_tedge(:,ichan),xyz_a_tedge)
        call uvw_to_xyz(d_cent(:,ichan), xyz_d_cent)
        call uvw_to_xyz(d_redge(:,ichan),xyz_d_redge)
        call uvw_to_xyz(d_tedge(:,ichan),xyz_d_tedge)
        ! Define detector/aperture hh/hw
        npa_chords%det(ichan)%detector%hw = norm2(xyz_d_redge - xyz_d_cent)
        npa_chords%det(ichan)%aperture%hw = norm2(xyz_a_redge - xyz_a_cent)
        npa_chords%det(ichan)%detector%hh = norm2(xyz_d_tedge - xyz_d_cent)
        npa_chords%det(ichan)%aperture%hh = norm2(xyz_a_tedge - xyz_a_cent)
        ! Define detector/aperture origin
        npa_chords%det(ichan)%detector%origin = xyz_d_cent
        npa_chords%det(ichan)%aperture%origin = xyz_a_cent
        ! Define detector/aperture basis
        call plane_basis(xyz_d_cent, xyz_d_redge, xyz_d_tedge, &
             npa_chords%det(ichan)%detector%basis, &
             npa_chords%det(ichan)%detector%inv_basis)
        call plane_basis(xyz_a_cent, xyz_a_redge, xyz_a_tedge, &
             npa_chords%det(ichan)%aperture%basis, &
             npa_chords%det(ichan)%aperture%inv_basis)
        v0 = xyz_a_cent - xyz_d_cent
        v0 = v0/norm2(v0)
        call grid_intersect(xyz_d_cent,v0,length,r0,r0_d)
        if(length.le.0.0) then
            if(inputs%verbose.ge.0) then
                WRITE(*,'("Channel ",i3," centerline missed the beam grid")') ichan
            endif
        endif
        if(inputs%calc_npa_wght.ge.1) then
            hw = npa_chords%det(ichan)%detector%hw
            hh = npa_chords%det(ichan)%detector%hh
            nd = size(xd)
            do i=1,nd
                xd(i) = -hw + 2*hw*(i-0.5)/real(nd)
                yd(i) = -hh + 2*hh*(i-0.5)/real(nd)
            enddo
            dx = abs(xd(2) - xd(1))
            dy = abs(yd(2) - yd(1))
            basis = npa_chords%det(ichan)%detector%basis
            inv_basis = npa_chords%det(ichan)%detector%inv_basis
            eff_rds = 0.d0
            probs = 0.d0
            ! For each grid point find the probability of hitting the detector given an isotropic source
            !$OMP PARALLEL DO schedule(guided) private(ic,i,j,k,ix,iy,total_prob,eff_rd,r0,r0_d, &
            !$OMP& rd_d,rd,d_index,v0,dprob,r,fields,id,ind_d,ind)
            do ic=istart,beam_grid%ngrid,istep
                call ind2sub(beam_grid%dims,ic,ind)
                i = ind(1) ; j = ind(2) ; k = ind(3)
                r0 = [beam_grid%xc(i),beam_grid%yc(j),beam_grid%zc(k)]
                r0_d = matmul(inv_basis,r0-xyz_d_cent)
                do id = 1, nd*nd
                    call ind2sub([nd,nd],id,ind_d)
                    ix = ind_d(1) ; iy = ind_d(2)
                    rd_d = [xd(ix),yd(iy),0.d0]
                    rd = matmul(basis,rd_d) + xyz_d_cent
                    v0 = rd - r0
                    d_index = 0
                    call hit_npa_detector(r0,v0,d_index,det=ichan)
                    if(d_index.ne.0) then
                        r = norm2(rd_d - r0_d)**2
                        dprob = (dx*dy) * inv_4pi * r0_d(3)/(r*sqrt(r))
                        eff_rds(:,ic) = eff_rds(:,ic) + dprob*rd
                        probs(ic) = probs(ic) + dprob
                    endif
                enddo
            enddo
            !$OMP END PARALLEL DO
#ifdef _MPI
            call parallel_sum(eff_rds)
            call parallel_sum(probs)
#endif
            do ic = 1, beam_grid%ngrid
                if(probs(ic).gt.0.0) then
                    call ind2sub(beam_grid%dims, ic, ind)
                    i = ind(1) ; j = ind(2) ; k = ind(3)
                    r0 = [beam_grid%xc(i),beam_grid%yc(j),beam_grid%zc(k)]
                    eff_rd = eff_rds(:,ic)/probs(ic)
                    call get_fields(fields,pos=r0)
                    v0 = (eff_rd - r0)/norm2(eff_rd - r0)
                    npa_chords%phit(i,j,k,ichan)%pitch = dot_product(fields%b_norm,v0)
                    npa_chords%phit(i,j,k,ichan)%p = probs(ic)
                    npa_chords%phit(i,j,k,ichan)%dir = v0
                    npa_chords%phit(i,j,k,ichan)%eff_rd = eff_rd
                    npa_chords%hit(i,j,k) = .True.
                endif
            enddo
            total_prob = sum(probs)
            if(total_prob.le.0.d0) then
                if(inputs%verbose.ge.0) then
                    WRITE(*,'("Channel ",i3," missed the beam grid")') ichan
                endif
                cycle chan_loop
            endif
        endif
    enddo chan_loop
    if(inputs%verbose.ge.1) write(*,'(50X,a)') ""
    deallocate(a_shape,a_cent,a_redge,a_tedge)
    deallocate(d_shape,d_cent,d_redge,d_tedge)
end subroutine read_npa
All Procedures
approx_eq approx_ge approx_le Aq_cx Aq_cx_n Aq_cx_n_adas Aq_cx_n_janev Aq_excit Aq_excit_1_2_janev Aq_excit_1_3_janev Aq_excit_1_4_janev Aq_excit_1_5_janev Aq_excit_1_janev Aq_excit_2_10_janev Aq_excit_2_3_janev Aq_excit_2_4_janev Aq_excit_2_5_janev Aq_excit_2_6_janev Aq_excit_2_7_janev Aq_excit_2_8_janev Aq_excit_2_9_janev Aq_excit_2_janev Aq_excit_3_10_janev Aq_excit_3_4_janev Aq_excit_3_5_janev Aq_excit_3_6_janev Aq_excit_3_7_janev Aq_excit_3_8_janev Aq_excit_3_9_janev Aq_excit_3_janev Aq_excit_n Aq_excit_n_janev Aq_excit_n_m Aq_ioniz Aq_ioniz_n Aq_ioniz_n_janev assignment(=) attenuate B5_cx_1_adas B5_cx_1_janev B5_cx_2_adas B5_ioniz_1_janev balance balback bb_cx_rates boundary_edge bremsstrahlung bt_cx_rates bt_maxwellian bt_maxwellian_eb bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m C6_cx_1_adas C6_cx_1_janev C6_cx_2_adas C6_cx_3_adas C6_ioniz_1_janev calc_perp_vectors check_compression_availability circle_grid_intersect cleanup_mpi cold_spec colrad comabs Comdiv cross_product cumsum d_d_fusion_he d_d_fusion_t d_t_fusion dcx dcx_spec deriv e_excit e_excit_1_2_janev e_excit_1_3_janev e_excit_1_4_janev e_excit_1_5_janev e_excit_1_janev e_excit_2_3_janev e_excit_f e_excit_n e_excit_n_m e_ioniz e_ioniz_1_janev e_ioniz_2_janev e_ioniz_3_janev e_ioniz_n eigen elmhes elmtrans fast_ion_assign ff_add ff_assign ff_subtract fida_f fida_mc fida_weights_los fida_weights_mc flf_assign fs_divide fs_multiply get_beam_cx_rate get_distribution get_ep_denf get_fields get_indices get_neutron_rate get_nlaunch get_plasma get_position get_rate_matrix get_rng get_value grid_intersect gyro_correction gyro_radius gyro_range gyro_step gyro_surface gyro_surface_coordinates gyro_trajectory h5ltmake_compressed_dataset_double_f h5ltmake_compressed_dataset_double_f_1 h5ltmake_compressed_dataset_double_f_2 h5ltmake_compressed_dataset_double_f_3 h5ltmake_compressed_dataset_double_f_4 h5ltmake_compressed_dataset_double_f_5 h5ltmake_compressed_dataset_double_f_6 h5ltmake_compressed_dataset_double_f_7 h5ltmake_compressed_dataset_int_f h5ltmake_compressed_dataset_int_f_1 h5ltmake_compressed_dataset_int_f_2 h5ltmake_compressed_dataset_int_f_3 h5ltmake_compressed_dataset_int_f_4 h5ltmake_compressed_dataset_int_f_5 h5ltmake_compressed_dataset_int_f_6 h5ltmake_compressed_dataset_int_f_7 h5ltread_dataset_double_scalar_f h5ltread_dataset_int_scalar_f halo halo_spec hit_npa_detector hqr2 hqrvec in_boundary in_grid in_gyro_surface in_plasma ind2sub init_mpi interpol interpol1D_arr interpol1D_coeff interpol1D_coeff_arr interpol2D_2D_arr interpol2D_arr interpol2D_coeff interpol2D_coeff_arr interpol_coeff lff_assign lflf_add lflf_assign lflf_subtract lfs_divide lfs_multiply line_basis line_gyro_surface_intersect line_plane_intersect linsolve lplp_add lplp_assign lplp_subtract lpp_assign lps_divide lps_multiply lubksb ludcmp m_spread make_beam_grid matinv mc_fastion mc_halo mc_nbi mc_nbi_cell my_rank nbi_spec ndmc neutron_f neutron_mc norm2 npa_f npa_gyro_range npa_mc npa_part_assign npa_weights num_ranks operator(*) operator(+) operator(-) operator(/) outerprod p_cx p_cx_1 p_cx_1_1_adas p_cx_1_2_adas p_cx_1_3_adas p_cx_1_4_adas p_cx_1_janev p_cx_2 p_cx_2_2_adas p_cx_2_3_adas p_cx_2_janev p_cx_3 p_cx_3_2_adas p_cx_3_3_adas p_cx_3_4_adas p_cx_3_5_adas p_cx_3_6inf_adas p_cx_3_janev p_cx_janev p_cx_n p_cx_n_janev p_cx_n_m p_excit p_excit_1_2_janev p_excit_1_3_janev p_excit_1_4_janev p_excit_1_5_janev p_excit_1_6_janev p_excit_1_janev p_excit_2_10_janev p_excit_2_3_janev p_excit_2_4_janev p_excit_2_5_janev p_excit_2_6_janev p_excit_2_7_janev p_excit_2_8_janev p_excit_2_9_janev p_excit_2_janev p_excit_3_10_janev p_excit_3_4_janev p_excit_3_5_janev p_excit_3_6_janev p_excit_3_7_janev p_excit_3_8_janev p_excit_3_9_janev p_excit_3_janev p_excit_n p_excit_n_m p_ioniz p_ioniz_1_janev p_ioniz_2_omullane p_ioniz_3_omullane p_ioniz_4_omullane p_ioniz_5_omullane p_ioniz_n parallel_sum parallel_sum_d0 parallel_sum_d1 parallel_sum_d2 parallel_sum_d3 parallel_sum_d4 parallel_sum_d5 parallel_sum_i0 parallel_sum_i1 parallel_sum_i2 pfida_f pfida_mc pitch_to_vec plane_basis plp_assign pnpa_f pnpa_mc pp_add pp_assign pp_subtract print_banner print_default_namelist ps_divide ps_multiply randind randind_cdf randn randu read_atomic_cross read_atomic_rate read_atomic_transitions read_beam read_chords read_distribution read_equilibrium read_f read_inputs read_mc read_neutrals read_npa read_nuclear_rates read_tables rng_init rng_normal rng_seed rng_uniform RSWAP sf_multiply simpsons_rule slf_multiply slp_multiply sp_multiply sparse spectrum store_bes_photons store_births store_fida_photons store_fw_photons store_fw_photons_at_chan store_neutrals store_neutrons store_npa store_photons sub2ind swap tb_zyx time track uvw_to_xyz write_bb_D_D write_bb_D_T write_bb_H_Aq write_bb_H_e write_bb_H_H write_beam_grid write_birth_profile write_bt_D_D write_bt_D_T write_bt_H_Aq write_bt_H_e write_bt_H_H write_einstein write_fida_weights write_neutrals write_neutrons write_npa write_npa_weights write_spectra xyz_to_uvw
Call graph
read_npa calls h5ltread_dataset_string_f, grid_intersect, parallel_sum, uvw_to_xyz, h5ltread_dataset_int_f, h5gopen_f, get_fields, ind2sub, h5ltread_dataset_int_scalar_f, plane_basis, h5close_f, h5open_f, h5fopen_f, h5ltpath_valid_f, hit_npa_detector, h5ltread_dataset_double_f, h5fclose_f, h5gclose_f
parallel_sum calls parallel_sum_d3, parallel_sum_d4, parallel_sum_d0, parallel_sum_d2, parallel_sum_d1, parallel_sum_i0, parallel_sum_i2, parallel_sum_d5, parallel_sum_i1
get_fields calls get_position, in_plasma, calc_perp_vectors
h5ltread_dataset_int_scalar_f calls h5ltread_dataset_int_f
plane_basis calls cross_product
hit_npa_detector calls line_plane_intersect, in_boundary
parallel_sum_d3 calls mpi_allreduce
parallel_sum_d4 calls mpi_allreduce
parallel_sum_d0 calls mpi_allreduce
parallel_sum_d2 calls mpi_allreduce
parallel_sum_d1 calls mpi_allreduce
parallel_sum_i0 calls mpi_allreduce
parallel_sum_i2 calls mpi_allreduce
parallel_sum_d5 calls mpi_allreduce
parallel_sum_i1 calls mpi_allreduce
in_plasma calls xyz_to_uvw, interpol_coeff
interpol_coeff calls interpol1d_coeff_arr, interpol2d_coeff_arr, interpol1d_coeff, interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
interpol2d_coeff_arr calls interpol2d_coeff
fidasim calls read_npa