read_plasma – FIDASIM
read_plasma Subroutine
55 statements
Source File
public subroutine read_plasma()
Reads in Plasma composition e.g. the thermal, fast-ion, and impurity species
Arguments
None
Calls
Called by
Contents
None
Call graph
read_plasma calls h5gopen_f, h5ltread_dataset_int_scalar_f, h5gclose_f, h5ltread_dataset_double_f, h5open_f, h5close_f, h5fopen_f, h5fclose_f
h5ltread_dataset_int_scalar_f calls h5ltread_dataset_int_f
fidasim calls read_plasma