read_chords – FIDASIM
read_chords Subroutine
142 statements
Source File
public subroutine read_chords()
Reads the spectral geometry and stores the quantities in spec_chords
Arguments
None
Calls
Called By
Source Code
read_chords
Source Code
subroutine read_chords
    !+ Reads the spectral geometry and stores the quantities in [[libfida:spec_chords]]
    integer(HID_T) :: fid, gid
    integer(HSIZE_T), dimension(2) :: dims
    logical :: path_valid
    real(Float64), dimension(:,:), allocatable :: lenses
    real(Float64), dimension(:,:), allocatable :: axes
    real(Float64), dimension(:,:,:), allocatable :: dlength
    real(Float64), dimension(:), allocatable :: spot_size, sigma_pi
    type(LOSElement), dimension(:), allocatable :: los_elem
    real(Float64) :: r0(3), v0(3), r_enter(3), r_exit(3)
    real(Float64) :: xyz_lens(3), xyz_axis(3), length
    real(Float64), dimension(3,3) :: basis
    real(Float64), dimension(2) :: randomu
    real(Float64) :: theta, sqrt_rho, dl
    type(ParticleTrack), dimension(beam_grid%ntrack) :: tracks
    character(len=20) :: system = ''
    integer :: i, j, ic, nc, ntrack, ind(3), ii, jj, kk
    integer :: error
    if(inputs%verbose.ge.1) then
        write(*,'(a)') '---- FIDA/BES settings ----'
    endif
    !!Initialize HDF5 interface
    call h5open_f(error)
    !!Open HDF5 file
    call h5fopen_f(inputs%geometry_file, H5F_ACC_RDONLY_F, fid, error)
    !!Check if SPEC group exists
    call h5ltpath_valid_f(fid, "/spec", .True., path_valid, error)
    if(.not.path_valid) then
        if(inputs%verbose.ge.1) then
            write(*,'(a)') 'FIDA/BES geometry is not in the geometry file'
            write(*,'(a)') 'Continuing without spectral diagnostics'
        endif
        inputs%calc_spec = 0
        inputs%calc_fida = 0
        inputs%calc_pfida = 0
        inputs%calc_nbi = 0
        inputs%calc_dcx = 0
        inputs%calc_halo = 0
        inputs%calc_cold = 0
        inputs%calc_brems = 0
        inputs%calc_fida_wght = 0
        call h5fclose_f(fid, error)
        call h5close_f(error)
        return
    endif
    !!Open SPEC group
    call h5gopen_f(fid, "/spec", gid, error)
    call h5ltread_dataset_string_f(gid, "/spec/system", system, error)
    call h5ltread_dataset_int_scalar_f(gid, "/spec/nchan", spec_chords%nchan, error)
    allocate(lenses(3, spec_chords%nchan))
    allocate(axes(3, spec_chords%nchan))
    allocate(spot_size(spec_chords%nchan))
    allocate(sigma_pi(spec_chords%nchan))
    allocate(spec_chords%los(spec_chords%nchan))
    allocate(spec_chords%radius(spec_chords%nchan))
    allocate(dlength(beam_grid%nx, &
                     beam_grid%ny, &
                     beam_grid%nz) )
    dims = [3,spec_chords%nchan]
    call h5ltread_dataset_double_f(gid, "/spec/lens", lenses, dims, error)
    call h5ltread_dataset_double_f(gid, "/spec/axis", axes, dims, error)
    call h5ltread_dataset_double_f(gid, "/spec/spot_size", spot_size, dims(2:2), error)
    call h5ltread_dataset_double_f(gid, "/spec/sigma_pi", sigma_pi, dims(2:2), error)
    call h5ltread_dataset_double_f(gid, "/spec/radius", spec_chords%radius, dims(2:2), error)
    !!Close SPEC group
    call h5gclose_f(gid, error)
    !!Close file id
    call h5fclose_f(fid, error)
    !!Close HDF5 interface
    call h5close_f(error)
    chan_loop: do i=1,spec_chords%nchan
        call uvw_to_xyz(lenses(:,i),xyz_lens)
        xyz_axis = matmul(beam_grid%inv_basis,axes(:,i))
        spec_chords%los(i)%lens = xyz_lens
        spec_chords%los(i)%axis = xyz_axis
        spec_chords%los(i)%sigma_pi = sigma_pi(i)
        spec_chords%los(i)%spot_size = spot_size(i)
        r0 = xyz_lens
        v0 = xyz_axis
        v0 = v0/norm2(v0)
        call line_basis(r0,v0,basis)
        call grid_intersect(r0,v0,length,r_enter,r_exit)
        if(length.le.0.d0) then
            if(inputs%verbose.ge.0) then
                WRITE(*,'("Channel ",i5," missed the beam grid")') i
            endif
            cycle chan_loop
        endif
        if(spot_size(i).le.0.d0) then
            nc = 1
        else
            nc = 100
        endif
        dlength = 0.d0
        !$OMP PARALLEL DO schedule(guided) private(ic,randomu,sqrt_rho,theta,r0, &
        !$OMP& length, r_enter, r_exit, j, tracks, ntrack, ind)
        do ic=1,nc
            ! Uniformally sample within spot size
            call randu(randomu)
            sqrt_rho = sqrt(randomu(1))
            theta = 2*pi*randomu(2)
            r0(1) = 0.d0
            r0(2) = spot_size(i)*sqrt_rho*cos(theta)
            r0(3) = spot_size(i)*sqrt_rho*sin(theta)
            r0 = matmul(basis,r0) + xyz_lens
            call grid_intersect(r0, v0, length, r_enter, r_exit)
            call track(r_enter, v0, tracks, ntrack)
            track_loop: do j=1, ntrack
                ind = tracks(j)%ind
                !inds can repeat so add rather than assign
                !$OMP ATOMIC UPDATE
                dlength(ind(1),ind(2),ind(3)) = &
                dlength(ind(1),ind(2),ind(3)) + tracks(j)%time/real(nc) !time == distance
                !$OMP END ATOMIC
            enddo track_loop
        enddo
        !$OMP END PARALLEL DO
        do kk=1,beam_grid%nz
            do jj=1,beam_grid%ny
                xloop: do ii=1, beam_grid%nx
                    if(dlength(ii,jj,kk).ne.0.d0) then
                        dl = dlength(ii,jj,kk)
                        nc = spec_chords%inter(ii,jj,kk)%nchan + 1
                        if(nc.eq.1) then
                            allocate(spec_chords%inter(ii,jj,kk)%los_elem(nc))
                            spec_chords%inter(ii,jj,kk)%los_elem(nc) = LOSElement(i, dl)
                        else
                            allocate(los_elem(nc))
                            los_elem(1:(nc-1)) = spec_chords%inter(ii,jj,kk)%los_elem
                            los_elem(nc) = LOSElement(i, dl)
                            deallocate(spec_chords%inter(ii,jj,kk)%los_elem)
                            call move_alloc(los_elem, spec_chords%inter(ii,jj,kk)%los_elem)
                        endif
                        spec_chords%inter(ii,jj,kk)%nchan = nc
                    endif
                enddo xloop
            enddo
        enddo
    enddo chan_loop
    spec_chords%ncell = count(spec_chords%inter%nchan.gt.0)
    allocate(spec_chords%cell(spec_chords%ncell))
    nc = 0
    do ic=1,beam_grid%ngrid
        call ind2sub(beam_grid%dims,ic,ind)
        ii = ind(1) ; jj = ind(2) ; kk = ind(3)
        if(spec_chords%inter(ii,jj,kk)%nchan.gt.0) then
            nc = nc + 1
            spec_chords%cell(nc) = ic
        endif
    enddo
    if(inputs%verbose.ge.1) then
        write(*,'(T2,"FIDA/BES System: ",a)') trim(adjustl(system))
        write(*,'(T2,"Number of channels: ",i5)') spec_chords%nchan
        write(*,*) ''
    endif
    deallocate(lenses,axes,spot_size,sigma_pi)
end subroutine read_chords
All Procedures
approx_eq approx_ge approx_le Aq_cx Aq_cx_n Aq_cx_n_adas Aq_cx_n_janev Aq_excit Aq_excit_1_2_janev Aq_excit_1_3_janev Aq_excit_1_4_janev Aq_excit_1_5_janev Aq_excit_1_janev Aq_excit_2_10_janev Aq_excit_2_3_janev Aq_excit_2_4_janev Aq_excit_2_5_janev Aq_excit_2_6_janev Aq_excit_2_7_janev Aq_excit_2_8_janev Aq_excit_2_9_janev Aq_excit_2_janev Aq_excit_3_10_janev Aq_excit_3_4_janev Aq_excit_3_5_janev Aq_excit_3_6_janev Aq_excit_3_7_janev Aq_excit_3_8_janev Aq_excit_3_9_janev Aq_excit_3_janev Aq_excit_n Aq_excit_n_janev Aq_excit_n_m Aq_ioniz Aq_ioniz_n Aq_ioniz_n_janev assignment(=) attenuate B5_cx_1_adas B5_cx_1_janev B5_cx_2_adas B5_ioniz_1_janev balance balback bb_cx_rates boundary_edge bremsstrahlung bt_cx_rates bt_maxwellian bt_maxwellian_eb bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m C6_cx_1_adas C6_cx_1_janev C6_cx_2_adas C6_cx_3_adas C6_ioniz_1_janev calc_perp_vectors check_compression_availability circle_grid_intersect cold_spec colrad comabs Comdiv cross_product cumsum d_d_fusion_he d_d_fusion_t d_t_fusion dcx dcx_spec deriv e_excit e_excit_1_2_janev e_excit_1_3_janev e_excit_1_4_janev e_excit_1_5_janev e_excit_1_janev e_excit_2_3_janev e_excit_f e_excit_n e_excit_n_m e_ioniz e_ioniz_1_janev e_ioniz_2_janev e_ioniz_3_janev e_ioniz_n eigen elmhes elmtrans fast_ion_assign ff_add ff_assign ff_subtract fida_f fida_mc fida_weights_los fida_weights_mc fidampi_clenup fidampi_init fidampi_my_rank fidampi_num_ranks fidampi_sum fidampi_sum_d0 fidampi_sum_d1 fidampi_sum_d2 fidampi_sum_d3 fidampi_sum_d4 fidampi_sum_d5 fidampi_sum_i0 fidampi_sum_i1 fidampi_sum_i2 flf_assign fs_divide fs_multiply get_beam_cx_rate get_distribution get_ep_denf get_fields get_indices get_neutron_rate get_nlaunch get_plasma get_position get_rate_matrix get_rng get_value grid_intersect gyro_correction gyro_radius gyro_range gyro_step gyro_surface gyro_surface_coordinates gyro_trajectory h5ltmake_compressed_dataset_double_f h5ltmake_compressed_dataset_double_f_1 h5ltmake_compressed_dataset_double_f_2 h5ltmake_compressed_dataset_double_f_3 h5ltmake_compressed_dataset_double_f_4 h5ltmake_compressed_dataset_double_f_5 h5ltmake_compressed_dataset_double_f_6 h5ltmake_compressed_dataset_double_f_7 h5ltmake_compressed_dataset_int_f h5ltmake_compressed_dataset_int_f_1 h5ltmake_compressed_dataset_int_f_2 h5ltmake_compressed_dataset_int_f_3 h5ltmake_compressed_dataset_int_f_4 h5ltmake_compressed_dataset_int_f_5 h5ltmake_compressed_dataset_int_f_6 h5ltmake_compressed_dataset_int_f_7 h5ltread_dataset_double_scalar_f h5ltread_dataset_int_scalar_f halo halo_spec hit_npa_detector hqr2 hqrvec in_boundary in_grid in_gyro_surface in_plasma ind2sub interpol interpol1D_arr interpol1D_coeff interpol1D_coeff_arr interpol2D_2D_arr interpol2D_arr interpol2D_coeff interpol2D_coeff_arr interpol_coeff lff_assign lflf_add lflf_assign lflf_subtract lfs_divide lfs_multiply line_basis line_gyro_surface_intersect line_plane_intersect linsolve lplp_add lplp_assign lplp_subtract lpp_assign lps_divide lps_multiply lubksb ludcmp m_spread make_beam_grid matinv mc_fastion mc_halo mc_nbi mc_nbi_cell nbi_spec ndmc neutron_f neutron_mc norm2 npa_f npa_gyro_range npa_mc npa_part_assign npa_weights operator(*) operator(+) operator(-) operator(/) outerprod p_cx p_cx_1 p_cx_1_1_adas p_cx_1_2_adas p_cx_1_3_adas p_cx_1_4_adas p_cx_1_janev p_cx_2 p_cx_2_2_adas p_cx_2_3_adas p_cx_2_janev p_cx_3 p_cx_3_2_adas p_cx_3_3_adas p_cx_3_4_adas p_cx_3_5_adas p_cx_3_6inf_adas p_cx_3_janev p_cx_janev p_cx_n p_cx_n_janev p_cx_n_m p_excit p_excit_1_2_janev p_excit_1_3_janev p_excit_1_4_janev p_excit_1_5_janev p_excit_1_6_janev p_excit_1_janev p_excit_2_10_janev p_excit_2_3_janev p_excit_2_4_janev p_excit_2_5_janev p_excit_2_6_janev p_excit_2_7_janev p_excit_2_8_janev p_excit_2_9_janev p_excit_2_janev p_excit_3_10_janev p_excit_3_4_janev p_excit_3_5_janev p_excit_3_6_janev p_excit_3_7_janev p_excit_3_8_janev p_excit_3_9_janev p_excit_3_janev p_excit_n p_excit_n_m p_ioniz p_ioniz_1_janev p_ioniz_2_omullane p_ioniz_3_omullane p_ioniz_4_omullane p_ioniz_5_omullane p_ioniz_n pfida_f pfida_mc pitch_to_vec plane_basis plp_assign pnpa_f pnpa_mc pp_add pp_assign pp_subtract print_banner print_default_namelist ps_divide ps_multiply randind randind_cdf randn randu read_atomic_cross read_atomic_rate read_atomic_transitions read_beam read_chords read_distribution read_equilibrium read_f read_inputs read_mc read_neutrals read_npa read_nuclear_rates read_tables rng_init rng_normal rng_seed rng_uniform RSWAP sf_multiply simpsons_rule slf_multiply slp_multiply sp_multiply sparse spectrum store_bes_photons store_births store_fida_photons store_fw_photons store_fw_photons_at_chan store_neutrals store_neutrons store_npa store_photons sub2ind swap tb_zyx time track uvw_to_xyz write_bb_D_D write_bb_D_T write_bb_H_Aq write_bb_H_e write_bb_H_H write_beam_grid write_birth_profile write_bt_D_D write_bt_D_T write_bt_H_Aq write_bt_H_e write_bt_H_H write_einstein write_fida_weights write_neutrals write_neutrons write_npa write_npa_weights write_spectra xyz_to_uvw
Call graph
read_chords calls h5close_f, randu, h5ltread_dataset_double_f, line_basis, uvw_to_xyz, h5fopen_f, ind2sub, h5ltread_dataset_int_scalar_f, h5ltpath_valid_f, grid_intersect, h5open_f, h5ltread_dataset_string_f, h5gopen_f, track, h5fclose_f, h5gclose_f
line_basis calls tb_zyx
h5ltread_dataset_int_scalar_f calls h5ltread_dataset_int_f
track calls get_indices, in_plasma
in_plasma calls xyz_to_uvw, interpol_coeff
interpol_coeff calls interpol2d_coeff_arr, interpol2d_coeff, interpol1d_coeff, interpol1d_coeff_arr
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
fidasim calls read_chords