simpsons_rule – FIDASIM
simpsons_rule Function
22 statements
Source File
public function simpsons_rule(f, dx) result(I)
Performs 1D integration using Simpsons rule
###References * Simpson's rule
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in), dimension(:) :: f
Array of equally spaced values
real(kind=Float64), intent(in) :: dx
Spacing between x values
Return Value real(kind=Float64)
Called by
Contents
Source Code
simpsons_rule
Source Code
function simpsons_rule(f, dx) result(I)
    !+ Performs 1D integration using Simpsons rule
    !+
    !+ ###References
    !+* [Simpson's rule](http://mathworld.wolfram.com/SimpsonsRule.html)
    real(Float64), dimension(:), intent(in) :: f
        !+ Array of equally spaced \(f(x)\) values
    real(Float64), intent(in)               :: dx
        !+ Spacing between x values
    real(Float64)                           :: I
    integer :: s, ii
    s = size(f)
    I = 0.d0
    if(mod(s,2).eq.1) then
        write(*,'(a)') "Length of array must be even"
        return
    endif
    I = f(1)
    do ii=2,s-1
        if(mod(ii,2).eq.1) then
            I = I + 4.0*f(ii)
        else
            I = I + 2.0*f(ii)
        endif
    enddo
    I = I + f(s)
    I = (dx/3.0)*I
end function simpsons_rule
Call graph
bt_maxwellian_eb calls simpsons_rule
bt_maxwellian_n calls simpsons_rule
bt_maxwellian_q_n_m calls simpsons_rule
bt_maxwellian_q_n calls simpsons_rule
bt_maxwellian_n_m calls simpsons_rule
bt_maxwellian calls bt_maxwellian_eb, bt_maxwellian_n, bt_maxwellian_q_n_m, bt_maxwellian_q_n, bt_maxwellian_n_m
write_bt_d_he3 calls bt_maxwellian
write_bt_h_h calls bt_maxwellian
write_bt_h_aq calls bt_maxwellian
write_bt_d_d calls bt_maxwellian
write_bt_h_e calls bt_maxwellian
write_bt_d_t calls bt_maxwellian
generate_tables calls write_bt_d_he3, write_bt_h_h, write_bt_h_aq, write_bt_d_d, write_bt_h_e