store_npa – FIDASIM
store_npa Subroutine
76 statements
Source File
public subroutine store_npa(det, ri, rf, vn, flux, orbit_class, passive)
Store NPA particles in npa
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: det
Detector/Channel Number
real(kind=Float64), intent(in), dimension(3) :: ri
Birth position in beam coordinates [cm]
real(kind=Float64), intent(in), dimension(3) :: rf
Detector position in beam coordinates [cm]
real(kind=Float64), intent(in), dimension(3) :: vn
Particle velocity [cm/s]
real(kind=Float64), intent(in) :: flux
Neutral flux [neutrals/s]
integer, intent(in), optional :: orbit_class
Orbit class ID
logical, intent(in), optional :: passive
Indicates whether npa particle is passive
Calls
Called By
Source Code
store_npa
Source Code
subroutine store_npa(det, ri, rf, vn, flux, orbit_class, passive)
    !+ Store NPA particles in [[libfida:npa]]
    integer, intent(in)                     :: det
        !+ Detector/Channel Number
    real(Float64), dimension(3), intent(in) :: ri
        !+ Birth position in beam coordinates [cm]
    real(Float64), dimension(3), intent(in) :: rf
        !+ Detector position in beam coordinates [cm]
    real(Float64), dimension(3), intent(in) :: vn
        !+ Particle velocity [cm/s]
    real(Float64), intent(in)               :: flux
        !+ Neutral flux [neutrals/s]
    integer, intent(in), optional           :: orbit_class
        !+ Orbit class ID
    logical, intent(in), optional           :: passive
        !+ Indicates whether npa particle is passive
    integer :: iclass
    type(LocalEMFields) :: fields
    real(Float64), dimension(3) :: uvw_ri, uvw_rf,vn_norm
    real(Float64) :: energy, pitch, dE
    integer(Int32), dimension(1) :: ienergy
    type(NPAParticle), dimension(:), allocatable :: parts
    logical :: pas = .False.
    if(present(orbit_class)) then
        iclass = orbit_class
    else
        iclass = 1
    endif
    if(present(passive)) pas = passive
    ! Convert to machine coordinates
    call xyz_to_uvw(ri,uvw_ri)
    call xyz_to_uvw(rf,uvw_rf)
    ! Calculate energy
    energy = inputs%ab*v2_to_E_per_amu*dot_product(vn,vn)
    dE = npa%energy(2)-npa%energy(1)
    ! Calculate pitch if distribution actually uses pitch
    if(inputs%dist_type.le.2) then
        call get_fields(fields, pos = ri)
        vn_norm = vn/norm2(vn)
        pitch = dot_product(fields%b_norm,vn_norm)
    else
        pitch = 0.d0
    endif
    if(pas) then
        !$OMP CRITICAL(store_npa_1)
        pnpa%npart = pnpa%npart + 1
        if(pnpa%npart.gt.pnpa%nmax) then
            pnpa%nmax = int(pnpa%nmax*2)
            allocate(parts(pnpa%nmax))
            parts(1:(pnpa%npart-1)) = pnpa%part
            deallocate(pnpa%part)
            call move_alloc(parts, pnpa%part)
        endif
        pnpa%part(pnpa%npart)%detector = det
        pnpa%part(pnpa%npart)%xi = uvw_ri(1)
        pnpa%part(pnpa%npart)%yi = uvw_ri(2)
        pnpa%part(pnpa%npart)%zi = uvw_ri(3)
        pnpa%part(pnpa%npart)%xf = uvw_rf(1)
        pnpa%part(pnpa%npart)%yf = uvw_rf(2)
        pnpa%part(pnpa%npart)%zf = uvw_rf(3)
        pnpa%part(pnpa%npart)%energy = energy
        pnpa%part(pnpa%npart)%pitch = pitch
        pnpa%part(pnpa%npart)%weight = flux
        ienergy = minloc(abs(pnpa%energy - energy))
        pnpa%flux(ienergy(1),det,iclass) = &
            pnpa%flux(ienergy(1),det,iclass) + flux/dE
        !$OMP END CRITICAL(store_npa_1)
    else
        !$OMP CRITICAL(store_npa_2)
        npa%npart = npa%npart + 1
        if(npa%npart.gt.npa%nmax) then
            npa%nmax = int(npa%nmax*2)
            allocate(parts(npa%nmax))
            parts(1:(npa%npart-1)) = npa%part
            deallocate(npa%part)
            call move_alloc(parts, npa%part)
        endif
        npa%part(npa%npart)%detector = det
        npa%part(npa%npart)%xi = uvw_ri(1)
        npa%part(npa%npart)%yi = uvw_ri(2)
        npa%part(npa%npart)%zi = uvw_ri(3)
        npa%part(npa%npart)%xf = uvw_rf(1)
        npa%part(npa%npart)%yf = uvw_rf(2)
        npa%part(npa%npart)%zf = uvw_rf(3)
        npa%part(npa%npart)%energy = energy
        npa%part(npa%npart)%pitch = pitch
        npa%part(npa%npart)%weight = flux
        ienergy = minloc(abs(npa%energy - energy))
        npa%flux(ienergy(1),det,iclass) = &
            npa%flux(ienergy(1),det,iclass) + flux/dE
        !$OMP END CRITICAL(store_npa_2)
    endif
end subroutine store_npa
All Procedures
approx_eq approx_ge approx_le Aq_cx Aq_cx_n Aq_cx_n_adas Aq_cx_n_janev Aq_excit Aq_excit_1_2_janev Aq_excit_1_3_janev Aq_excit_1_4_janev Aq_excit_1_5_janev Aq_excit_1_janev Aq_excit_2_10_janev Aq_excit_2_3_janev Aq_excit_2_4_janev Aq_excit_2_5_janev Aq_excit_2_6_janev Aq_excit_2_7_janev Aq_excit_2_8_janev Aq_excit_2_9_janev Aq_excit_2_janev Aq_excit_3_10_janev Aq_excit_3_4_janev Aq_excit_3_5_janev Aq_excit_3_6_janev Aq_excit_3_7_janev Aq_excit_3_8_janev Aq_excit_3_9_janev Aq_excit_3_janev Aq_excit_n Aq_excit_n_janev Aq_excit_n_m Aq_ioniz Aq_ioniz_n Aq_ioniz_n_janev assignment(=) attenuate B5_cx_1_adas B5_cx_1_janev B5_cx_2_adas B5_ioniz_1_janev balance balback bb_cx_rates boundary_edge bremsstrahlung bt_cx_rates bt_maxwellian bt_maxwellian_eb bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m C6_cx_1_adas C6_cx_1_janev C6_cx_2_adas C6_cx_3_adas C6_ioniz_1_janev calc_perp_vectors check_compression_availability circle_grid_intersect cleanup_mpi cold_spec colrad comabs Comdiv cross_product cumsum d_d_fusion_he d_d_fusion_t d_t_fusion dcx dcx_spec deriv e_excit e_excit_1_2_janev e_excit_1_3_janev e_excit_1_4_janev e_excit_1_5_janev e_excit_1_janev e_excit_2_3_janev e_excit_f e_excit_n e_excit_n_m e_ioniz e_ioniz_1_janev e_ioniz_2_janev e_ioniz_3_janev e_ioniz_n eigen elmhes elmtrans fast_ion_assign ff_add ff_assign ff_subtract fida_f fida_mc fida_weights_los fida_weights_mc flf_assign fs_divide fs_multiply get_beam_cx_rate get_distribution get_ep_denf get_fields get_indices get_neutron_rate get_nlaunch get_plasma get_position get_rate_matrix get_rng get_value grid_intersect gyro_correction gyro_radius gyro_range gyro_step gyro_surface gyro_surface_coordinates gyro_trajectory h5ltmake_compressed_dataset_double_f h5ltmake_compressed_dataset_double_f_1 h5ltmake_compressed_dataset_double_f_2 h5ltmake_compressed_dataset_double_f_3 h5ltmake_compressed_dataset_double_f_4 h5ltmake_compressed_dataset_double_f_5 h5ltmake_compressed_dataset_double_f_6 h5ltmake_compressed_dataset_double_f_7 h5ltmake_compressed_dataset_int_f h5ltmake_compressed_dataset_int_f_1 h5ltmake_compressed_dataset_int_f_2 h5ltmake_compressed_dataset_int_f_3 h5ltmake_compressed_dataset_int_f_4 h5ltmake_compressed_dataset_int_f_5 h5ltmake_compressed_dataset_int_f_6 h5ltmake_compressed_dataset_int_f_7 h5ltread_dataset_double_scalar_f h5ltread_dataset_int_scalar_f halo halo_spec hit_npa_detector hqr2 hqrvec in_boundary in_grid in_gyro_surface in_plasma ind2sub init_mpi interpol interpol1D_arr interpol1D_coeff interpol1D_coeff_arr interpol2D_2D_arr interpol2D_arr interpol2D_coeff interpol2D_coeff_arr interpol_coeff lff_assign lflf_add lflf_assign lflf_subtract lfs_divide lfs_multiply line_basis line_gyro_surface_intersect line_plane_intersect linsolve lplp_add lplp_assign lplp_subtract lpp_assign lps_divide lps_multiply lubksb ludcmp m_spread make_beam_grid matinv mc_fastion mc_halo mc_nbi mc_nbi_cell my_rank nbi_spec ndmc neutron_f neutron_mc norm2 npa_f npa_gyro_range npa_mc npa_part_assign npa_weights num_ranks operator(*) operator(+) operator(-) operator(/) outerprod p_cx p_cx_1 p_cx_1_1_adas p_cx_1_2_adas p_cx_1_3_adas p_cx_1_4_adas p_cx_1_janev p_cx_2 p_cx_2_2_adas p_cx_2_3_adas p_cx_2_janev p_cx_3 p_cx_3_2_adas p_cx_3_3_adas p_cx_3_4_adas p_cx_3_5_adas p_cx_3_6inf_adas p_cx_3_janev p_cx_janev p_cx_n p_cx_n_janev p_cx_n_m p_excit p_excit_1_2_janev p_excit_1_3_janev p_excit_1_4_janev p_excit_1_5_janev p_excit_1_6_janev p_excit_1_janev p_excit_2_10_janev p_excit_2_3_janev p_excit_2_4_janev p_excit_2_5_janev p_excit_2_6_janev p_excit_2_7_janev p_excit_2_8_janev p_excit_2_9_janev p_excit_2_janev p_excit_3_10_janev p_excit_3_4_janev p_excit_3_5_janev p_excit_3_6_janev p_excit_3_7_janev p_excit_3_8_janev p_excit_3_9_janev p_excit_3_janev p_excit_n p_excit_n_m p_ioniz p_ioniz_1_janev p_ioniz_2_omullane p_ioniz_3_omullane p_ioniz_4_omullane p_ioniz_5_omullane p_ioniz_n parallel_sum parallel_sum_d0 parallel_sum_d1 parallel_sum_d2 parallel_sum_d3 parallel_sum_d4 parallel_sum_d5 parallel_sum_i0 parallel_sum_i1 parallel_sum_i2 pfida_f pfida_mc pitch_to_vec plane_basis plp_assign pnpa_f pnpa_mc pp_add pp_assign pp_subtract print_banner print_default_namelist ps_divide ps_multiply randind randind_cdf randn randu read_atomic_cross read_atomic_rate read_atomic_transitions read_beam read_chords read_distribution read_equilibrium read_f read_inputs read_mc read_neutrals read_npa read_nuclear_rates read_tables rng_init rng_normal rng_seed rng_uniform RSWAP sf_multiply simpsons_rule slf_multiply slp_multiply sp_multiply sparse spectrum store_bes_photons store_births store_fida_photons store_fw_photons store_fw_photons_at_chan store_neutrals store_neutrons store_npa store_photons sub2ind swap tb_zyx time track uvw_to_xyz write_bb_D_D write_bb_D_T write_bb_H_Aq write_bb_H_e write_bb_H_H write_beam_grid write_birth_profile write_bt_D_D write_bt_D_T write_bt_H_Aq write_bt_H_e write_bt_H_H write_einstein write_fida_weights write_neutrals write_neutrons write_npa write_npa_weights write_spectra xyz_to_uvw
Call graph
store_npa calls get_fields, xyz_to_uvw
get_fields calls calc_perp_vectors, get_position, in_plasma
in_plasma calls xyz_to_uvw, interpol_coeff
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol1d_coeff_arr, interpol2d_coeff
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
npa_f calls store_npa
npa_mc calls store_npa
pnpa_mc calls store_npa
pnpa_f calls store_npa
fidasim calls npa_f, npa_mc, pnpa_mc, pnpa_f