update_reservoir – FIDASIM
update_reservoir Subroutine
21 statements
Source File
public subroutine update_reservoir(res, vn, wght)
Store neutrals in reservoir
Arguments
Type Intent Optional Attributes Name
type(NeutralParticleReservoir), intent(inout) :: res
beam_grid indices
real(kind=Float64), intent(in), dimension(3) :: vn
Neutral particle velocity [cm/s]
real(kind=Float64), intent(in) :: wght
Neutral weight
Calls
Called by
Contents
Source Code
update_reservoir
Source Code
subroutine update_reservoir(res, vn, wght)
    !+ Store neutrals in reservoir
    type(NeutralParticleReservoir), intent(inout) :: res
        !+ [[libfida:beam_grid]] indices
    real(Float64), dimension(3), intent(in)       :: vn
        !+ Neutral particle velocity [cm/s]
    real(Float64), intent(in)                     :: wght
        !+ Neutral weight
    integer, dimension(1) :: randomi
    real(Float64), dimension(2) :: randomu
    !print*, res%n, res%k, res%i
    !$OMP CRITICAL(update_reservoir_1)
    if (res%n.le.res%k) then
        if (res%n.le.0) then
            call init_reservoir(res)
        endif
        res%R(res%n)%w = wght
        res%R(res%n)%v = vn
    elseif (res%n.eq.res%i) then
        call randind(res%k, randomi)
        res%R(randomi(1)) = NeutralParticle(wght, vn)
        call randu(randomu)
        res%W = res%W*exp(log(randomu(1))/res%k)
        res%i = res%i + floor(log(randomu(2))/log(1.0-res%W)) + 1
    endif
    res%n = res%n + 1
    !$OMP END CRITICAL(update_reservoir_1)
end subroutine update_reservoir
Call graph
update_reservoir calls randind, randu, init_reservoir
init_reservoir calls randu
merge_reservoirs calls update_reservoir
update_neutrals calls update_reservoir
store_photon_birth calls update_reservoir
store_neutrals calls update_neutrals
fida_mc calls store_photon_birth, parallel_merge_reservoirs
fida_f calls store_photon_birth, parallel_merge_reservoirs
pfida_mc calls store_photon_birth, parallel_merge_reservoirs
parallel_merge_reservoirs calls merge_reservoirs
pfida_f calls store_photon_birth, parallel_merge_reservoirs
dcx calls store_photon_birth, store_neutrals, parallel_merge_reservoirs, parallel_merge_populations
merge_neutral_populations calls merge_reservoirs
halo calls update_neutrals, store_photon_birth, parallel_merge_reservoirs, merge_neutral_populations, parallel_merge_populations
fidasim calls fida_mc, fida_f, pfida_mc, pfida_f, dcx, halo, ndmc
ndmc calls store_neutrals, parallel_merge_populations
parallel_merge_populations calls parallel_merge_reservoirs