uvw_to_cyl – FIDASIM
uvw_to_cyl Subroutine
7 statements
Source File
public subroutine uvw_to_cyl(uvw, cyl)
Convert machine coordinate uvw to cylindrical coordinate cyl
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in), dimension(3) :: uvw
real(kind=Float64), intent(out), dimension(3) :: cyl
Called by
Contents
Source Code
uvw_to_cyl
Source Code
subroutine uvw_to_cyl(uvw, cyl)
    !+ Convert machine coordinate `uvw` to cylindrical coordinate `cyl`
    real(Float64), dimension(3), intent(in)  :: uvw
    real(Float64), dimension(3), intent(out) :: cyl
    cyl(1) = sqrt(uvw(1)*uvw(1) + uvw(2)*uvw(2))
    cyl(2) = uvw(3)
    cyl(3) = atan2(uvw(2),uvw(1))
end subroutine uvw_to_cyl
Call graph
xyz_to_cyl calls uvw_to_cyl
in_passive_grid calls uvw_to_cyl
get_plasma_extrema calls uvw_to_cyl
make_passive_grid calls get_plasma_extrema
grid_intersect calls in_passive_grid
get_passive_grid_indices calls xyz_to_cyl
circle_grid_intersect calls grid_intersect
mc_nbi calls grid_intersect
store_photons calls get_passive_grid_indices
track_cylindrical calls get_passive_grid_indices
make_diagnostic_grids calls make_passive_grid, grid_intersect, track_cylindrical
store_photon_birth calls get_passive_grid_indices
fida_weights_los calls grid_intersect
halo_spec calls store_photons
store_fida_photons calls store_photons
cold_spec calls store_photons
fidasim calls make_diagnostic_grids, fida_weights_los, halo_spec, cold_spec, fida_mc, fida_f, pfida_mc, nbi_spec, pfida_f, dcx, dcx_spec, halo, ndmc, read_distribution
fida_mc calls store_photon_birth, store_fida_photons
fida_f calls store_photon_birth, store_fida_photons
pfida_mc calls track_cylindrical, store_photon_birth, store_fida_photons
read_mc calls circle_grid_intersect
nbi_spec calls store_photons
pfida_f calls track_cylindrical, store_photon_birth, store_fida_photons
dcx calls store_photons, store_photon_birth
store_nbi_photons calls store_photons
dcx_spec calls store_photons
halo calls store_photons, store_photon_birth
ndmc calls mc_nbi, store_nbi_photons
read_distribution calls read_mc