write_bt_H_Aq – FIDASIM
write_bt_H_Aq Subroutine
185 statements
Source File
public subroutine write_bt_H_Aq(id, namelist_file, n_max, m_max)
Write Hydrogen-Impurity reaction rates to a HDF5 file
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(inout) :: id
HDF5 file or group object id
character(len=*), intent(in) :: namelist_file
Namelist file that contains settings
integer, intent(in) :: n_max
Number of initial atomic energy states to calculate
integer, intent(in) :: m_max
Number of final atomic energy states to calculate
Calls
Called By
Source Code
write_bt_H_Aq
Source Code
subroutine write_bt_H_Aq(id, namelist_file, n_max, m_max)
    !+ Write Hydrogen-Impurity reaction rates to a HDF5 file
    integer(HID_T), intent(inout) :: id
        !+ HDF5 file or group object id
    character(len=*), intent(in)  :: namelist_file
        !+ Namelist file that contains settings
    integer, intent(in)           :: n_max
        !+ Number of initial atomic energy states to calculate
    integer, intent(in)           :: m_max
        !+ Number of final atomic energy states to calculate
    integer :: q
    real(Float64) :: mass
    real(Float64) :: emin
    real(Float64) :: emax
    integer :: nenergy
    real(Float64) :: tmin
    real(Float64) :: tmax
    integer :: ntemp
    real(Float64) :: eb
    real(Float64) :: dlogE
    real(Float64), dimension(:), allocatable :: ebarr
    real(Float64) :: ti
    real(Float64) :: dlogT
    real(Float64), dimension(:), allocatable :: tarr
    real(Float64), dimension(:,:,:,:), allocatable :: ioniz, cx
    real(Float64), dimension(:,:,:,:,:), allocatable :: excit
    integer(HID_T) :: gid
    integer(HSIZE_T), dimension(1) :: dim1
    integer(HSIZE_T), dimension(2) :: dim2
    integer(HSIZE_T), dimension(3) :: dim3
    integer(HSIZE_T), dimension(4) :: dim4
    integer(HSIZE_T), dimension(5) :: dim5
    integer :: ie, it, ia, n, m, error, cnt
    real(Float64) :: rate
    integer, parameter :: n_bt_amu = 2
    real(Float64), dimension(2,n_bt_amu) :: a
    character(len=10) :: aname
    character(len=5) :: asym
    logical :: exis
    NAMELIST /H_Aq_rates/ q, mass, nenergy, emin, emax, ntemp, tmin, tmax
    q = 6 ; mass = C_amu
    nenergy = 100; emin = 1.d-3 ; emax = 4.d2
    ntemp = 100; tmin = 1.d-3 ; tmax = 2.d1
    inquire(file=namelist_file,exist=exis)
    if(.not.exis) then
        write(*,'(a,a)') 'WRITE_BT_H_Aq: Input file does not exist: ',trim(namelist_file)
        write(*,'(a)') 'Continuing with default settings...'
    else
        open(13,file=namelist_file)
        read(13,NML=H_Aq_rates)
        close(13)
    endif
    allocate(ebarr(nenergy))
    allocate(tarr(ntemp))
    allocate(ioniz(n_max,nenergy,ntemp,n_bt_amu))
    allocate(cx(n_max,nenergy,ntemp,n_bt_amu))
    allocate(excit(n_max,m_max,nenergy,ntemp,n_bt_amu))
    select case (q)
      case (5)
          aname = "Boron"
          asym = "H_B5"
      case (6)
          aname = "Carbon"
          asym = "H_C6"
      case DEFAULT
          aname = "Impurity"
          asym = "H_Aq"
    end select
    ebarr = 0.d0
    ioniz = 0.d0
    cx = 0.d0
    excit = 0.d0
    a(:,1) = [H1_amu, mass]
    a(:,2) = [H2_amu, mass]
    dlogE = (log10(emax) - log10(emin))/(nenergy - 1)
    do ie=1, nenergy
        ebarr(ie) = 10.d0**(log10(emin) + (ie-1)*dlogE)
    enddo
    dlogT = (log10(tmax) - log10(tmin))/(ntemp - 1)
    do it=1, ntemp
        tarr(it) = 10.d0**(log10(tmin) + (it-1)*dlogT)
    enddo
    if(verbose) then
        write(*,'(a)') "---- H-"//trim(adjustl(aname))//" reaction rates settings ----"
        write(*,'(T2,"q = ", i2)') q
        write(*,'(T2,"mass = ",f7.2, " amu")') mass
        write(*,'(T2,"Emin = ",e9.2, " keV")') emin
        write(*,'(T2,"Emax = ",e9.2, " keV")') emax
        write(*,'(T2,"Nenergy = ", i4)') nenergy
        write(*,'(T2,"Tmin = ",e9.2, " keV")') tmin
        write(*,'(T2,"Tmax = ",e9.2, " keV")') tmax
        write(*,'(T2,"Ntemp = ", i4)') ntemp
        write(*,*) ''
    endif
    cnt = 0
    !$OMP PARALLEL DO private(ie, it, ia, n, m, eb, ti, rate)
    do ie=istart, nenergy, istep
        eb = ebarr(ie)
        do it=1, ntemp
            ti = tarr(it)
            do ia=1, n_bt_amu
                do n=1, n_max
                    do m=1, m_max
                        if(m.gt.n) then
                            call bt_maxwellian(Aq_excit_n_m, q, ti, eb, &
                                               a(2,ia), a(1,ia), n, m, rate)
                            excit(n,m,ie,it,ia) = rate
                            call bt_maxwellian(Aq_excit_n_m, q, ti, eb, &
                                               a(2,ia), a(1,ia), n, m, &
                                               rate, deexcit=.True.)
                            excit(m,n,ie,it,ia) = rate
                        endif
                    enddo
                    call bt_maxwellian(Aq_cx_n, q, ti, eb, &
                                       a(2,ia), a(1,ia), n, rate)
                    cx(n,ie,it,ia) = rate
                    call bt_maxwellian(Aq_ioniz_n, q, ti, eb, &
                                       a(2,ia), a(1,ia), n, rate)
                    ioniz(n,ie,it,ia) = rate
                enddo
            enddo
            cnt = cnt + 1
            if(verbose) WRITE(*,'(f7.2,"%",a,$)') 100*istep*cnt/real(nenergy*ntemp),char(13)
        enddo
    enddo
    !$OMP END PARALLEL DO
#ifdef _MPI
    call parallel_sum(ebarr)
    call parallel_sum(tarr)
    call parallel_sum(cx)
    call parallel_sum(excit)
    call parallel_sum(ioniz)
#endif
    if(verbose) then
        call h5gcreate_f(id, trim(adjustl(asym)), gid, error)
        dim1 = [1]
        dim4 = [n_max, nenergy, ntemp, n_bt_amu]
        dim5 = [n_max, m_max, nenergy, ntemp, n_bt_amu]
        call h5ltmake_dataset_int_f(gid, "nenergy", 0, dim1, [nenergy], error)
        call h5ltmake_dataset_int_f(gid, "ntemp", 0, dim1, [ntemp], error)
        call h5ltmake_dataset_int_f(gid, "n_bt_amu", 0, dim1, [n_bt_amu], error)
        call h5ltmake_dataset_int_f(gid, "n_max", 0, dim1, [n_max], error)
        call h5ltmake_dataset_int_f(gid, "m_max", 0, dim1, [m_max], error)
        call h5ltmake_dataset_double_f(gid, "dlogE", 0, dim1, [dlogE], error)
        call h5ltmake_dataset_double_f(gid, "emin", 0, dim1, [emin], error)
        call h5ltmake_dataset_double_f(gid, "emax", 0, dim1, [emax], error)
        call h5ltmake_dataset_double_f(gid, "dlogT", 0, dim1, [dlogT], error)
        call h5ltmake_dataset_double_f(gid, "tmin", 0, dim1, [tmin], error)
        call h5ltmake_dataset_double_f(gid, "tmax", 0, dim1, [tmax], error)
        dim2 = [2,n_bt_amu]
        call h5ltmake_compressed_dataset_double_f(gid, "bt_amu", 2, dim2, a, error)
        dim1 = [nenergy]
        call h5ltmake_compressed_dataset_double_f(gid, "energy", 1, dim1, ebarr, error)
        dim1 = [ntemp]
        call h5ltmake_compressed_dataset_double_f(gid, "temperature", 1, dim1, tarr, error)
        call h5ltmake_compressed_dataset_double_f(gid, "cx", 4, dim4, cx, error)
        call h5ltmake_compressed_dataset_double_f(gid, "ionization", 4, dim4, ioniz, error)
        call h5ltmake_compressed_dataset_double_f(gid, "excitation", 5, dim5, excit, error)
        call h5ltset_attribute_string_f(id, trim(adjustl(asym)), "description", &
             "Beam-Target reaction rates for Hydrogen(beam)-"//trim(adjustl(aname))// &
             "(target) interactions", error)
        call h5ltset_attribute_string_f(gid, "nenergy", "description", &
             "Number of energy values", error)
        call h5ltset_attribute_string_f(gid, "ntemp", "description", &
             "Number of target temperature values", error)
        call h5ltset_attribute_string_f(gid, "n_bt_amu", "description", &
             "Number of beam-target amu combinations", error)
        call h5ltset_attribute_string_f(gid, "n_max", "description", &
             "Number of initial energy levels", error)
        call h5ltset_attribute_string_f(gid, "m_max", "description", &
             "Number of final energy levels", error)
        call h5ltset_attribute_string_f(gid, "bt_amu", "description", &
             "Combinations of beam-target amu's e.g. b_amu, t_amu = bt_amu[:,i]", error)
        call h5ltset_attribute_string_f(gid, "energy", "description", &
             "Energy values", error)
        call h5ltset_attribute_string_f(gid, "energy", "units", "keV", error)
        call h5ltset_attribute_string_f(gid, "dlogE", "description", &
             "Energy spacing in log-10", error)
        call h5ltset_attribute_string_f(gid, "dlogE", "units", "log10(keV)", error)
        call h5ltset_attribute_string_f(gid, "emin","description", &
             "Minimum energy", error)
        call h5ltset_attribute_string_f(gid, "emin", "units", "keV", error)
        call h5ltset_attribute_string_f(gid, "emax","description", &
             "Maximum energy", error)
        call h5ltset_attribute_string_f(gid, "emax", "units", "keV", error)
        call h5ltset_attribute_string_f(gid, "temperature", "description", &
             "Target temperature values", error)
        call h5ltset_attribute_string_f(gid, "temperature", "units", "keV", error)
        call h5ltset_attribute_string_f(gid, "dlogT", "description", &
             "Temperature spacing in log-10", error)
        call h5ltset_attribute_string_f(gid, "dlogT", "units", "log10(keV)", error)
        call h5ltset_attribute_string_f(gid, "tmin","description", &
             "Minimum temperature", error)
        call h5ltset_attribute_string_f(gid, "tmin", "units", "keV", error)
        call h5ltset_attribute_string_f(gid, "tmax","description", &
             "Maximum temperature", error)
        call h5ltset_attribute_string_f(gid, "tmax", "units", "keV", error)
        call h5ltset_attribute_string_f(gid, "cx", "description", &
             "n-resolved charge exchange reaction rates: cx(n,energy,temp,bt_amu)", error)
        call h5ltset_attribute_string_f(gid, "cx", "units", "cm^3/s", error)
        call h5ltset_attribute_string_f(gid, "cx", "reaction", &
             "A(q+) + H(n) -> A((q-1)+) + H(+)", error)
        call h5ltset_attribute_string_f(gid, "excitation", "description", &
             "n/m resolved (de-)excitation reaction rates: excitation(n,m,energy,temp,bt_amu)", error)
        call h5ltset_attribute_string_f(gid, "excitation", "units", "cm^3/s", error)
        call h5ltset_attribute_string_f(gid, "excitation", "reaction", &
             "A(q+) + H(n) -> A(q+) + H(m); m > n excitation, m < n de-excitation", error)
        call h5ltset_attribute_string_f(gid, "ionization", "description", &
             "n resolved ionization reaction rates: ionization(n,energy,temp,bt_amu)", error)
        call h5ltset_attribute_string_f(gid, "ionization", "units", "cm^3/s", error)
        call h5ltset_attribute_string_f(gid, "ionization", "reaction", &
             "A(q+) + H(n) -> A(q+) + H(+) + e-", error)
        call h5gclose_f(gid, error)
    endif
    deallocate(ebarr, tarr, excit, ioniz)
end subroutine write_bt_H_Aq
All Procedures
approx_eq approx_ge approx_le Aq_cx Aq_cx_n Aq_cx_n_adas Aq_cx_n_janev Aq_excit Aq_excit_1_2_janev Aq_excit_1_3_janev Aq_excit_1_4_janev Aq_excit_1_5_janev Aq_excit_1_janev Aq_excit_2_10_janev Aq_excit_2_3_janev Aq_excit_2_4_janev Aq_excit_2_5_janev Aq_excit_2_6_janev Aq_excit_2_7_janev Aq_excit_2_8_janev Aq_excit_2_9_janev Aq_excit_2_janev Aq_excit_3_10_janev Aq_excit_3_4_janev Aq_excit_3_5_janev Aq_excit_3_6_janev Aq_excit_3_7_janev Aq_excit_3_8_janev Aq_excit_3_9_janev Aq_excit_3_janev Aq_excit_n Aq_excit_n_janev Aq_excit_n_m Aq_ioniz Aq_ioniz_n Aq_ioniz_n_janev assignment(=) attenuate B5_cx_1_adas B5_cx_1_janev B5_cx_2_adas B5_ioniz_1_janev balance balback bb_cx_rates boundary_edge bremsstrahlung bt_cx_rates bt_maxwellian bt_maxwellian_eb bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m C6_cx_1_adas C6_cx_1_janev C6_cx_2_adas C6_cx_3_adas C6_ioniz_1_janev calc_perp_vectors check_compression_availability circle_grid_intersect cleanup_mpi cold_spec colrad comabs Comdiv cross_product cumsum d_d_fusion_he d_d_fusion_t d_t_fusion dcx dcx_spec deriv e_excit e_excit_1_2_janev e_excit_1_3_janev e_excit_1_4_janev e_excit_1_5_janev e_excit_1_janev e_excit_2_3_janev e_excit_f e_excit_n e_excit_n_m e_ioniz e_ioniz_1_janev e_ioniz_2_janev e_ioniz_3_janev e_ioniz_n eigen elmhes elmtrans fast_ion_assign ff_add ff_assign ff_subtract fida_f fida_mc fida_weights_los fida_weights_mc flf_assign fs_divide fs_multiply get_beam_cx_rate get_distribution get_ep_denf get_fields get_indices get_neutron_rate get_nlaunch get_plasma get_position get_rate_matrix get_rng get_value grid_intersect gyro_correction gyro_radius gyro_range gyro_step gyro_surface gyro_surface_coordinates gyro_trajectory h5ltmake_compressed_dataset_double_f h5ltmake_compressed_dataset_double_f_1 h5ltmake_compressed_dataset_double_f_2 h5ltmake_compressed_dataset_double_f_3 h5ltmake_compressed_dataset_double_f_4 h5ltmake_compressed_dataset_double_f_5 h5ltmake_compressed_dataset_double_f_6 h5ltmake_compressed_dataset_double_f_7 h5ltmake_compressed_dataset_int_f h5ltmake_compressed_dataset_int_f_1 h5ltmake_compressed_dataset_int_f_2 h5ltmake_compressed_dataset_int_f_3 h5ltmake_compressed_dataset_int_f_4 h5ltmake_compressed_dataset_int_f_5 h5ltmake_compressed_dataset_int_f_6 h5ltmake_compressed_dataset_int_f_7 h5ltread_dataset_double_scalar_f h5ltread_dataset_int_scalar_f halo halo_spec hit_npa_detector hqr2 hqrvec in_boundary in_grid in_gyro_surface in_plasma ind2sub init_mpi interpol interpol1D_arr interpol1D_coeff interpol1D_coeff_arr interpol2D_2D_arr interpol2D_arr interpol2D_coeff interpol2D_coeff_arr interpol_coeff lff_assign lflf_add lflf_assign lflf_subtract lfs_divide lfs_multiply line_basis line_gyro_surface_intersect line_plane_intersect linsolve lplp_add lplp_assign lplp_subtract lpp_assign lps_divide lps_multiply lubksb ludcmp m_spread make_beam_grid matinv mc_fastion mc_halo mc_nbi mc_nbi_cell my_rank nbi_spec ndmc neutron_f neutron_mc norm2 npa_f npa_gyro_range npa_mc npa_part_assign npa_weights num_ranks operator(*) operator(+) operator(-) operator(/) outerprod p_cx p_cx_1 p_cx_1_1_adas p_cx_1_2_adas p_cx_1_3_adas p_cx_1_4_adas p_cx_1_janev p_cx_2 p_cx_2_2_adas p_cx_2_3_adas p_cx_2_janev p_cx_3 p_cx_3_2_adas p_cx_3_3_adas p_cx_3_4_adas p_cx_3_5_adas p_cx_3_6inf_adas p_cx_3_janev p_cx_janev p_cx_n p_cx_n_janev p_cx_n_m p_excit p_excit_1_2_janev p_excit_1_3_janev p_excit_1_4_janev p_excit_1_5_janev p_excit_1_6_janev p_excit_1_janev p_excit_2_10_janev p_excit_2_3_janev p_excit_2_4_janev p_excit_2_5_janev p_excit_2_6_janev p_excit_2_7_janev p_excit_2_8_janev p_excit_2_9_janev p_excit_2_janev p_excit_3_10_janev p_excit_3_4_janev p_excit_3_5_janev p_excit_3_6_janev p_excit_3_7_janev p_excit_3_8_janev p_excit_3_9_janev p_excit_3_janev p_excit_n p_excit_n_m p_ioniz p_ioniz_1_janev p_ioniz_2_omullane p_ioniz_3_omullane p_ioniz_4_omullane p_ioniz_5_omullane p_ioniz_n parallel_sum parallel_sum_d0 parallel_sum_d1 parallel_sum_d2 parallel_sum_d3 parallel_sum_d4 parallel_sum_d5 parallel_sum_i0 parallel_sum_i1 parallel_sum_i2 pfida_f pfida_mc pitch_to_vec plane_basis plp_assign pnpa_f pnpa_mc pp_add pp_assign pp_subtract print_banner print_default_namelist ps_divide ps_multiply randind randind_cdf randn randu read_atomic_cross read_atomic_rate read_atomic_transitions read_beam read_chords read_distribution read_equilibrium read_f read_inputs read_mc read_neutrals read_npa read_nuclear_rates read_tables rng_init rng_normal rng_seed rng_uniform RSWAP sf_multiply simpsons_rule slf_multiply slp_multiply sp_multiply sparse spectrum store_bes_photons store_births store_fida_photons store_fw_photons store_fw_photons_at_chan store_neutrals store_neutrons store_npa store_photons sub2ind swap tb_zyx time track uvw_to_xyz write_bb_D_D write_bb_D_T write_bb_H_Aq write_bb_H_e write_bb_H_H write_beam_grid write_birth_profile write_bt_D_D write_bt_D_T write_bt_H_Aq write_bt_H_e write_bt_H_H write_einstein write_fida_weights write_neutrals write_neutrons write_npa write_npa_weights write_spectra xyz_to_uvw
Call graph
write_bt_h_aq calls bt_maxwellian, h5gcreate_f, parallel_sum, h5ltmake_dataset_double_f, h5ltset_attribute_string_f, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f, h5gclose_f
bt_maxwellian calls bt_maxwellian_q_n_m, bt_maxwellian_eb, bt_maxwellian_q_n, bt_maxwellian_n_m, bt_maxwellian_n
parallel_sum calls parallel_sum_d4, parallel_sum_d3, parallel_sum_i1, parallel_sum_d2, parallel_sum_d1, parallel_sum_i0, parallel_sum_d5, parallel_sum_i2, parallel_sum_d0
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_6, h5ltmake_compressed_dataset_double_f_4
bt_maxwellian_q_n_m calls simpsons_rule
bt_maxwellian_eb calls simpsons_rule
bt_maxwellian_q_n calls simpsons_rule
bt_maxwellian_n_m calls simpsons_rule
bt_maxwellian_n calls simpsons_rule
parallel_sum_d4 calls mpi_allreduce
parallel_sum_d3 calls mpi_allreduce
parallel_sum_i1 calls mpi_allreduce
parallel_sum_d2 calls mpi_allreduce
parallel_sum_d1 calls mpi_allreduce
parallel_sum_i0 calls mpi_allreduce
parallel_sum_d5 calls mpi_allreduce
parallel_sum_i2 calls mpi_allreduce
parallel_sum_d0 calls mpi_allreduce
h5ltmake_compressed_dataset_double_f_1 calls h5ltmake_dataset_double_f, h5dcreate_f, h5pset_chunk_f, h5pset_deflate_f, h5pcreate_f, h5dwrite_f, h5pset_shuffle_f, h5dclose_f, h5sclose_f, h5screate_simple_f, h5pclose_f
h5ltmake_compressed_dataset_double_f_2 calls h5ltmake_dataset_double_f, h5dcreate_f, h5pset_chunk_f, h5pset_deflate_f, h5pcreate_f, h5dwrite_f, h5pset_shuffle_f, h5dclose_f, h5sclose_f, h5screate_simple_f, h5pclose_f
h5ltmake_compressed_dataset_double_f_3 calls h5ltmake_dataset_double_f, h5dcreate_f, h5pset_chunk_f, h5pset_deflate_f, h5pcreate_f, h5dwrite_f, h5pset_shuffle_f, h5dclose_f, h5sclose_f, h5screate_simple_f, h5pclose_f
h5ltmake_compressed_dataset_double_f_7 calls h5ltmake_dataset_double_f, h5dcreate_f, h5pset_chunk_f, h5pset_deflate_f, h5pcreate_f, h5dwrite_f, h5pset_shuffle_f, h5dclose_f, h5sclose_f, h5screate_simple_f, h5pclose_f
h5ltmake_compressed_dataset_double_f_5 calls h5ltmake_dataset_double_f, h5dcreate_f, h5pset_chunk_f, h5pset_deflate_f, h5pcreate_f, h5dwrite_f, h5pset_shuffle_f, h5dclose_f, h5sclose_f, h5screate_simple_f, h5pclose_f
h5ltmake_compressed_dataset_double_f_6 calls h5ltmake_dataset_double_f, h5dcreate_f, h5pset_chunk_f, h5pset_deflate_f, h5pcreate_f, h5dwrite_f, h5pset_shuffle_f, h5dclose_f, h5sclose_f, h5screate_simple_f, h5pclose_f
h5ltmake_compressed_dataset_double_f_4 calls h5ltmake_dataset_double_f, h5dcreate_f, h5pset_chunk_f, h5pset_deflate_f, h5pcreate_f, h5dwrite_f, h5pset_shuffle_f, h5dclose_f, h5sclose_f, h5screate_simple_f, h5pclose_f
generate_tables calls write_bt_h_aq