write_birth_profile – FIDASIM
write_birth_profile Subroutine
92 statements
Source File
public subroutine write_birth_profile()
Writes birth to a HDF5 file
Arguments
None
Calls
Called By
Source Code
write_birth_profile
Source Code
subroutine write_birth_profile
    !+ Writes [[libfida:birth]] to a HDF5 file
    integer(HID_T) :: fid
    integer(HSIZE_T), dimension(4) :: dim4
    integer(HSIZE_T), dimension(2) :: dim2
    integer(HSIZE_T), dimension(1) :: d
    integer :: error, i, c, npart, start_index, end_index
    character(charlim) :: filename
    real(Float64), dimension(:,:), allocatable :: ri
    real(Float64), dimension(:,:), allocatable :: vi
    integer, dimension(:,:), allocatable :: inds
    integer, dimension(:), allocatable :: neut_types
    real(Float64), dimension(3) :: xyz,uvw,v_uvw
    logical :: do_write
#ifdef _MPI
    integer :: my_rank
    integer, dimension(:), allocatable :: npart_image
#endif
    npart = birth%cnt-1
#ifdef _MPI
    call fidampi_sum(npart)
#endif
    allocate(ri(3,npart))
    allocate(vi(3,npart))
    allocate(inds(3,npart))
    allocate(neut_types(npart))
    ri = 0.d0
    vi = 0.d0
    inds = 0
    neut_types = 0
    c = 0
#ifdef _MPI
    my_rank = fidampi_my_rank()
    allocate(npart_image(0:fidampi_num_ranks()-1))
    npart_image(:) = 0
    npart_image(my_rank) = birth%cnt - 1
    call fidampi_sum(npart_image)
    do i=0,my_rank-1
        c = c +  npart_image(i)
    enddo
    deallocate(npart_image)
#endif
    start_index = 1 + c
    end_index = birth%cnt - 1 + c
    c = 1
    do i=start_index, end_index
        ! Convert position to rzphi
        xyz = birth%ri(:,c)
        call xyz_to_uvw(xyz,uvw)
        ri(1,i) = sqrt(uvw(1)*uvw(1) + uvw(2)*uvw(2))
        ri(2,i) = uvw(3)
        ri(3,i) = atan2(uvw(2),uvw(1))
        ! Convert velocity to rzphi
        v_uvw = matmul(beam_grid%basis, birth%vi(:,c))
        vi(1,i) = v_uvw(1)*cos(ri(3,i)) + v_uvw(2)*sin(ri(3,i))
        vi(2,i) = v_uvw(3)
        vi(3,i) = -v_uvw(1)*sin(ri(3,i)) + v_uvw(2)*cos(ri(3,i))
        inds(:,i) = birth%ind(:,c)
        neut_types(i) = birth%neut_type(c)
        c = c + 1
    enddo
    filename=trim(adjustl(inputs%result_dir))//"/"//trim(adjustl(inputs%runid))//"_birth.h5"
    do_write = .True.
#ifdef _MPI
    call fidampi_sum(ri)
    call fidampi_sum(vi)
    call fidampi_sum(inds)
    call fidampi_sum(neut_types)
    if(fidampi_my_rank().ne.0) do_write = .False.
#endif
    if(do_write) then
        !Open HDF5 interface
        call h5open_f(error)
        !Create file overwriting any existing file
        call h5fcreate_f(filename, H5F_ACC_TRUNC_F, fid, error)
        !Write variables
        call write_beam_grid(fid, error)
        d(1) = 1
        call h5ltmake_dataset_int_f(fid, "/n_birth", 0, d, [npart], error)
        dim4 = shape(birth%dens)
        call h5ltmake_compressed_dataset_double_f(fid,"/dens", 4, dim4, birth%dens, error)
        dim2 = [3, npart]
        call h5ltmake_compressed_dataset_double_f(fid,"/ri", 2, dim2, ri, error)
        call h5ltmake_compressed_dataset_double_f(fid,"/vi", 2, dim2, vi, error)
        call h5ltmake_compressed_dataset_int_f(fid,"/ind", 2, dim2, inds, error)
        call h5ltmake_compressed_dataset_int_f(fid,"/type", 1, dim2(2:2), neut_types, error)
        !Add attributes
        call h5ltset_attribute_string_f(fid, "/n_birth","description", &
             "Number of birth mc particles deposited", error)
        call h5ltset_attribute_string_f(fid, "/dens", "description", &
             "Birth density: dens(beam_component,x,y,z)", error)
        call h5ltset_attribute_string_f(fid, "/dens", "units", &
             "fast-ions/(s*cm^3)", error)
        call h5ltset_attribute_string_f(fid, "/ri", "description", &
             "Fast-ion birth position in R-Z-Phi: ri([r,z,phi],particle)", error)
        call h5ltset_attribute_string_f(fid, "/ri", "units", "cm, radians", error)
        call h5ltset_attribute_string_f(fid, "/vi", "description", &
             "Fast-ion birth velocity in R-Z-Phi: vi([r,z,phi],particle)", error)
        call h5ltset_attribute_string_f(fid, "/vi", "units", "cm/s", error)
        call h5ltset_attribute_string_f(fid, "/ind", "description", &
             "Fast-ion birth beam grid indices: ind([i,j,k],particle)", error)
        call h5ltset_attribute_string_f(fid, "/type", "description", &
             "Fast-ion birth type (1=Full, 2=Half, 3=Third)", error)
        call h5ltset_attribute_string_f(fid, "/", "coordinate_system", &
             "Cylindrical (R,Z,Phi)",error)
        call h5ltset_attribute_string_f(fid, "/", "version", version, error)
        call h5ltset_attribute_string_f(fid, "/", "description", &
             "Birth density and particles calculated by FIDASIM", error)
        !!Close file
        call h5fclose_f(fid, error)
        !!Close HDF5 interface
        call h5close_f(error)
    endif
    deallocate(ri,vi)
    if(inputs%verbose.ge.1) then
        write(*,'(T4,a,a)') 'birth profile written to: ',trim(filename)
    endif
end subroutine write_birth_profile
All Procedures
approx_eq approx_ge approx_le Aq_cx Aq_cx_n Aq_cx_n_adas Aq_cx_n_janev Aq_excit Aq_excit_1_2_janev Aq_excit_1_3_janev Aq_excit_1_4_janev Aq_excit_1_5_janev Aq_excit_1_janev Aq_excit_2_10_janev Aq_excit_2_3_janev Aq_excit_2_4_janev Aq_excit_2_5_janev Aq_excit_2_6_janev Aq_excit_2_7_janev Aq_excit_2_8_janev Aq_excit_2_9_janev Aq_excit_2_janev Aq_excit_3_10_janev Aq_excit_3_4_janev Aq_excit_3_5_janev Aq_excit_3_6_janev Aq_excit_3_7_janev Aq_excit_3_8_janev Aq_excit_3_9_janev Aq_excit_3_janev Aq_excit_n Aq_excit_n_janev Aq_excit_n_m Aq_ioniz Aq_ioniz_n Aq_ioniz_n_janev assignment(=) attenuate B5_cx_1_adas B5_cx_1_janev B5_cx_2_adas B5_ioniz_1_janev balance balback bb_cx_rates boundary_edge bremsstrahlung bt_cx_rates bt_maxwellian bt_maxwellian_eb bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m C6_cx_1_adas C6_cx_1_janev C6_cx_2_adas C6_cx_3_adas C6_ioniz_1_janev calc_perp_vectors check_compression_availability circle_grid_intersect cold_spec colrad comabs Comdiv cross_product cumsum d_d_fusion_he d_d_fusion_t d_t_fusion dcx dcx_spec deriv e_excit e_excit_1_2_janev e_excit_1_3_janev e_excit_1_4_janev e_excit_1_5_janev e_excit_1_janev e_excit_2_3_janev e_excit_f e_excit_n e_excit_n_m e_ioniz e_ioniz_1_janev e_ioniz_2_janev e_ioniz_3_janev e_ioniz_n eigen elmhes elmtrans fast_ion_assign ff_add ff_assign ff_subtract fida_f fida_mc fida_weights_los fida_weights_mc fidampi_clenup fidampi_init fidampi_my_rank fidampi_num_ranks fidampi_sum fidampi_sum_d0 fidampi_sum_d1 fidampi_sum_d2 fidampi_sum_d3 fidampi_sum_d4 fidampi_sum_d5 fidampi_sum_i0 fidampi_sum_i1 fidampi_sum_i2 flf_assign fs_divide fs_multiply get_beam_cx_rate get_distribution get_ep_denf get_fields get_indices get_neutron_rate get_nlaunch get_plasma get_position get_rate_matrix get_rng get_value grid_intersect gyro_correction gyro_radius gyro_range gyro_step gyro_surface gyro_surface_coordinates gyro_trajectory h5ltmake_compressed_dataset_double_f h5ltmake_compressed_dataset_double_f_1 h5ltmake_compressed_dataset_double_f_2 h5ltmake_compressed_dataset_double_f_3 h5ltmake_compressed_dataset_double_f_4 h5ltmake_compressed_dataset_double_f_5 h5ltmake_compressed_dataset_double_f_6 h5ltmake_compressed_dataset_double_f_7 h5ltmake_compressed_dataset_int_f h5ltmake_compressed_dataset_int_f_1 h5ltmake_compressed_dataset_int_f_2 h5ltmake_compressed_dataset_int_f_3 h5ltmake_compressed_dataset_int_f_4 h5ltmake_compressed_dataset_int_f_5 h5ltmake_compressed_dataset_int_f_6 h5ltmake_compressed_dataset_int_f_7 h5ltread_dataset_double_scalar_f h5ltread_dataset_int_scalar_f halo halo_spec hit_npa_detector hqr2 hqrvec in_boundary in_grid in_gyro_surface in_plasma ind2sub interpol interpol1D_arr interpol1D_coeff interpol1D_coeff_arr interpol2D_2D_arr interpol2D_arr interpol2D_coeff interpol2D_coeff_arr interpol_coeff lff_assign lflf_add lflf_assign lflf_subtract lfs_divide lfs_multiply line_basis line_gyro_surface_intersect line_plane_intersect linsolve lplp_add lplp_assign lplp_subtract lpp_assign lps_divide lps_multiply lubksb ludcmp m_spread make_beam_grid matinv mc_fastion mc_halo mc_nbi mc_nbi_cell nbi_spec ndmc neutron_f neutron_mc norm2 npa_f npa_gyro_range npa_mc npa_part_assign npa_weights operator(*) operator(+) operator(-) operator(/) outerprod p_cx p_cx_1 p_cx_1_1_adas p_cx_1_2_adas p_cx_1_3_adas p_cx_1_4_adas p_cx_1_janev p_cx_2 p_cx_2_2_adas p_cx_2_3_adas p_cx_2_janev p_cx_3 p_cx_3_2_adas p_cx_3_3_adas p_cx_3_4_adas p_cx_3_5_adas p_cx_3_6inf_adas p_cx_3_janev p_cx_janev p_cx_n p_cx_n_janev p_cx_n_m p_excit p_excit_1_2_janev p_excit_1_3_janev p_excit_1_4_janev p_excit_1_5_janev p_excit_1_6_janev p_excit_1_janev p_excit_2_10_janev p_excit_2_3_janev p_excit_2_4_janev p_excit_2_5_janev p_excit_2_6_janev p_excit_2_7_janev p_excit_2_8_janev p_excit_2_9_janev p_excit_2_janev p_excit_3_10_janev p_excit_3_4_janev p_excit_3_5_janev p_excit_3_6_janev p_excit_3_7_janev p_excit_3_8_janev p_excit_3_9_janev p_excit_3_janev p_excit_n p_excit_n_m p_ioniz p_ioniz_1_janev p_ioniz_2_omullane p_ioniz_3_omullane p_ioniz_4_omullane p_ioniz_5_omullane p_ioniz_n pfida_f pfida_mc pitch_to_vec plane_basis plp_assign pnpa_f pnpa_mc pp_add pp_assign pp_subtract print_banner print_default_namelist ps_divide ps_multiply randind randind_cdf randn randu read_atomic_cross read_atomic_rate read_atomic_transitions read_beam read_chords read_distribution read_equilibrium read_f read_inputs read_mc read_neutrals read_npa read_nuclear_rates read_tables rng_init rng_normal rng_seed rng_uniform RSWAP sf_multiply simpsons_rule slf_multiply slp_multiply sp_multiply sparse spectrum store_bes_photons store_births store_fida_photons store_fw_photons store_fw_photons_at_chan store_neutrals store_neutrons store_npa store_photons sub2ind swap tb_zyx time track uvw_to_xyz write_bb_D_D write_bb_D_T write_bb_H_Aq write_bb_H_e write_bb_H_H write_beam_grid write_birth_profile write_bt_D_D write_bt_D_T write_bt_H_Aq write_bt_H_e write_bt_H_H write_einstein write_fida_weights write_neutrals write_neutrons write_npa write_npa_weights write_spectra xyz_to_uvw
Call graph
write_birth_profile calls h5close_f, fidampi_num_ranks, fidampi_sum, fidampi_my_rank, h5ltmake_compressed_dataset_int_f, h5fcreate_f, xyz_to_uvw, h5ltmake_dataset_int_f, write_beam_grid, h5ltmake_compressed_dataset_double_f, h5fclose_f, h5ltset_attribute_string_f, h5open_f
fidampi_sum calls fidampi_sum_d4, fidampi_sum_i2, fidampi_sum_d5, fidampi_sum_i0, fidampi_sum_d2, fidampi_sum_i1, fidampi_sum_d3, fidampi_sum_d0, fidampi_sum_d1
h5ltmake_compressed_dataset_int_f calls h5ltmake_compressed_dataset_int_f_4, h5ltmake_compressed_dataset_int_f_2, h5ltmake_compressed_dataset_int_f_6, h5ltmake_compressed_dataset_int_f_1, h5ltmake_compressed_dataset_int_f_7, h5ltmake_compressed_dataset_int_f_5, h5ltmake_compressed_dataset_int_f_3
write_beam_grid calls xyz_to_uvw, h5ltmake_dataset_int_f, h5ltmake_compressed_dataset_double_f, h5ltset_attribute_string_f, h5gcreate_f, h5gclose_f
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_6, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_4
fidampi_sum_d4 calls mpi_allreduce
fidampi_sum_i2 calls mpi_allreduce
fidampi_sum_d5 calls mpi_allreduce
fidampi_sum_i0 calls mpi_allreduce
fidampi_sum_d2 calls mpi_allreduce
fidampi_sum_i1 calls mpi_allreduce
fidampi_sum_d3 calls mpi_allreduce
fidampi_sum_d0 calls mpi_allreduce
fidampi_sum_d1 calls mpi_allreduce
h5ltmake_compressed_dataset_int_f_4 calls h5ltmake_dataset_int_f, h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5dclose_f, h5sclose_f
h5ltmake_compressed_dataset_int_f_2 calls h5ltmake_dataset_int_f, h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5dclose_f, h5sclose_f
h5ltmake_compressed_dataset_int_f_6 calls h5ltmake_dataset_int_f, h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5dclose_f, h5sclose_f
h5ltmake_compressed_dataset_int_f_1 calls h5ltmake_dataset_int_f, h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5dclose_f, h5sclose_f
h5ltmake_compressed_dataset_int_f_7 calls h5ltmake_dataset_int_f, h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5dclose_f, h5sclose_f
h5ltmake_compressed_dataset_int_f_5 calls h5ltmake_dataset_int_f, h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5dclose_f, h5sclose_f
h5ltmake_compressed_dataset_int_f_3 calls h5ltmake_dataset_int_f, h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5dclose_f, h5sclose_f
h5ltmake_compressed_dataset_double_f_6 calls h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5dclose_f, h5sclose_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f_2 calls h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5dclose_f, h5sclose_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f_5 calls h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5dclose_f, h5sclose_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f_3 calls h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5dclose_f, h5sclose_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f_1 calls h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5dclose_f, h5sclose_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f_7 calls h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5dclose_f, h5sclose_f, h5ltmake_dataset_double_f
h5ltmake_compressed_dataset_double_f_4 calls h5pset_shuffle_f, h5pcreate_f, h5pclose_f, h5dwrite_f, h5pset_deflate_f, h5pset_chunk_f, h5screate_simple_f, h5dcreate_f, h5dclose_f, h5sclose_f, h5ltmake_dataset_double_f
fidasim calls write_birth_profile