xyz_to_cyl – FIDASIM
xyz_to_cyl Subroutine
7 statements
Source File
public subroutine xyz_to_cyl(xyz, cyl)
Convert beam coordinate xyz to cylindrical coordinate cyl
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in), dimension(3) :: xyz
real(kind=Float64), intent(out), dimension(3) :: cyl
Calls
Called by
Contents
Source Code
xyz_to_cyl
Source Code
subroutine xyz_to_cyl(xyz, cyl)
    !+ Convert beam coordinate `xyz` to cylindrical coordinate `cyl`
    real(Float64), dimension(3), intent(in)  :: xyz
    real(Float64), dimension(3), intent(out) :: cyl
    real(Float64), dimension(3) :: uvw
    call xyz_to_uvw(xyz, uvw)
    call uvw_to_cyl(uvw, cyl)
end subroutine xyz_to_cyl
Call graph
xyz_to_cyl calls uvw_to_cyl, xyz_to_uvw
get_passive_grid_indices calls xyz_to_cyl
store_photons calls get_passive_grid_indices
track_cylindrical calls get_passive_grid_indices
make_diagnostic_grids calls track_cylindrical
nbi_spec calls store_photons
store_fida_photons calls store_photons
halo calls store_photons
pfida_f calls track_cylindrical, store_fida_photons
dcx_spec calls store_photons
cold_spec calls store_photons
pfida_mc calls track_cylindrical, store_fida_photons
dcx calls store_photons
store_nbi_photons calls store_photons
halo_spec calls store_photons
ndmc calls store_nbi_photons
fida_mc calls store_fida_photons
fidasim calls make_diagnostic_grids, nbi_spec, halo, pfida_f, dcx_spec, cold_spec, pfida_mc, dcx, halo_spec, ndmc, fida_mc, fida_f
fida_f calls store_fida_photons