"""Public API for reusable Fortran namelist configuration handling."""

from .config import (
    ConfigError,
    as_list,
    normalize_path,
    normalize_string,
    print_config,
    read_namelist,
    reject_unknown_blocks,
    reject_unknown_fields,
    require_boolean,
    require_blocks,
    require_choice,
    require_existing_directory,
    require_existing_file,
    require_fields,
    require_integer,
    require_real,
    require_string,
    validate_schema,
)

__all__ = [
    "ConfigError",
    "as_list",
    "normalize_path",
    "normalize_string",
    "print_config",
    "read_namelist",
    "reject_unknown_blocks",
    "reject_unknown_fields",
    "require_boolean",
    "require_blocks",
    "require_choice",
    "require_existing_directory",
    "require_existing_file",
    "require_fields",
    "require_integer",
    "require_real",
    "require_string",
    "validate_schema",
]
