fidasim – FIDASIM
fidasim Program
349 statements
Source File
Uses
omp_lib
libfida
mpi_utils
hdf5_utils
FIDASIM 3.0.0-dev
Calls
Contents
Variables
arg i narg nthreads max_threads seed
Source Code
fidasim
Variables
Type Attributes Name Initial
character(len=3) :: arg = ''
integer :: i
integer :: narg
integer :: nthreads
integer :: max_threads
integer :: seed
Source Code
program fidasim
    !+ FIDASIM {!../VERSION!}
    use libfida
    use hdf5_utils
#ifdef _OMP
    use omp_lib
#endif
#ifdef _MPI
    use mpi_utils
#endif
    implicit none
    character(3)          :: arg = ''
    integer               :: i,narg,nthreads,max_threads,seed
#ifdef _VERSION
    version = _VERSION
#endif
#ifdef _MPI
    call init_mpi()
    if(my_rank().eq.0) call print_banner()
#else
    call print_banner()
#endif
    narg = command_argument_count()
    if(narg.eq.0) then
#ifdef _MPI
        if(my_rank().eq.0) write(*,'(a)') "usage: mpirun -np [num_processes] ./fidasim namelist_file"
        call cleanup_mpi()
#else
        write(*,'(a)') "usage: ./fidasim namelist_file [num_threads]"
#endif
        stop
    else
        call get_command_argument(1,namelist_file)
    endif
    !! Check if compression is possible
    call check_compression_availability()
    !! measure time
    call date_and_time (values=time_start)
    call read_inputs()
#ifdef _OMP
    max_threads = OMP_get_num_procs()
    if(narg.ge.2) then
        call get_command_argument(2,arg)
        read(arg,'(i3)') nthreads
    else
        nthreads = max_threads
    endif
    max_threads = min(nthreads,max_threads)
    if(inputs%verbose.ge.1) then
        write(*,'(a)') "---- OpenMP settings ----"
        write(*,'(T2,"Number of threads: ",i2)') max_threads
        write(*,*) ''
    endif
    call OMP_set_num_threads(max_threads)
#else
    max_threads = 1
#endif
#ifdef _MPI
    istart = my_rank()+1
    istep = num_ranks()
    if(inputs%verbose.ge.1) then
        write(*,'(a)') "---- MPI settings ----"
        write(*,'(T2,"Number of processes: ",i3)') istep
        write(*,*) ''
    endif
#endif
    !! ----------------------------------------------------------
    !! ------ INITIALIZE THE RANDOM NUMBER GENERATOR  -----------
    !! ----------------------------------------------------------
    allocate(rng(max_threads))
#ifdef _OMP
    do i=1,max_threads
        if(inputs%seed.lt.0) then
            call rng_init(rng(i), inputs%seed)
        else
            call rng_init(rng(i), inputs%seed + i)
        endif
    enddo
#else
    call rng_init(rng(1), inputs%seed)
#endif
    if(inputs%verbose.ge.1) then
        write(*,'(a)') "---- Random Number Generator settings ----"
        write(*,'(T2,"RNG Seed: ",i10)') inputs%seed
        write(*,*) ''
    endif
    !! ----------------------------------------------------------
    !! ------- READ GRIDS, PROFILES, LOS, TABLES, & FBM --------
    !! ----------------------------------------------------------
    call read_plasma()
    call read_tables()
    call read_equilibrium()
    call make_beam_grid()
    if(inputs%calc_beam.ge.1) call read_beam()
    call read_distribution()
    call quasineutrality_check()
    allocate(spec_chords%inter(beam_grid%nx,beam_grid%ny,beam_grid%nz))
    if((inputs%calc_spec.ge.1).or.(inputs%calc_fida_wght.ge.1)) then
        call read_chords()
    endif
    if((inputs%calc_npa.ge.1).or.(inputs%calc_npa_wght.ge.1).or.(inputs%calc_pnpa.ge.1)) then
        call read_npa()
    endif
    if(inputs%calc_cfpd.ge.1) then
        call read_cfpd()
    endif
    call make_diagnostic_grids()
    !! ----------------------------------------------------------
    !! --------------- ALLOCATE THE RESULT ARRAYS ---------------
    !! ----------------------------------------------------------
    if(inputs%calc_birth.ge.1) then
        allocate(birth%dens(3, &
                            beam_grid%nx, &
                            beam_grid%ny, &
                            beam_grid%nz))
        allocate(birth%part(int(3*inputs%n_birth*inputs%n_nbi)))
    endif
    !! Spectra
    if(inputs%calc_spec.ge.1) then
        if(inputs%calc_brems.ge.1) then
            allocate(spec%brems(inputs%nlambda,spec_chords%nchan))
            spec%brems = 0.d0
        endif
        if(inputs%calc_bes.ge.1) then
            allocate(spec%full(n_stark,inputs%nlambda,spec_chords%nchan))
            allocate(spec%half(n_stark,inputs%nlambda,spec_chords%nchan))
            allocate(spec%third(n_stark,inputs%nlambda,spec_chords%nchan))
            spec%full = 0.d0
            spec%half = 0.d0
            spec%third = 0.d0
            allocate(spec%fullstokes(n_stark,4,inputs%nlambda,spec_chords%nchan))
            allocate(spec%halfstokes(n_stark,4,inputs%nlambda,spec_chords%nchan))
            allocate(spec%thirdstokes(n_stark,4,inputs%nlambda,spec_chords%nchan))
            spec%fullstokes = 0.d0
            spec%halfstokes = 0.d0
            spec%thirdstokes = 0.d0
        endif
        if(inputs%calc_dcx.ge.1) then
            allocate(spec%dcx(n_stark,inputs%nlambda,spec_chords%nchan,n_thermal))
            spec%dcx = 0.d0
            allocate(spec%dcxstokes(n_stark,4,inputs%nlambda,spec_chords%nchan,n_thermal))
            spec%dcxstokes = 0.d0
        endif
        if(inputs%calc_halo.ge.1) then
            allocate(spec%halo(n_stark,inputs%nlambda,spec_chords%nchan,n_thermal))
            spec%halo = 0.d0
            allocate(spec%halostokes(n_stark,4,inputs%nlambda,spec_chords%nchan,n_thermal))
            spec%halostokes = 0.d0
        endif
        if(inputs%calc_cold.ge.1) then
            allocate(spec%cold(n_stark,inputs%nlambda,spec_chords%nchan,n_thermal))
            spec%cold = 0.d0
            allocate(spec%coldstokes(n_stark,4,inputs%nlambda,spec_chords%nchan,n_thermal))
            spec%coldstokes = 0.d0
        endif
        if(inputs%calc_fida.ge.1) then
            allocate(spec%fida(n_stark,inputs%nlambda,spec_chords%nchan,particles%nclass))
            spec%fida = 0.d0
            allocate(spec%fidastokes(n_stark,4,inputs%nlambda,spec_chords%nchan,particles%nclass))
            spec%fidastokes = 0.d0
        endif
        if(inputs%calc_pfida.ge.1) then
            allocate(spec%pfida(n_stark,inputs%nlambda,spec_chords%nchan,particles%nclass))
            spec%pfida = 0.d0
            allocate(spec%pfidastokes(n_stark,4,inputs%nlambda,spec_chords%nchan,particles%nclass))
            spec%pfidastokes = 0.d0
        endif
    endif
    if(inputs%calc_res.ge.1) then
        if(inputs%calc_dcx.ge.1) allocate(spatres%dcx(spec_chords%nchan))
        if(inputs%calc_halo.ge.1) allocate(spatres%halo(spec_chords%nchan))
        if(inputs%calc_fida.ge.1) allocate(spatres%fida(spec_chords%nchan))
        if(inputs%calc_pfida.ge.1) allocate(spatres%pfida(spec_chords%nchan))
    endif
    if(inputs%calc_npa.ge.1)then
        npa%nchan = npa_chords%nchan
        allocate(npa%part(npa%nmax))
        if(inputs%dist_type.eq.1) then
            npa%nenergy = fbm%nenergy
            allocate(npa%energy(npa%nenergy))
            npa%energy = fbm%energy
        else
            allocate(npa%energy(npa%nenergy))
            do i=1,npa%nenergy
                npa%energy(i)=real(i-0.5)
            enddo
        endif
        allocate(npa%flux(npa%nenergy,npa%nchan,particles%nclass))
        npa%flux = 0.0
    endif
    if(inputs%calc_pnpa.ge.1)then
        pnpa%nchan = npa_chords%nchan
        allocate(pnpa%part(pnpa%nmax))
        if(inputs%dist_type.eq.1) then
            pnpa%nenergy = fbm%nenergy
            allocate(pnpa%energy(pnpa%nenergy))
            pnpa%energy = fbm%energy
        else
            allocate(pnpa%energy(pnpa%nenergy))
            do i=1,pnpa%nenergy
                pnpa%energy(i)=real(i-0.5)
            enddo
        endif
        allocate(pnpa%flux(pnpa%nenergy,pnpa%nchan,particles%nclass))
        pnpa%flux = 0.0
    endif
    if(inputs%calc_neutron.ge.1)then
        allocate(neutron%rate(particles%nclass))
        neutron%rate = 0.d0
    endif
    !! -----------------------------------------------------------------------
    !! --------------- CALCULATE/LOAD the BEAM and HALO DENSITY---------------
    !! -----------------------------------------------------------------------
    if(inputs%load_neutrals.eq.1) then
        call read_neutrals()
        if(inputs%calc_bes.ge.1) then
            if(inputs%verbose.ge.1) then
                write(*,*) 'nbi:     ' , time_string(time_start)
            endif
            call nbi_spec()
            if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
        endif
        if(inputs%calc_dcx.ge.1) then
            if(inputs%verbose.ge.1) then
                write(*,*) 'dcx:     ' , time_string(time_start)
            endif
            call dcx_spec()
            if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
        endif
        if(inputs%calc_halo.ge.1) then
            if(inputs%verbose.ge.1) then
                write(*,*) 'halo:    ' , time_string(time_start)
            endif
            call halo_spec()
            if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
        endif
    else
        if(inputs%calc_beam.ge.1) then
            !! ----------- BEAM NEUTRALS ---------- !!
            if(inputs%calc_nbi_dens.ge.1) then
                if(inputs%verbose.ge.1) then
                    write(*,*) 'nbi:     ' , time_string(time_start)
                endif
                call ndmc()
                if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
                if(inputs%calc_birth.eq.1)then
                    if(inputs%verbose.ge.1) then
                        write(*,*) 'write birth:    ' , time_string(time_start)
                    endif
                    call write_birth_profile()
                    if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
                endif
            endif
            !! ---------- DCX (Direct charge exchange) ---------- !!
            if(inputs%calc_dcx_dens.ge.1) then
                if(inputs%verbose.ge.1) then
                    write(*,*) 'dcx:     ' , time_string(time_start)
                endif
                call dcx()
                if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
            endif
            !! ---------- HALO ---------- !!
            if(inputs%calc_halo_dens.ge.1) then
                if(inputs%verbose.ge.1) then
                    write(*,*) 'halo:    ' , time_string(time_start)
                endif
                call halo()
                if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
            endif
            !! ---------- WRITE NEUTRALS ---------- !!
            if(inputs%verbose.ge.1) then
                write(*,*) 'write neutrals:    ' , time_string(time_start)
            endif
#ifdef _MPI
            if(my_rank().eq.0) call write_neutrals()
#else
            call write_neutrals()
#endif
            if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
        endif
    endif
    !! -----------------------------------------------------------------------
    !!------------------------------ COLD D-ALPHA ----------------------------
    !! -----------------------------------------------------------------------
    if(inputs%calc_cold.ge.1) then
        if(inputs%verbose.ge.1) then
            write(*,*) 'cold:    ' ,time_string(time_start)
        endif
        call cold_spec()
        if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
    endif
    !! -----------------------------------------------------------------------
    !!----------------------------- BREMSSTRAHLUNG ---------------------------
    !! -----------------------------------------------------------------------
    if(inputs%calc_brems.ge.1) then
        if(inputs%verbose.ge.1) then
            write(*,*) 'bremsstrahlung:    ' ,time_string(time_start)
        endif
        call bremsstrahlung()
        if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
    endif
    !! -----------------------------------------------------------------------
    !! --------------------- CALCULATE the FIDA RADIATION --------------------
    !! -----------------------------------------------------------------------
    if(inputs%calc_fida.ge.1)then
        if(inputs%verbose.ge.1) then
            write(*,*) 'fida:    ' ,time_string(time_start)
        endif
        if(inputs%dist_type.eq.1) then
            call fida_f()
        else
            call fida_mc()
        endif
        if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
    endif
    if(inputs%calc_pfida.ge.1)then
        if(inputs%verbose.ge.1) then
            write(*,*) 'pfida:   ' ,time_string(time_start)
        endif
        if(inputs%dist_type.eq.1) then
            call pfida_f()
        else
            call pfida_mc()
        endif
        if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
    endif
    if(inputs%calc_spec.ge.1) then
        if(inputs%verbose.ge.1) then
            write(*,*) 'write spectra:    ' , time_string(time_start)
        endif
#ifdef _MPI
        if(my_rank().eq.0) call write_spectra()
#else
        call write_spectra()
#endif
        if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
    endif
    !! -----------------------------------------------------------------------
    !! ----------------------- CALCULATE the NPA FLUX ------------------------
    !! -----------------------------------------------------------------------
    if(inputs%calc_npa.ge.1)then
        if(inputs%verbose.ge.1) then
            write(*,*) 'npa:     ' ,time_string(time_start)
        endif
        if(inputs%dist_type.eq.1) then
            call npa_f()
        else
            call npa_mc()
        endif
        if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
    endif
    if(inputs%calc_pnpa.ge.1)then
        if(inputs%verbose.ge.1) then
            write(*,*) 'pnpa:     ' ,time_string(time_start)
        endif
        if(inputs%dist_type.eq.1) then
            call pnpa_f()
        else
            call pnpa_mc()
        endif
        if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
    endif
    if((inputs%calc_npa.ge.1).or.(inputs%calc_pnpa.ge.1)) then
        if(inputs%verbose.ge.1) then
            write(*,*) 'write npa:    ' , time_string(time_start)
        endif
        call write_npa()
        if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
    endif
    !! -------------------------------------------------------------------
    !! ------------------- Calculation of neutron flux -------------------
    !! -------------------------------------------------------------------
    if(inputs%calc_neutron.ge.1) then
        if(inputs%verbose.ge.1) then
            write(*,*) 'neutron rate:    ', time_string(time_start)
        endif
        if(inputs%dist_type.eq.1) then
            call neutron_f()
        else
            call neutron_mc()
        endif
        if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
    endif
    if(inputs%calc_cfpd.ge.1) then
        if(inputs%verbose.ge.1) then
            write(*,*) 'charged fusion products:    ', time_string(time_start)
        endif
        call cfpd_f()
        if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
    endif
    !! -------------------------------------------------------------------
    !! ----------- Calculation of weight functions -----------------------
    !! -------------------------------------------------------------------
    if(inputs%calc_fida_wght.ge.1) then
        if(inputs%verbose.ge.1) then
            write(*,*) 'fida weight function:    ', time_string(time_start)
        endif
        if(inputs%calc_fida_wght.eq.1) then
            call fida_weights_los()
        else
            call fida_weights_mc()
        endif
        if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
    endif
    if(inputs%calc_npa_wght.ge.1) then
        if(inputs%verbose.ge.1) then
            write(*,*) 'npa weight function:    ', time_string(time_start)
        endif
        call npa_weights()
        if(inputs%verbose.ge.1) write(*,'(30X,a)') ''
    endif
#ifdef _MPI
    call cleanup_mpi()
#endif
    if(inputs%verbose.ge.1) then
        write(*,*) 'END: hour:minute:second ', time_string(time_start)
    endif
end program fidasim
Call graph
fidasim calls time_string, dcx_spec, pnpa_mc, pnpa_f, dcx, omp_get_num_procs, rng_init, quasineutrality_check, halo_spec, pfida_mc, npa_weights, make_beam_grid, read_chords, read_inputs, my_rank, read_distribution, read_neutrals, neutron_f, fida_weights_los, fida_f, print_banner, read_cfpd, cfpd_f, init_mpi, check_compression_availability, read_npa, write_spectra, write_npa, neutron_mc, cold_spec, npa_f, fida_mc, pfida_f, num_ranks, read_plasma, ndmc, bremsstrahlung, cleanup_mpi, omp_set_num_threads, write_birth_profile, write_neutrals, read_tables, read_equilibrium, read_beam, nbi_spec, halo, npa_mc, fida_weights_mc, make_diagnostic_grids
dcx_spec calls mc_halo, get_plasma, randu, store_photons, parallel_sum, in_plasma, ind2sub
pnpa_mc calls attenuate, gyro_trajectory, bt_cx_rates, hit_npa_detector, npa_gyro_range, get_plasma, gyro_surface, randu, get_fields, parallel_sum, uvw_to_xyz, store_npa
pnpa_f calls attenuate, gyro_trajectory, bt_cx_rates, hit_npa_detector, npa_gyro_range, get_plasma, gyro_surface, get_nlaunch_pass_grid, mc_fastion_pass_grid, parallel_sum, ind2sub, store_npa
dcx calls mc_halo, track, get_total_cx_rate, store_neutrals, get_plasma, store_photon_birth, parallel_merge_reservoirs, mc_beam_grid, get_nlaunch, parallel_merge_populations, store_photons, colrad, parallel_sum, init_neutral_population, ind2sub
rng_init calls my_rank, rng_seed
halo_spec calls mc_halo, get_plasma, randu, store_photons, parallel_sum, in_plasma, ind2sub
pfida_mc calls gyro_correction, bt_cx_rates, store_fida_photons, get_plasma, store_photon_birth, track_cylindrical, parallel_merge_reservoirs, randu, get_fields, colrad, parallel_sum
npa_weights calls time_string, my_rank, attenuate, get_total_cx_rate, hit_npa_detector, write_npa_weights, get_fields, get_ep_denf, parallel_sum, gyro_step
make_beam_grid calls tb_zyx, in_plasma
read_chords calls h5gopen_f, h5ltread_dataset_string_f, h5ltread_dataset_int_scalar_f, h5ltread_dataset_double_f, h5fclose_f, h5close_f, h5ltpath_valid_f, h5open_f, h5gclose_f, uvw_to_xyz, h5fopen_f
read_inputs calls my_rank, identify_transition, rng_seed
read_distribution calls read_mc, h5ltread_dataset_int_scalar_f, read_f, h5fclose_f, h5close_f, h5open_f, h5fopen_f
read_neutrals calls h5gopen_f, read_neutral_population, h5ltread_dataset_int_scalar_f, h5fclose_f, h5close_f, h5ltpath_valid_f, h5open_f, h5gclose_f, h5fopen_f
neutron_f calls time_string, my_rank, gyro_correction, get_plasma, get_dd_rate, get_fields, parallel_sum, store_neutrons, write_neutrons
fida_weights_los calls time_string, my_rank, store_fw_photons_at_chan, track, bt_cx_rates, grid_intersect, get_plasma, get_fields, bb_cx_rates, get_ep_denf, colrad, write_fida_weights, parallel_sum, in_plasma, pitch_to_vec
fida_f calls track, gyro_correction, get_total_cx_rate, store_fida_photons, get_plasma, store_photon_birth, parallel_merge_reservoirs, get_nlaunch, colrad, parallel_sum, ind2sub, mc_fastion
read_cfpd calls h5gopen_f, h5ltread_dataset_string_f, h5ltread_dataset_int_scalar_f, h5ltread_dataset_double_f, h5fclose_f, h5close_f, h5ltpath_valid_f, h5open_f, h5gclose_f, h5fopen_f
cfpd_f calls time_string, my_rank, get_ddpt_anisotropy, get_plasma, get_pgyro, get_dd_rate, convert_sightline_to_xyz, get_fields, get_ep_denf, parallel_sum, gyro_step, write_cfpd_weights, pitch_to_vec
init_mpi calls mpi_init, mpi_init_thread, mpi_comm_rank, mpi_comm_size
check_compression_availability calls h5zget_filter_info_f, h5zfilter_avail_f, h5close_f, h5open_f
read_npa calls h5gopen_f, h5ltread_dataset_string_f, h5ltread_dataset_int_scalar_f, h5ltread_dataset_double_f, h5fclose_f, h5ltread_dataset_int_f, h5close_f, h5ltpath_valid_f, h5open_f, h5gclose_f, uvw_to_xyz, h5fopen_f, plane_basis
write_spectra calls h5fclose_f, h5close_f, h5fcreate_f, h5ltmake_compressed_dataset_double_f, h5ltset_attribute_string_f, h5open_f, h5gclose_f, h5gcreate_f, h5ltmake_dataset_int_f
write_npa calls my_rank, num_ranks, h5fclose_f, h5ltmake_compressed_dataset_int_f, h5close_f, h5fcreate_f, h5ltmake_compressed_dataset_double_f, h5ltset_attribute_string_f, parallel_sum, h5open_f, h5gclose_f, h5gcreate_f, h5ltmake_dataset_int_f
neutron_mc calls time_string, my_rank, gyro_correction, get_plasma, get_dd_rate, get_fields, parallel_sum, store_neutrons, write_neutrons
cold_spec calls mc_halo, get_plasma, store_photons, parallel_sum, cyl_to_uvw, ind2sub
npa_f calls attenuate, gyro_trajectory, get_total_cx_rate, hit_npa_detector, npa_gyro_range, get_plasma, gyro_surface, get_nlaunch, parallel_sum, ind2sub, mc_fastion, store_npa, get_indices
fida_mc calls track, gyro_correction, get_total_cx_rate, store_fida_photons, get_plasma, store_photon_birth, parallel_merge_reservoirs, randu, get_fields, colrad, parallel_sum, uvw_to_xyz
pfida_f calls gyro_correction, bt_cx_rates, store_fida_photons, get_plasma, store_photon_birth, track_cylindrical, parallel_merge_reservoirs, get_nlaunch_pass_grid, mc_fastion_pass_grid, colrad, parallel_sum, ind2sub
read_plasma calls h5gopen_f, h5ltread_dataset_int_scalar_f, h5ltread_dataset_double_f, h5fclose_f, h5close_f, h5open_f, h5gclose_f, h5fopen_f
ndmc calls track, store_nbi_photons, store_neutrals, get_plasma, randind, randu, mc_nbi, parallel_merge_populations, get_fields, colrad, parallel_sum, init_neutral_population, store_births, gyro_step
bremsstrahlung calls get_plasma, randu, line_basis, parallel_sum
cleanup_mpi calls mpi_barrier, mpi_finalize
write_birth_profile calls my_rank, num_ranks, h5fclose_f, h5ltmake_compressed_dataset_int_f, h5close_f, h5fcreate_f, h5ltmake_compressed_dataset_double_f, write_beam_grid, h5ltset_attribute_string_f, parallel_sum, xyz_to_uvw, h5open_f, h5ltmake_dataset_int_f
write_neutrals calls write_neutral_population, h5fclose_f, h5close_f, h5fcreate_f, write_beam_grid, h5ltset_attribute_string_f, h5open_f, h5gclose_f, h5gcreate_f
read_tables calls read_atomic_rate, h5ltread_dataset_int_scalar_f, h5ltread_dataset_double_f, h5fclose_f, read_nuclear_rates, h5close_f, read_atomic_transitions, h5open_f, h5fopen_f, read_atomic_cross
read_equilibrium calls mc_halo, h5gopen_f, deriv, h5ltread_dataset_int_scalar_f, h5ltread_dataset_double_f, h5fclose_f, h5ltread_dataset_int_f, h5close_f, h5ltpath_valid_f, colrad, h5open_f, h5gclose_f, h5fopen_f, ind2sub
read_beam calls h5gopen_f, h5ltread_dataset_string_f, h5ltread_dataset_int_scalar_f, tb_zyx, h5ltread_dataset_double_f, h5fclose_f, h5ltread_dataset_int_f, h5close_f, h5ltpath_valid_f, h5open_f, h5gclose_f, uvw_to_xyz, h5fopen_f, h5ltread_dataset_double_scalar_f
nbi_spec calls mc_nbi_cell, randu, store_photons, parallel_sum, in_plasma, ind2sub
halo calls mc_halo, track, neutral_cx_rate, get_plasma, store_photon_birth, parallel_merge_reservoirs, mc_beam_grid, get_nlaunch, parallel_merge_populations, free_neutral_population, store_photons, merge_neutral_populations, colrad, parallel_sum, init_neutral_population, ind2sub, update_neutrals
npa_mc calls attenuate, gyro_trajectory, get_total_cx_rate, hit_npa_detector, npa_gyro_range, gyro_surface, randu, get_fields, parallel_sum, uvw_to_xyz, store_npa, get_indices
fida_weights_mc calls time_string, my_rank, track, gyro_correction, get_total_cx_rate, get_plasma, randind, randu, get_nlaunch, get_fields, get_ep_denf, colrad, write_fida_weights, parallel_sum, store_fw_photons, ind2sub
make_diagnostic_grids calls track, make_passive_grid, grid_intersect, hit_npa_detector, track_cylindrical, randu, line_basis, get_fields, parallel_sum, ind2sub
mc_halo calls randn
store_fw_photons_at_chan calls spectrum
attenuate calls get_plasma, colrad
track calls get_plasma, get_fields, in_plasma, get_indices, doppler_stark
gyro_correction calls randu, gyro_step, pitch_to_vec
neutral_cx_rate calls bb_cx_rates
read_mc calls h5ltread_dataset_int_scalar_f, h5ltread_dataset_double_f, h5ltread_dataset_int_f, h5ltpath_valid_f, uvw_to_xyz, in_plasma, circle_grid_intersect, in_grid
get_ddpt_anisotropy calls interpol_coeff
read_neutral_population calls h5gopen_f, h5ltread_dataset_int_scalar_f, h5ltread_dataset_double_f, h5ltread_dataset_int_f, init_neutral_population, h5gclose_f, ind2sub, init_reservoir
bt_cx_rates calls interpol_coeff
store_nbi_photons calls store_photons
make_passive_grid calls xyz_to_uvw, get_plasma_extrema
get_total_cx_rate calls neutral_cx_rate
grid_intersect calls in_passive_grid
read_atomic_rate calls h5ltread_dataset_int_scalar_f, h5ltread_dataset_double_f, h5ltpath_valid_f, h5ltread_dataset_double_scalar_f, h5ltget_dataset_ndims_f
store_neutrals calls update_neutrals
mc_nbi_cell calls randu
hit_npa_detector calls in_boundary, line_plane_intersect
npa_gyro_range calls gyro_range, approx_eq
h5ltread_dataset_int_scalar_f calls h5ltread_dataset_int_f
store_fida_photons calls store_photons
get_plasma calls xyz_to_uvw, uvw_to_xyz, in_plasma, get_position
get_pgyro calls cross_product
get_dd_rate calls interpol_coeff
read_f calls h5ltread_dataset_int_scalar_f, h5ltread_dataset_double_f, h5ltpath_valid_f
store_photon_birth calls get_indices, get_passive_grid_indices, update_reservoir
track_cylindrical calls get_plasma, get_fields, cyl_to_uvw, in_plasma, plane_basis, get_passive_grid_indices, line_cylinder_intersect, doppler_stark, line_plane_intersect
parallel_merge_reservoirs calls my_rank, num_ranks, parallel_sum, init_reservoir, merge_reservoirs
write_neutral_population calls h5ltmake_compressed_dataset_int_f, h5ltmake_compressed_dataset_double_f, h5ltset_attribute_string_f, h5gclose_f, h5gcreate_f, ind2sub, h5ltmake_dataset_int_f
h5ltmake_compressed_dataset_int_f calls h5ltmake_compressed_dataset_int_f_1, h5ltmake_compressed_dataset_int_f_2, h5ltmake_compressed_dataset_int_f_3, h5ltmake_compressed_dataset_int_f_4, h5ltmake_compressed_dataset_int_f_6, h5ltmake_compressed_dataset_int_f_7, h5ltmake_compressed_dataset_int_f_5
read_nuclear_rates calls h5ltread_dataset_int_scalar_f, h5ltread_dataset_double_f, h5ltpath_valid_f, h5ltread_dataset_double_scalar_f
convert_sightline_to_xyz calls uvw_to_xyz
mc_beam_grid calls randu
get_nlaunch calls rng_init, ind2sub, randind_cdf, cumsum
mc_nbi calls grid_intersect, randu, in_plasma, randn
parallel_merge_populations calls parallel_merge_reservoirs, parallel_sum, ind2sub
line_basis calls tb_zyx
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_6, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_4, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_2
write_npa_weights calls h5fclose_f, h5close_f, h5fcreate_f, h5ltmake_compressed_dataset_double_f, write_beam_grid, h5ltset_attribute_string_f, h5open_f, h5ltmake_dataset_int_f
get_nlaunch_pass_grid calls rng_init, ind2sub, randind_cdf, cumsum
write_beam_grid calls h5ltmake_compressed_dataset_double_f, h5ltset_attribute_string_f, xyz_to_uvw, h5gclose_f, h5gcreate_f, h5ltmake_dataset_int_f
store_photons calls get_fields, uvw_to_xyz, get_indices, get_passive_grid_indices, spectrum
get_fields calls xyz_to_uvw, uvw_to_xyz, in_plasma, calc_perp_vectors, get_position
bb_cx_rates calls interpol_coeff
mc_fastion_pass_grid calls randind, randu, get_fields, get_distribution, mc_passive_grid
get_ep_denf calls xyz_to_uvw, interpol, get_position
read_atomic_transitions calls h5ltread_dataset_int_scalar_f, h5ltread_dataset_double_f, h5ltpath_valid_f, h5ltread_dataset_double_scalar_f, h5ltget_dataset_ndims_f
merge_neutral_populations calls ind2sub, merge_reservoirs
colrad calls get_rate_matrix, eigen, linsolve
write_fida_weights calls h5fclose_f, h5close_f, h5fcreate_f, h5ltmake_compressed_dataset_double_f, h5ltset_attribute_string_f, h5open_f, h5ltmake_dataset_int_f
parallel_sum calls parallel_sum_i3, parallel_sum_d0, parallel_sum_d1, parallel_sum_d5, parallel_sum_i1, parallel_sum_i0, parallel_sum_i2, parallel_sum_d4, parallel_sum_d3, parallel_sum_d2
store_fw_photons calls store_fw_photons_at_chan, get_fields, get_indices
gyro_step calls cross_product
write_cfpd_weights calls h5fclose_f, h5close_f, h5fcreate_f, h5ltmake_compressed_dataset_double_f, h5ltset_attribute_string_f, h5open_f, h5ltmake_dataset_int_f
in_plasma calls xyz_to_uvw, cyl_to_uvw, interpol_coeff
mc_fastion calls randind, randu, mc_beam_grid, get_fields, get_distribution
plane_basis calls cross_product
read_atomic_cross calls h5ltread_dataset_int_scalar_f, h5ltread_dataset_double_f, h5ltpath_valid_f, h5ltread_dataset_double_scalar_f
store_npa calls get_fields, xyz_to_uvw
h5ltread_dataset_double_scalar_f calls h5ltread_dataset_double_f
update_neutrals calls update_reservoir
write_neutrons calls h5fclose_f, h5close_f, h5fcreate_f, h5ltmake_compressed_dataset_double_f, h5ltset_attribute_string_f, h5open_f, h5ltmake_dataset_int_f, h5ltmake_dataset_double_f
get_passive_grid_indices calls xyz_to_cyl
h5ltmake_compressed_dataset_int_f_1 calls h5ltmake_dataset_int_f, h5sclose_f, chunk_size, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
h5ltmake_compressed_dataset_int_f_2 calls h5ltmake_dataset_int_f, h5sclose_f, chunk_size, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
parallel_sum_i3 calls parallel_sum_i1, mpi_allreduce
h5ltmake_compressed_dataset_int_f_3 calls h5ltmake_dataset_int_f, h5sclose_f, chunk_size, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
get_distribution calls xyz_to_uvw, interpol, get_position
h5ltmake_compressed_dataset_int_f_4 calls h5ltmake_dataset_int_f, h5sclose_f, chunk_size, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
h5ltmake_compressed_dataset_double_f_1 calls h5ltmake_dataset_double_f, h5sclose_f, chunk_size, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
init_reservoir calls randu
circle_grid_intersect calls grid_intersect, approx_eq, in_grid
gyro_range calls in_boundary, line_plane_intersect, in_gyro_surface, line_gyro_surface_intersect, boundary_edge, gyro_surface_coordinates
parallel_sum_d0 calls mpi_allreduce
parallel_sum_d1 calls parallel_sum_d1, mpi_allreduce
h5ltmake_compressed_dataset_double_f_6 calls h5ltmake_dataset_double_f, h5sclose_f, chunk_size, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
in_grid calls approx_le, approx_ge
in_passive_grid calls approx_le, approx_ge, uvw_to_cyl
h5ltmake_compressed_dataset_double_f_5 calls h5ltmake_dataset_double_f, h5sclose_f, chunk_size, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
parallel_sum_d5 calls parallel_sum_d1, mpi_allreduce
h5ltmake_compressed_dataset_double_f_7 calls h5ltmake_dataset_double_f, h5sclose_f, chunk_size, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
parallel_sum_i1 calls parallel_sum_i1, mpi_allreduce
parallel_sum_i0 calls mpi_allreduce
merge_reservoirs calls randu, init_reservoir, update_reservoir, float
h5ltmake_compressed_dataset_double_f_4 calls h5ltmake_dataset_double_f, h5sclose_f, chunk_size, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
parallel_sum_i2 calls parallel_sum_i1, mpi_allreduce
update_reservoir calls randind, randu, init_reservoir
get_rate_matrix calls interpol_coeff
eigen calls balback, balance, elmhes, hqr2, elmtrans
h5ltmake_compressed_dataset_int_f_6 calls h5ltmake_dataset_int_f, h5sclose_f, chunk_size, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
h5ltmake_compressed_dataset_int_f_7 calls h5ltmake_dataset_int_f, h5sclose_f, chunk_size, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
h5ltmake_compressed_dataset_double_f_3 calls h5ltmake_dataset_double_f, h5sclose_f, chunk_size, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
parallel_sum_d4 calls parallel_sum_d1, mpi_allreduce
linsolve calls matinv, dgetrf, dgetrs
parallel_sum_d3 calls parallel_sum_d1, mpi_allreduce
get_position calls cyl_to_xyz
h5ltmake_compressed_dataset_double_f_2 calls h5ltmake_dataset_double_f, h5sclose_f, chunk_size, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
get_plasma_extrema calls in_plasma, uvw_to_cyl
h5ltmake_compressed_dataset_int_f_5 calls h5ltmake_dataset_int_f, h5sclose_f, chunk_size, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
mc_passive_grid calls randu, cyl_to_uvw
parallel_sum_d2 calls parallel_sum_d1, mpi_allreduce
approx_le calls approx_eq
matinv calls ludcmp, lubksb
cyl_to_xyz calls cyl_to_uvw, uvw_to_xyz
approx_ge calls approx_eq
balback calls rswap
balance calls rswap
elmhes calls rswap
xyz_to_cyl calls xyz_to_uvw, uvw_to_cyl
hqr2 calls hqrvec
ludcmp calls swap, outerprod
hqrvec calls comdiv