generate_tables – FIDASIM
generate_tables Program
110 statements
Source File
Uses
utilities
atomic_tables
HDF5
H5LT
hdf5_utils
omp_lib
Tabulates cross sections and reaction rates and writes them to a HDF5 file
Calls
Contents
Variables
namelist_file arg tables_file n_max m_max time_start hour minu sec argc max_threads nthreads fid gid error exis
Variables
Type Attributes Name Initial
character(len=200) :: namelist_file
character(len=3) :: arg
character(len=200) :: tables_file = ''
integer :: n_max
integer :: m_max
integer, dimension(8) :: time_start
integer :: hour
integer :: minu
integer :: sec
integer :: argc
integer :: max_threads
integer :: nthreads
integer(kind=HID_T) :: fid
integer(kind=HID_T) :: gid
integer :: error
logical :: exis
Call graph
generate_tables calls time_string, write_bt_d_he3, write_einstein, omp_get_num_procs, write_bt_d_d, h5close_f, write_bb_h_h, my_rank, write_bt_h_e, h5open_f, h5fcreate_f, write_bb_h_e, h5gclose_f, write_bt_h_h, write_bb_h_aq, init_mpi, check_compression_availability, h5gcreate_f, print_default_namelist, write_bb_d_he3, write_bt_h_aq, num_ranks, omp_set_num_threads, h5fclose_f, cleanup_mpi, write_bb_d_d, h5ltset_attribute_string_f
write_bt_d_he3 calls h5gclose_f, h5gcreate_f, h5ltset_attribute_string_f, parallel_sum, h5ltmake_dataset_double_f, h5ltmake_compressed_dataset_double_f, bt_maxwellian, h5ltmake_dataset_int_f
write_einstein calls h5gclose_f, h5gcreate_f, h5ltset_attribute_string_f, h5ltmake_compressed_dataset_double_f, h5ltmake_dataset_int_f
write_bt_d_d calls h5gclose_f, h5gcreate_f, h5ltset_attribute_string_f, parallel_sum, h5ltmake_dataset_double_f, h5ltmake_compressed_dataset_double_f, bt_maxwellian, h5ltmake_dataset_int_f
write_bb_h_h calls h5gclose_f, h5gcreate_f, h5ltset_attribute_string_f, p_cx, parallel_sum, h5ltmake_dataset_double_f, p_excit, p_ioniz, h5ltmake_compressed_dataset_double_f, h5ltmake_dataset_int_f
write_bt_h_e calls h5gclose_f, h5gcreate_f, h5ltset_attribute_string_f, parallel_sum, h5ltmake_dataset_double_f, h5ltmake_compressed_dataset_double_f, bt_maxwellian, h5ltmake_dataset_int_f
write_bb_h_e calls h5gclose_f, h5gcreate_f, h5ltset_attribute_string_f, e_ioniz, parallel_sum, h5ltmake_dataset_double_f, h5ltmake_compressed_dataset_double_f, e_excit, h5ltmake_dataset_int_f
write_bt_h_h calls h5gclose_f, h5gcreate_f, h5ltset_attribute_string_f, parallel_sum, h5ltmake_dataset_double_f, h5ltmake_compressed_dataset_double_f, bt_maxwellian, h5ltmake_dataset_int_f
write_bb_h_aq calls h5gclose_f, h5gcreate_f, h5ltset_attribute_string_f, parallel_sum, h5ltmake_dataset_double_f, h5ltmake_compressed_dataset_double_f, aq_cx, aq_ioniz, aq_excit, h5ltmake_dataset_int_f
init_mpi calls mpi_init, mpi_comm_rank, mpi_init_thread, mpi_comm_size
check_compression_availability calls h5close_f, h5open_f, h5zfilter_avail_f, h5zget_filter_info_f
write_bb_d_he3 calls h5gclose_f, h5gcreate_f, h5ltset_attribute_string_f, d_he3_fusion, parallel_sum, h5ltmake_dataset_double_f, h5ltmake_compressed_dataset_double_f, h5ltmake_dataset_int_f
write_bt_h_aq calls h5gclose_f, h5gcreate_f, h5ltset_attribute_string_f, parallel_sum, h5ltmake_dataset_double_f, h5ltmake_compressed_dataset_double_f, bt_maxwellian, h5ltmake_dataset_int_f
cleanup_mpi calls mpi_barrier, mpi_finalize
write_bb_d_d calls h5gclose_f, h5gcreate_f, h5ltset_attribute_string_f, parallel_sum, h5ltmake_dataset_double_f, h5ltmake_compressed_dataset_double_f, h5ltmake_dataset_int_f, d_d_fusion_he, d_d_fusion_t
e_ioniz calls e_ioniz_n
p_cx calls p_cx_n
parallel_sum calls parallel_sum_i3, parallel_sum_d0, parallel_sum_d1, parallel_sum_d5, parallel_sum_i1, parallel_sum_i0, parallel_sum_i2, parallel_sum_d4, parallel_sum_d3, parallel_sum_d2
p_excit calls p_excit_n
p_ioniz calls p_ioniz_n
h5ltmake_compressed_dataset_double_f calls h5ltmake_compressed_dataset_double_f_1, h5ltmake_compressed_dataset_double_f_5, h5ltmake_compressed_dataset_double_f_7, h5ltmake_compressed_dataset_double_f_4, h5ltmake_compressed_dataset_double_f_3, h5ltmake_compressed_dataset_double_f_2, h5ltmake_compressed_dataset_double_f_6
aq_cx calls aq_cx_n
aq_ioniz calls aq_ioniz_n
aq_excit calls aq_excit_n
e_excit calls e_excit_n
bt_maxwellian calls bt_maxwellian_q_n, bt_maxwellian_eb, bt_maxwellian_n, bt_maxwellian_q_n_m, bt_maxwellian_n_m
parallel_sum_i3 calls parallel_sum_i1, mpi_allreduce
p_excit_n calls p_excit_2_janev, p_excit_3_janev, p_excit_1_janev
aq_ioniz_n calls aq_ioniz_n_janev, c6_ioniz_1_janev, b5_ioniz_1_janev
p_cx_n calls p_cx_3_4_adas, p_cx_janev, m_spread, p_cx_2, p_cx_1_4_adas, p_cx_3, p_cx_1, p_cx_3_5_adas
p_ioniz_n calls p_ioniz_3_omullane, p_ioniz_2_omullane, p_ioniz_4_omullane, p_ioniz_5_omullane, p_ioniz_1_janev
h5ltmake_compressed_dataset_double_f_1 calls h5ltmake_dataset_double_f, chunk_size, h5sclose_f, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
bt_maxwellian_q_n calls simpsons_rule
parallel_sum_d0 calls mpi_allreduce
parallel_sum_d1 calls parallel_sum_d1, mpi_allreduce
bt_maxwellian_eb calls simpsons_rule
bt_maxwellian_n calls simpsons_rule
parallel_sum_d5 calls parallel_sum_d1, mpi_allreduce
h5ltmake_compressed_dataset_double_f_5 calls h5ltmake_dataset_double_f, chunk_size, h5sclose_f, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
e_excit_n calls e_excit_1_janev, e_excit_2_3_janev, e_excit_f
parallel_sum_i1 calls parallel_sum_i1, mpi_allreduce
parallel_sum_i0 calls mpi_allreduce
h5ltmake_compressed_dataset_double_f_7 calls h5ltmake_dataset_double_f, chunk_size, h5sclose_f, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
parallel_sum_i2 calls parallel_sum_i1, mpi_allreduce
h5ltmake_compressed_dataset_double_f_4 calls h5ltmake_dataset_double_f, chunk_size, h5sclose_f, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
bt_maxwellian_q_n_m calls simpsons_rule
parallel_sum_d4 calls parallel_sum_d1, mpi_allreduce
h5ltmake_compressed_dataset_double_f_3 calls h5ltmake_dataset_double_f, chunk_size, h5sclose_f, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
parallel_sum_d3 calls parallel_sum_d1, mpi_allreduce
aq_cx_n calls aq_cx_n_janev, aq_cx_n_adas
bt_maxwellian_n_m calls simpsons_rule
e_ioniz_n calls e_ioniz_1_janev, e_ioniz_2_janev, e_ioniz_3_janev
h5ltmake_compressed_dataset_double_f_2 calls h5ltmake_dataset_double_f, chunk_size, h5sclose_f, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
aq_excit_n calls aq_excit_n_janev, aq_excit_3_janev, aq_excit_1_janev, aq_excit_2_janev
parallel_sum_d2 calls parallel_sum_d1, mpi_allreduce
h5ltmake_compressed_dataset_double_f_6 calls h5ltmake_dataset_double_f, chunk_size, h5sclose_f, h5pclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5dclose_f, h5dwrite_f, h5pset_chunk_f, h5dcreate_f
aq_cx_n_janev calls b5_cx_1_janev, c6_cx_1_janev
p_cx_janev calls p_cx_n_janev, p_cx_3_janev, p_cx_1_janev, p_cx_2_janev
e_excit_1_janev calls e_excit_f, e_excit_1_4_janev, e_excit_1_3_janev, e_excit_1_2_janev, e_excit_1_5_janev
aq_cx_n_adas calls b5_cx_2_adas, c6_cx_1_adas, c6_cx_2_adas, b5_cx_1_adas, c6_cx_3_adas
p_excit_2_janev calls p_excit_2_6_janev, p_excit_2_9_janev, p_excit_2_8_janev, p_excit_2_7_janev, p_excit_2_3_janev, p_excit_2_4_janev, p_excit_2_5_janev, p_excit_2_10_janev
aq_excit_3_janev calls aq_excit_3_4_janev, aq_excit_3_7_janev, aq_excit_3_8_janev, aq_excit_3_6_janev, aq_excit_3_5_janev, aq_excit_3_10_janev, aq_excit_3_9_janev
p_cx_2 calls p_cx_janev, m_spread, p_cx_2_3_adas, p_cx_1_2_adas, p_cx_2_2_adas
p_excit_3_janev calls p_excit_3_10_janev, p_excit_3_5_janev, p_excit_3_9_janev, p_excit_3_7_janev, p_excit_3_4_janev, p_excit_3_8_janev, p_excit_3_6_janev
aq_excit_1_janev calls aq_excit_1_4_janev, aq_excit_1_5_janev, aq_excit_1_3_janev, aq_excit_1_2_janev
p_cx_3 calls p_cx_3_4_adas, p_cx_janev, m_spread, p_cx_1, p_cx_3_5_adas, p_cx_3_3_adas, p_cx_1_3_adas, p_cx_3_2_adas, p_cx_3_6inf_adas
aq_excit_2_janev calls aq_excit_2_4_janev, aq_excit_2_6_janev, aq_excit_2_9_janev, aq_excit_2_8_janev, aq_excit_2_3_janev, aq_excit_2_10_janev, aq_excit_2_5_janev, aq_excit_2_7_janev
p_cx_1 calls p_cx_janev, p_cx_1_4_adas, p_cx_1_3_adas, p_cx_1_2_janev, p_cx_1_2_adas, p_cx_1_1_adas
p_excit_1_janev calls p_excit_1_4_janev, p_excit_1_6_janev, p_excit_1_3_janev, p_excit_1_5_janev, p_excit_1_2_janev
p_excit_2_6_janev calls p_excit_2_5_janev
p_excit_3_10_janev calls p_excit_3_6_janev
p_excit_2_9_janev calls p_excit_2_5_janev
p_cx_1_2_janev calls aljan1
aq_excit_2_6_janev calls aq_excit_2_5_janev
p_excit_2_8_janev calls p_excit_2_5_janev
p_excit_3_9_janev calls p_excit_3_6_janev
aq_excit_2_9_janev calls aq_excit_2_5_janev
aq_excit_3_7_janev calls aq_excit_3_6_janev
aq_excit_3_8_janev calls aq_excit_3_6_janev
p_excit_3_7_janev calls p_excit_3_6_janev
p_excit_2_7_janev calls p_excit_2_5_janev
aq_excit_2_8_janev calls aq_excit_2_5_janev
aq_excit_3_10_janev calls aq_excit_3_6_janev
aq_excit_3_9_janev calls aq_excit_3_6_janev
p_excit_3_8_janev calls p_excit_3_6_janev
p_excit_2_10_janev calls p_excit_2_5_janev
aq_excit_2_10_janev calls aq_excit_2_5_janev
aq_excit_2_7_janev calls aq_excit_2_5_janev