.PHONY: all test_001 test_003 test_004 clean

all: test_001 test_003 test_004

test_001:
	@cd test_001; make

test_003:
	@cd test_003; make

test_004:
	@cd test_004; make

clean:
	@cd test_001; make clean
	@cd test_003; make clean
	@cd test_004; make clean
