approx_le – FIDASIM
approx_le Function
7 statements
Source File
public function approx_le(x, y, tol) result(a)
Inexact less then or equal to comparison: x <~= y
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: x
First value in comparison
real(kind=Float64), intent(in) :: y
Second value in comparison
real(kind=Float64), intent(in) :: tol
Equality tolerance
Return Value logical
Calls
Called by
Contents
Source Code
approx_le
Source Code
function approx_le(x,y,tol) result(a)
    !+ Inexact less then or equal to comparison: `x <~= y`
    real(Float64), intent(in) :: x
        !+First value in comparison
    real(Float64), intent(in) :: y
        !+Second value in comparison
    real(Float64), intent(in) :: tol
        !+Equality tolerance
    logical :: a
    a = (x.lt.y).or.(approx_eq(x,y,tol))
end function approx_le
Call graph
approx_le calls approx_eq
in_grid calls approx_le
circle_grid_intersect calls in_grid
read_mc calls circle_grid_intersect
read_distribution calls read_mc
fidasim calls read_distribution