Aq_cx_n – FIDASIM
Aq_cx_n Function
10 statements
Source File
public function Aq_cx_n(eb, q, n) result(sigma)
Calculates the total charge exchange cross section for a Neutral Hydrogen atom in the n state colliding with a ion with charge q at energy eb
Note
Uses ADAS(Ref. 4) cross sections if available else uses Janev (Ref. 5) cross sections
Equation
References
Ref. 4 atomic_tables
Page 166 in Ref. 5 atomic_tables
Page 168 in Ref. 5 atomic_tables
Page 174 in Ref. 5 atomic_tables
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: eb
Relative collision energy [keV/amu]
integer, intent(in) :: q
Ion charge
integer, intent(in) :: n
Initial atomic energy level/state
Return Value real(kind=Float64)
Cross Section []
Calls
Called by
Contents
Source Code
Aq_cx_n
Source Code
function Aq_cx_n(eb, q, n) result(sigma)
    !+ Calculates the total charge exchange cross section for a Neutral Hydrogen atom
    !+in the `n` state colliding with a ion with charge `q` at energy `eb`
    !+
    !+@note Uses ADAS(Ref. 4) cross sections if available else uses Janev (Ref. 5) cross sections
    !+
    !+###Equation
    !+$$ A^{q+} + H(n) \rightarrow A^{(q-1)+} + H^+, q \gt 3 $$
    !+
    !+###References
    !+* Ref. 4 [[atomic_tables(module)]]
    !+* Page 166 in Ref. 5 [[atomic_tables(module)]]
    !+* Page 168 in Ref. 5 [[atomic_tables(module)]]
    !+* Page 174 in Ref. 5 [[atomic_tables(module)]]
    real(Float64), intent(in) :: eb
        !+ Relative collision energy [keV/amu]
    integer, intent(in)       :: q
        !+ Ion charge
    integer, intent(in)       :: n
        !+ Initial atomic energy level/state
    real(Float64)             :: sigma
        !+ Cross Section [\(cm^2\)]
    sigma = Aq_cx_n_adas(eb, q, n)
    if(sigma.eq.0.d0) then
        sigma = Aq_cx_n_janev(eb, q, n)
    endif
end function Aq_cx_n
Call graph
aq_cx_n calls aq_cx_n_janev, aq_cx_n_adas
aq_cx_n_janev calls c6_cx_1_janev, b5_cx_1_janev
aq_cx_n_adas calls c6_cx_2_adas, c6_cx_3_adas, b5_cx_1_adas, b5_cx_2_adas, c6_cx_1_adas
aq_cx calls aq_cx_n
write_bb_h_aq calls aq_cx
generate_tables calls write_bb_h_aq