Aq_excit_3_6_janev – FIDASIM
Aq_excit_3_6_janev Function
11 statements
Source File
public function Aq_excit_3_6_janev(eb, q) result(sigma)
Calculates the excitation cross section for a neutral Hydrogen atom transitioning from the state to the state due to a collision an ion with charge q at energy eb
Equation
References
Page 142 in Ref. 5 atomic_tables
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: eb
Collision energy [keV]
integer, intent(in) :: q
Ion charge
Return Value real(kind=Float64)
Cross Section []
Called by
Contents
Source Code
Aq_excit_3_6_janev
Source Code
function Aq_excit_3_6_janev(eb, q) result(sigma)
    !+Calculates the excitation cross section for a neutral Hydrogen atom transitioning from
    !+the \(n=3\) state to the \(m=6\) state due to a collision an ion with charge `q` at energy `eb`
    !+
    !+###Equation
    !+$$ A^{q+} + H(3) \rightarrow A^{q+} + H(6), q \gt 3 $$
    !+
    !+###References
    !+* Page 142 in Ref. 5 [[atomic_tables(module)]]
    !+
    real(Float64), intent(in) :: eb
        !+ Collision energy [keV]
    integer, intent(in)       :: q
        !+ Ion charge
    real(Float64)             :: sigma
        !+ Cross Section [\(cm^2\)]
    real(Float64), dimension(6), parameter :: A = [63.494d0, 11.507d0,   &
                                                   4.3417d0, 0.077953d0, &
                                                   0.53461d0, -1.2881d0 ]
    real(Float64) :: Etil, qf, xsi
    qf = real(q)
    etil = eb/qf
    xsi = 2.0**(0.397*(1 - sqrt(2.0/qf)))
    sigma = qf*1.e-16*xsi*A(1)*(exp(-A(2)/etil)*log(1+A(3)*etil)/etil &
          + A(4)*exp(-A(5)*etil)/etil**A(6))
end function Aq_excit_3_6_janev
Call graph
aq_excit_3_7_janev calls aq_excit_3_6_janev
aq_excit_3_janev calls aq_excit_3_6_janev, aq_excit_3_7_janev, aq_excit_3_10_janev, aq_excit_3_9_janev, aq_excit_3_8_janev
aq_excit_3_10_janev calls aq_excit_3_6_janev
aq_excit_3_9_janev calls aq_excit_3_6_janev
aq_excit_3_8_janev calls aq_excit_3_6_janev
aq_excit_n calls aq_excit_3_janev
aq_excit calls aq_excit_n
aq_excit_n_m calls aq_excit_n
write_bb_h_aq calls aq_excit
generate_tables calls write_bb_h_aq