Aq_excit_3_10_janev – FIDASIM
Aq_excit_3_10_janev Function
9 statements
Source File
public function Aq_excit_3_10_janev(eb, q) result(sigma)
Calculates the excitation cross section for a neutral Hydrogen atom transitioning from the state to the state due to a collision an ion with charge q at energy eb
Equation
References
Page 144 in Ref. 5 atomic_tables
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: eb
Collision energy [keV]
integer, intent(in) :: q
Ion charge
Return Value real(kind=Float64)
Cross Section []
Calls
Called by
Contents
Source Code
Aq_excit_3_10_janev
Source Code
function Aq_excit_3_10_janev(eb, q) result(sigma)
    !+Calculates the excitation cross section for a neutral Hydrogen atom transitioning from
    !+the \(n=3\) state to the \(m=10\) state due to a collision an ion with charge `q` at energy `eb`
    !+
    !+###Equation
    !+$$ A^{q+} + H(3) \rightarrow A^{q+} + H(10), q \gt 3 $$
    !+
    !+###References
    !+* Page 144 in Ref. 5 [[atomic_tables(module)]]
    !+
    real(Float64), intent(in) :: eb
        !+ Collision energy [keV]
    integer, intent(in)       :: q
        !+ Ion charge
    real(Float64)             :: sigma
        !+ Cross Section [\(cm^2\)]
    real(Float64), parameter :: A = 0.1d0
    real(Float64) :: hi
    hi=2.0**(0.397*(1.0 - sqrt(2.0/q)))
    sigma=hi*A*Aq_excit_3_6_janev(eb, q)
end function Aq_excit_3_10_janev
Call graph
aq_excit_3_10_janev calls aq_excit_3_6_janev
aq_excit_3_janev calls aq_excit_3_10_janev
aq_excit_n calls aq_excit_3_janev
aq_excit calls aq_excit_n
aq_excit_n_m calls aq_excit_n
write_bb_h_aq calls aq_excit
generate_tables calls write_bb_h_aq