p_cx_1_4_adas – FIDASIM
p_cx_1_4_adas Function
17 statements
Source File
public function p_cx_1_4_adas(Erel) result(sigma)
Calculates cross section for a proton-Hydrogen charge exchange interaction from the state to the state at energy Erel
Equation
References
Ref. 4 atomic_tables
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: Erel
Relative collision energy [keV/amu]
Return Value real(kind=Float64)
Cross Section []
Called by
Contents
Source Code
p_cx_1_4_adas
Source Code
function p_cx_1_4_adas(Erel) result(sigma)
    !+Calculates cross section for a proton-Hydrogen charge exchange interaction
    !+from the \(n=1\) state to the \(m=4\) state at energy `Erel`
    !+
    !+###Equation
    !+ $$H^+ + H(1) \rightarrow H(4) + H^+$$
    !+###References
    !+* Ref. 4 [[atomic_tables(module)]]
    real(Float64), intent(in) :: Erel
        !+ Relative collision energy [keV/amu]
    real(Float64)             :: sigma
        !+ Cross Section [\(cm^2\)]
    real(Float64), dimension(10), parameter :: a = [6.826447557d4, -1.431980004d5, &
                                                    1.323968679d5, -7.083995050d4, &
                                                    2.417608863d4, -5.458418789d3, &
                                                    8.154875237d2, -7.776012846d1, &
                                                    4.295431731d0, -1.047567211d-1 ]
    real(Float64) :: e, ee, fac, l, p
    e = Erel*1.d3
    if(e.ge.2.d3) then
        ee = max(e,1.0)
        fac = 1.d0
    else
        ee = 2.0d3
        fac = (Erel**(2.0))/4.0
    endif
    l = log10(ee)
    p = a(1) + a(2)*l + a(3)*l**2.0 + a(4)*l**3.0 + &
        a(5)*l**4.0   + a(6)*l**5.0 + a(7)*l**6.0 + &
        a(8)*l**7.0   + a(9)*l**8.0 + a(10)*l**9.0
    sigma = fac*(10.d0**p)
end function p_cx_1_4_adas
Call graph
p_cx_n calls p_cx_1_4_adas, p_cx_1, p_cx_3
p_cx_1 calls p_cx_1_4_adas
p_cx calls p_cx_n
p_cx_n_m calls p_cx_n
p_cx_3 calls p_cx_1
write_bb_h_h calls p_cx
generate_tables calls write_bb_h_h