Aq_excit_2_5_janev – FIDASIM
Aq_excit_2_5_janev Function
Source File
public function Aq_excit_2_5_janev(eb, q) result(sigma)
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: eb
Collision energy [keV]
integer, intent(in) :: q
Ion charge
Return Value real(kind=Float64)
Cross Section [\(cm^2\)]
Description
Calculates the excitation cross section for a neutral Hydrogen atom transitioning from the \(n=2\) state to the \(m=5\) state due to a collision an ion with charge q at energy eb
Equation
$$ A^{q+} + H(2) \rightarrow A^{q+} + H(5), q \gt 3 $$
References
Page 138 in Ref. 5 atomic_tables
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=Float64), public, parameter, dimension(6) :: A = [18.264d0, 18.973d0, 2.9056d0, 0.013701d0, 0.31711d0, -1.4775d0]
real(kind=Float64), public :: etil
real(kind=Float64), public :: qf
real(kind=Float64), public :: xsi
Source Code
function Aq_excit_2_5_janev(eb, q) result(sigma)
    !+Calculates the excitation cross section for a neutral Hydrogen atom transitioning from
    !+the \(n=2\) state to the \(m=5\) state due to a collision an ion with charge `q` at energy `eb`
    !+
    !+###Equation
    !+$$ A^{q+} + H(2) \rightarrow A^{q+} + H(5), q \gt 3 $$
    !+
    !+###References
    !+* Page 138 in Ref. 5 [[atomic_tables(module)]]
    !+
    real(Float64), intent(in) :: eb
        !+ Collision energy [keV]
    integer, intent(in)       :: q
        !+ Ion charge
    real(Float64)             :: sigma
        !+ Cross Section [\(cm^2\)]
    real(Float64), dimension(6), parameter :: A = [18.264d0, 18.973d0,   &
                                                   2.9056d0, 0.013701d0, &
                                                   0.31711d0, -1.4775d0 ]
    real(Float64) :: etil, qf, xsi
    qf = real(q)
    etil = eb/qf
    xsi = 2.0**(0.5238*(1 - sqrt(2.0/qf)))
    sigma = qf*1.e-16*xsi*A(1)*(exp(-A(2)/etil)*log(1 + A(3)*etil)/etil &
          + A(4)*exp(-A(5)*etil)/etil**A(6))
end function Aq_excit_2_5_janev
Call graph
aq_excit_2_8_janev calls aq_excit_2_5_janev
aq_excit_2_9_janev calls aq_excit_2_5_janev
aq_excit_2_10_janev calls aq_excit_2_5_janev
aq_excit_2_janev calls aq_excit_2_5_janev, aq_excit_2_8_janev, aq_excit_2_9_janev, aq_excit_2_10_janev, aq_excit_2_6_janev, aq_excit_2_7_janev
aq_excit_2_6_janev calls aq_excit_2_5_janev
aq_excit_2_7_janev calls aq_excit_2_5_janev
aq_excit_n calls aq_excit_2_janev
aq_excit calls aq_excit_n
aq_excit_n_m calls aq_excit_n
write_bb_h_aq calls aq_excit
generate_tables calls write_bb_h_aq