Aq_excit_3_4_janev – FIDASIM
Aq_excit_3_4_janev Function
Source File
public function Aq_excit_3_4_janev(eb, q) result(sigma)
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: eb
Collision energy [keV]
integer, intent(in) :: q
Ion charge
Return Value real(kind=Float64)
Cross Section [\(cm^2\)]
Description
Calculates the excitation cross section for a neutral Hydrogen atom transitioning from the \(n=3\) state to the \(m=4\) state due to a collision an ion with charge q at energy eb
Equation
$$ A^{q+} + H(3) \rightarrow A^{q+} + H(4), q \gt 3 $$
References
Page 142 in Ref. 5 atomic_tables
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=Float64), public, parameter, dimension(6) :: A = [1247.5d0, 11.319d0, 2.6235d0, 0.068781d0, 0.521176d0, -1.2722d0]
real(kind=Float64), public :: Etil
real(kind=Float64), public :: qf
real(kind=Float64), public :: xsi
Source Code
function Aq_excit_3_4_janev(eb, q) result(sigma)
    !+Calculates the excitation cross section for a neutral Hydrogen atom transitioning from
    !+the \(n=3\) state to the \(m=4\) state due to a collision an ion with charge `q` at energy `eb`
    !+
    !+###Equation
    !+$$ A^{q+} + H(3) \rightarrow A^{q+} + H(4), q \gt 3 $$
    !+
    !+###References
    !+* Page 142 in Ref. 5 [[atomic_tables(module)]]
    !+
    real(Float64), intent(in) :: eb
        !+ Collision energy [keV]
    integer, intent(in)       :: q
        !+ Ion charge
    real(Float64)             :: sigma
        !+ Cross Section [\(cm^2\)]
    real(Float64), dimension(6), parameter :: A = [1247.5d0, 11.319d0,   &
                                                   2.6235d0, 0.068781d0, &
                                                   0.521176d0, -1.2722d0 ]
    real(Float64) :: Etil, qf, xsi
    qf = real(q)
    etil = eb/qf
    xsi = 2.0**(0.397*(1 - sqrt(2.0/qf)))
    sigma = qf*1.e-16*xsi*A(1)*(exp(-A(2)/etil)*log(1+A(3)*etil)/etil &
          + A(4)*exp(-A(5)*etil)/etil**A(6))
end function Aq_excit_3_4_janev
Call graph
aq_excit_3_janev calls aq_excit_3_4_janev
aq_excit_n calls aq_excit_3_janev
aq_excit calls aq_excit_n
aq_excit_n_m calls aq_excit_n
write_bb_h_aq calls aq_excit
generate_tables calls write_bb_h_aq