balback – FIDASIM
balback Subroutine
Source File
public subroutine balback(n, low, high, scal, eivec)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
Dimension of matrix
integer, intent(in) :: low
First nonzero row
integer, intent(in) :: high
Last nonzero row
real(kind=double), intent(in) :: scal(0:n)
Scaling data from balance
real(kind=double), intent(inout) :: eivec(0:n,0:n)
Description
Reverses the balancing of balance for the eigenvectors
Calls
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=double), public :: s
integer, public :: i
integer, public :: j
integer, public :: k
Source Code
  subroutine balback(n, low, high, scal, eivec )
    !+  Reverses the balancing of balance for the eigenvectors
    integer,intent(in)         :: n
      !+ Dimension of matrix
    integer,intent(in)         :: low
      !+ First nonzero row
    integer,intent(in)         :: high
      !+ Last nonzero row
    real(double), intent(in)   ::  scal(0:n)
      !+ Scaling data from balance
    real(double), intent(inout):: eivec(0:n,0:n)
      !+ Input: n x n matrix of eigenvectors, as computed in qr2
      !+ Output: Non-normalized eigenvectors of the original matrix
    real(double) :: s
    integer      :: i,j,k
    do i = low, high
       s = scal(i)
       do j = 0, n-1
      eivec(i,j) = eivec(i,j) * s
       enddo
    enddo
    do i = low-1, 0, -1
       k = Int(scal(i))
       if (k.ne.i) then
          do j = 0, n-1
             call RSWAP(eivec(i,j), eivec(k,j))
          enddo
       endif
    enddo
    do i = high + 1, n-1
       k = Int(scal(i))
       if (k.ne.i) then
          do j = 0, n-1
             call RSWAP(eivec(i,j), eivec(k,j))
          enddo
       endif
    enddo
    return
  end subroutine balback
Call graph
balback calls rswap
eigen calls balback
colrad calls eigen
halo calls colrad
fida_f calls colrad
ndmc calls colrad
fida_mc calls colrad
fida_weights_los calls colrad
attenuate calls colrad
fida_weights_mc calls colrad
dcx calls colrad
fidasim calls halo, fida_f, ndmc, fida_mc, fida_weights_los, fida_weights_mc, dcx, npa_f, npa_mc, npa_weights
npa_f calls attenuate
npa_mc calls attenuate
npa_weights calls attenuate