e_excit_1_3_janev – FIDASIM
e_excit_1_3_janev Function
Source File
public function e_excit_1_3_janev(eb) result(sigma)
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: eb
Collision energy [keV]
Return Value real(kind=Float64)
Cross Section [\(cm^2\)]
Description
Calculates cross section for a electron-Hydrogen impact excitation transition from the \(n=1\) state to the \(m=3\) state at energy eb
Equation
$$ e + H(1) \rightarrow e + H(3) $$
References
Eq. 5 and Table 2 in Ref. 2 atomic_tables
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=Float64), public, parameter :: sigma0 = 5.984d0
real(kind=Float64), public, parameter :: deltaE = 12.09d0
Fitting parameter from Table 2 in Ref. 2
real(kind=Float64), public, parameter :: alpha = 0.38277d0
Fitting parameter from Table 2 in Ref. 2
real(kind=Float64), public, parameter, dimension(5) :: A = [0.75448d0, 0.42956d0, -0.58288d0, 1.0693d0, 0.d0]
Fitting parameters from Table 2 in Ref. 2
real(kind=Float64), public :: ecoll
real(kind=Float64), public :: x
real(kind=Float64), public :: s
Source Code
function e_excit_1_3_janev(eb) result(sigma)
    !+Calculates cross section for a electron-Hydrogen impact excitation transition from
    !+the \(n=1\) state to the \(m=3\) state at energy `eb`
    !+
    !+###Equation
    !+$$ e + H(1) \rightarrow e + H(3) $$
    !+
    !+###References
    !+* Eq. 5 and Table 2 in Ref. 2 [[atomic_tables(module)]]
    !+
    real(Float64), intent(in) :: eb
        !+ Collision energy [keV]
    real(Float64)             :: sigma
        !+ Cross Section [\(cm^2\)]
    real(Float64), parameter :: sigma0 = 5.984d0
    real(Float64), parameter :: deltaE = 12.09d0
        !+ Fitting parameter from Table 2 in Ref. 2
    real(Float64), parameter :: alpha = 0.38277d0
        !+ Fitting parameter from Table 2 in Ref. 2
    real(Float64), dimension(5), parameter :: A = [ 0.75448d0, 0.42956d0, &
                                                   -0.58288d0, 1.0693d0,  &
                                                    0.d0 ]
        !+ Fitting parameters from Table 2 in Ref. 2
    real(Float64) :: ecoll, x, s
    ecoll = eb*1.d3
    x=ecoll/deltaE
    s = A(2) + A(3)/x + A(4)/x**2.0 + A(5)/x**3.0
    sigma = 1.d-16 * sigma0/(deltaE*x) * (1.0 - 1.0/x)**alpha * (A(1)*log(x) + s)
    if(x.le.1.0) sigma = 0.d0
end function e_excit_1_3_janev
Call graph
e_excit_1_janev calls e_excit_1_3_janev
e_excit_n calls e_excit_1_janev
e_excit calls e_excit_n
e_excit_n_m calls e_excit_n
write_bb_h_e calls e_excit
generate_tables calls write_bb_h_e