h5ltmake_compressed_dataset_int_f_7 – FIDASIM
h5ltmake_compressed_dataset_int_f_7 Subroutine
Source File
public subroutine h5ltmake_compressed_dataset_int_f_7(loc_id, dset_name, rank, dims, buf, error)
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: loc_id
HDF5 file or group identifier
character(len=*), intent(in) :: dset_name
Name of the dataset to create
integer, intent(in) :: rank
Number of dimensions of dataspace
integer(kind=HSIZE_T), intent(in), dimension(*) :: dims
Array of the size of each dimension
integer, intent(in), dimension(dims(1),dims(2),dims(3),dims(4),dims(5),dims(6),dims(7)) :: buf
Buffer with data to be written to the dataset
integer, intent(out) :: error
HDF5 error code
Description
Write a compressed 32-bit integer dataset of dimension 7
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=HID_T), public :: did
integer(kind=HID_T), public :: sid
integer(kind=HID_T), public :: plist_id
Source Code
subroutine h5ltmake_compressed_dataset_int_f_7(loc_id,&
           dset_name, rank, dims, buf, error )
    !+ Write a compressed 32-bit integer dataset of dimension 7
    IMPLICIT NONE
    integer(hid_t), intent(in)                                           :: loc_id
        !+ HDF5 file or group identifier
    character(len=*), intent(in)                                         :: dset_name
        !+ Name of the dataset to create
    integer, intent(in)                                                  :: rank
        !+ Number of dimensions of dataspace
    integer(HSIZE_T), dimension(*), intent(in)                           :: dims
        !+ Array of the size of each dimension
    integer, intent(in), &
      dimension(dims(1),dims(2),dims(3),dims(4),dims(5),dims(6),dims(7)) :: buf
        !+ Buffer with data to be written to the dataset
    integer, intent(out)                                                 :: error
        !+ HDF5 error code
    integer(HID_T) :: did, sid, plist_id
    if(.not.compress_data) then
        call h5ltmake_dataset_int_f(loc_id, dset_name, rank, dims, buf, error)
    else
        call h5screate_simple_f(rank, dims, sid, error)
        call h5pcreate_f(H5P_DATASET_CREATE_F, plist_id, error)
        call h5pset_shuffle_f(plist_id, error)
        call h5pset_deflate_f(plist_id, 9, error)
        call h5pset_chunk_f(plist_id, rank, dims, error)
        call h5dcreate_f(loc_id, dset_name, H5T_NATIVE_INTEGER, sid, &
             did, error, dcpl_id=plist_id)
        call h5dwrite_f(did, H5T_NATIVE_INTEGER, buf, dims, error)
        call h5sclose_f(sid, error)
        call h5pclose_f(plist_id, error)
        call h5dclose_f(did, error)
    endif
end subroutine h5ltmake_compressed_dataset_int_f_7
Call graph
h5ltmake_compressed_dataset_int_f_7 calls h5pclose_f, h5dclose_f, h5screate_simple_f, h5pcreate_f, h5pset_shuffle_f, h5pset_deflate_f, h5ltmake_dataset_int_f, h5pset_chunk_f, h5dcreate_f, h5dwrite_f, h5sclose_f
h5ltmake_compressed_dataset_int_f calls h5ltmake_compressed_dataset_int_f_7
write_npa calls h5ltmake_compressed_dataset_int_f
write_birth_profile calls h5ltmake_compressed_dataset_int_f
fidasim calls write_npa, write_birth_profile