mc_fastion – FIDASIM
mc_fastion Subroutine
70 statements
Source File
public subroutine mc_fastion(ind, ri, vi, denf, at_guiding_center)
Samples Fast-ion distribution function in a given beam_grid index
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(3) :: ind
beam_grid index
real(kind=Float64), intent(out), dimension(3) :: ri
Fast-ion position
real(kind=Float64), intent(out), dimension(3) :: vi
Fast-ion velocity [cm/s]
real(kind=Float64), intent(out) :: denf
Fast-ion density at guiding center
logical, intent(in), optional :: at_guiding_center
Indicates that ri should be the particles gyrocenter. Defaults to true
Calls
Called By
Source Code
mc_fastion
Source Code
subroutine mc_fastion(ind,ri,vi,denf,at_guiding_center)
    !+ Samples Fast-ion distribution function in a given [[libfida:beam_grid]] index
    integer, dimension(3), intent(in)        :: ind
        !+ [[libfida:beam_grid]] index
    real(Float64), dimension(3), intent(out) :: ri
        !+ Fast-ion position
    real(Float64), dimension(3), intent(out) :: vi
        !+ Fast-ion velocity [cm/s]
    real(Float64), intent(out)               :: denf
        !+ Fast-ion density at guiding center
    logical, intent(in), optional            :: at_guiding_center
        !+ Indicates that ri should be the particles gyrocenter. Defaults to true
    type(LocalEMFields) :: fields
    real(Float64), dimension(fbm%nenergy,fbm%npitch) :: fbeam
    real(Float64), dimension(3) :: r_gyro, rp
    real(Float64) :: eb ,ptch
    integer :: ii, ienergy, ipitch
    real(Float64) :: vabs, phi
    real(Float64), dimension(3) :: randomu3
    real(Float64), dimension(4) :: randomu4
    integer, dimension(1) :: minpos
    integer, dimension(2,1) :: ep_ind
    real(Float64), dimension(1) :: max_fbm
    logical :: use_inverse_sampler
    if(present(at_guiding_center)) then
        use_inverse_sampler = at_guiding_center
    else
        use_inverse_sampler = .True.
    endif
    call randu(randomu3)
    ri(1) = beam_grid%xc(ind(1)) + beam_grid%dr(1)*(randomu3(1) - 0.5)
    ri(2) = beam_grid%yc(ind(2)) + beam_grid%dr(2)*(randomu3(2) - 0.5)
    ri(3) = beam_grid%zc(ind(3)) + beam_grid%dr(3)*(randomu3(3) - 0.5)
    vi=0.d0
    denf=0.d0
    call get_fields(fields,pos=ri)
    if(.not.fields%in_plasma) return
    if(use_inverse_sampler) then
        call get_distribution(fbeam,denf,pos=ri)
        call randind(fbeam,ep_ind)
        call randu(randomu3)
        eb = fbm%energy(ep_ind(1,1)) + fbm%dE*(randomu3(1)-0.5)
        ptch = fbm%pitch(ep_ind(2,1)) + fbm%dp*(randomu3(2)-0.5)
        phi = 2.d0*pi*randomu3(3)
        !! Calculate gyroradius
        vabs  = sqrt(eb/(v2_to_E_per_amu*inputs%ab))
        call pitch_to_vec(ptch,phi,fields,vi)
        vi = vabs*vi
        call gyro_correction(vi,fields,r_gyro)
        !! Move a gyro-orbit away
        ri=ri-r_gyro
    else
        !! Use rejection method to determine velocity vector
        rejection_loop: do ii=1,10000
            call randu(randomu4)
            !! Pick a random energy, pitch, and gyro angle
            eb   = fbm%emin + fbm%e_range * randomu4(1)
            ptch = fbm%pmin + fbm%p_range * randomu4(2)
            phi  = 2.d0*pi*randomu4(3)
            !! Calculate gyroradius
            vabs  = sqrt(eb/(v2_to_E_per_amu*inputs%ab))
            call pitch_to_vec(ptch,phi,fields,vi)
            vi = vabs*vi
            call gyro_correction(vi,fields,r_gyro)
            !! Move a gyro-orbit away and sample distribution there
            rp=ri+r_gyro
            call get_distribution(fbeam,denf,pos=rp)
            max_fbm = maxval(fbeam)
            !! Find new cell
            if(max_fbm(1).gt.0.0) then
                !! take point in FBM distribution closest to eb, ptch.
                minpos=minloc(abs(eb - fbm%energy))
                ienergy= minpos(1)
                minpos=minloc(abs(ptch - fbm%pitch ))
                ipitch = minpos(1)
                if((fbeam(ienergy,ipitch)).gt.(randomu4(4)*max_fbm(1)))then
                    return
                endif
            endif
            vi=0.d0
        enddo rejection_loop
        write(*,'(a)') 'MC_FASTION: Rejection method found no solution!'
    endif
end subroutine mc_fastion
All Procedures
Aq_cx Aq_cx_n Aq_cx_n_adas Aq_cx_n_janev Aq_excit Aq_excit_1_2_janev Aq_excit_1_3_janev Aq_excit_1_4_janev Aq_excit_1_5_janev Aq_excit_1_janev Aq_excit_2_10_janev Aq_excit_2_3_janev Aq_excit_2_4_janev Aq_excit_2_5_janev Aq_excit_2_6_janev Aq_excit_2_7_janev Aq_excit_2_8_janev Aq_excit_2_9_janev Aq_excit_2_janev Aq_excit_3_10_janev Aq_excit_3_4_janev Aq_excit_3_5_janev Aq_excit_3_6_janev Aq_excit_3_7_janev Aq_excit_3_8_janev Aq_excit_3_9_janev Aq_excit_3_janev Aq_excit_n Aq_excit_n_janev Aq_excit_n_m Aq_ioniz Aq_ioniz_n Aq_ioniz_n_janev assignment(=) attenuate B5_cx_1_adas B5_cx_1_janev B5_cx_2_adas B5_ioniz_1_janev balance balback bremsstrahlung bt_maxwellian bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m C6_cx_1_adas C6_cx_1_janev C6_cx_2_adas C6_cx_3_adas C6_ioniz_1_janev calc_perp_vectors check_compression_availability colrad comabs Comdiv cross_product dcx e_excit e_excit_1_2_janev e_excit_1_3_janev e_excit_1_4_janev e_excit_1_5_janev e_excit_1_janev e_excit_2_3_janev e_excit_f e_excit_n e_excit_n_m e_ioniz e_ioniz_1_janev e_ioniz_2_janev e_ioniz_3_janev e_ioniz_n eigen elmhes elmtrans fast_ion_assign ff_add ff_assign ff_subtract fida_f fida_mc fida_weights_los fida_weights_mc flf_assign fs_divide fs_multiply get_beam_cx_prob get_distribution get_ep_denf get_fields get_indices get_nlaunch get_plasma get_position get_rate_matrix grid_intersect gyro_correction h5ltmake_compressed_dataset_double_f h5ltmake_compressed_dataset_double_f_1 h5ltmake_compressed_dataset_double_f_2 h5ltmake_compressed_dataset_double_f_3 h5ltmake_compressed_dataset_double_f_4 h5ltmake_compressed_dataset_double_f_5 h5ltmake_compressed_dataset_double_f_6 h5ltmake_compressed_dataset_double_f_7 h5ltmake_compressed_dataset_int_f h5ltmake_compressed_dataset_int_f_1 h5ltmake_compressed_dataset_int_f_2 h5ltmake_compressed_dataset_int_f_3 h5ltmake_compressed_dataset_int_f_4 h5ltmake_compressed_dataset_int_f_5 h5ltmake_compressed_dataset_int_f_6 h5ltmake_compressed_dataset_int_f_7 h5ltread_dataset_double_scalar_f h5ltread_dataset_int_scalar_f halo hit_npa_detector hqr2 hqrvec in_boundary in_plasma ind2sub interpol interpol1D_arr interpol1D_coeff interpol1D_coeff_arr interpol2D_2D_arr interpol2D_arr interpol2D_coeff interpol2D_coeff_arr interpol_coeff lff_assign lflf_add lflf_assign lflf_subtract lfs_divide lfs_multiply line_basis lplp_add lplp_assign lplp_subtract lpp_assign lps_divide lps_multiply lubksb ludcmp m_spread make_beam_grid matinv mc_fastion mc_halo mc_nbi ndmc neut_rates normp npa_f npa_mc npa_part_assign npa_weights operator(*) operator(+) operator(-) operator(/) outerprod p_cx p_cx_1 p_cx_1_1_adas p_cx_1_2_adas p_cx_1_3_adas p_cx_1_4_adas p_cx_1_janev p_cx_2 p_cx_2_2_adas p_cx_2_3_adas p_cx_2_janev p_cx_3 p_cx_3_2_adas p_cx_3_3_adas p_cx_3_4_adas p_cx_3_5_adas p_cx_3_6inf_adas p_cx_3_janev p_cx_janev p_cx_n p_cx_n_janev p_cx_n_m p_excit p_excit_1_2_janev p_excit_1_3_janev p_excit_1_4_janev p_excit_1_5_janev p_excit_1_6_janev p_excit_1_janev p_excit_2_10_janev p_excit_2_3_janev p_excit_2_4_janev p_excit_2_5_janev p_excit_2_6_janev p_excit_2_7_janev p_excit_2_8_janev p_excit_2_9_janev p_excit_2_janev p_excit_3_10_janev p_excit_3_4_janev p_excit_3_5_janev p_excit_3_6_janev p_excit_3_7_janev p_excit_3_8_janev p_excit_3_9_janev p_excit_3_janev p_excit_n p_excit_n_m p_ioniz p_ioniz_1_janev p_ioniz_2_omullane p_ioniz_3_omullane p_ioniz_4_omullane p_ioniz_5_omullane p_ioniz_n pitch_to_vec plane_basis plane_intercept plp_assign pp_add pp_assign pp_subtract print_banner print_default_namelist ps_divide ps_multiply randind randn randu read_beam read_chords read_cross read_distribution read_equilibrium read_f read_inputs read_mc read_neutrals read_npa read_rates read_tables rng_init rng_normal rng_uniform RSWAP sf_multiply simpsons_rule slf_multiply slp_multiply sp_multiply spectrum store_bes_photons store_births store_fida_photons store_fw_photons store_fw_photons_at_chan store_neutrals store_npa swap tb_zyx track uvw_to_xyz write_bb_H_Aq write_bb_H_e write_bb_H_H write_beam_grid write_birth_profile write_bt_H_Aq write_bt_H_e write_bt_H_H write_dcx write_einstein write_fida_weights write_neutrals write_npa write_npa_weights write_spectra xyz_to_uvw
Call graph
mc_fastion calls get_distribution, randind, get_fields, gyro_correction, randu, pitch_to_vec
get_distribution calls xyz_to_uvw, interpol, get_position, in_plasma
get_fields calls xyz_to_uvw, get_position, in_plasma, interpol_coeff, normp, calc_perp_vectors
gyro_correction calls cross_product
randu calls omp_get_thread_num, rng_uniform
interpol calls interpol1d_arr, interpol2d_2d_arr, interpol2d_arr
in_plasma calls xyz_to_uvw, interpol
interpol1d_arr calls interpol_coeff
interpol2d_2d_arr calls interpol_coeff
interpol2d_arr calls interpol_coeff
interpol_coeff calls interpol1d_coeff, interpol2d_coeff_arr, interpol2d_coeff, interpol1d_coeff_arr
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
calc_perp_vectors calls normp
fida_f calls mc_fastion
npa_f calls mc_fastion
fidasim calls fida_f, npa_f