p_cx_3_2_adas – FIDASIM
p_cx_3_2_adas Function
Source File
public function p_cx_3_2_adas(Erel) result(sigma)
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: Erel
Relative collision energy [keV/amu]
Return Value real(kind=Float64)
Cross Section [\(cm^2\)]
Description
Calculates cross section for a proton-Hydrogen charge exchange interaction from the \(n=3\) state to the \(m=2\) state at energy Erel
Equation
$$H^+ + H(3) \rightarrow H(2) + H^+$$
References
Ref. 4 atomic_tables
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=Float64), public, parameter, dimension(11) :: a = [-1.149224555d6, 2.750368877d6, -2.942222842d6, 1.852584954d6, -7.603284323d5, 2.125284465d5, -4.097580431d4, 5.380901722d3, -4.606297192d2, 2.321345254d1, -5.230186707d-1]
real(kind=Float64), public, parameter :: n = 3.0
real(kind=Float64), public :: ee
real(kind=Float64), public :: fac
real(kind=Float64), public :: l
real(kind=Float64), public :: p
Source Code
function p_cx_3_2_adas(Erel) result(sigma)
    !+Calculates cross section for a proton-Hydrogen charge exchange interaction
    !+from the \(n=3\) state to the \(m=2\) state at energy `Erel`
    !+
    !+###Equation
    !+ $$H^+ + H(3) \rightarrow H(2) + H^+$$
    !+###References
    !+* Ref. 4 [[atomic_tables(module)]]
    real(Float64), intent(in) :: Erel
        !+ Relative collision energy [keV/amu]
    real(Float64)             :: sigma
        !+ Cross Section [\(cm^2\)]
    real(Float64), dimension(11), parameter :: a = [-1.149224555d6, 2.750368877d6, &
                                                    -2.942222842d6, 1.852584954d6, &
                                                    -7.603284323d5, 2.125284465d5, &
                                                    -4.097580431d4, 5.380901722d3, &
                                                    -4.606297192d2, 2.321345254d1, &
                                                    -5.230186707d-1 ]
    real(Float64), parameter :: n = 3.0
    real(Float64) :: ee, fac, l, p
    if(Erel.lt.90.0) then
        ee = max(Erel * 1.d3 * n**2.0, 1.d3) !keV to eV
        fac = 1.d0
    else
        ee = 90.0 * 1.d3 * n**2.0
        fac = 1.d16 * (Erel*n**2.0)**(-5.5)
    endif
    l = log10(ee)
    p = a(1) + a(2)*l + a(3)*l**2.0 + a(4)*l**3.0 + &
        a(5)*l**4.0   + a(6)*l**5.0 + a(7)*l**6.0 + &
        a(8)*l**7.0   + a(9)*l**8.0 + a(10)*l**9.0 + a(11)*l**10.d0
    sigma = fac*(10.d0**p)
end function p_cx_3_2_adas
Call graph
p_cx_3 calls p_cx_3_2_adas
p_cx_n calls p_cx_3
p_cx_n_m calls p_cx_n
p_cx calls p_cx_n
write_bb_h_h calls p_cx
generate_tables calls write_bb_h_h