p_excit_2_5_janev – FIDASIM
p_excit_2_5_janev Function
Source File
public function p_excit_2_5_janev(eb) result(sigma)
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: eb
Relative collision energy [keV/amu]
Return Value real(kind=Float64)
Cross Section [\(cm^2\)]
Description
Calculates cross section for a proton-Hydrogen impact excitation transition from the \(n=2\) state to the \(m=5\) state at energy eb
Equation
$$ H^+ + H(2) \rightarrow H^+ + H(5) $$
References
Eq. 32 and Table 6 in Ref. 2 atomic_tables
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=Float64), public, parameter, dimension(6) :: c = [18.264d0, 0.013701d0, 0.31711d0, -1.4775d0, 18.973d0, 2.9056d0]
Fitting parameters from Table 6 in Ref. 2
Source Code
function p_excit_2_5_janev(eb) result(sigma)
    !+Calculates cross section for a proton-Hydrogen impact excitation transition from
    !+the \(n=2\) state to the \(m=5\) state at energy `eb`
    !+
    !+###Equation
    !+$$ H^+ + H(2) \rightarrow H^+ + H(5) $$
    !+
    !+###References
    !+* Eq. 32 and Table 6 in Ref. 2 [[atomic_tables(module)]]
    !+
    real(Float64), intent(in) :: eb
        !+ Relative collision energy [keV/amu]
    real(Float64)             :: sigma
        !+ Cross Section [\(cm^2\)]
    real(Float64), dimension(6), parameter :: c = [18.264d0, 0.013701d0, &
                                                   0.31711d0, -1.4775d0, &
                                                   18.973d0,   2.9056d0  ]
        !+ Fitting parameters from Table 6 in Ref. 2
    sigma = 1.d-16 * c(1)*(c(2)*exp(-c(3)*eb)/(eb**c(4)) + &
                     exp(-c(5)/eb)*log(1.+c(6)*eb)/eb)
end function p_excit_2_5_janev
Call graph
p_excit_2_7_janev calls p_excit_2_5_janev
p_excit_2_8_janev calls p_excit_2_5_janev
p_excit_2_9_janev calls p_excit_2_5_janev
p_excit_2_10_janev calls p_excit_2_5_janev
p_excit_2_janev calls p_excit_2_5_janev, p_excit_2_7_janev, p_excit_2_8_janev, p_excit_2_9_janev, p_excit_2_10_janev, p_excit_2_6_janev
p_excit_2_6_janev calls p_excit_2_5_janev
p_excit_n calls p_excit_2_janev
p_excit calls p_excit_n
p_excit_n_m calls p_excit_n
write_bb_h_h calls p_excit
generate_tables calls write_bb_h_h