p_excit_3_9_janev – FIDASIM
p_excit_3_9_janev Function
6 statements
Source File
public function p_excit_3_9_janev(eb) result(sigma)
Calculates cross section for a proton-Hydrogen impact excitation transition from the state to the state at energy eb
Equation
References
Eq. 36 and Table 7 in Ref. 2 atomic_tables
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: eb
Relative collision energy [keV/amu]
Return Value real(kind=Float64)
Cross Section []
Calls
Called by
Contents
Source Code
p_excit_3_9_janev
Source Code
function p_excit_3_9_janev(eb) result(sigma)
    !+Calculates cross section for a proton-Hydrogen impact excitation transition from
    !+the \(n=3\) state to the \(m=9\) state at energy `eb`
    !+
    !+###Equation
    !+$$ H^+ + H(3) \rightarrow H^+ + H(9) $$
    !+
    !+###References
    !+* Eq. 36 and Table 7 in Ref. 2 [[atomic_tables(module)]]
    !+
    real(Float64), intent(in) :: eb
        !+ Relative collision energy [keV/amu]
    real(Float64)             :: sigma
        !+ Cross Section [\(cm^2\)]
    real(Float64), parameter :: A = 1.54d-1
    sigma = A*p_excit_3_6_janev(eb)
end function p_excit_3_9_janev
Call graph
p_excit_3_9_janev calls p_excit_3_6_janev
p_excit_3_janev calls p_excit_3_9_janev
p_excit_n calls p_excit_3_janev
p_excit_n_m calls p_excit_n
p_excit calls p_excit_n
write_bb_h_h calls p_excit
generate_tables calls write_bb_h_h