p_ioniz_2_omullane – FIDASIM
p_ioniz_2_omullane Function
13 statements
Source File
public function p_ioniz_2_omullane(eb) result(sigma)
Calculates cross section for a proton-Hydrogen impact ionization interaction from the state at energy eb
Equation
References
Eq. 5 and Table 1 in Ref. 3 atomic_tables
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: eb
Relative collision energy [keV/amu]
Return Value real(kind=Float64)
Cross Section []
Called by
Contents
Source Code
p_ioniz_2_omullane
Source Code
function p_ioniz_2_omullane(eb) result(sigma)
    !+Calculates cross section for a proton-Hydrogen impact ionization interaction
    !+from the \(n=2\) state at energy `eb`
    !+
    !+###Equation
    !+ $$H^+ + H(2) \rightarrow H^+ + H^+ + e$$
    !+###References
    !+* Eq. 5 and Table 1 in Ref. 3 [[atomic_tables(module)]]
    real(Float64), intent(in) :: eb
        !+ Relative collision energy [keV/amu]
    real(Float64)             :: sigma
        !+ Cross Section [\(cm^2\)]
    real(Float64), dimension(8), parameter :: b = [3.9330d-3, 1.8188d0,  &
                                                   1.8870d-2, 6.7489d-3, &
                                                   1.3768d0, 6.8852d2,   &
                                                   9.6435d1, 5.6515d23 ]
        !+ Fitting Parameters from Table 1 in Ref. 3
    real(Float64), parameter :: n2 = 4.d0
    real(Float64) :: Ehat
    real(Float64) :: p1, p2, p3
    Ehat = eb*n2
    p1 = b(1)*(n2)**2.0
    p2 = Ehat**b(2) * exp(-b(3)*Ehat) / (1.d0 + b(4)*Ehat**b(5))
    p3 = (b(6)* exp(-b(7)/Ehat) *log(1.d0  +b(8)*Ehat) ) /Ehat
    sigma = 1.0d-16 * p1 * (p2 + p3)
end function p_ioniz_2_omullane
Call graph
p_ioniz_n calls p_ioniz_2_omullane
p_ioniz calls p_ioniz_n
write_bb_h_h calls p_ioniz
generate_tables calls write_bb_h_h