plane_intercept – FIDASIM
plane_intercept Subroutine
Source File
public subroutine plane_intercept(l0, l, p0, n, p, t)
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in), dimension(3) :: l0
Point on line
real(kind=Float64), intent(in), dimension(3) :: l
Ray of line
real(kind=Float64), intent(in), dimension(3) :: p0
Point on plane
real(kind=Float64), intent(in), dimension(3) :: n
Normal vector of plane
real(kind=Float64), intent(out), dimension(3) :: p
Line-plane intercept point
real(kind=Float64), intent(out) :: t
"time" to intercept
Description
Calculates the intersection of a line and a plane
Called By
Source Code
subroutine plane_intercept(l0, l, p0, n, p, t)
    !+ Calculates the intersection of a line and a plane
    real(Float64), dimension(3), intent(in)  :: l0
        !+ Point on line
    real(Float64), dimension(3), intent(in)  :: l
        !+ Ray of line
    real(Float64), dimension(3), intent(in)  :: p0
        !+ Point on plane
    real(Float64), dimension(3), intent(in)  :: n
        !+ Normal vector of plane
    real(Float64), dimension(3), intent(out) :: p
        !+ Line-plane intercept point
    real(Float64), intent(out)               :: t
        !+ "time" to intercept
    t = dot_product(p0 - l0, n)/dot_product(l, n)
    p = l0 + t*l
end subroutine plane_intercept
Call graph
hit_npa_detector calls plane_intercept
npa_f calls hit_npa_detector
read_npa calls hit_npa_detector
npa_weights calls hit_npa_detector
npa_mc calls hit_npa_detector
fidasim calls npa_f, read_npa, npa_weights, npa_mc