read_mc – FIDASIM
read_mc Subroutine
126 statements
Source File
public subroutine read_mc(fid, error)
Reads in a MC particle fast-ion distribution and puts them in particles
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(inout) :: fid
HDF5 file ID
integer, intent(out) :: error
Error code
Calls
Called By
Source Code
read_mc
Source Code
subroutine read_mc(fid, error)
    !+ Reads in a MC particle fast-ion distribution and puts them in [[libfida:particles]]
    integer(HID_T), intent(inout) :: fid
        !+ HDF5 file ID
    integer, intent(out)          :: error
        !+ Error code
    integer(HSIZE_T), dimension(1) :: dims
    integer(Int32) :: i,j,ii,ir,iz
    real(Float64) :: phi,phi_enter,phi_exit,delta_phi,r_ratio
    real(Float64), dimension(3) :: uvw,ri,vi,e1_xyz,e2_xyz,C_xyz,dum
    integer(Int32), dimension(1) :: minpos
    real(Float64), dimension(:), allocatable :: weight
    real(Float64), dimension(:), allocatable :: r, z, vr, vt, vz
    real(Float64), dimension(:), allocatable :: energy, pitch
    integer(Int32), dimension(:), allocatable :: orbit_class
    type(LocalEMFields) :: fields
    integer :: cnt,num
    logical :: inp
    integer(Int32) :: npart,nrep
    character(len=32) :: dist_type_name = ''
    if(inputs%verbose.ge.1) then
        write(*,'(a)') '---- Fast-ion distribution settings ----'
    endif
    call h5ltread_dataset_int_scalar_f(fid, "/nparticle", npart, error)
    call h5ltread_dataset_int_scalar_f(fid, "/nclass", particles%nclass, error)
    nrep = ceiling(dble(inputs%n_fida)/npart)
    particles%nparticle = int(nrep*npart)
    !!ALLOCATE SPACE
    allocate(particles%fast_ion(particles%nparticle))
    allocate(r(npart))
    allocate(z(npart))
    allocate(vr(npart))
    allocate(vt(npart))
    allocate(vz(npart))
    allocate(weight(npart))
    allocate(orbit_class(npart))
    dims(1) = npart
    call h5ltread_dataset_double_f(fid, "/r", r, dims, error)
    call h5ltread_dataset_double_f(fid, "/z", z, dims, error)
    call h5ltread_dataset_double_f(fid, "/weight", weight, dims, error)
    call h5ltread_dataset_int_f(fid, "/class", orbit_class, dims, error)
    if(any(orbit_class.gt.particles%nclass)) then
        if(inputs%verbose.ge.0) then
            write(*,'(a)') 'READ_MC: Orbit class ID greater then the number of classes'
        endif
        stop
    endif
    if(inputs%dist_type.eq.2) then
        dist_type_name = "Guiding Center Monte Carlo"
        allocate(energy(npart))
        allocate(pitch(npart))
        call h5ltread_dataset_double_f(fid, "/energy", energy, dims, error)
        call h5ltread_dataset_double_f(fid, "/pitch", pitch, dims, error)
    else
        dist_type_name = "Full Orbit Monte Carlo"
        call h5ltread_dataset_double_f(fid, "/vr", vr, dims, error)
        call h5ltread_dataset_double_f(fid, "/vt", vt, dims, error)
        call h5ltread_dataset_double_f(fid, "/vz", vz, dims, error)
    endif
    cnt=0
    e1_xyz = matmul(beam_grid%inv_basis,[1.0,0.0,0.0])
    e2_xyz = matmul(beam_grid%inv_basis,[0.0,1.0,0.0])
    !$OMP PARALLEL DO schedule(guided) private(i,ii,j,ir,iz,minpos,fields,uvw,phi,ri,vi, &
    !$OMP& delta_phi,phi_enter,phi_exit,r_ratio,C_xyz)
    particle_loop: do i=1,npart
        if(inputs%verbose.ge.2) then
            WRITE(*,'(f7.2,"% completed",a,$)') cnt/real(npart)*100,char(13)
        endif
        uvw = [r(i), 0.d0, z(i)]
        call in_plasma(uvw,inp,machine_coords=.True.)
        if(.not.inp) cycle particle_loop
        do ii=1,nrep
            j = int((i-1)*nrep + ii)
            if(inputs%dist_type.eq.2) then
                !! Transform to full orbit
                call get_fields(fields,pos = uvw, machine_coords=.True.)
                call gyro_correction(fields, uvw, energy(i), pitch(i), ri, vi)
                particles%fast_ion(j)%r = sqrt(ri(1)**2 + ri(2)**2)
                particles%fast_ion(j)%z = ri(3)
                !r_ratio = particles%fast_ion(j)%r/r(i)
                r_ratio = 1.0
                phi = atan2(ri(2),ri(1))
                particles%fast_ion(j)%vr =  vi(1)*cos(phi) + vi(2)*sin(phi)
                particles%fast_ion(j)%vt = -vi(1)*sin(phi) + vi(2)*cos(phi)
                particles%fast_ion(j)%vz =  vi(3)
                particles%fast_ion(j)%pitch =  pitch(i)
            else
                particles%fast_ion(j)%r = r(i)
                particles%fast_ion(j)%z = z(i)
                particles%fast_ion(j)%vr = vr(i)
                particles%fast_ion(j)%vt = vt(i)
                particles%fast_ion(j)%vz = vz(i)
                r_ratio = 1.0
            endif
            particles%fast_ion(j)%vabs = sqrt(particles%fast_ion(j)%vr**2 + &
                                              particles%fast_ion(j)%vt**2 + &
                                              particles%fast_ion(j)%vz**2)
            particles%fast_ion(j)%energy = v2_to_E_per_amu*inputs%ab*particles%fast_ion(j)%vabs**2
            particles%fast_ion(j)%class = orbit_class(i)
            phi_enter = 0.0
            phi_exit = 0.0
            dum = [0.d0, 0.d0, particles%fast_ion(j)%z]
            call uvw_to_xyz(dum, C_xyz)
            call circle_grid_intersect(C_xyz,e1_xyz,e2_xyz,particles%fast_ion(j)%r,phi_enter,phi_exit)
            delta_phi = phi_exit-phi_enter
            if(delta_phi.gt.0) then
                particles%fast_ion(j)%cross_grid = .True.
            else
                particles%fast_ion(j)%cross_grid = .False.
                delta_phi = 2*pi
            endif
            particles%fast_ion(j)%phi_enter = phi_enter
            particles%fast_ion(j)%delta_phi = delta_phi
            particles%fast_ion(j)%weight = (r_ratio*weight(i)/nrep) * &
                                           (delta_phi/(2*pi))/beam_grid%dv
            minpos = minloc(abs(inter_grid%r - particles%fast_ion(j)%r))
            ir = minpos(1)
            minpos = minloc(abs(inter_grid%z - particles%fast_ion(j)%z))
            iz = minpos(1)
            !$OMP CRITICAL(mc_denf)
            equil%plasma(ir,iz)%denf = equil%plasma(ir,iz)%denf + &
                                       (r_ratio*weight(i)/nrep) / &
                                       (2*pi*particles%fast_ion(j)%r*inter_grid%da)
            !$OMP END CRITICAL(mc_denf)
        enddo
        cnt=cnt+1
    enddo particle_loop
    !$OMP END PARALLEL DO
    num = count(particles%fast_ion%cross_grid)
    if(num.le.0) then
        if(inputs%verbose.ge.0) then
            write(*,'(a)') 'READ_MC: No mc particles in beam grid'
        endif
        stop
    endif
    if(inputs%verbose.ge.1) then
        write(*,'(T2,"Distribution type: ",a)') dist_type_name
        write(*,'(T2,"Number of mc particles: ",i9)') npart
        write(*,'(T2,"Number of orbit classes: ",i6)') particles%nclass
        write(*,*) ''
    endif
end subroutine read_mc
All Procedures
approx_eq approx_ge approx_le Aq_cx Aq_cx_n Aq_cx_n_adas Aq_cx_n_janev Aq_excit Aq_excit_1_2_janev Aq_excit_1_3_janev Aq_excit_1_4_janev Aq_excit_1_5_janev Aq_excit_1_janev Aq_excit_2_10_janev Aq_excit_2_3_janev Aq_excit_2_4_janev Aq_excit_2_5_janev Aq_excit_2_6_janev Aq_excit_2_7_janev Aq_excit_2_8_janev Aq_excit_2_9_janev Aq_excit_2_janev Aq_excit_3_10_janev Aq_excit_3_4_janev Aq_excit_3_5_janev Aq_excit_3_6_janev Aq_excit_3_7_janev Aq_excit_3_8_janev Aq_excit_3_9_janev Aq_excit_3_janev Aq_excit_n Aq_excit_n_janev Aq_excit_n_m Aq_ioniz Aq_ioniz_n Aq_ioniz_n_janev assignment(=) attenuate B5_cx_1_adas B5_cx_1_janev B5_cx_2_adas B5_ioniz_1_janev balance balback bremsstrahlung bt_maxwellian bt_maxwellian_eb bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m C6_cx_1_adas C6_cx_1_janev C6_cx_2_adas C6_cx_3_adas C6_ioniz_1_janev calc_perp_vectors check_compression_availability circle_grid_intersect colrad comabs Comdiv cross_product d_d_fusion_he d_d_fusion_t d_t_fusion dcx e_excit e_excit_1_2_janev e_excit_1_3_janev e_excit_1_4_janev e_excit_1_5_janev e_excit_1_janev e_excit_2_3_janev e_excit_f e_excit_n e_excit_n_m e_ioniz e_ioniz_1_janev e_ioniz_2_janev e_ioniz_3_janev e_ioniz_n eigen elmhes elmtrans fast_ion_assign ff_add ff_assign ff_subtract fida_f fida_mc fida_weights_los fida_weights_mc flf_assign fs_divide fs_multiply get_beam_cx_prob get_distribution get_ep_denf get_fields get_indices get_neutron_rate get_nlaunch get_plasma get_position get_rate_matrix get_value grid_intersect gyro_correction gyro_step h5ltmake_compressed_dataset_double_f h5ltmake_compressed_dataset_double_f_1 h5ltmake_compressed_dataset_double_f_2 h5ltmake_compressed_dataset_double_f_3 h5ltmake_compressed_dataset_double_f_4 h5ltmake_compressed_dataset_double_f_5 h5ltmake_compressed_dataset_double_f_6 h5ltmake_compressed_dataset_double_f_7 h5ltmake_compressed_dataset_int_f h5ltmake_compressed_dataset_int_f_1 h5ltmake_compressed_dataset_int_f_2 h5ltmake_compressed_dataset_int_f_3 h5ltmake_compressed_dataset_int_f_4 h5ltmake_compressed_dataset_int_f_5 h5ltmake_compressed_dataset_int_f_6 h5ltmake_compressed_dataset_int_f_7 h5ltread_dataset_double_scalar_f h5ltread_dataset_int_scalar_f halo hit_npa_detector hqr2 hqrvec in_boundary in_grid in_plasma ind2sub interpol interpol1D_arr interpol1D_coeff interpol1D_coeff_arr interpol2D_2D_arr interpol2D_arr interpol2D_coeff interpol2D_coeff_arr interpol_coeff lff_assign lflf_add lflf_assign lflf_subtract lfs_divide lfs_multiply line_basis lplp_add lplp_assign lplp_subtract lpp_assign lps_divide lps_multiply lubksb ludcmp m_spread make_beam_grid matinv mc_fastion mc_halo mc_nbi ndmc neut_rates neutron_f neutron_mc npa_f npa_mc npa_part_assign npa_weights operator(*) operator(+) operator(-) operator(/) outerprod p_cx p_cx_1 p_cx_1_1_adas p_cx_1_2_adas p_cx_1_3_adas p_cx_1_4_adas p_cx_1_janev p_cx_2 p_cx_2_2_adas p_cx_2_3_adas p_cx_2_janev p_cx_3 p_cx_3_2_adas p_cx_3_3_adas p_cx_3_4_adas p_cx_3_5_adas p_cx_3_6inf_adas p_cx_3_janev p_cx_janev p_cx_n p_cx_n_janev p_cx_n_m p_excit p_excit_1_2_janev p_excit_1_3_janev p_excit_1_4_janev p_excit_1_5_janev p_excit_1_6_janev p_excit_1_janev p_excit_2_10_janev p_excit_2_3_janev p_excit_2_4_janev p_excit_2_5_janev p_excit_2_6_janev p_excit_2_7_janev p_excit_2_8_janev p_excit_2_9_janev p_excit_2_janev p_excit_3_10_janev p_excit_3_4_janev p_excit_3_5_janev p_excit_3_6_janev p_excit_3_7_janev p_excit_3_8_janev p_excit_3_9_janev p_excit_3_janev p_excit_n p_excit_n_m p_ioniz p_ioniz_1_janev p_ioniz_2_omullane p_ioniz_3_omullane p_ioniz_4_omullane p_ioniz_5_omullane p_ioniz_n pitch_to_vec plane_basis plane_intercept plp_assign pp_add pp_assign pp_subtract print_banner print_default_namelist ps_divide ps_multiply randind randn randu read_atomic_cross read_atomic_rates read_beam read_chords read_distribution read_equilibrium read_f read_inputs read_mc read_neutrals read_npa read_nuclear_rates read_tables rng_init rng_normal rng_uniform RSWAP sf_multiply simpsons_rule slf_multiply slp_multiply sp_multiply sparse spectrum store_bes_photons store_births store_fida_photons store_fw_photons store_fw_photons_at_chan store_neutrals store_neutrons store_npa sub2ind swap tb_zyx track uvw_to_xyz write_bb_D_D write_bb_D_T write_bb_H_Aq write_bb_H_e write_bb_H_H write_beam_grid write_birth_profile write_bt_D_D write_bt_D_T write_bt_H_Aq write_bt_H_e write_bt_H_H write_dcx write_einstein write_fida_weights write_neutrals write_neutrons write_npa write_npa_weights write_spectra xyz_to_uvw
Call graph
read_mc calls uvw_to_xyz, in_plasma, h5ltread_dataset_int_f, gyro_correction, circle_grid_intersect, get_fields, h5ltread_dataset_double_f, h5ltread_dataset_int_scalar_f
in_plasma calls xyz_to_uvw, interpol_coeff
gyro_correction calls gyro_step, randu, pitch_to_vec
circle_grid_intersect calls grid_intersect, in_grid, approx_eq
get_fields calls in_plasma, get_position, calc_perp_vectors
h5ltread_dataset_int_scalar_f calls h5ltread_dataset_int_f
interpol_coeff calls interpol1d_coeff_arr, interpol2d_coeff_arr, interpol1d_coeff, interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
interpol2d_coeff_arr calls interpol2d_coeff
gyro_step calls cross_product
randu calls omp_get_thread_num, rng_uniform
in_grid calls approx_ge, approx_le
approx_ge calls approx_eq
approx_le calls approx_eq
read_distribution calls read_mc
fidasim calls read_distribution