bt_maxwellian – FIDASIM
bt_maxwellian Interface
4 statements
Source File
public interface bt_maxwellian
Calculates the reaction rate coefficients given beam energy eb and target temperature T where the velocity distribution of the target is a Maxwellian
Calls
Called By
Module Procedures
bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m
Module Procedures
public subroutine bt_maxwellian_n(fn, T, eb, am, ab, n, rate)
Calculates Maxwellian reaction rate for a beam with atomic mass ab, energy eb, and energy level n firing into a target with atomic mass am and temperature T which has a cross section given by the function fn
Arguments
Type Intent Optional Attributes Name
public function fn(a, b)
Cross section function
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in) :: a
integer, intent(in) :: b
Return Value real(kind=8)
real(kind=Float64), intent(in) :: T
Target temperature [keV]
real(kind=Float64), intent(in) :: eb
Beam energy [keV]
real(kind=Float64), intent(in) :: am
Target atomic mass [amu]
real(kind=Float64), intent(in) :: ab
Beam atomic mass [amu]
integer, intent(in) :: n
Initial atomic energy level/state
real(kind=Float64), intent(out) :: rate
Reaction Rate [\(cm^3/s\)]
public subroutine bt_maxwellian_n_m(fnm, T, eb, am, ab, n, m, rate, deexcit)
Calculates Maxwellian reaction rate for a n(\rightarrow)m transition due to a beam with atomic mass ab and energy eb firing into a target with atomic mass am and temperature T which has a cross section given by the function fnm
Arguments
Type Intent Optional Attributes Name
public function fnm(a, b, c)
Cross section function
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in) :: a
integer, intent(in) :: b
integer, intent(in) :: c
Return Value real(kind=8)
real(kind=Float64), intent(in) :: T
Target temperature [keV]
real(kind=Float64), intent(in) :: eb
Beam energy [keV]
real(kind=Float64), intent(in) :: am
Target atomic mass [amu]
real(kind=Float64), intent(in) :: ab
Beam atomic mass [amu]
integer, intent(in) :: n
Initial atomic energy level/state
integer, intent(in) :: m
Final atomic energy level/state
real(kind=Float64), intent(out) :: rate
Reaction Rate [\(cm^3/s\)]
logical, intent(in), optional :: deexcit
Calculate de-excitation reaction rate
public subroutine bt_maxwellian_q_n(fqn, q, T, eb, am, ab, n, rate)
Calculates Maxwellian reaction rate for a beam with atomic mass ab, energy eb, and energy level n firing into a target with atomic mass am, temperature T, and charge q which has a cross section given by the function fqn
Arguments
Type Intent Optional Attributes Name
public function fqn(a, b, c)
Cross section function
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in) :: a
integer, intent(in) :: b
integer, intent(in) :: c
Return Value real(kind=8)
integer, intent(in) :: q
Target charge
real(kind=Float64), intent(in) :: T
Target temperature [keV]
real(kind=Float64), intent(in) :: eb
Beam energy [keV]
real(kind=Float64), intent(in) :: am
Target atomic mass [amu]
real(kind=Float64), intent(in) :: ab
Beam atomic mass [amu]
integer, intent(in) :: n
Initial atomic energy level/state
real(kind=Float64), intent(out) :: rate
Reaction Rate [\(cm^3/s\)]
public subroutine bt_maxwellian_q_n_m(fqnm, q, T, eb, am, ab, n, m, rate, deexcit)
Calculates Maxwellian reaction rate for a n(\rightarrow)m transition due to a beam with atomic mass ab and energy eb firing into a target with atomic mass am, temperature T, and charge q which has a cross section given by the function fqnm
Arguments
Type Intent Optional Attributes Name
public function fqnm(a, b, c, d)
Cross section function
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in) :: a
integer, intent(in) :: b
integer, intent(in) :: c
integer, intent(in) :: d
Return Value real(kind=8)
integer, intent(in) :: q
Target charge
real(kind=Float64), intent(in) :: T
Target temperature [keV]
real(kind=Float64), intent(in) :: eb
Beam energy [keV]
real(kind=Float64), intent(in) :: am
Target atomic mass [amu]
real(kind=Float64), intent(in) :: ab
Beam atomic mass [amu]
integer, intent(in) :: n
Initial atomic energy level/state
integer, intent(in) :: m
Final atomic energy level/state
real(kind=Float64), intent(out) :: rate
Reaction Rate [\(cm^3/s\)]
logical, intent(in), optional :: deexcit
Calculate de-excitation reaction rate
All Procedures
approx_eq approx_ge approx_le Aq_cx Aq_cx_n Aq_cx_n_adas Aq_cx_n_janev Aq_excit Aq_excit_1_2_janev Aq_excit_1_3_janev Aq_excit_1_4_janev Aq_excit_1_5_janev Aq_excit_1_janev Aq_excit_2_10_janev Aq_excit_2_3_janev Aq_excit_2_4_janev Aq_excit_2_5_janev Aq_excit_2_6_janev Aq_excit_2_7_janev Aq_excit_2_8_janev Aq_excit_2_9_janev Aq_excit_2_janev Aq_excit_3_10_janev Aq_excit_3_4_janev Aq_excit_3_5_janev Aq_excit_3_6_janev Aq_excit_3_7_janev Aq_excit_3_8_janev Aq_excit_3_9_janev Aq_excit_3_janev Aq_excit_n Aq_excit_n_janev Aq_excit_n_m Aq_ioniz Aq_ioniz_n Aq_ioniz_n_janev assignment(=) attenuate B5_cx_1_adas B5_cx_1_janev B5_cx_2_adas B5_ioniz_1_janev balance balback bremsstrahlung bt_maxwellian bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m C6_cx_1_adas C6_cx_1_janev C6_cx_2_adas C6_cx_3_adas C6_ioniz_1_janev calc_perp_vectors check_compression_availability circle_grid_intersect colrad comabs Comdiv cross_product dcx e_excit e_excit_1_2_janev e_excit_1_3_janev e_excit_1_4_janev e_excit_1_5_janev e_excit_1_janev e_excit_2_3_janev e_excit_f e_excit_n e_excit_n_m e_ioniz e_ioniz_1_janev e_ioniz_2_janev e_ioniz_3_janev e_ioniz_n eigen elmhes elmtrans fast_ion_assign ff_add ff_assign ff_subtract fida_f fida_mc fida_weights_los fida_weights_mc flf_assign fs_divide fs_multiply get_beam_cx_prob get_distribution get_ep_denf get_fields get_indices get_nlaunch get_plasma get_position get_rate_matrix grid_intersect gyro_correction gyro_step h5ltmake_compressed_dataset_double_f h5ltmake_compressed_dataset_double_f_1 h5ltmake_compressed_dataset_double_f_2 h5ltmake_compressed_dataset_double_f_3 h5ltmake_compressed_dataset_double_f_4 h5ltmake_compressed_dataset_double_f_5 h5ltmake_compressed_dataset_double_f_6 h5ltmake_compressed_dataset_double_f_7 h5ltmake_compressed_dataset_int_f h5ltmake_compressed_dataset_int_f_1 h5ltmake_compressed_dataset_int_f_2 h5ltmake_compressed_dataset_int_f_3 h5ltmake_compressed_dataset_int_f_4 h5ltmake_compressed_dataset_int_f_5 h5ltmake_compressed_dataset_int_f_6 h5ltmake_compressed_dataset_int_f_7 h5ltread_dataset_double_scalar_f h5ltread_dataset_int_scalar_f halo hit_npa_detector hqr2 hqrvec in_boundary in_grid in_plasma ind2sub interpol interpol1D_arr interpol1D_coeff interpol1D_coeff_arr interpol2D_2D_arr interpol2D_arr interpol2D_coeff interpol2D_coeff_arr interpol_coeff lff_assign lflf_add lflf_assign lflf_subtract lfs_divide lfs_multiply line_basis lplp_add lplp_assign lplp_subtract lpp_assign lps_divide lps_multiply lubksb ludcmp m_spread make_beam_grid matinv mc_fastion mc_halo mc_nbi ndmc neut_rates npa_f npa_mc npa_part_assign npa_weights operator(*) operator(+) operator(-) operator(/) outerprod p_cx p_cx_1 p_cx_1_1_adas p_cx_1_2_adas p_cx_1_3_adas p_cx_1_4_adas p_cx_1_janev p_cx_2 p_cx_2_2_adas p_cx_2_3_adas p_cx_2_janev p_cx_3 p_cx_3_2_adas p_cx_3_3_adas p_cx_3_4_adas p_cx_3_5_adas p_cx_3_6inf_adas p_cx_3_janev p_cx_janev p_cx_n p_cx_n_janev p_cx_n_m p_excit p_excit_1_2_janev p_excit_1_3_janev p_excit_1_4_janev p_excit_1_5_janev p_excit_1_6_janev p_excit_1_janev p_excit_2_10_janev p_excit_2_3_janev p_excit_2_4_janev p_excit_2_5_janev p_excit_2_6_janev p_excit_2_7_janev p_excit_2_8_janev p_excit_2_9_janev p_excit_2_janev p_excit_3_10_janev p_excit_3_4_janev p_excit_3_5_janev p_excit_3_6_janev p_excit_3_7_janev p_excit_3_8_janev p_excit_3_9_janev p_excit_3_janev p_excit_n p_excit_n_m p_ioniz p_ioniz_1_janev p_ioniz_2_omullane p_ioniz_3_omullane p_ioniz_4_omullane p_ioniz_5_omullane p_ioniz_n pitch_to_vec plane_basis plane_intercept plp_assign pp_add pp_assign pp_subtract print_banner print_default_namelist ps_divide ps_multiply randind randn randu read_beam read_chords read_cross read_distribution read_equilibrium read_f read_inputs read_mc read_neutrals read_npa read_rates read_tables rng_init rng_normal rng_uniform RSWAP sf_multiply simpsons_rule slf_multiply slp_multiply sp_multiply spectrum store_bes_photons store_births store_fida_photons store_fw_photons store_fw_photons_at_chan store_neutrals store_npa swap tb_zyx track uvw_to_xyz write_bb_H_Aq write_bb_H_e write_bb_H_H write_beam_grid write_birth_profile write_bt_H_Aq write_bt_H_e write_bt_H_H write_dcx write_einstein write_fida_weights write_neutrals write_npa write_npa_weights write_spectra xyz_to_uvw
Call graph
bt_maxwellian calls bt_maxwellian_q_n_m, bt_maxwellian_q_n, bt_maxwellian_n, bt_maxwellian_n_m
bt_maxwellian_q_n_m calls simpsons_rule
bt_maxwellian_q_n calls simpsons_rule
bt_maxwellian_n calls simpsons_rule
bt_maxwellian_n_m calls simpsons_rule
write_bt_h_h calls bt_maxwellian
write_bt_h_e calls bt_maxwellian
write_bt_h_aq calls bt_maxwellian
generate_tables calls write_bt_h_h, write_bt_h_e, write_bt_h_aq