assignment(=) – FIDASIM
assignment(=) Interface
3 statements
Source File
public interface assignment(=)
Allows for assigning Profiles,LocalProfiles, EMFields,LocalEMFields,FastIon, NPAParticle, and BirthParticle
Calls
Contents
Module Procedures
pp_assign lpp_assign plp_assign lplp_assign ff_assign lff_assign flf_assign lflf_assign fast_ion_assign npa_part_assign birth_part_assign neutral_part_assign npr_assign np_assign oo_assign
Module Procedures
public pure subroutine pp_assign(p1, p2)
Defines how to assign Profiles types to eachother
Arguments
Type Intent Optional Attributes Name
type(Profiles), intent(inout) :: p1
type(Profiles), intent(in) :: p2
public pure subroutine lpp_assign(p1, p2)
Defines how to assign a Profiles type to a LocalProfiles type
Arguments
Type Intent Optional Attributes Name
type(LocalProfiles), intent(inout) :: p1
type(Profiles), intent(in) :: p2
public pure subroutine plp_assign(p1, p2)
Defines how to assign a LocalProfiles type to a Profiles type
Arguments
Type Intent Optional Attributes Name
type(Profiles), intent(inout) :: p1
type(LocalProfiles), intent(in) :: p2
public pure subroutine lplp_assign(p1, p2)
Defines how to assign LocalProfiles types to eachother
Arguments
Type Intent Optional Attributes Name
type(LocalProfiles), intent(inout) :: p1
type(LocalProfiles), intent(in) :: p2
public pure subroutine ff_assign(p1, p2)
Defines how to assign EMFields types to eachother
Arguments
Type Intent Optional Attributes Name
type(EMFields), intent(inout) :: p1
type(EMFields), intent(in) :: p2
public pure subroutine lff_assign(p1, p2)
Defines how to assign a EMFields type to a LocalEMFields type
Arguments
Type Intent Optional Attributes Name
type(LocalEMFields), intent(inout) :: p1
type(EMFields), intent(in) :: p2
public pure subroutine flf_assign(p1, p2)
Defines how to assign a LocalEMFields type to a EMFields type
Arguments
Type Intent Optional Attributes Name
type(EMFields), intent(inout) :: p1
type(LocalEMFields), intent(in) :: p2
public pure subroutine lflf_assign(p1, p2)
Defines how to assign LocalEMFields types to eachother
Arguments
Type Intent Optional Attributes Name
type(LocalEMFields), intent(inout) :: p1
type(LocalEMFields), intent(in) :: p2
public subroutine fast_ion_assign(p1, p2)
Defines how to assign FastIon types to eachother
Arguments
Type Intent Optional Attributes Name
type(FastIon), intent(out) :: p1
type(FastIon), intent(in) :: p2
public subroutine npa_part_assign(p1, p2)
Defines how to assign NPAParticle types to eachother
Arguments
Type Intent Optional Attributes Name
type(NPAParticle), intent(out) :: p1
type(NPAParticle), intent(in) :: p2
public subroutine birth_part_assign(p1, p2)
Defines how to assign BirthParticle types to eachother
Arguments
Type Intent Optional Attributes Name
type(BirthParticle), intent(out) :: p1
type(BirthParticle), intent(in) :: p2
public subroutine neutral_part_assign(p1, p2)
Defines how to assign NeutralParticle types to eachother
Arguments
Type Intent Optional Attributes Name
type(NeutralParticle), intent(out) :: p1
type(NeutralParticle), intent(in) :: p2
public subroutine npr_assign(r1, r2)
Defines how to assign NeutralParticleReservoir to eachother
Arguments
Type Intent Optional Attributes Name
type(NeutralParticleReservoir), intent(inout) :: r1
type(NeutralParticleReservoir), intent(in) :: r2
public subroutine np_assign(n1, n2)
Defines how to assign NeutralPopulation to eachother
Arguments
Type Intent Optional Attributes Name
type(NeutralPopulation), intent(inout) :: n1
type(NeutralPopulation), intent(in) :: n2
public pure subroutine oo_assign(p1, p2)
Defines how to assign CFPDTable types to eachother
Arguments
Type Intent Optional Attributes Name
type(CFPDTable), intent(out) :: p1
type(CFPDTable), intent(in) :: p2
Call graph
assignment(=) calls lff_assign, oo_assign, lplp_assign, birth_part_assign, neutral_part_assign, plp_assign, flf_assign, ff_assign, npa_part_assign, np_assign, lpp_assign, fast_ion_assign, lflf_assign, npr_assign, pp_assign
np_assign calls npr_assign, ind2sub
npr_assign calls init_reservoir
init_reservoir calls randu