interpol_coeff – FIDASIM
interpol_coeff Interface
4 statements
Source File
public interface interpol_coeff
Calculates linear interpolation coefficients
Calls
Called By
Module Procedures
interpol1D_coeff interpol1D_coeff_arr interpol2D_coeff interpol2D_coeff_arr
Module Procedures
public subroutine interpol1D_coeff(xmin, dx, nx, xout, c, err)
Linear interpolation coefficients and index for a 1D grid y(x)
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: xmin
Minimum abscissa value
real(kind=Float64), intent(in) :: dx
Absissa spacing
integer, intent(in) :: nx
Number of abscissa
real(kind=Float64), intent(in) :: xout
Abscissa value to interpolate
type(InterpolCoeffs1D), intent(out) :: c
Interpolation Coefficients
integer, intent(out), optional :: err
Error code
public subroutine interpol1D_coeff_arr(x, xout, c, err)
Linear interpolation coefficients and index for a 1D grid y(x)
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in), dimension(:) :: x
Abscissa values
real(kind=Float64), intent(in) :: xout
Abscissa value to interpolate
type(InterpolCoeffs1D), intent(out) :: c
Interpolation Coefficients
integer, intent(out), optional :: err
Error code
public subroutine interpol2D_coeff(xmin, dx, nx, ymin, dy, ny, xout, yout, c, err)
Bilinear interpolation coefficients and indicies for a 2D grid z(x,y)
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in) :: xmin
Minimum abscissa
real(kind=Float64), intent(in) :: dx
Abscissa spacing
integer, intent(in) :: nx
Number of abscissa
real(kind=Float64), intent(in) :: ymin
Minimum ordinate
real(kind=Float64), intent(in) :: dy
Ordinate spacing
integer, intent(in) :: ny
Number of ordinates points
real(kind=Float64), intent(in) :: xout
Abscissa value to interpolate
real(kind=Float64), intent(in) :: yout
Ordinate value to interpolate
type(InterpolCoeffs2D), intent(out) :: c
Interpolation Coefficients
integer, intent(out), optional :: err
Error code
public subroutine interpol2D_coeff_arr(x, y, xout, yout, c, err)
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in), dimension(:) :: x
Abscissa values
real(kind=Float64), intent(in), dimension(:) :: y
Ordinate values
real(kind=Float64), intent(in) :: xout
Abscissa value to interpolate
real(kind=Float64), intent(in) :: yout
Ordinate value to interpolate
type(InterpolCoeffs2D), intent(out) :: c
Interpolation Coefficients
integer, intent(out), optional :: err
Error code
All Procedures
approx_eq approx_ge approx_le Aq_cx Aq_cx_n Aq_cx_n_adas Aq_cx_n_janev Aq_excit Aq_excit_1_2_janev Aq_excit_1_3_janev Aq_excit_1_4_janev Aq_excit_1_5_janev Aq_excit_1_janev Aq_excit_2_10_janev Aq_excit_2_3_janev Aq_excit_2_4_janev Aq_excit_2_5_janev Aq_excit_2_6_janev Aq_excit_2_7_janev Aq_excit_2_8_janev Aq_excit_2_9_janev Aq_excit_2_janev Aq_excit_3_10_janev Aq_excit_3_4_janev Aq_excit_3_5_janev Aq_excit_3_6_janev Aq_excit_3_7_janev Aq_excit_3_8_janev Aq_excit_3_9_janev Aq_excit_3_janev Aq_excit_n Aq_excit_n_janev Aq_excit_n_m Aq_ioniz Aq_ioniz_n Aq_ioniz_n_janev assignment(=) attenuate B5_cx_1_adas B5_cx_1_janev B5_cx_2_adas B5_ioniz_1_janev balance balback bb_cx_rates boundary_edge bremsstrahlung bt_cx_rates bt_maxwellian bt_maxwellian_eb bt_maxwellian_n bt_maxwellian_n_m bt_maxwellian_q_n bt_maxwellian_q_n_m C6_cx_1_adas C6_cx_1_janev C6_cx_2_adas C6_cx_3_adas C6_ioniz_1_janev calc_perp_vectors check_compression_availability circle_grid_intersect cold_spec colrad comabs Comdiv cross_product cumsum d_d_fusion_he d_d_fusion_t d_t_fusion dcx dcx_spec deriv e_excit e_excit_1_2_janev e_excit_1_3_janev e_excit_1_4_janev e_excit_1_5_janev e_excit_1_janev e_excit_2_3_janev e_excit_f e_excit_n e_excit_n_m e_ioniz e_ioniz_1_janev e_ioniz_2_janev e_ioniz_3_janev e_ioniz_n eigen elmhes elmtrans fast_ion_assign ff_add ff_assign ff_subtract fida_f fida_mc fida_weights_los fida_weights_mc fidampi_clenup fidampi_init fidampi_my_rank fidampi_num_ranks fidampi_sum fidampi_sum_d0 fidampi_sum_d1 fidampi_sum_d2 fidampi_sum_d3 fidampi_sum_d4 fidampi_sum_d5 fidampi_sum_i0 fidampi_sum_i1 fidampi_sum_i2 flf_assign fs_divide fs_multiply get_beam_cx_rate get_distribution get_ep_denf get_fields get_indices get_neutron_rate get_nlaunch get_plasma get_position get_rate_matrix get_rng get_value grid_intersect gyro_correction gyro_radius gyro_range gyro_step gyro_surface gyro_surface_coordinates gyro_trajectory h5ltmake_compressed_dataset_double_f h5ltmake_compressed_dataset_double_f_1 h5ltmake_compressed_dataset_double_f_2 h5ltmake_compressed_dataset_double_f_3 h5ltmake_compressed_dataset_double_f_4 h5ltmake_compressed_dataset_double_f_5 h5ltmake_compressed_dataset_double_f_6 h5ltmake_compressed_dataset_double_f_7 h5ltmake_compressed_dataset_int_f h5ltmake_compressed_dataset_int_f_1 h5ltmake_compressed_dataset_int_f_2 h5ltmake_compressed_dataset_int_f_3 h5ltmake_compressed_dataset_int_f_4 h5ltmake_compressed_dataset_int_f_5 h5ltmake_compressed_dataset_int_f_6 h5ltmake_compressed_dataset_int_f_7 h5ltread_dataset_double_scalar_f h5ltread_dataset_int_scalar_f halo halo_spec hit_npa_detector hqr2 hqrvec in_boundary in_grid in_gyro_surface in_plasma ind2sub interpol interpol1D_arr interpol1D_coeff interpol1D_coeff_arr interpol2D_2D_arr interpol2D_arr interpol2D_coeff interpol2D_coeff_arr interpol_coeff lff_assign lflf_add lflf_assign lflf_subtract lfs_divide lfs_multiply line_basis line_gyro_surface_intersect line_plane_intersect linsolve lplp_add lplp_assign lplp_subtract lpp_assign lps_divide lps_multiply lubksb ludcmp m_spread make_beam_grid matinv mc_fastion mc_halo mc_nbi mc_nbi_cell nbi_spec ndmc neutron_f neutron_mc norm2 npa_f npa_gyro_range npa_mc npa_part_assign npa_weights operator(*) operator(+) operator(-) operator(/) outerprod p_cx p_cx_1 p_cx_1_1_adas p_cx_1_2_adas p_cx_1_3_adas p_cx_1_4_adas p_cx_1_janev p_cx_2 p_cx_2_2_adas p_cx_2_3_adas p_cx_2_janev p_cx_3 p_cx_3_2_adas p_cx_3_3_adas p_cx_3_4_adas p_cx_3_5_adas p_cx_3_6inf_adas p_cx_3_janev p_cx_janev p_cx_n p_cx_n_janev p_cx_n_m p_excit p_excit_1_2_janev p_excit_1_3_janev p_excit_1_4_janev p_excit_1_5_janev p_excit_1_6_janev p_excit_1_janev p_excit_2_10_janev p_excit_2_3_janev p_excit_2_4_janev p_excit_2_5_janev p_excit_2_6_janev p_excit_2_7_janev p_excit_2_8_janev p_excit_2_9_janev p_excit_2_janev p_excit_3_10_janev p_excit_3_4_janev p_excit_3_5_janev p_excit_3_6_janev p_excit_3_7_janev p_excit_3_8_janev p_excit_3_9_janev p_excit_3_janev p_excit_n p_excit_n_m p_ioniz p_ioniz_1_janev p_ioniz_2_omullane p_ioniz_3_omullane p_ioniz_4_omullane p_ioniz_5_omullane p_ioniz_n pfida_f pfida_mc pitch_to_vec plane_basis plp_assign pnpa_f pnpa_mc pp_add pp_assign pp_subtract print_banner print_default_namelist ps_divide ps_multiply randind randind_cdf randn randu read_atomic_cross read_atomic_rate read_atomic_transitions read_beam read_chords read_distribution read_equilibrium read_f read_inputs read_mc read_neutrals read_npa read_nuclear_rates read_tables rng_init rng_normal rng_seed rng_uniform RSWAP sf_multiply simpsons_rule slf_multiply slp_multiply sp_multiply sparse spectrum store_bes_photons store_births store_fida_photons store_fw_photons store_fw_photons_at_chan store_neutrals store_neutrons store_npa store_photons sub2ind swap tb_zyx time track uvw_to_xyz write_bb_D_D write_bb_D_T write_bb_H_Aq write_bb_H_e write_bb_H_H write_beam_grid write_birth_profile write_bt_D_D write_bt_D_T write_bt_H_Aq write_bt_H_e write_bt_H_H write_einstein write_fida_weights write_neutrals write_neutrons write_npa write_npa_weights write_spectra xyz_to_uvw
Call graph
interpol_coeff calls interpol2d_coeff_arr, interpol2d_coeff, interpol1d_coeff, interpol1d_coeff_arr
interpol2d_coeff_arr calls interpol2d_coeff
interpol1d_coeff_arr calls interpol1d_coeff
in_plasma calls interpol_coeff
bt_cx_rates calls interpol_coeff
interpol2d_arr calls interpol_coeff
get_neutron_rate calls interpol_coeff
interpol2d_2d_arr calls interpol_coeff
get_rate_matrix calls interpol_coeff
interpol1d_arr calls interpol_coeff
bb_cx_rates calls interpol_coeff
mc_nbi calls in_plasma
halo_spec calls in_plasma, get_plasma, store_photons
get_fields calls in_plasma
track calls in_plasma
get_plasma calls in_plasma
dcx_spec calls in_plasma, get_plasma, store_photons
read_mc calls in_plasma
nbi_spec calls in_plasma, store_photons
make_beam_grid calls in_plasma
ndmc calls mc_nbi, track, get_plasma, store_bes_photons, colrad
fidasim calls halo_spec, dcx_spec, nbi_spec, make_beam_grid, ndmc, read_npa, neutron_f, npa_weights, fida_mc, fida_weights_los, neutron_mc, pnpa_mc, fida_weights_mc, npa_mc, pfida_mc, fida_f, pnpa_f, pfida_f, npa_f, cold_spec, dcx, halo, read_chords, bremsstrahlung, read_distribution, read_equilibrium
store_fw_photons calls get_fields
mc_fastion calls get_fields, get_distribution
read_npa calls get_fields
neutron_f calls get_neutron_rate, get_fields, get_plasma
npa_weights calls get_fields, attenuate, get_beam_cx_rate, get_ep_denf
fida_mc calls get_fields, track, get_plasma, store_fida_photons, get_beam_cx_rate, colrad
fida_weights_los calls bt_cx_rates, bb_cx_rates, get_fields, track, get_plasma, get_ep_denf, colrad
neutron_mc calls get_neutron_rate, get_fields, get_plasma
pnpa_mc calls bt_cx_rates, get_fields, get_plasma, store_npa, attenuate
store_npa calls get_fields
fida_weights_mc calls get_fields, track, get_plasma, store_fw_photons, get_beam_cx_rate, get_ep_denf, colrad
store_photons calls get_fields
npa_mc calls get_fields, store_npa, attenuate, get_beam_cx_rate
pfida_mc calls bt_cx_rates, get_fields, track, get_plasma, store_fida_photons, colrad
fida_f calls track, get_plasma, mc_fastion, store_fida_photons, get_beam_cx_rate, colrad
pnpa_f calls bt_cx_rates, get_plasma, mc_fastion, store_npa, attenuate
pfida_f calls bt_cx_rates, track, get_plasma, mc_fastion, store_fida_photons, colrad
npa_f calls get_plasma, mc_fastion, store_npa, attenuate, get_beam_cx_rate
store_fida_photons calls store_photons
cold_spec calls get_plasma, store_photons
store_bes_photons calls store_photons
dcx calls track, get_plasma, store_bes_photons, mc_halo, get_beam_cx_rate, colrad
halo calls bt_cx_rates, track, get_plasma, store_bes_photons, mc_halo, colrad
read_chords calls track
mc_halo calls get_plasma
attenuate calls get_plasma, colrad
bremsstrahlung calls get_plasma
get_beam_cx_rate calls bt_cx_rates, bb_cx_rates, get_plasma
read_distribution calls read_mc
interpol calls interpol2d_arr, interpol2d_2d_arr, interpol1d_arr
get_distribution calls interpol
get_ep_denf calls interpol
colrad calls get_rate_matrix
read_equilibrium calls colrad