randind_cdf – FIDASIM
randind_cdf Interface
4 statements
Source File
public interface randind_cdf
Procedure for generating a random array index/subscripts
Called by
Contents
Module Procedures
randind_r_cdf_1 randind_cdf_1
Module Procedures
private subroutine randind_r_cdf_1(r, cdf, randomi)
Generate an array of random indices of an 1D array distributed according to cdf
Arguments
Type Intent Optional Attributes Name
type(rng_type), intent(inout) :: r
Random Number Generator
real(kind=Float64), intent(in), dimension(:) :: cdf
1D array of index weights
integer, intent(out), dimension(:) :: randomi
Random indices
private subroutine randind_cdf_1(cdf, randomi)
Generate an array of random indices of an 1D array distributed according to cdf
Arguments
Type Intent Optional Attributes Name
real(kind=Float64), intent(in), dimension(:) :: cdf
1D array of index weights
integer, intent(out), dimension(:) :: randomi
Random indices
Call graph
get_nlaunch calls randind_cdf
get_nlaunch_pass_grid calls randind_cdf
dcx calls get_nlaunch
pfida_f calls get_nlaunch_pass_grid
npa_f calls get_nlaunch
pnpa_f calls get_nlaunch_pass_grid
fida_f calls get_nlaunch
fida_weights_mc calls get_nlaunch
halo calls get_nlaunch
fidasim calls dcx, pfida_f, npa_f, pnpa_f, fida_f, fida_weights_mc, halo